go-delve/delve

_fixtures/testvariables2.go
service/dap/server.go
service/dap/server_test.go

When keys are truncated, there is risk of duplication in remaining strings. Using address keys as suffixes fixes that.
Removes suffixes in all other cases because after change #2383 keys that have not been truncated are unique inlined values rather than identical key type placeholders.
Updates https://github.com/golang/vscode-go/issues/1267

service/dap: truncate long compound map keys and use unique address suffix for uniqueness

---

Documentation/cli/README.md
pkg/terminal/command.go
pkg/terminal/command_test.go
pkg/terminal/terminal.go
service/api/prettyprint.go
service/test/integration1_test.go
service/test/integration2_test.go
service/test/variables_test.go

Changes print so a format argument can be specified by using '%' as
prefix. For example:
print %x d
will print variable 'd' in hexadecimal. The interpretarion of the
format argument is the same as that of fmt's package.
Fixes #1038
Fixes #1800
Fixes #2159

terminal: add optional format argument to print, display

---

service/dap/server.go

Error level logging shows up in the users' consoles/terminals
so be more conservative when logging. Move the followings to
Debug logging.
- DAP error reponses caused by invalid requests.
They are application level errors and DAP clients should handle them.
- Errors reported when debugee already exited.
Fixes golang/vscode-go#1392

service/dap: change dap error response logging to debug level

---

service/dap/server.go
service/dap/server_test.go

The step in, next, and step out requests all include a specified argument of a threadId.
This change will switch to the specified goroutine, if necessary, before executing
the step command.

service/dap: switch goroutines when stepping

---

Documentation/installation/README.md

Some users seem to need to do this in order to use a debugger.

Documentation: mention developer group in macOS install instructions

---

service/dap/server.go
service/dap/server_test.go

PR #2400 added support for noDebug launch requests - that was done
by directly starting the target program using os/exec.Cmd and blocking
the launch request indefinitely until the program terminates or
is stopped with a disconnect request (when dlv dap can support it).
This PR updates the logic slightly - instead of skipping the launch response,
we now return the launch response. But still we don't send 'initialized' event
hoping that the client not to send any debug-related requests.
Still the handler goroutine will block in the onLaunchRequest handler until
the debugged program terminates.
Updates #2318

dap: change how noDebug launch request is served

---

pkg/proc/bininfo.go
pkg/proc/types.go

* allow a concrete subprogram to be treated as the abstract origin for an inlined call
* allow nameless concrete and abstract subprograms
Fixes #2393

proc: be more lenient when parsing debug_info

---

service/dap/server.go
service/dap/server_test.go

It's expected that users enter invalid expressions through DEBUG
CONSOLE. Pop up for every error is not pleasant.

dap: suppress error popup for failed evaluation request in repl mode

---

service/dap/daptest/client.go
service/dap/error_ids.go
service/dap/server.go
service/dap/server_test.go

Updates https://github.com/golang/vscode-go/issues/1410

service/dap: delay disconnect response and log teardown progress

---

pkg/proc/target.go
service/debugger/debugger.go
service/test/integration2_test.go

When restarting we must take care of setting breakpoint IDs correctly
so that enabled breakpoints do not end up having the same ID as a
disabled breakpoint, also we must make sure that breakpoints created
after restart will not get an ID already used by a disabled breakpoint.

service: fix breakpoint IDs after Restart with disabled breakpoints

---

_scripts/make.go

Support macOS Big Sur for `make install`.
macOS has been increase major kernel version. Now Big Sur is `11.0`.
handle it and check whether the major version greater than `10`.

_scripts: support macOS Big Sur

---

service/rpc1/server.go
service/rpc2/server.go
service/rpccommon/server.go
service/test/integration2_test.go

Ignore the closed listener error when the server is being shut down in
response to a SIGINT signal.
Fixes #1633
Detach will close DisconnectChan causing the server to initiate
shutdown, there is a race between Detach writing its response to the
client and the shutdown terminating the server process.
If Detach loses the race the response to the Detach request is never
sent to the client and the client will report an EOF error instead.
This change delays the start of the shutdown process until after Detach
has written its response.
Fixes an occasional failure of TestContinue.

service/rpccommon: fix shutdown related bugs

---

pkg/proc/proc_test.go

There seems to be a problem where debugserver will leave a zombie
process instead of detaching correctly, we are sending the right
commands, it doesn't seem to be a problem with Delve.

proc: disable part of TestAttachDetach test on macOS

---

service/dap/server.go
service/dap/server_test.go
service/debugger/debugger.go

Due to variable shadowing the SwitchGoroutine command never failed.

debugger: report error when switching goroutine is impossible

---

pkg/gobuild/gobuild.go
service/dap/server.go
service/dap/server_test.go

When there is a build error, the error returned by the go command includes the exit code,
but not much detail. This change adds the information from stderr to the error message
to provide more useful information to the client.
Updates golang/vscode-go#1425

service/dap: add go build stderr to error response

---

Documentation/api/ClientHowto.md

The documentation mentions flags that do not exist. Replace them with
the existing, --log-dest flag.

Documentation: correct the flag name used to configure log destination

---

pkg/proc/gdbserial/gdbserver.go

Instead of purely checking for a specific version of gdbserver (`"1200"`), we assume that all versions greater than 1200 are affected and thus `p.gcmdok` needs to be set to false.
Fixes #2436

Slightly better version check for gdb server on newer macOS (arm64)

---

pkg/dwarf/line/line_parser.go
pkg/dwarf/line/parse_util.go
pkg/dwarf/line/state_machine.go
pkg/dwarf/util/util.go

Check for errors, log them and return early, do not try to allocate
large chunks of memory that we can never possibly read from the file.
Fixes #2449

dwarf: make debug_line header parser more resilient

---

Documentation/usage/dlv_test.md
cmd/dlv/cmds/commands.go

Add documentation on how to pass arguments to the program generated by
`dlv test`.
Fixes #2458

Documentation: document passing arguments to the test program

---

_fixtures/testvariables2.go
service/dap/server.go
service/dap/server_test.go

This change provides support for automatically reloading fully missing pointers, structs, arrays and maps (subject to partial config limits on reload). It does not attempt to reload partially loaded variables, which need a different way of handling (TBD). 
This change reuses the code used for auto-loading interfaces, factored out into a helper `reloadVariable`. Since VariablesRequest focuses on looking up already loaded variables, we auto-load the children proactively when looking up their outer container variable. This allows us to update the inlined string value of the parent (but not grandparent) variable as well and avoid supplying references that resolve to nothing if auto-loading fails.
Pointers loading has a couple of quirks comparing to other types. If a pointer was not loaded …

service/dap: auto-loading for fully missing children of nested vars

---

Documentation/cli/README.md
Documentation/cli/expr.md
pkg/proc/amd64_arch.go
pkg/proc/arch.go
pkg/proc/arm64_arch.go
pkg/proc/eval.go
pkg/proc/i386_arch.go
pkg/proc/variables.go
pkg/terminal/command.go
service/api/types.go
service/test/integration2_test.go

Changes the expression evaluation code so that register names, when not
shadowed by local or global variables, will evaluate to the current
value of the corresponding CPU register.
This allows a greater flexibility with displaying CPU registers than is
possible with using the ListRegisters API call. Also it allows
debuggers users to view register values even if the frontend they are
using does not implement a register view.

proc: add way to use CPU registers in expressions

---

_scripts/test_windows.ps1

Bintray is shutting down and the URL we used to install mingw is no
longer available. Use chocolatey instead.

TeamCity: fix Windows builds

---

service/dap/daptest/gen/main.go
service/dap/daptest/resp.go

Message logging doesn't look good with %q.

daptest/gen: use %#v instead of %q

---

service/dap/server_test.go

Accept the empty threads response in case the threads request arrived after the program
terminated.

service/dap: fix continueOnEntryTest

---

service/dap/server.go
service/dap/server_test.go
service/debugger/debugger.go

Unlike vscode-go, this implementation does not resume execution after halting and setting breakpoints. Resuming automatically turns out to be much trickier than just skipping a stopped event and continuing. It is possible that the stop occurred due to reasons other than our manual stop (breakpoint, call return), so we would need to detect thtat and report any stops that the user might be interested in. In addition, next would be cancelled by the halt command, so to resume it, we would need to implement an alternative version of halt that doesn't cancel next. So for now, we will just be reporting the pause to the user and let them decide when and how to resume execution manually.
Updates #1515
Updates https://github.com/golang/vscode-go/issues/1475

service/dap: support setting breakpoints while running

---

Documentation/backend_test_health.md
pkg/proc/native/proc_linux.go
pkg/proc/native/threads_linux.go
pkg/proc/proc_test.go
service/api/types.go

A RequestManualStop received while the target program is stopped can
induce a crash when the target is restarted.
This is caused by the phantom breakpoint detection that was introduced
in PR #2179 / commit e69d536.
Instead of always interpreting an unexplained SIGTRAP as a phantom
breakpoint memorize all possible unreported breakpoint hits and only
act on it when the thread hasn't moved from one.
Also clarifies the behavior of the halt command when it is received
while the target is stopped or in the process of stopping.

pkg/proc/native/linux: fix target crashes induced by RequestManualStop

---

service/dap/server.go

My local build of delve which apparently pulls in the master branch started breaking. This is the culprit.
Error:
```
#9 75.27 # github.com/go-delve/delve/service/dap
#9 75.27 /usr/src/github.com/go-delve/delve/service/dap/server.go:107:1: syntax error: unexpected <<, expecting field name or embedded type
#9 75.27 /usr/src/github.com/go-delve/delve/service/dap/server.go:110:1: syntax error: unexpected ==, expecting field name or embedded type
#9 75.27 /usr/src/github.com/go-delve/delve/service/dap/server.go:113:1: syntax error: unexpected >>, expecting field name or embedded type
```

Fix build error due to unresolved merge conflict

---

pkg/dwarf/op/op.go
pkg/proc/dwarf_expr_test.go
pkg/proc/mem.go
pkg/proc/proc_test.go

According to DWARFv4 section 2.6.1.3 having a DW_OP_piece when nothing
is on the stack is legal and represents uninitialized/unavailable
memory.

dwarf/op,proc: fix handling of DW_OP_piece

---

pkg/proc/gdbserial/gdbserver.go

The maintainer of debugserver says he wants to fix the problem with the
'g' command but doesn't know when it will happen. Treat the error 'E74'
for the 'g' command on debugserver as if the server had returned an
unsupported error so that, for this specific problem, the error doesn't
resurface in the future.

gdbserial: for the 'g' command on debugserver treat E74 as unsupported

---

pkg/proc/eval.go
pkg/proc/proc_unexported_test.go
service/test/variables_test.go

Truncates the result of binary operations on integers to the size of
the resulting type.
Also rewrites convertInt to not require allocations.
Fixes #2454

proc: correctly truncate the result of binary ops on integers

---

service/dap/server.go
service/dap/server_test.go

Next/step/stepout requests assume that execution is only resumed
on the thread that was specified. We cannot resume execution on
only a single thread, so we need to send a continued event to let
the client know that all threads have resumed.

service/dap: send 'continued' event on next/step/stepout requests

---

cmd/dlv/cmds/commands.go
service/dap/server.go
service/internal/sameuser/doc.go
service/internal/sameuser/sameuser.go
service/internal/sameuser/sameuser_linux.go
service/internal/sameuser/sameuser_linux_test.go
service/rpccommon/sameuser.go
service/rpccommon/server.go

On linux, delve RPC server allows only connections from the same user
if --only-same-user is set (true, by default). Do the same for DAP
server.
Moved the sameuser check logic to service/internal/sameuser.
Considered importing service/rpccommon from the dap server,
but when we eventually migrate to multiplex rpc and dap from one
port, I am afraid that can cause cyclic imports.

dap: add sameuser check

---

pkg/proc/bininfo.go
pkg/proc/types.go

The code populating runtimeTypeToDIE was incorrectly adding StaticBase
to the offset. We never noticed because on statically compiled
executables StaticBase is always zero and on PIE and plugins the
fallback code took care of the problem anyway.
A change in Go 1.17 broke the fallback code, making the issue apparent.
This commit fixes the setup of runtimeTypeToDIE and disables the
fallback code for Go 1.17 and later.
This change also fixes a rare failure in TestPluginVariables when PIE
is enabled.

proc: fix runtimeTypeToDIE setup

---

service/dap/daptest/client.go
service/dap/server.go
service/dap/server_test.go

We can support evaluate for hover context in order to provide more
useful hover info for dap users. This can be particularly useful when
hovering over fields in a struct type.
Updates go-delve/delve#2491
Updates golang/vscode-go#1510

service/dap: support evaluate for hover context

---

pkg/proc/proc_test.go

Sometimes on Windows TestFrameEvaluation fails because the stacktrace
doesn't look deep enough.

tests: increase stack depth for TestFrameEvaluation

---

_fixtures/testvariables2.go
service/dap/daptest/client.go
service/dap/error_ids.go
service/dap/server.go
service/dap/server_test.go

The handler invokes debugger.SetVariableInScope, except for
string type variables. For which, we rely on the `call` command.
Moved the call expression handling logic to the new `doCall`
function, so it can be reused by the SetVariable request handler.
Earlier attempt of this PR tried to trigger a Stopped Event whenever
a variable is changed in order to force the editors to refetch data and
refresh UI. But that seems too expensive and some may think annoying
so we decided to not do that. Editors like VSCode tries to make a local
update for the variable after a successful set variable request. However,
if there are aliases, some info may look inconsistent.
```
i1 := 1
p1 :=&i1
pp1 := &p1
``` 
For example, after updating *p1 for the code, users would see
This inconsistency will be corrected …

dap: handle SetVariable requests

---

service/dap/server.go

The Types field is only set in childrenToDAPVariables if the client
capability is supported. There is no need to check again after the
children have been calculated.

service/dap: remove unnecessary capability check

---

Documentation/backend_test_health.md
pkg/proc/proc_test.go

These seem to magically work again on my M1 Mac so, enabling them again.

pkg/proc: Enable CGO Stacktrace tests on arm64

---

Documentation/backend_test_health.md
_scripts/gen-backend_test_health.go

Change gen-backend_test_health.go so that it only prints the number of
tests skipped and not the total or the percentage.
As it is it causes too many merge conflicts.

_scripts: change gen-backend_test_health.go to be more stable

---

service/dap/daptest/gen/main.go
service/dap/daptest/resp.go
service/dap/server_test.go

Separates checking already read messages into separate helpers. Renames all helpers to follow the same convention:
- Expect = read + verify
- Check = only verify

service/dap: test refactoring

---

pkg/proc/native/proc_freebsd.c
pkg/proc/native/proc_freebsd.h

fix cast to smaller integer type 'int' from 'void *'

Fix freebsd native backend

---

service/dap/server.go
service/dap/server_test.go

If the output binary name does not end with .exe, it can't run on Windows
in noDebug mode. If user-provided output name doesn't have file extension
name (.exe), append it.
Fixes golang/vscode-go#1473

dap: clean output executable name for windows

---

_fixtures/fputest/fputest_amd64.s
pkg/proc/variables.go
service/test/integration2_test.go

If the base address isn't set then indexing and slicing will not work.
Large floating point registers already had the base set but small
general purpose registers did not.

proc: when converting registers to slices set Base address

---

Documentation/cli/README.md
pkg/terminal/command.go
pkg/terminal/command_test.go

Adds a -hitcount argument to condition that sets a hitcount condition
on breakpoints.

terminal: support setting hitcount conditions on breakpoints

---

service/dap/daptest/gen/main.go
service/dap/daptest/resp.go
service/dap/server_test.go

Generate the checks for continued events after step, next, step out requests, to take the burden off the test writer to remember to check for the event.

service/dap: generate continued events for step tests

---

service/dap/daptest/client.go
service/dap/server.go
service/dap/server_test.go

* add 'clipboard' capability
* apply a larger string limit for 'hover' and 'clipboard' context
* truncate the string representation of a compound type (or pointer of a compound type) variable if the length of the value is larger than 256. But when a variable is returned as a result of Evaluate Request for hover or copy value feature (clipboard or variables context), do not truncate the value.
Updates golang/vscode-go#1318
Fixes golang/vscode-go#1435

dap: add 'clipboard' support, and truncate a long value

---

service/dap/server.go
service/dap/server_test.go

This change removes "Paused on" in the stopped event description for panics, throws and runtime errors. We do not need to match the "Paused on reason" format that VS Code uses to display stopped events. For panics, throws, and runtime errors, "paused on" is actually not a useful description. Even if it is possible to continue executing the program, it is usually not going to be useful since it is crashing.

service/dap: make stopped event description for exception more concise

---

service/dap/server.go
service/dap/server_test.go

On hovers, including the full value for complex types is unnecessary, since the user will likely need to expand the children to inspect the values. Additionally, this can really slow down getting the hover values. This change will allow truncating the value
in hover if the variable has a variables reference.
Updates golang/vscode-go#1435

service/dap: truncate value for expandable types in hover

---

service/internal/sameuser/sameuser_linux.go

Sometimes we observe failure in the same user check (not a file read/parse error).
Log uid/remoteUID, and the info from /proc/net/tcp{6} file.
Updates golang/vscode-go#1555

sameuser: log the uid/remoteUID when they are not matching

---

pkg/terminal/command.go
pkg/terminal/command_test.go
service/api/prettyprint.go
service/dap/server.go

Commit 30cdedae6910f5e9af6739845bacfd5b8778e745 introduced a dependency
from service/dap to pkg/terminal to call a stack printing function,
it's weird to have code that implements the DAP protocol depend on the
code for the JSON-RPC client.
Move PrintStack to a different package that can be called by both.

terminal,api: move PrintStack function

---

pkg/proc/interface.go
pkg/proc/target.go
pkg/proc/target_exec.go
pkg/terminal/command.go
service/api/types.go
service/debugger/debugger.go
service/test/integration2_test.go

Ensure that any command executed after the process we are trying to
debug prints a correct and consistent exit status.
Previously the exit code was being lost after the first time we printed
that a process has exited. Additionally, certain commands would print
the PID of the process and other would not. This change makes everything
more correct and consistent.

proc,terminal: Ensure correct exit status

---

pkg/dwarf/line/line_parser.go
pkg/dwarf/line/line_parser_test.go
pkg/dwarf/line/parse_util.go
pkg/dwarf/line/state_machine.go
pkg/dwarf/line/state_machine_test.go
pkg/proc/bininfo.go
pkg/proc/proc_test.go

While Go still mostly uses DWARF v4, newer versions of GCC will emit
DWARF v5 by default. This patch improves support for DWARF v5 by parsing
the .debug_line_str section and using that during file:line lookups.

proc,dwarf: Improve DWARF v5 support

---

_fixtures/longstrings.go
_fixtures/testvariables2.go
service/dap/server.go
service/dap/server_test.go

This PR proposes a limit of 512 with a TODO to consider 1024. 
Vscode truncates display values at 1023, so any higher won't give additional viewing power.
For additional inspiration, the C/C++ vscode adapter appears to be limiting string loads at 1024.
updates https://github.com/golang/vscode-go/issues/1318

service/dap: increase default string loading limit and refactor

---

service/dap/daptest/client.go
service/dap/server.go
service/dap/server_test.go

It is often convenient to view the string representation of a byte or rune slice when debugging.
We can display the string representation as a child of the byte slice variable. In an interactive
debugging UI, this will only get loaded when the user expands the slice.
This is implemented as a "Named" variable, so that this is shown separately from the paged index
variables.
Updates golang/vscode-go#1459

service/dap: add string value of byte/rune slice as child

---

.gitignore

We should ignore this by default.

*: Add .vscode to .gitignore

---

_fixtures/fatalerror.go
service/dap/server.go
service/dap/server_test.go
service/debugger/debugger.go

We can get the throw reason by looking at the argument "s" in runtime.throw. This is not currently working in Go 1.16 or Go 1.17 (see golang/go#46425), but does work in Go 1.15 and Go 1.14

service/dap: add throw reason to exception info

---

service/test/integration2_test.go

The rr backend does not report avx512 registers back to us.

test: disable avx512 test when backend is 'rr'

---

service/debugger/debugger.go
service/rpc2/client.go
service/rpc2/server.go

The existing documentation was a little light on details. This patch
gives more insight into how the argument to this function is used and
interpreted.

service/debugger: improve CreateBreakpoint docs

---

Documentation/cli/README.md
Documentation/cli/starlark.md
_fixtures/goroutinegroup.go
cmd/dlv/dlv_test.go
pkg/proc/variables.go
pkg/terminal/command.go
pkg/terminal/starbind/starlark_mapping.go
service/api/types.go
service/client.go
service/dap/server.go
service/debugger/debugger.go
service/rpc2/client.go
service/rpc2/server.go
service/test/integration2_test.go

Adds filtering and grouping to the goroutines command.
The current implementation of the goroutines command is modeled after
the threads command of gdb. It works well for programs that have up to
a couple dozen goroutines but becomes unusable quickly after that.
This commit adds the ability to filter and group goroutines by several
different properties, allowing a better debugging experience on
programs that have hundreds or thousands of goroutines.

terminal,service: Add filtering and grouping to goroutines command

---

pkg/proc/gdbserial/gdbserver.go
pkg/proc/macutil/rosetta_darwin.go
pkg/proc/macutil/rosetta_other.go
pkg/proc/native/proc_darwin.go

Delve does not run under Rosetta. Detect this condition and point
confused users towards the solution.

proc/native,proc/gdbserial: detect and complain about Rosetta

---

pkg/proc/core/minidump/minidump.go
pkg/proc/gdbserial/gdbserver.go

The LLVM project archived their repository and moved it elsewhere,
Microsoft broke their minidump documentation URLs.

proc/core/minidump,proc/gdbserial: update broken ext links

---

service/dap/server.go
service/dap/server_test.go

By setting the breakpoint id for the breakpoint that was hit, the dap client can show the user
which breakpoint was hit by this stopped event. VS Code does this by shifting focus in the
breakpoints view to the breakpoint with the returned id.

service/dap: set hit breakpoint ids

---

service/dap/daptest/client.go
service/dap/error_ids.go
service/dap/server.go
service/dap/server_test.go

The code previously expected the server to close when receiving
a message that it could not decode. However, there may be changes to
the spec that make new requests that we have not handled yet. In
that case, it would be preferable to return an error.

service/dap: send dap error response on dap error

---

service/rpc2/server.go

The slice `out.List` is created with a length of 0 but a capacity of
`len(imgs)`. This causes the line below to panic as we try to index into
the `out.List` slice instead of append to it. This patch resolves the
issue by appending instead of indexing into the slice.

service/rpc2: Fix panic in ListDynamicLibraries

---

service/dap/server.go
service/dap/server_test.go

Fixes #2590
The above issue breaks clients that don't expect null as per spec.
From [dap spec](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Variables) ([json](https://microsoft.github.io/debug-adapter-protocol/debugAdapterProtocol.json)), 
```
variables: Variable[];
```
```
"variables": {
"type": "array",  <========== no "null" option
```
Technically, only top-level scope variables (Arguments, Locals, etc) would result variables requests and could trigger this issue. The rest of childless variables are mapped to a reference of 0 and therefore do not offer an option for further expansion to view the children that result in a variable request/response. But just in case I am updating children initialization for all types and cases.

service/dap: variables response must not have null variables array

---

service/dap/server.go
service/dap/server_test.go

This change adds an additional metadata variable for maps. There is currently no place that the size of a map is included. To make this information easier for users to access, we can add it as a named variable to be returned as a child of a map.
Map:
Paged Indexed:
Empty map:

service/dap: add len as metadata for map

---

.teamcity/settings.kts

We've only ever tested the latest version of Go on everything except
linux/amd64.

TeamCity: remove 1.16 testing for linux/arm64, windows/amd64 and mac/*

---

service/dap/server_test.go

TestPreSetBreakpoint sometimes fail because a goroutine is stopped in
some runtime/internal package instead of just 'runtime'.

service/dap: fix TestPreSetBreakpoint

---

service/dap/daptest/gen/main.go
service/dap/daptest/resp.go
service/dap/server.go

Send the continued event before the step response to make sure that there is no time where the client believes that only a single thread is running.
Fixes golang/vscode-go#1629
Updates golang/vscode-go#1617

service/dap: send continued event before step response

---

.teamcity/settings.kts

It looks like editing settings both in UI and in git leads to problems. This change disables settings editing in UI. If applied, all changes should be made by editing settings.kts. Feel free to reject if you want edit settings in UI, but in this case it is better to give teamcity permissions to push changes in settings to the repository, currently push fails. Otherwise every failed push disables settings synchronization.

Make teamcity ui settings readonly

---

cmd/dlv/cmds/commands.go

SIGINT might get forwarded to the target process, so we need another way to request clean shutdown.
**Before**
```
DAP server listening at: [::]:54321
2021-07-12T03:00:21-07:00 debug layer=dap DAP server pid = 19852
Terminated: 15
```
```
API server listening at: [::]:54321
2021-07-12T03:03:23-07:00 debug layer=rpc API server pid = 20146
2021-07-12T03:03:23-07:00 info layer=debugger launching process with args: [/Users/polina/delve/__debug_bin]
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1205.0.27
for x86_64.
Got a connection, launched process /Users/polina/delve/__debug_bin (pid = 20161).
Terminated: 15
Exiting.
```
**After**
```
DAP server listening at: [::]:54321
2021-07-12T03:00:53-07:00 debug layer=dap DAP server pid = 19889
2021-07-12T03:01:04-07:00 debug layer=dap DAP server …
```

cmd: treat SIGTERM as a server disconnect signal

---

service/dap/server.go

This adds a cap and a log message if there are many goroutines. This will help
prevent the debugger from freezing, but does not yet address making sure the
interesting goroutines are the ones that are returned.
Updates golang/vscode-go#129

service/dap: limit the number of goroutines returned from threads req

---

Documentation/cli/README.md
pkg/terminal/command.go
pkg/terminal/command_test.go

Adds the ability to edit the list of commands executed after stopping
on a breakpoint, as well as converting a breakpoint into a tracepoint
and vice versa.
Prior to this it was possible to add commands to a breakpoint but
removing commands or changing a breakpoint into a tracepoint, or vice
versa, could only be done by removing and recreating the breakpoint.

terminal: improve 'on' command

---

pkg/proc/bininfo.go
pkg/proc/types.go

Conversion form a moduledata object into an image object was
implemented by looking for a function covering the start address of the
text section of the moduledata object, and then converting that into
its corresponding image.
Unfortunately this seems to not always work. In particular it does not
work on linux/386 with go1.17 (but it might also fail on other
combinations): the start address of the text section is, for whatever
reason, not part of any function.
As a fallback simply scan all images we know of and return the closest
one that has start address less than or equal to the start address of
the text section we are looking for.
Fixes TestPluginVariables on go1.17/linux/386.
Fixes #2611

proc: make moduleDataToImage more robust

---

service/dap/server.go
service/dap/server_test.go

Disable this test for Go 1.17 for the time being so it doesn't block test CI for unrelated PRs.

service/dap: disable TestFatalThrowBreakpoint for Go 1.17

---

service/dap/server.go
service/dap/server_test.go

Replay mode configuration suffered during a rebase, and the issue was not caught by the unittests because there were none testing that replay mode args get set up and passed to `debugger.New` correctly. Because we added backend parsing (#2567) in parallel with replay/core support (#2367), `CoreFile` was set in `replay` mode, but `rr` backend was replaced with `"default"`, so this was treated as a `core` mode instead:
https://github.com/go-delve/delve/blob/658d36cb1909cd4267e538b10f2f84df8f752216/service/debugger/debugger.go#L167-L177
@lggomez

service/dap: fix backend parsing in replay mode

---

pkg/proc/bininfo.go

StaticBase is the difference between the entry point declared in the
image file and the entry point as loaded in memory, since this
difference could be a negative number we have to use a signed
comparison when searching for a mapping.
Causes intermittent test failures on windows when resolving interface
types for position independent executables.
Fixes #2620

proc: use signed comparison when searching image for module data

---

pkg/terminal/command.go
pkg/terminal/command_test.go

Adds a prompt asking the user what to do when a breakpoint is hit on a
different goroutine while next/step/stepout is being executed.
Gives the user the opportunity to cancel next/step/stepout, continue
once skipping the breakpoint or automatically skipping all other
concurrent breakpoints until next/step/stepout is finished.
Fixes #2317

terminal: add prompt when breakpoint is hit during next/step/stepout

---

Documentation/usage/dlv_version.md
cmd/dlv/cmds/commands.go
cmd/dlv/dlv_test.go
pkg/version/buildinfo.go
pkg/version/version.go
pkg/version/version_test.go

With `-v` or `--verbose`, dlv version prints out runtime/debug.BuildInfo 
read from the dlv binary. Users can retrieve the same info using 
`go version -m <path_to_dlv>` but I think it is convenient to have.
runtime/debug.BuildInfo is available since go1.12. I placed built tag
but already the current delve repo requires go1.12, so maybe that isn't
necessary. A different approach is exec `go version -m <self>`, but if
the user's go version in PATH is older than go1.12 this won't work.
If dlv was built from cloned delve repo:
```
$ ./dlv version -v
Delve Debugger
Version: 1.7.0
Build: $Id: e353a65161e6ed74952b96bbb62ebfc56090832b $
Build Details: go1.16.5
mod    github.com/go-delve/delve       (devel)
dep    github.com/cosiner/argv v0.1.0  h1:BVDiEL32lwHukgJKP87btEPenzrrHUjajs/8yzaqcXg=
... …
```

cmd/dlv: dlv version --verbose

---

pkg/proc/amd64_arch.go
pkg/proc/arm64_arch.go
pkg/proc/i386_arch.go
pkg/proc/proc_test.go
pkg/proc/target.go
service/dap/server.go
service/dap/server_test.go

Currently there is a breakpoint set at runtime.fatalthrow to catch any
situation where the runtime crashes (e.g. deadlock).
When we do this, we go up a frame in order to parse the crash reason.
The problem is that there is no guarentee the "s" variable we attempt to
parse will still be considered "live".
Since runtime.fatalthrow is never called directly, set a breakpoint on
runtime.throw instead and prevent having
to search up a stack frame in order to
get the throw reason.
Fixes #2602

pkg/proc: Prefer throw instead of fatalthrow

---

Documentation/cli/README.md
pkg/terminal/command.go

Before this change when you typed `help` at the Delve prompt you would
only see the following:
```
examinemem (alias: x)  Examine memory:
```
Now with this patch the output is more descriptive:
```
examinemem (alias: x)  Examine raw memory at the given address.
```

Documentation: Improve help output for examinemem

---

pkg/terminal/command.go
pkg/terminal/command_test.go

Ignore existing breakpoints when using the continue command to continue
to a specific location such as `continue main.main`. The point of this
command is to continue to a specific location, so if there is already a
breakpoint set there there should be no error returned, just continue
until we hit the breakpoint already set in that location.

pkg/terminal: Ignore existing breakpoints for continue until

---

pkg/proc/stack.go

We're making a few cleanups to the _defer struct on the dev.typeparams branch that currently cause Delve to crash. The plan is to merge dev.typeparams to the Go main branch as soon as 1.18 development opens, so this PR is getting ahead of that (also, we like to be able to use Delve ourselves :). It inspects the struct's type, so it should adapt smoothly to these changes without having to be keyed off the Go version.

Fix crashes on Go dev.typeparams (soon to be Go main branch)

---

service/dap/server.go
service/dap/server_test.go

To make it more clear that the user can resume the program when they encounter a next while nexting error, make the exception information have instructions for resuming the program. This implements the suggestions outlined by @polinasok in https://github.com/go-delve/delve/pull/2443#issuecomment-869455021.

service/dap: make next while nexting error more clear

---

pkg/proc/test/support.go

The install of gcc sometimes fails on our CI, it is not an error if the
tests for cgo can not run because there's no C compiler.

tests: check presence of gcc for cgo tests

---

service/dap/server_test.go

The loop searching for a suitable goroutine is not guaranteed to ever
find it, and failing to find one is not an error.
Changes testStepParkedHelper to match the behavior of TestNextParked in
proc_test.go.
Deletes TestStepInParked because it does not test anything meaningful
beyond what's already tested by TestNextParked.

service/dap: fix TestNextParked/TestStepInParked

---

service/debugger/debugger.go

There is already a lock on the actual buffered tracepoints collection
within proc, and this method call doesn't do anything to mutate Target
otherwise so we shouldn't be opening ourselves up for a race condition
error or any other kind of parallelism problem.
Additionally, with this lock we essentially can never get the data until
the process has exited becuase `continue` will lock the target. This
change allows us to get the buffered tracepoint information immediately
and display it as the program is running.

service/debugger: Remove target lock on GetBufferedTracepoints

---

vendor/modules.txt

run 'go mod vendor' to update vendor/modules.txt to explicitly require module 'github.com/derekparker/trie'.
close #2646

fix/vendor: to explicitly require package github.com/derekparker/trie

---

cmd/dlv/cmds/commands.go

Use simple chan read instead of select-case on only one chan.
When run `golangci-lint run .`, it reports several chan receive problems that use select-case on only one chan. We can use simple chan receive instead of select-case.

fix/cmds: use simple chan read instead of select-case

---

_scripts/make.go
pkg/proc/breakpoints.go
pkg/proc/core/core_test.go
pkg/proc/eval.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/moduledata.go
pkg/proc/native/proc_windows.go
pkg/proc/native/threads.go
pkg/proc/native/threads_windows.go
pkg/proc/proc_test.go
pkg/proc/target.go
pkg/proc/target_exec.go
pkg/proc/variables.go
service/debugger/debugger.go
service/test/variables_test.go

Moves breakpoint condition evaluation from the point where breakpoints
are set, inside ContinueOnce, to (*Target).Continue.
This accomplishes three things:
1. the breakpoint evaluation method needs not be exported anymore
2. breakpoint condition evaluation can be done with a full scope,
containing a Target object, something that wasn't possible before
because ContinueOnce doesn't have access to the Target object.
3. moves breakpoint condition evaluation out of the critical section
where some of the threads of the target process might be still
running.

proc: move breakpoint condition evaluation out of backends

---

Documentation/backend_test_health.md
Documentation/cli/README.md
Documentation/cli/starlark.md
_fixtures/databpstack.go
pkg/proc/breakpoints.go
pkg/proc/proc_test.go
pkg/proc/stackwatch.go
pkg/proc/target_exec.go
pkg/terminal/command.go
pkg/terminal/starbind/starlark_mapping.go
service/api/types.go
service/client.go
service/dap/server.go
service/debugger/debugger.go
service/rpc1/server.go
service/rpc2/client.go
service/rpc2/server.go
service/test/common_test.go
service/test/integration2_test.go

Adds support for watchpoints on stack allocated variables.
When a stack variable is watched, in addition to the normal watchpoint
some support breakpoints are created:
* one breakpoint inside runtime.copystack, used to adjust the address
of the watchpoint when the stack is resized
* one or more breakpoints used to detect when the stack variable goes
out of scope, those are similar to the breakpoints set by StepOut.
Implements #279
Now that Delve has internal breakpoints that survive for long periods
of time it will be useful to have an option to display them.
Changes Breakpoint to allow multiple overlapping internal breakpoints
on the same instruction address.
This is done by changing the Breakpoint structure to contain a list of
"breaklets", each breaklet has a BreakpointKind and a …

proc,terminal,service: support stack watchpoints

---

service/dap/server.go
service/internal/sameuser/sameuser.go
service/internal/sameuser/sameuser_linux.go
service/internal/sameuser/sameuser_linux_test.go
service/rpccommon/server.go

Change the socket search to check both the remote and local fields of the
socket match the socket we want to find.
Sockets are identified by the 4-uple
local_addr, local_port, remote_addr, remote_port
Two socket can differ by a single one of this four elements.
It is possible for the same local_port to be used by two different sockets,
as long as they are connecting to different remote addresses (or remote
ports).
An example of this bug in action can be seen at:
https://github.com/golang/vscode-go/runs/3141270564?check_suite_focus=true
There the server starts listening on 127.0.0.1:46011 and rejects a valid
client connection by finding the following socket:
60: 0100007F:DD82 0100007F:962D 06 00000000:00000000 03:00000133 00000000     0        0 0 3 0000000000000000
the local address of …

service: fix sameuser check

---

Documentation/internal/README.md
Documentation/internal/portnotes.md

Once in a while we get asked about porting Delve, I thought we should write it down somewhere.

Documentation: add notes on porting Delve to other architectures

---

Documentation/usage/dlv_dap.md
cmd/dlv/cmds/commands.go
service/dap/server.go
service/dap/server_test.go

Closes #2392
Updates golang/vscode-go#1680
Updates golang/vscode-go#1348
This PR adds tests, logging and `--help` documentation note confirming that relative program paths are indeed handled and are interpreted relative to server's working directory.

service/dap: clarify handling of relative program path

---

pkg/terminal/config.go

Commit 8e91d3b0b added a number of configuration options to control the
colors of sytnax highlighting, unfortunately 'config -list' will print
all of those to stdout without quoting them, resulting in the color of
the last one being applied to all subsequent text.
Change 'config -list' to print strings in quotes so that we don't
accidentally send escape sequences to the terminal.

terminal: config -list should print strings in quotes

---

_scripts/rtype-out.txt
_scripts/rtype.go
cmd/dlv/dlv_test.go
pkg/proc/moduledata.go
pkg/proc/stack.go
pkg/proc/target.go
pkg/proc/types.go
pkg/proc/variables.go

Adds a script that check automatically that the the assumptions that
pkg/proc makes about runtime are met by the actual runtime, using a
combination of parsing and magic comments.
Also emits a file describing all the struct fields, constants and
variables of the runtime that we use in pkg/proc.

_scripts: auto check that pkg/proc and runtime are synchronized

---

.teamcity/settings.kts
Makefile
_scripts/test_linux.sh
_scripts/test_mac.sh
cmd/dlv/cmds/commands.go
cmd/dlv/dlv_test.go
pkg/proc/breakpoints.go
pkg/proc/core/core.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/interface.go
pkg/proc/internal/ebpf/context.go
pkg/proc/internal/ebpf/helpers.go
pkg/proc/internal/ebpf/helpers_disabled.go
pkg/proc/internal/ebpf/trace_probe/Dockerfile
pkg/proc/internal/ebpf/trace_probe/function_vals.bpf.h
pkg/proc/internal/ebpf/trace_probe/trace.bpf.c
pkg/proc/internal/ebpf/trace_probe/trace.bpf.h
pkg/proc/native/nonative_darwin.go
pkg/proc/native/proc_darwin.go
pkg/proc/native/proc_freebsd.go
pkg/proc/native/proc_linux.go
pkg/proc/native/proc_windows.go
pkg/proc/target.go
pkg/proc/variables.go
service/api/types.go
service/debugger/debugger.go

This patch enables the eBPF tracer backend to parse the ID of the
Goroutine which hit the uprobe. This implementation is specific to AMD64
and will have to be generalized further in order to be used on other
architectures.
This patch also adds a test for the eBPF tracer backend. The test will skip
if it is not being run as root because we need SYS_CAP_ADMIN in order to
load the BPF program.

pkg/proc: Parse Goroutine ID in eBPF tracer

---

pkg/proc/proc_general_test.go
pkg/proc/proc_test.go
pkg/proc/test/support.go

The tests incorrectly assumed that regabi was enabled everywhere on Go1.17/amd64, in fact it is not enabled on freebsd.

tests: correct checks that depend on regabi (fixes Cirrus-CI builds)

---

pkg/proc/bininfo.go

If we cannot find debug information locally on the system, try and
invoke debuginfod-find in order to ask the linux distribution we're on
to find the debug information for us.

pkg/proc: attempt to leverage debuginfod-find

---

pkg/proc/proc_unix_test.go

errChan should not be closed otherwise the function that requests the
manual stop might find it closed.

tests: fix TestIssue419

---

service/dap/server.go
service/dap/server_test.go

When we set a limit on the number of threads that would be
returned, it was possible that the selected thread was not
included in the list of threads. This could cause issues
because the stopped reason is associated with the selected
goroutine, so users could be missing out on important info.
This change makes sure that the selected goroutine is included
by adding it to the end of the list.

service/dap: include selected goroutine in threads request

---

pkg/terminal/config.go

Commit 3d6bbbe9 made "config -list" print strings in quotes to avoid
the strings being interpreted as terminal escape codes.  This commit
does the same for "source-list-line-color", which is a raw interface.
This fixes "config -list" with a config like
source-list-line-color: "\x1b[34m"
The "int" variant is already printed correctly, so just use the
default case for that.

terminal: config -list to print strings inside interfaces in quotes

---

pkg/config/config.go

This commit allows to use either of the following two lines in
~/.config/dlv/config.yml to highlight keywords in red
source-list-keyword-color: "\x1b[31m"
source-list-keyword-color: 31
This was already possible for "source-list-line-color", which was also
in the default config with the integer syntax.
I don't have a strong opinion on whether we should support both, but
it took me a bit to figure out the correct syntax for "\x1b[31m"
(Are quotes required? Can I write \033 or \e instead of \x1b?)
so it seems alright to support bare numbers.

Prefer string variant for source-list-line-color config option

---

Documentation/installation/README.md
README.md

These 4 pages don't really have any value.
https://github.com/go-delve/delve/blob/master/Documentation/installation/linux/install.md
https://github.com/go-delve/delve/blob/master/Documentation/installation/osx/install.md
https://github.com/go-delve/delve/blob/master/Documentation/installation/windows/install.md
https://github.com/go-delve/delve/blob/master/Documentation/installation/freebsd/install.md

documentation: remove unnecessary pages for install instructions

---

_scripts/make.go

This change adds `--GOARCH=[arch]` and `--GOOS=[os]` as arguments for
the make script to simplify the process of cross compilling.

terminal/make: Add GOARCH and GOOS arguments

---

service/dap/server.go
service/dap/server_test.go

As discussed in golang/vscode-go#1459, users may want to see different representations of bytes and runes.
This change displays the hex value for all uints alongside the decimal value.
In addition to the variables response, this will impact the values in all evaluate contexts.
Examples:
```
myuint8: 255 = 0xff
myuint16: 65535 = 0xffff
myuint32: 4294967295 = 0xffffffff
myuint64: 18446744073709551615 = 0xffffffffffffffff
```

service/dap: show decimal and hex values for uint

---

pkg/goversion/go_version.go
pkg/goversion/version_test.go

This changes allow us to parse Go+BoringCrypto which formatted in <GoVersion>b<BoringCryptoVersion> so that we can surpress `Version of Go is too old for this version of Delve` error.
Fixes https://github.com/go-delve/delve/issues/2711

cmd/dlv: Parse Go+BoringCrypto version

---

_fixtures/fncall.go
pkg/dwarf/op/regs.go
pkg/proc/dwarf_expr_test.go
pkg/proc/mem.go
service/test/variables_test.go

Right now, if (*compositeMemory).WriteMemory needs to write a value to
a register that's smaller than the full size of the register (say, a
uint32 being passed as an argument), then (*AMD64Registers).SetReg can
later fail a sanity check that ensures the passed DwarfRegister is a
full size register.
Fix this by reading the old value of the register and overwriting just
the relevant parts with the new register. For the purposes of an
argument, it would probably be fine to just pad with zeroes, but merging
with the existing value is more generally correct.
Fixes #2698

pkg/proc: merge register data in (*compositeMemory).WriteMemory

---

Documentation/usage/dlv.md
Documentation/usage/dlv_attach.md
Documentation/usage/dlv_backend.md
Documentation/usage/dlv_connect.md
Documentation/usage/dlv_core.md
Documentation/usage/dlv_dap.md
Documentation/usage/dlv_debug.md
Documentation/usage/dlv_exec.md
Documentation/usage/dlv_log.md
Documentation/usage/dlv_redirect.md
Documentation/usage/dlv_replay.md
Documentation/usage/dlv_run.md
Documentation/usage/dlv_test.md
Documentation/usage/dlv_trace.md
Documentation/usage/dlv_version.md
cmd/dlv/cmds/commands.go
pkg/goversion/compat.go
pkg/logflags/logflags.go
service/debugger/debugger.go

Since Delve doesn't forcefully take out support for no-longer-supported versions, users and clients might want to turn off the version check to continue debugging with older versions of Go. Add a warning to notify them of the incompatibility in this case as well.  This will apply to too-new Go versions as well. Also, log the Go version.
Before
```
$ dlv debug _fixtures/increment.go 
Version of Go is too old for this version of Delve (minimum supported version 1.15, suppress this error with --check-go-version=false)
$ dlv debug _fixtures/increment.go --check-go-version=false
Type 'help' for list of commands.
(dlv)
```
After
```
$ ./dlv debug _fixtures/increment.go
Go version 1.14.15 is too old for this version of Delve (minimum supported version 1.15, suppress this error with …
```

pkg/goversion: visibly warn the user with --check-go-version=false

---

pkg/proc/breakpoints.go
pkg/proc/gdbserial/rr_test.go
pkg/proc/proc_test.go
pkg/proc/scope_test.go
pkg/proc/stackwatch.go
pkg/proc/target.go
service/api/conversions.go
service/debugger/debugger.go

Internal breakpoints do not need IDs and assigning them from a counter
separate from the user ID counter can be a cause of confusion.
If a user breakpoint is overlayed on top of a pre-existing internal
breakpoint the temporary ID will be surfaced as if it was a user ID,
possibly conflicting with another user ID.
If a temporary breakpoint is overlayed on top of a pre-existing user
breakpoint and the user breakpoint is first deleted and then
re-created, the user ID will be resurrected along with the breakpoint,
instead of allocating a fresh one.
This change removes internal breakpoint IDs entirely, only user
breakpoints receive an ID.

proc: do not assign temporary breakpoint IDs

---

service/dap/server.go
service/dap/server_test.go

This change splits `dap.Server`
- `Server` - starts run goroutine, accept a client, starts `Session` for client connection and shuts down on stop signal
- `Session` - handles the traffic for an open generalized `io.ReadWriteCloser` connection and triggers server's `Stop` on user disconnect or connection error
This will allow `rpccommon.Server` to use `dap.Session.serveDAPCodec` as a `rpccommon.ServerImpl.ServeJSONCodec` alternative.

service/dap: refactor the server into two layers

---

Documentation/backend_test_health.md
Documentation/cli/README.md
_fixtures/databpeasy.go
_fixtures/databpstack.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/gdbserver_conn.go
pkg/proc/proc_test.go
pkg/proc/stackwatch.go
pkg/terminal/command.go

Adds watchpoint support to gdbserver backend for rr debugger and
debugserver on macOS/amd64 and macOS/arm64.

proc/gdbserver: support watchpoints

---

service/dap/server.go
service/dap/server_test.go

Separating the args and the locals scopes in DAP currently provides a worse user experience, since VS Code only auto expands the first non-expensive scope (microsoft/vscode#93230). To handle this, we combine the args and the locals into a single scope, with the arguments appearing first.
Fixes golang/vscode-go#1798

service/dap: merge arguments and local scopes

---

_fixtures/goroutinebreak.go
service/dap/server.go
service/dap/server_test.go

Determining the stopped goroutine id on a breakpoint required
checking for breakpoints since some may be tracepoints. However,
there may be goroutines stopped on hardcoded breakpoints with
no breakpoint. We fix this by checking for runtime.breakpoint or
StopReason=proc.StopHardcodedBreakpoint.

service/dap: fix goroutine id selection for hardcoded breakpoints

---

Documentation/backend_test_health.md
pkg/proc/native/threads_windows.go
pkg/proc/proc_test.go

There are persistent issues with watchpoints on Windows, it is not
clear whether it's a problem with the VM running the tests or if there
is a real bug in our implementation of hardware breakpoints on Windows.
Until the cause can be determined watchpoints on Windows will be
disabled.
Updates #2768

proc/native: disable watchpoints on Windows

---

_fixtures/setymmreg/main.go
_fixtures/setymmreg/setymmreg_amd64.s
pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/gdbserver_conn.go
pkg/proc/proc_test.go

Debugserver has a bug where writing to a AVX-2 or AVX-512 register does
not work unless it is followed by at least a write to a AVX (not 2 or
512) register.
See also: https://bugs.llvm.org/show_bug.cgi?id=52362
Fixes #2767

proc/gdbserial: workaround for debugserver register set bug

---

_scripts/test_windows.ps1

Shaves off 3 minutes out of every windows build.

TeamCity: disable Windows Defender

---

cmd/dlv/dlv_test.go
service/dap/server.go

If connection is closed while the debuggee is running, any pending goroutine handling the running command and analyzing its stop reasons should stop right away without calling any debugger methods as the debugger pointer would have already been cleared at session closure.
This fixes the following failure that especially impacts repeated remote attach to a multi-client server, but can also show up when server is shutting down:
```
2021-11-08T00:12:34-08:00 error layer=dap recovered panic: runtime error: invalid memory address or nil pointer dereference
goroutine 50 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/go-delve/delve/service/dap.(*Session).recoverPanic(0xc0002421c0, {0x16c43e0, 0xc000ea32f0}) …
```

server/dap: stop running command if conn closed - fixes nil dereference bug

---

service/dap/command.go
service/dap/server_test.go

This change exposes the list sources feature in the debug console in order to facilitate easier substitute path mappings. When user's have symlinks, are debugging on a remote host, or use trimpath to build, the source paths may not line up with the source files sent from the dap client. By allowing users to see the source names that the program was actually built with, this will allow users to more easily set up a correct configuration of substitutePath to debug their programs.
Updates #2795

service/dap: expose sources command in evaluate request

---

_scripts/test_linux.sh

The version check to disable the buildvcs option is wrong, it doesn't
matter now but it will start failing when 1.18.1 is released.

_scripts: fix test_linux.sh version check

---

pkg/version/fixbuild.go
pkg/version/version.go

In go1.18 buildInfo will include the git revision hash, use that to fix
the Build field of Version so that it is correct even if Delve wasn't
built using make.go.

version: fix build version using buildInfo

---

service/dap/daptest/client.go
service/dap/server_test.go

This fixes 2 issues:
(1) `testNextParkedHelper` now correctly processes `TerminatedEvents`.
(2) Test harness used by `TestNextParked` and other tests now does not care about the exit status of a terminated target. This will minimize [flakiness in tests](#2762) that do not care about exit status. This part of the fix is suggested as an alternative to #2765.
Fixes #2762

service/dap: fix TestNextParked

---

pkg/proc/core/core.go
pkg/proc/core/core_test.go
pkg/proc/dump.go
pkg/proc/eval.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/interface.go
pkg/proc/native/dump_linux.go
pkg/proc/native/nonative_darwin.go
pkg/proc/native/proc.go
pkg/proc/native/proc_darwin.go
pkg/proc/native/proc_freebsd.go
pkg/proc/native/proc_linux.go
pkg/proc/native/proc_windows.go
pkg/proc/proc_test.go
pkg/proc/scope_test.go
pkg/proc/target.go
service/debugger/debugger.go
service/test/variables_test.go

* made Pid a field of Target instead of a method of Process
* changed argument of NewTarget to ProcessInternal, since that's the
interface that backends have to implement
* removed warnings about ProcessInternal since there is no way for
users of pkg/proc to access those methods anyway
* made RecordingManipulation an optional interface for backends, Target
supplies its own dummy implementation when the backend doesn't
* inlined small interfaces that only existed to be inlined in
proc.Process anyway
* removed unused function findExecutable in the Windows and no-native
darwin backends
* removed (*EvalScope).EvalVariable, an old synonym for EvalExpression

proc/*: minor miscellaneous code cleanups

---

pkg/proc/bininfo.go

Updates #2786
Because of an incorrect use of debug/dwarf.Reader errors encountered
while reading debug_info were not reported.
Updates #2786

proc: support DWARF5 on Windows/macOS

---

service/dap/server.go
service/dap/server_test.go

This change visually indicates which frames are runtime code using frame.presentationHint. This removes "deemphasize" from the source presentation hint. "deemphasize" indicated that the source should be skipped in stepping, causing the frames to be collapsed. This was inconvenient for users if they wanted to inspect the runtime code that they were stepping through.
Updates golang/vscode-go#1916

service/dap: move presentationHint to frame from source

---

pkg/proc/internal/ebpf/bpf/dummy.go
pkg/proc/internal/ebpf/bpf/include/dummy.go
pkg/proc/internal/ebpf/dummy.go

Add some dummy go files so that 'go mod vendor' works for modules that
require Delve, becuase directories that do not contain any go code will
not be vendored.

proc: add dummy files to fix vendoring of Delve

---

_fixtures/asmnilptr/main.go
_fixtures/asmnilptr/main_386.s
_fixtures/asmnilptr/main_amd64.s
_fixtures/asmnilptr/main_arm64.s
pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/gdbserver_conn.go
pkg/proc/native/ptrace_linux.go
pkg/proc/native/threads_linux.go
pkg/proc/proc_test.go

Fix signal handling during thread single stepping so that signals that
are generated by executing the current instruction are immediately
propagated to the inferior, while signals other signals sent to the
thread are delayed until the full resume happens.
Fixes a bug where a breakpoint set on an instruction that causes a
SIGSEGV would make Delve hang and a bug where signals received during
single step would make it look like an instruction is executed twice.
Fixes #2801
Fixes #2792

proc: fix signal handling during stepping

---

cmd/dlv/dlv_test.go
service/dap/daptest/client.go
service/dap/server.go
service/dap/server_test.go
service/dap/types.go

- Improve mismatched launch/attach request/mode errors
- Log if process was halted/running on client exit
- Update attach config comments to include new remote mode
Updates #2328

service/dap: misc remote attach improvements

---

pkg/terminal/command.go

Prior to this, sending a `deferred` command with no arguments would immediately
crash the debug session.

terminal/command: fix up OoB in `deferred` command

---

pkg/proc/breakpoints.go
pkg/proc/gdbserial/gdbserver.go
service/debugger/debugger.go
service/test/integration2_test.go

It is sometimes useful to set breakpoints and rewind a terminated
process when using rr, for example if interested in the last execution
of some function.
RR will not allow a backward continue after the process exit packet has
been  sent, however rr will also generate a synthetic SIGKILL right
before process exit.
Treat this packet as a process exit and change some things so both
continuing backwards and setting breakpoints can be done, on recorded
targets, after process exit has been reported.
If Restart is called after a Continue and Rewind on a recorded target
that has already terminated it will return an internal error.

proc/gdbserial: allow rewind to work after process exit with rr

---

service/api/conversions.go
service/debugger/debugger.go
service/test/integration2_test.go

When printing breakpoints on generic functions use the function name
without parameters instead of using the name of the first instantiation
that appears on the list.

service: use name w/o parameters for breakpoints on generic funcs

---

pkg/proc/native/dump_linux.go

proc/native: ignore 'pf' mappings during core dump creation

---

.teamcity/settings.kts
_scripts/test_linux.sh
_scripts/test_mac.sh
_scripts/test_windows.ps1
go.mod
go.sum
pkg/goversion/compat.go
pkg/proc/native/proc.go
pkg/proc/proc_test.go
pkg/proc/stack.go
pkg/proc/test/support.go
service/dap/server_test.go
vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
vendor/golang.org/x/tools/go/internal/gcimporter/support_go118.go
vendor/golang.org/x/tools/internal/typeparams/common.go
vendor/golang.org/x/tools/internal/typeparams/normalize.go
vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
vendor/modules.txt

Asyncpreempt on linux/arm64 can sometimes restart a sequence of
instructions which will make breakpoint appear to be hit twice in some
cases.
Make sure that stacktrace registers always contain the PC register of
the current frame, even though the debug_frame rules might not specify
it on architectures that use a link register.
The PC register is needed to look up loclist entries for variable
evaluation.
Add 1.18 to test matrix. Remove 1.15 from test matrix and from support range.
Fixes TestGeneratedDoc on go1.18

Updates for go1.18beta1

---

Documentation/cli/README.md
pkg/terminal/command.go

This could probably be more user-friendly, in that you can't give a name
to such a breakpoint.  To add support for names, we would need to try
a single arg first as a location, and if that fails try it as a name for
current line.  That seems somewht dubious, so I didn't try.
Fixes #2788

Support `b` and `t` without a linespec

---

Documentation/usage/dlv.md
Documentation/usage/dlv_attach.md
Documentation/usage/dlv_backend.md
Documentation/usage/dlv_connect.md
Documentation/usage/dlv_core.md
Documentation/usage/dlv_dap.md
Documentation/usage/dlv_debug.md
Documentation/usage/dlv_exec.md
Documentation/usage/dlv_log.md
Documentation/usage/dlv_redirect.md
Documentation/usage/dlv_replay.md
Documentation/usage/dlv_run.md
Documentation/usage/dlv_test.md
Documentation/usage/dlv_trace.md
Documentation/usage/dlv_version.md
cmd/dlv/cmds/commands.go

commands: update DAP overview in help

---

Documentation/api/README.md
Documentation/api/dap/README.md

I am still figuring out what to do with [api/ClientHowto.md](https://github.com/go-delve/delve/blob/master/Documentation/api/ClientHowto.md). It should either be moved as-is under [api/json-rpc](https://github.com/go-delve/delve/tree/master/Documentation/api/json-rpc) or we can keep the parts common to both JSON-RPC and DAP at the `api/` level and move JSON-RPC specific sections into [api/json-rpc/README.md](https://github.com/go-delve/delve/blob/master/Documentation/api/json-rpc/README.md).
Updates #1515

Documentation: add DAP API page

---

pkg/proc/variables.go

packages
Changes UserCurrent to exclude frames stopped inside the 'internal' and
'runtime/internal' packages of the standard library.
Before this change a goroutine blocked accepting or reading from a
socket would be reported as having a user current frame of:
internal/poll.runtime_pollWait
After this change accepting goroutines will be reported with a user
current frame of:
net.(*netFD).accept
and reading goroutines as:
net.(*netFD).read

proc: change UserCurrent to exclude internal and runtime/internal

---

pkg/proc/bininfo.go

All values greater than or equal to 1 indicate that the function has
been inlined.

proc: interpret value of DW_AT_inline correctly

---

Documentation/cli/README.md
pkg/terminal/command.go

Fixes #2870 (Documentation for "rewind" command is misleading)

Documentation: improve wording for "rewind" command (#2870)

---

pkg/proc/bininfo.go

Signed-off-by: Morten Linderud <morten@linderud.pw>

bininfo: Strip whitespace from debuginfod-find output

---

pkg/proc/bininfo.go

Always load eh_frame section from the executable file instead of the
split debug info file. The eh_frame section is meant to be loaded in
memory along with the executable file so it will usually not be present
in a split debug info file (or, if it is present, it will be the wrong
one).

proc: always load eh_frame section from executable

---

service/dap/daptest/client.go
service/dap/server_test.go

1. change ExpectOutputEventProcessExited to accept -1 exit status, this
is a real problem on linux but we don't know how to fix it and we
already have a test in proc for it.
2. change TestNoDebug_AcceptNoRequestButDisconnect to be less picky
about message ordering, all message orderings seem to be fine, there
is no reason to insist on a particular one, since the DAP server is
unable to actually produce it deterministically.
Fixes #2860

service/dap: deflake DAP tests

---

_fixtures/doubleinline.go
pkg/proc/bininfo.go
pkg/proc/proc_test.go

It's possible that an inlined function call also contains an inlined
subroutine. In this case we should also parse the children of
inlined calls to ensure we don't lose this information.

pkg/proc: handle double inlined calls

---

Documentation/cli/starlark.md

The ext should be '.star' instead of '.start' when starlark script.
Fix #1466

Documentation: fix typo

---

pkg/proc/native/proc.go

Core dumping for Windows was implemented a while ago but never enabled.

proc: enable core dumping on windows

---

Documentation/cli/README.md
cmd/dlv/cmds/commands.go
cmd/dlv/dlv_test.go
pkg/terminal/command.go
pkg/terminal/command_test.go
pkg/terminal/starbind/repl.go
pkg/terminal/starbind/starlark.go
pkg/terminal/terminal.go

Adds a transcript command that appends all command output to a file.
This command is equivalent to gdb's 'set logging'.
As part of this refactor the pkg/terminal commands to always write to a
io.Writer instead of using os.Stdout directly (through
fmt.Printf/fmt.Println).

terminal: add transcript command

---

Documentation/cli/starlark.md
_scripts/gen-starlark-bindings.go
pkg/proc/bininfo.go
pkg/proc/debuginfod/debuginfod.go
pkg/terminal/command.go
pkg/terminal/starbind/starlark_mapping.go
service/client.go
service/debugger/debugger.go
service/rpc2/client.go
service/rpc2/server.go

This pull-request does  a few things.
We implement a BuilID call in the RPC so the client can figure out which binary it's working on.
We implement support for fetching file listing through `debuginfod-find` if they are not present locally.
Then lastly we try to remove a bit of the duplicated code around dealing with `debuginfod-find`.
I'm not sure how much testing you want around this, or if new package belongs under `pkg/proc/debuginfod`. Feel free to nitpick and I'll try fix up all the issues around this patch :)

Implement source listing from debuginfo

---

_scripts/gen-starlark-bindings.go

Fix camelToDash so that it handles BuildID and CreateEBPFTracepoint
correctly.

_scripts: fix camelToDash in gen-starlark-bindings.go

---

pkg/proc/bininfo.go

If debugInfoDirectories is set, the executable does not have debug info
and build-id is not set we should not crash.

proc: fix crash trying to open separate debug info

---

pkg/proc/bininfo.go

Most binaries do not have build-ids and it's fine, there's no reason to
report it as an error.

proc: downgrade loadBuildID errors to warnings

---

Documentation/cli/README.md
pkg/terminal/command.go
pkg/terminal/command_test.go

This change adds the 'clearcond' which will clear condtion on a breakpoint.

pkg/terminal: add '-clear' option to 'condition' command

---

pkg/proc/eval.go
pkg/proc/eval_go117.go
pkg/proc/eval_go118.go
pkg/proc/fncall.go
service/test/variables_test.go

Try to produce better error messages when we can't distinguish between
a function call and a type cast.
Fixes #2902

proc: better error messages for ambiguous function calls/type casts

---

Documentation/backend_test_health.md
_fixtures/hcbpcountstest.go
pkg/proc/breakpoints.go
pkg/proc/core/core.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/native/nonative_darwin.go
pkg/proc/native/proc_windows.go
pkg/proc/native/threads_darwin.go
pkg/proc/native/threads_freebsd.go
pkg/proc/native/threads_linux.go
pkg/proc/native/threads_windows.go
pkg/proc/proc_test.go
pkg/proc/target_exec.go
pkg/proc/threads.go

This commit improves the handling of hardcoded breakpoints in Delve.
A hardcoded breakpoint is a breakpoint instruction hardcoded in the
text of the program, for example through runtime.Breakpoint.
1. hardcoded breakpoints are now indicated by setting the breakpoint
field on any thread stopped by a hardcoded breakpoint
2. if multiple hardcoded breakpoints are hit during a single stop all
will be notified to the user.
3. a debugger breakpoint with an unmet condition can't hide a hardcoded
breakpoint anymore.

proc: better handling of hardcoded breakpoints

---

pkg/proc/native/ptrace_linux.go
pkg/proc/native/ptrace_linux_386.go
pkg/proc/native/ptrace_linux_64bit.go

Replaces sys.Iovec with a similar struct that uses uintptr instead of
*byte for the base field when referring to addresses of the target
process, so that we do not generate invalid pointers.
Fixes #2919

proc/native/linux: replace uses of unix.Iovec for target addresses

---

pkg/proc/core/core.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/gdbserver_conn.go
pkg/proc/interface.go
pkg/proc/native/nonative_darwin.go
pkg/proc/native/proc.go
pkg/proc/native/proc_darwin.go
pkg/proc/native/proc_freebsd.go
pkg/proc/native/proc_linux.go
pkg/proc/native/proc_windows.go
pkg/proc/target.go
pkg/proc/target_exec.go

Moves handling of ResumeNotify and manualStopRequested to Target instead of the backends
Updates #2551

proc: move resume notify and manual stop handling to Target

---

cmd/dlv/dlv_test.go
service/dap/daptest/client.go
service/dap/server.go
service/dap/server_test.go

I realized that we end up with Stop and Disconnect options both for Attach (correct) and Launch (incorrect). So change the code to request this capability in Attach cases only. This also sets us up for when suspendDebuggee option is added, which should only apply to remote attach (microsoft/vscode#134412). Turns out this currently makes no difference in the UI - filed an issue (microsoft/vscode#145650).

service/dap: support terminateDebuggee option for attach only

---

Documentation/cli/README.md
pkg/terminal/command.go

Often in the CLI documentation we were to inputs as linespec when in reality we mean locspec which is a
location specifier, not necessarily a line specifier.

Prefer locspec to linespec

---

_fixtures/testvariables2.go
pkg/proc/variables.go
service/api/conversions.go
service/api/prettyprint.go
service/dap/server_test.go
service/test/variables_test.go

proc,service: pretty print time.Time variables

---

cmd/dlv/dlv_test.go
service/debugger/debugger.go

Updates golang/vscode-go/issues/182

debugger: clarify no debug info errors

---

_scripts/make.go

Something changed in TeamCity's infrastructure that makes 'git
rev-parse HEAD' fail systematically on most configurations.
Since the SHA ID isn't necessary anyway, print an error and continue.

_scripts/make: do not exit if git SHA ID can not be retrieved

---

Documentation/cli/README.md
pkg/terminal/command.go

This missing blank line breaks the example block, every lines are inlined in a single one.

Fix example block in cli README

---

Documentation/api/dap/README.md

Add usage details for each of the configuration/server options in response to confusion in https://github.com/emacs-lsp/dap-mode/issues/318.

Documentation: expand DAP launch/attach configurations section

---

service/debugger/debugger_unix_test.go

FreeBSD does not have lsof, rather it has fstat. Additionally, the TTY name
does not match up with the current code.

service/debugger: make TestDebugger_LaunchWithTTY pass on FreeBSD

---

pkg/proc/native/registers_freebsd_amd64.go

These are needed for delve to work on freebsd/amd64 with regabi.

proc: add support for setting additional registers on freebsd/amd64

---

service/debugger/debugger_unix.go
service/debugger/debugger_windows.go

Close executable file after we open it.

service/debugger: close executable file

---

_scripts/test_mac.sh

So that we can mute failing tests in TeamCity.

_scripts: always return exit code 0 when testing on tip

---

_scripts/test_linux.sh
_scripts/test_windows.ps1

Same as what we do for test_mac.sh

_scripts/test_linux.sh: always return exit code 0 when testing on tip

---

.cirrus.yml
pkg/proc/target.go
pkg/proc/test/support.go
service/test/variables_test.go

On FreeBSD it seems we have problems restoring and setting floating
point registers, since at least restoring is necessary for call
injection to function properly fully disable call injection on FreeBSD.
On rr the same problem exists, however due to the fact that we are
acting on a recording and ending a diversion will restore register
values anyway simply disable the floatsum test.
See also: https://github.com/rr-debugger/rr/issues/3208
Updates #3001

proc: fixes concerning call injection on freebsd and rr

---

pkg/proc/gdbserial/gdbserver.go
pkg/proc/proc_test.go
service/test/variables_test.go

Issue https://github.com/rr-debugger/rr/issues/3208 was fixed so finish
fixing call injection on rr and remove the test exception.

proc/gdbserver: fix function call injection on rr

---

pkg/proc/target.go

Also set breakpoint on runtime.fatal, which didn't exist before go1.19.
Updates #2993

proc: fix fatal throw breakpoint on go1.19

---

pkg/terminal/terminal.go

Add auto-complete for local variables when using `print` or `whatis` commands.

Add auto-complete for local variables

---

pkg/proc/breakpoints.go
pkg/proc/gdbserial/rr_test.go
pkg/proc/proc_test.go
pkg/proc/stackwatch.go
pkg/proc/target.go
pkg/proc/target_exec.go
service/api/conversions.go
service/dap/server.go
service/debugger/debugger.go
service/rpc1/server.go
service/rpc2/server.go

Adds a LogicalBreakpoint type to represent logical breakpoints
explicitly. Until now logical breakpoints were constructed implicitly
by grouping physical breakpoints together by their LogicalID.
Having logical breakpoints represented explicitly allows for a simpler
implementation of disabled breakpoints, as well as allowing a simple
implementation of delayed breakpoints (#1653, #2551) and in general of
breakpoints spanning multiple processes if we implement debugging
process trees (#2551).
Updates #1653
Updates #2551

proc,service: represent logical breakpoints explicitly

---

_scripts/test_windows.ps1
pkg/proc/native/registers_windows_amd64.go

Commit b53fcbe broke the build on Windows, we didn't notice because 2d9a9d broke the test script.

proc/native: fix Windows build

---

go.mod
go.sum
vendor/modules.txt

go.mod: use pseudo verion for github.com/go-delve/liner

---

_fixtures/xmm0print/main.go
_fixtures/xmm0print/main.s
_scripts/test_windows.ps1
pkg/proc/native/registers_windows_amd64.go
pkg/proc/variables.go
service/test/integration2_test.go

Fix pretty printing for CPU register components (created with the
XMM0.uintN syntax) while using format strings
Also fixes printing large literal constants with format strings.
Fixes #3020

proc: fix prettyprint for register components with large values

---

pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/gdbserver_conn.go

When we send an interrupt request to debugserver we, sometimes, get one
extra spurious stop packet back.
This stop packet gets interpreted as a response to a qThreadStopInfo request
we make causing the protocol to become desynchronized for a while, until
eventually some kind of error appears.
Here's an example of this problem, distilled from issue #3013:
```
1 <- $vCont;c#a8
2 <- interrupt
3 -> $T05thread:12efb47;threads:12efb47,12efb8d,12efb8e,12efb8f,12efb90,12efb91;thread-pcs:10abe83,7ff81b20e2be,7ff81b20e3ea,...
4 <- $qThreadStopInfo12efb8e#28
5 -> $T05thread:12efb47;threads:12efb47,12efb8d,12efb8e,12efb8f,12efb90,12efb91;thread-pcs:10abe83,7ff81b20e2be,7ff81b20e3ea,...
6 <- $qThreadStopInfo12efb8f#29
7 -> $T00thread:12efb8e;threads:12efb47,12efb8d,12efb8e,12efb8f,12efb90,12efb91;threa …
```

proc/gdbserver: ignore spurious stop packet from debugserver

---

pkg/proc/eval.go
pkg/proc/variables_test.go

When doing a map lookup with a string literal we should load as much of
the keys to at least match the length of the string literal, so that
the lookup doesn't fail with the "string too long" error.
Fixes #3034

proc: map access with string literal key should always succeed

---

pkg/proc/native/proc_windows.go

In non-headless instances Ctrl-C should pause the process, not
terminate it. To make this work on Windows we have to pass the
syscall.CREATE_NEW_PROCESS_GROUP flag to os.StartProcess.

proc/native: fix Ctrl-C handling on non-headless instances on windows

---

pkg/dwarf/frame/entries.go
pkg/dwarf/frame/parser.go

We don't do anything with the personality function so there is no point
in complaining that we don't fully support the pointer encoding flags
used to describe it.
This matches the current level of support of pointer encodings in gdb
(they are discarded when reading the personality function and not
supported for FDEs because gcc doesn't generate them).
Fixes #3015

dwarf/frame: discard indirect flag reading personality func in eh_frame

---

_scripts/test_windows.ps1

The version of mingw was pinned to 10.2.0 because mingw 11 started
using DWARFv5, which wasn't supported by Go 1.17. We are now testing
only 1.18 and 1.19 and both support DWARFv5 correctly.

_scripts: un-pin mingw version

---

pkg/config/config.go
pkg/terminal/command.go
pkg/terminal/command_test.go
pkg/terminal/disasmprint.go

Adds ability to show current position as disassembly instead of source
listing every time execution stops. Change default to show disassembly
after step-instruction and source listing in every other case.
Fixes #2878

terminal: add ability to show disassembly instead of source

---

pkg/proc/breakpoints.go
pkg/proc/core/core.go
pkg/proc/core/core_test.go
pkg/proc/fncall.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/rr_test.go
pkg/proc/interface.go
pkg/proc/native/proc.go
pkg/proc/proc_export_test.go
pkg/proc/proc_test.go
pkg/proc/proc_unix_test.go
pkg/proc/stackwatch.go
pkg/proc/target.go
pkg/proc/target_exec.go
pkg/proc/target_group.go
pkg/proc/variables_test.go
service/dap/server.go
service/debugger/debugger.go
service/debugger/debugger_darwin.go
service/debugger/debugger_freebsd.go
service/debugger/debugger_linux.go
service/debugger/debugger_windows.go

Introduces a new TargetGroup abstraction that can be used to manage
multiple related targets.
No actual management of child processes is implemented here, this is
just a refactoring to make it possible to do that in the future.
Updates #2551

proc,service/debugger: introduce TargetGroup abstraction

---

_fixtures/cgodisass.go
service/dap/server.go
service/dap/server_test.go

Due to dyanmically loaded libraries there could be aribitrarily large
gaps in the address space, between functions. Limit the memory size we
are willing to disassemble.
Fixes #3040

service/dap: limit disassembly range

---

pkg/dwarf/op/op.go
pkg/dwarf/op/op_test.go
pkg/dwarf/regnum/i386.go
pkg/proc/amd64_arch.go
pkg/proc/arch.go
pkg/proc/arm64_arch.go
pkg/proc/bininfo.go
pkg/proc/dwarf_expr_test.go
pkg/proc/i386_arch.go
pkg/proc/target.go

Output the architecture specific register name when printing location
expression after DW_OP_regN and DW_OP_bregN operators.

dwarf/op,proc: output register name when printing location exprs

---

Documentation/usage/dlv_trace.md
cmd/dlv/cmds/commands.go
pkg/proc/breakpoints.go

1. return an error when SetUProbe fails, while creating ebpf tracepoints
2. if no tracepoint can be set for 'dlv trace' exit early
3. never leave the traced program running
4. fix typo in description of --ebpf flag

cmd/dlv,proc: misc improvements to trace subcommand

---

_scripts/test_linux.sh
cmd/dlv/dlv_test.go
pkg/proc/disasm.go
pkg/proc/internal/ebpf/helpers.go
pkg/proc/internal/ebpf/helpers_disabled.go
pkg/proc/internal/ebpf/helpers_test.go
pkg/proc/internal/ebpf/testhelper/testhelper.go

The ebpf implementations uses cgo, but only to access some C struct
definitions. Instead of using cgo simply duplicate the defintion of
those two structs in Go and add a test to check that the duplicate
definitions remain synchronized.
Fixes #2827

proc/internal/ebpf: drop dependency on cgo

---

pkg/locspec/locations.go
pkg/terminal/terminal_test.go
service/dap/server.go

In order to support substituting a single file within
a larger package, and not substituting a directory wholesale,
this commit introduces the ability for SubstitutePath
to replace individual file paths if there is an exact match.
This behavior is backwards-compatible with the previous
configuration.
Fixes #3074

pkg/locspec: support exact match in SubstitutePath

---

pkg/proc/bininfo.go
pkg/proc/proc_test.go

Load separate debug info using gnu_debuglink.
Fixes #2150

proc: support gnu_debuglink section

---

service/dap/server.go
service/dap/server_test.go

There was a bug that cut off the second half of a map, because the
number of variables was not accurately reported to the client.
Fixes golang/vscode-go#2351

service/dap: fix indexing bug for maps

---

_fixtures/break/break_amd64.s
_fixtures/break/main.go
pkg/proc/proc_test.go
pkg/proc/target_exec.go

For architectures that `BreakInstrMovesPC() == true`, `StepInstruction` does not move forward the PC when the PC is on an instruction with the same size as the breakpoint (1 byte for amd64) and there is a software breakpoint active on that instruction.
This happens because `StepInstruction` calls `SetCurrentBreakpoint(true)` after advancing the PC, which sees a breakpoint and moves the PC 1 instruction backwards, ending at the same original point. This bug is difficult to trigger becase the breakpoint instruction is small, just one byte.
This PR changes `StepInstruction` to call `SetCurrentBreakpoint(false)` instead.
I've found this while working on #3063, where this issue is hit more times because all instructions have the same length.
@aarzilli @derekparker

Fix StepInstruction on 1 byte instruction with a software breakpoint

---

Documentation/cli/README.md
pkg/terminal/command.go

The 'addr' option was removed during review and doesn't exist.
Fixes #3086

Documentation: fix documentation of examinemem

---

_fixtures/goroutines-trace.go
cmd/dlv/cmds/commands.go
cmd/dlv/dlv_test.go
pkg/proc/threads.go
pkg/terminal/command.go
pkg/terminal/terminal.go

This patch improves the output of the trace subcommand by
adding better line breaks, adding goroutine info to the
return statement, and removing unnecessary output.

:* Improve trace subcommand output

---

pkg/dwarf/line/line_parser.go
pkg/dwarf/line/state_machine.go
pkg/proc/proc_test.go

As we parse this informatin in the loop we must take care to assemble
things correctly. In this situation when we encounter a file name,
the dir index is -1, then subsequently we get the correct dir index
for that file and can put them together. Previously we were adding the
file and then the directory location to the file list instead of
correctly concatenating them, resulting in an incorrect file list making
indexing into the list return incorrect results later on.

pkg/dwarf/line: Fix parsing file table for DWARFv5

---

.teamcity/settings.kts
pkg/goversion/compat.go

Add Go 1.19 to test matrix, drop 1.16.

TeamCity,goversion: bump test matrix

---

_scripts/test_linux.sh

We should exclude rc/beta versions as we already run tests
against tip, we don't explicitly test RC versions.

_scripts: fix command to download Go version

---

pkg/proc/eval.go
pkg/proc/variables_test.go

We allowed integer and pointer type casts everywhere but type casts to
string, []byte and []rune only at toplevel.
Fuse evalToplevelTypeCast and evalTypeCast and allow both kinds
everywhere. There are multiple other ways to create variables than
don't reference user memory anyway (which wasn't the case back when
evalToplevelTypeCast was implemented).
Fixes #1423

proc: fuse evalToplevelTypeCast and evalTypeCast

---

pkg/config/split.go
pkg/config/split_test.go
pkg/locspec/locations.go
pkg/locspec/locations_test.go
service/dap/config_test.go
service/dap/types.go

This changes adds the support to replace relative paths sources with "" as representing current directory.
For example:
Rule like '{from: "", to: "/my/project"}' will map path "src/my/code.go" into "/my/project/src/my/code.go"
Rule like '{from: "/my/project", to: ""}' will map path "/my/project/src/my/code.go" into "src/my/code.go"
Solves #3082

service/dap: Add support for empty string in substitutePath

---

_scripts/make.go
_scripts/test_linux.sh
cmd/dlv/dlv_test.go
pkg/proc/test/support.go

Go 1.19 is broken on linux/386 with some C compilers, this is a
workaround for our build script. See:
https://github.com/golang/go/issues/52919
Also fix TestBuild if the first message reported by delve is not the
message that indicates the server is listening.

_scripts: fix CI on go1.19/linux/386

---

_scripts/rtype-out.txt
_scripts/rtype.go
pkg/proc/breakpoints.go
pkg/proc/eval.go
pkg/proc/goroutine_cache.go
pkg/proc/proc_test.go
pkg/proc/target.go
pkg/proc/variables.go
pkg/terminal/command.go
service/api/conversions.go
service/api/types.go
service/client.go
service/dap/server.go
service/debugger/debugger.go
service/rpc1/client.go
service/rpc1/server.go
service/rpc2/client.go
service/rpc2/server.go
service/test/integration1_test.go

Go 1.20 switched to uint64 to represent goroutine IDs, we can't
actually follow suit because we have allowed clients to use -1 to refer
to the currently selected goroutine, however we should at least switch
to int64 and also update the rtype check to accept the 1.20 type.

*: switch to int64 for goroutine IDs

---

Documentation/usage/README.md
pkg/terminal/command.go
pkg/terminal/command_test.go
pkg/terminal/out.go
pkg/terminal/terminal.go

For commands that could produce large amounts of output switch to a
pager command ($DELVE_PAGER, $PAGER or more) after a certain amount of
output is produced.
Fixes #919

terminal: send large output to pager

---

_fixtures/test.c
pkg/proc/target_group.go
pkg/proc/test/support.go
service/test/integration2_test.go

The logical breakpoints map was created as a side effect of
createUnrecoveredPanicBreakpoint or createFatalThrowBreakpoint, however
with an executable with incomplete debug info (that must be incomplete
in just the right way) both will fail and the logical breakpoint map
will never be created.
It's unknown how such an executable could be created, one easy way is
to debug a non-go executable.
Fixes #3114

proc: make sure logical breakpoints map exists

---

Documentation/EditorIntegration.md

Added Debugger to the list of UIs as suggested [here](https://github.com/go-delve/delve/discussions/3126#discussioncomment-3491801)

Add Debugger to UIs list in EditorIntegration

---

Documentation/cli/README.md
pkg/terminal/command.go
pkg/terminal/docgen.go

Remove leftover references to $GOPATH in documentation, change script
that generates markdown documentation to look for substrings that start
with "Documentation/" instead.

terminal: remove leftover GOPATH references

---

pkg/terminal/command.go

g.waitsince is the output of runtime.nanotime and represents a
monotonic clock which can not be converted directly into unix time. A
better fix would be to convert it to a time.Duration by reading the
current value of runtime.nanotime. This is complicated, however,
because on some systems (for example macOS) the current value of
runtime.nanotime can only be read by making a system call.
Updates #3137

terminal: do not use WaitSince as unix time

---

pkg/proc/bininfo.go
pkg/proc/variables_test.go

Fix cast to empty interface type. This is a workaround for a
discrepancy between how type names are serialized by the compiler vs
how type expressions are formatted by go/printer.

proc: fix cast to empty interface type

---

pkg/proc/bininfo.go

Fix openSeparateDebugInfo backwards compatibility path to actually be
backwards compatible.

proc: fix openSeparateDebugInfo backwards compatibility path

---

_scripts/rtype-out.txt
_scripts/rtype.go
cmd/dlv/dlv_test.go
pkg/proc/variables.go

Adds some rtype annotations for g.atomicstatus and update
_scripts/rtype.go to handle types outside of the runtime package.

proc,_scripts/rtype.go: add rtype annotations for g.atomicstatus

---

service/dap/server.go
service/dap/server_test.go

When evaluating variables in a log message, do not truncate the string representation.
Updates golang/vscode-go#2447

service/dap: show full value when evaluating log messages

---

pkg/locspec/locations.go
pkg/proc/target_group.go
pkg/terminal/command.go
service/api/conversions.go
service/api/types.go
service/dap/server.go
service/debugger/debugger.go

Changes FindLocation to support multiple targets and adds an AddrPid
member to api.Breakpoint so that clients can set breakpoints by address
when multiple targets are connected (but at them moment this field is
ignored).
Updates #1653
Updates #2551

proc,service: change FindLocation to work with multiple targets

---

Documentation/cli/starlark.md
_fixtures/testfnpos1.go
_fixtures/testfnpos2.go
pkg/proc/breakpoints.go
pkg/proc/target_group.go
pkg/terminal/command.go
pkg/terminal/starbind/starlark_mapping.go
service/client.go
service/dap/server.go
service/debugger/debugger.go
service/rpc1/server.go
service/rpc2/client.go
service/rpc2/server.go
service/test/integration2_test.go

Adds field to breakpoint struct to track how a breakpoint was
originally set, moves the logic for disabling and enabling a breakpoint
to proc.
This will allow creating suspended breakpoints that are automatically
enabled when a plugin is loaded. When follow exec mode is implemented
it will also be possible to automatically enable breakpoints (whether
or not they were suspended) on new child processes, as they are
spawned.
It also improves breakpoint restore after a restart, before this after
a restart breakpoints would be re-enabled using their file:line
position, for breakpoints set using a function name or a location
expression this could be the wrong location after a recompile.
Updates #1653
Updates #2551

proc,service/debugger: track how breakpoints were originally set

---

_fixtures/testvariables2.go
pkg/proc/eval.go
pkg/proc/variables.go
pkg/proc/variables_test.go
service/dap/server_test.go

Go allows some type casts when the underlying types are the same.
Conform to that behavior.
Fixes #3130

proc: allow type casts between compatible types

---

cmd/dlv/dlv_test.go

This test seems to fail frequently on FreeBSD.

cmd/dlv: disable TestTraceMultipleGoroutines on FreeBSD

---

pkg/proc/native/ptrace_linux_386.go

proc: remove import "C" for linux/386 backend

---

pkg/proc/proc_test.go

proc: disable TestCGONext on darwin/amd64

---

service/dap/server.go

Solve https://github.com/go-delve/delve/issues/3170 for `evaluateExpression` so that the type of the evaluation is returned upon evaluating an expression. Implemented so when there's an actual evaluated variable with a type with a variable reference, which is the either a `call` expression or a plain expression.

Add type to simple expression evaluation in DAP's `evaluateRequest`

---

pkg/terminal/terminal.go

This patch includes the path to the history file itself so that users can better fix the issue when an error arises.
Fixes #3168

pkg/terminal: Improve error when unable to read history file

---

pkg/proc/native/proc_windows.go
service/debugger/debugger.go
service/debugger/debugger_test.go

This patch modifies the behavior of the exec subcommand such that you don't necessarily have to write the "./" prefix when trying to debug a precompiled binary in your working directory.
For example (given foo.test in working dir), before this change:
dlv exec foo.test
Would result in an error, forcing the user to type:
dlv exec ./foo.test
This just makes things a bit more convenient.

service/debugger: Assume current dir for exec

---

service/debugger/debugger.go
service/test/integration2_test.go

Before 4c5b111a it was possible for a client to create a breakpoint
with a specific logical ID, restore this ability for backwards
compatibility.

service/debugger: allow setting a breakpoint with a specific ID

---

pkg/proc/bininfo.go

If Delve finds a file listed in `.gnu_debuglink` it looks for it, so it can read debug symbols from it.
If it fails to find it, it does not tell the user. If Delve fails to find any debug symbols, the user does not know _why_ Delve failed to find them, since Delve multiple strategies to look for the debug symbols.
This change makes Delve log a message when it looks for a file listed in `.gnu_debuglink`, but fails to find it:
```console
2022-11-09T17:39:25Z info layer=debugger attaching to pid 1
2022-11-09T17:39:25Z warning layer=debugger gnu_debuglink link "example.debug.custom.extension" not found in any debug info directory
could not attach to pid 1: could not open debug info - debuggee must not be built with 'go run' or -ldflags='-s -w', which strip debug info
```
Fixes …

bininfo: Log when the file listed in .gnu_debuglink is not found

---

pkg/proc/eval.go
pkg/proc/variables_test.go

Fix type casts to **type.
We've allowed doing this with uintptr but we should allow
unsafe.Pointer to be used like Go uses it.

Two fixes to type cast evaluation

---

Documentation/backend_test_health.md
pkg/proc/amd64_arch.go
pkg/proc/arm64_arch.go
pkg/proc/proc_test.go
pkg/proc/stack.go
pkg/proc/variables.go

This patch introduces some changes, particularly to arm64SwitchStack
which fixes the test when running on linux/arm64. The changes are
specific to linux, integrating them directly causes the test to fail on
apple/m1, so special case linux for now.
Fixes #2340

pkg/proc: fix arm64 linux cgo stacktrace

---

pkg/proc/target_group.go
pkg/terminal/command_test.go

If a breakpoint has both a list of addresses and an expression prefer
the list of addresses, otherwise it is impossible to set breakpoint
with expressions that depend on the current scope, like 'break +0'
which sets a breakpoint on the current line.

proc: prefer addresses when setting a breakpoint

---

cmd/dlv/cmds/commands.go

`coredumpctl` attempts to pass the core file to the debugger through the `-c` flag. However delve does not support such a flag.
This patch makes it a bool flag so we can receive the coredump file from `coredumpctl`
$ GOTRACEBACK=crash ./main
panic:
goroutine 1 [running]:
[....]
zsh: IOT instruction (core dumped)  GOTRACEBACK=crash ./main
$ coredumpctl list main
TIME                            PID  UID  GID SIG     COREFILE EXE                             SIZE
Tue 2022-11-15 23:29:07 CET 2047401 1000 1000 SIGABRT present  /tmp/go-test/main 60.2K
$ coredumpctl gdb --debugger=dlv -A core main
PID: 2047401 (main)
Signal: 6 (ABRT)
Timestamp: Tue 2022-11-15 23:29:07 CET (1min 27s ago)
Command Line: ./main
Executable: /tmp/go-test/main
Owner UID: 1000 (fox)
Size on Disk: 60.2K
Message: Process …

cmds/command: Include hidden flag -c for coredumpctl support

---

pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/gdbserver_unix.go
pkg/proc/gdbserial/gdbserver_windows.go

Newer versions of debugserver (which contain [1]) will spawn the target
process on a new process group, when we detect that this happen, and we
are a headless instance and stdin is a tty, make the child process'
process group the controlling group for the terminal.
[1] https://reviews.llvm.org/rG33ac4fddc7906ba712c50cd3a9b02ae041d751ab

proc/gdbserver: set child process pgrp as foreground group

---

_scripts/test_linux.sh
pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/gdbserver_unix.go

Do not stop if tcsetpgrp errors, also only do it if the target process
got its own process group.
Fixes #3210

gdbserial: continue if tcsetpgrp fails

---

Documentation/usage/dlv_test.md
cmd/dlv/cmds/commands.go

Add -test.run to the example of how 'dlv test' can be used.

Documentation: add -test.run to test example

---

pkg/proc/core/linux_core.go
pkg/proc/variables.go

This PR refactors two files in `proc` by replacing `os.SEEK_CUR` with `io.SeekCurrent`.
`os.SEEK_CUR` is deprecated. [Documentation](https://pkg.go.dev/os@go1.15.15#pkg-constants) suggests using  `io.SeekCurrent`.

proc: replace deprecated os.SEEK_CUR with io.SeekCurrent

---

go.mod
go.sum
vendor/github.com/derekparker/trie/go.mod
vendor/github.com/derekparker/trie/trie.go
vendor/modules.txt

Fixes #3217 with the fix in https://github.com/derekparker/trie/pull/33.
Changes generated by running:
```
$ go get github.com/derekparker/trie
$ go mod vendor
```

Update github.com/derekparker/trie dependency

---

Documentation/faq.md

The text of the substitute-path section in the FAQ ("Can not set breakpoints or see source listing in a complicated debugging environment") mentions the command 'config help substitute-path', but 'help' is not a valid argument to the 'config' command.
Use 'help config' instead, which does mention 'substitute-path' and how to set it.
Also, the command to list source files is 'sources', not 'source'. Fix that.

Documentation/faq: Correct commands in substitute-path section

---

.teamcity/settings.kts
_scripts/test_windows.ps1

Windows/amd64 builds are not runnning because the current settings.kts
has an implicity requirement to property teamcity.build.systemDir which
does not exist on windows/amd64 agents.

TeamCity: fix windows/amd64 builds

---

Documentation/backend_test_health.md
cmd/dlv/dlv_test.go
pkg/proc/native/proc.go
pkg/proc/native/proc_freebsd.go
pkg/proc/native/ptrace_freebsd.go
pkg/proc/native/threads.go
pkg/proc/native/threads_darwin.go
pkg/proc/native/threads_freebsd.go
pkg/proc/native/threads_linux.go
pkg/proc/native/threads_windows.go
pkg/proc/proc_test.go
pkg/terminal/command_test.go
service/dap/server_test.go
service/test/integration1_test.go
service/test/integration2_test.go

* use PT_SUSPEND/PT_RESUME to control running threads in
resume/stop/singleStep
* change manual stop signal from SIGTRAP to SIGSTOP to make manual stop
handling simpler
* change (*nativeProcess).trapWaitInternal to suspend newly created
threads when we are stepping a thread
* change (*nativeProcess).trapWaitInternal to handle some unhandled
stop events
* remove misleading (*nativeProcess).waitFast which does not do
anything different from the normal wait variant
* rewrite (*nativeProcess).stop to only set breakpoints for threads of
which we have received SIGTRAP
* rewrite (*nativeThread).singleStep to actually execute a single
instruction and to properly route signals

proc/native: fix FreeBSD backend

---

pkg/proc/bininfo.go
pkg/proc/core/minidump/minidump.go
pkg/proc/dump.go
pkg/proc/fncall.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/gdbserver_conn.go
pkg/proc/native/proc_linux.go
pkg/proc/native/threads_windows.go
pkg/proc/stack.go
pkg/proc/target.go
pkg/proc/target_group.go
pkg/proc/types.go
pkg/proc/variables.go

This PR fixes typos in the comments in `proc`.

proc: Fix typos in comments

---

Documentation/faq.md
_scripts/gen-faq-toc.go
cmd/dlv/dlv_test.go

Add FAQ entry to document how to debug the Go runtime using Delve.
Also add table of contents to FAQ.

Documentation: document how to debug runtime with Delve

---

_fixtures/testfnpos.go
_fixtures/testunsafepointers.go
pkg/proc/eval.go
pkg/proc/variables.go
pkg/proc/variables_test.go

This patch changes how Value and Unreadable are populated for pointer
Variables. Before this patch, variables of kind reflect.Ptr did not have
their Value field populated. This patch populates it in
Variable.loadValue(), which seems natural and consistent with other
types of variables. The Value is the address that the pointer points to.
The Unreadable field was populated inconsistently for pointer variables:
it was never populated for an outer pointer, but it could be populated
for an inner pointer in pointer-to-pointer types. Before this patch,
in pointer whose value could not be read was not easily distinguishable
from a pointer with a value that could be read, but that cannot be
dereferenced (i.e. a dangling pointer): neither of these would be marked
as Unreadable, and both would have …

proc: populate pointer values

---

cmd/dlv/cmds/commands.go
cmd/dlv/dlv_test.go

When 'dlv test' is called with a list of files it should match the
behavior of 'go test' and chdir to the directory where the go files are
(if they are all in the same directory).
Fixes #3230

cmd/dlv: match go test behavior when dlv test gets a list of .go files

---

pkg/proc/gdbserial/gdbserver.go

I just noticed that my fix actually didn't work since I had ill assumption (didn't notice) that the code isn't iterating keys, but `key=value` format, hence this never did anything (I tested the previous iteration where it was HasPrefix and probably didn't test the new one, sorry for that)
https://github.com/go-delve/delve/pull/3181

fix stripping DYLD_INSERT_LIBRARIES on macOS

---

pkg/config/config.go
pkg/terminal/colorize/colorize.go
pkg/terminal/colorize/colorize_test.go
pkg/terminal/config.go
pkg/terminal/out.go
pkg/terminal/terminal.go

New config "tab" allows user to set a string instead of literal tab (e.g. "... ").
New config "source-list-tab-color" allows that string to be colored.
This builds on top of the `updateColorScheme` change  #3240

Add config options for tab printing

---

pkg/terminal/command.go
pkg/terminal/terminal.go

The typical convention with `[Y/n]` type command line questions is that the capitalized letter represents the default if the user simply hits "enter" instead of typing an actual response. This patch fixes our implementation to use the implied default response.

pkg/terminal: use default for Y/n empty response

---

pkg/dwarf/dwarfbuilder/info.go
pkg/dwarf/dwarfbuilder/loc.go
pkg/dwarf/frame/parser.go
pkg/dwarf/frame/table.go
pkg/dwarf/leb128/decode.go
pkg/dwarf/leb128/decode_test.go
pkg/dwarf/leb128/doc.go
pkg/dwarf/leb128/encode.go
pkg/dwarf/leb128/encode_test.go
pkg/dwarf/line/line_parser.go
pkg/dwarf/line/parse_util.go
pkg/dwarf/line/state_machine.go
pkg/dwarf/line/state_machine_test.go
pkg/dwarf/loclist/dwarf5_loclist.go
pkg/dwarf/loclist/loclist5_test.go
pkg/dwarf/op/op.go
pkg/dwarf/util/util.go
pkg/dwarf/util/util_test.go

This PR moves encode/decode LEB128 functions out from the `util` package to the `leb128` to improve maintainability. And because `util` is too general package name.

proc/dwarf: Move LEB128 encode/decode functions to a separate package

---

pkg/dwarf/frame/parser.go
pkg/dwarf/godwarf/addr.go
pkg/dwarf/godwarf/buf.go
pkg/dwarf/godwarf/type.go
pkg/dwarf/line/line_parser.go
pkg/dwarf/line/parse_util.go
pkg/dwarf/line/state_machine.go
pkg/dwarf/line/state_machine_test.go
pkg/dwarf/loclist/dwarf5_loclist.go
pkg/dwarf/op/op.go
pkg/dwarf/parseutil.go
pkg/dwarf/parseutil_test.go
pkg/proc/bininfo.go

This PR follows #3235 and does the following:
- moves`github.com/go-delve/delve/pkg/dwarf/util/buf.go` to `github.com/go-delve/delve/pkg/dwarf/godwarf/buf.go`;
- moves `github.com/go-delve/delve/pkg/dwarf/util/util.go` to `github.com/go-delve/delve/pkg/dwarf/parseutil.go`;
- renames `ParseString` to `ReadString` for consistency with `ReadUintRaw, ReadDwarfLengthVersion, ReadUnitVersions`;
- removes deprecated `DecodeULEB128, DecodeSLEB128, EncodeULEB128, EncodeSLEB128`.

proc/dwarf: Move util functions to dwarf package

---

_fixtures/traceprog.go
cmd/dlv/dlv_test.go
pkg/dwarf/line/line_parser.go
pkg/proc/eval.go

This essentially reverts #2235.
Fixes a bug where we cannot get locals (including arguments and return values) from a given scope because the line number state machine ends up in an invalid state because of this parameter being set to false.
Also fixes some disassembly output:
Before:
```
TEXT main.callme(SB) /home/deparker/Code/delve/localtests/trace/main.go
=>      main.go:5       0x49c8a0*       4883ec10                sub rsp, 0x10
main.go:5       0x49c8a4        48896c2408              mov qword ptr [rsp+0x8], rbp
main.go:5       0x49c8a9        488d6c2408              lea rbp, ptr [rsp+0x8]
main.go:5       0x49c8ae        4889442418              mov qword ptr [rsp+0x18], rax
main.go:5       0x49c8b3        48c7042400000000        mov qword ptr [rsp], 0x0
main.go:6       0x49c8bb …
```

pkg/proc: do not check decl line for FunctionArguments

---

cmd/dlv/dlv_test.go
pkg/proc/core/core_test.go

This PR simplifies tests in `cmd/dlv` and `pkg/proc` by replacing usages of `ioutil.TempDir` with `t.TempDir`.
[`T.TempDir`](https://pkg.go.dev/testing#T.TempDir) automatically removes the temporary directory at the end of a test. So, no need to manually call `defer os.RemoveAll(tmpDir)`

cmd/dlv, pkg/proc: use T.TempDir in tests for temp dirs

---

_scripts/make.go

This PR replaces `%w` with `%v` in `make.go` because `%w` can be used only in [`fmt.Errorf`](https://pkg.go.dev/fmt#Errorf).

_scripts: fix log.Printf format specifier

---

pkg/dwarf/godwarf/tree.go
pkg/proc/fncall.go

Previously it was only possible to extract a value of type `any` using an attribute name. This poses challenges when fields are allowed to have different classes, and it is ambiguous how to handle them.
I for example am seeing a case where a subroutine has a `DW_AT_name` that is not of class string, but string alt, therefore requiring a lookup in the `.debug_str` table. (https://dwarfstd.org/ShowIssue.php?issue=120604.1)
Being able to extract the whole field is better as we can decide what to do based on the class of the field and not guess based on the data type in Go.

godwarf: Allow extracting a DWARF entry's field

---

cmd/dlv/cmds/commands.go
cmd/dlv/dlv_test.go

We currently return an error when the command exits because a process
exited error is always returned. Detect this like we do in other code
paths to return a 0 exit code instead of nonzero which indicates the
command itself failed and can confuse other tools.

cmd/dlv: fix exit status for trace subcommand 

---

service/dap/server.go
service/dap/server_test.go

This PR fixes typos in the comments.

service/dap: correct typos in comments

---

pkg/dwarf/regnum/arm64.go

just fixing a broken url in a comment.

docs: fix broken external url to arm dwarf mapping

---

pkg/proc/native/ptrace_freebsd.go
pkg/proc/native/ptrace_linux_386.go
pkg/proc/native/ptrace_linux_64bit.go

Per https://pkg.go.dev/unsafe#Pointer conversions from unsafe.Pointer
to uintptr are only safe in limited circumstances. In particular only
conversions made in the syscall call are pinned.
Additionally add a call to runtime.KeepAlive to mitigate the bug
described in: https://github.com/golang/go/issues/58351

proc/native: fix syscalls to SYS_PROCESS_VM_READV (and WRITEV)

---

pkg/proc/bininfo.go
pkg/proc/native/proc_freebsd.go
pkg/proc/proc_test.go
pkg/proc/scope_test.go
pkg/proc/test/support.go
service/test/common_test.go

Use [strings.ReplaceAll](https://pkg.go.dev/strings#ReplaceAll) instead of `strings.Replace` with `-1` as the last argument.
`strings.ReplaceAll` available since go 1.12. But the code already has `ReplaceAll` occurrences in `pkg/dwarf/line/line_parser.go`, `pkg/proc/native/proc_linux.go`, `pkg/terminal/colorize/colorize_test.go`. So, delve supports go version >= 1.12 and PR changes won't break anything.

pkg/proc,service/test: refactor to use strings.ReplaceAll

---

pkg/proc/fncall.go
pkg/proc/proc_test.go
pkg/proc/variables_test.go
service/test/integration2_test.go

Delve no longer compiles on Go1.12 and earlier, we don't test it on
these versions and they are 4 years old and unsupported. Remove some
code related to Go 1.12 and earlier, mostly from tests.

*: remove some code for Go 1.12 or earlier

---

pkg/logflags/logflags.go
pkg/logflags/logflags_test.go
pkg/logflags/logger.go
pkg/proc/bininfo.go
pkg/proc/gdbserial/gdbserver_conn.go
service/dap/server.go
service/debugger/debugger.go
service/rpccommon/server.go

This change will enable people who want to embed Delve into their applications to adjust the logging better to their needs.

terminal/logflags: Added `SetLoggerFactory(LoggerFactory)`

---

.teamcity/pom.xml
README.md
service/dap/server_test.go

This PR changes `delve.beta.teamcity.com` to `delve.teamcity.com` in README, tests, and TeamCity config.
The old URL is `delve.beta.teamcity.com` and it's unreachable:
[![Build Status](https://delve.beta.teamcity.com/app/rest/builds/buildType:(id:Delve_AggregatorBuild)/statusIcon.svg)](https://delve.beta.teamcity.com/viewType.html?buildTypeId=Delve_AggregatorBuild&guest=1)
New is `delve.teamcity.com`:
[![Build Status](https://delve.teamcity.com/app/rest/builds/buildType:(id:Delve_AggregatorBuild)/statusIcon.svg)](https://delve.teamcity.com/viewType.html?buildTypeId=Delve_AggregatorBuild&guest=1)

TeamCity,Documentation: use new TeamCity URL

---

pkg/dwarf/line/state_machine.go
pkg/proc/eval.go

This patch changes how we handle end_seq in the debug_line state machine program. Instead of always considering the state machine invalid at the end_seq instead simply consider the *current* address invalid. This solves a number of issues such as incorrect disassemble output for the last few instructions in certain functions, and creating an eval scope at an address within the last few instructions of certain functions. It also handles the case where the end_seq address is the same as the start address of the next adjacent function, which would previously confuse Delve which is why we initially marked end_seq as invalid for the entire state machine. This approach is more nuanced and still solves that initial problem while fixing some problems introduced by that patch.

dwarf/line: handle end_seq properly

---

_scripts/test_windows.ps1

There are several bootstrapping situations that can leave Windows builders in a bad state.
For example, the windows/arm64 builder has been failing since last week because it failed to download the new go1.20.1 version and left a directory which marks it as installed, making following runs to fail because `go` could not be found.
This PR updates the Windows testing script to fix that.

Default to stop test_windows.ps1 when there is an error

---

pkg/dwarf/line/state_machine_test.go

The test `TestGrafana` succeeds on Windows:
- https://delve.teamcity.com/buildConfiguration/Delve_windows_amd64_1_20/45212?buildTab=tests&name=TestGrafana
- https://delve.teamcity.com/buildConfiguration/Delve_windows_amd64_tip/45213?buildTab=tests&name=TestGrafana

dwarf/line: enable TestGrafana for Windows

---

Documentation/api/ClientHowto.md
Documentation/api/dap/README.md
Documentation/cli/README.md
Documentation/cli/expr.md
Documentation/cli/starlark.md
Documentation/usage/dlv_test.md
cmd/dlv/cmds/commands.go
pkg/terminal/command.go

Fix typos in `*.md` files and in `*.go` filesfrom which docs are generated.

Documentation: fix typo and grammar issues

---

Documentation/usage/dlv_replay.md
cmd/dlv/cmds/commands.go
pkg/proc/gdbserial/rr.go
service/debugger/debugger.go

Add `-p` or `rr-onprocess-pid` to replay
command to pass `-p` or `--onprocess` pid
to `rr`.

Add flag to replay for rr onprocess pid

---

pkg/proc/proc_test.go
pkg/terminal/command_test.go

`getg` and `countOccurrences` are leftovers from past tests and are currently unused.

proc,terminal: remove unused unexported functions

---

pkg/proc/target.go
pkg/proc/target_group.go
service/test/integration2_test.go

Unrecovered-panic and fatal-throw were no longer part of the breakpoint
list because starting in 37e44bf they were created before the logical
breakpoints map was switched to the logical breakpoints map of the
target group.

proc: fix automatic breakpoints visibility

---

Documentation/cli/getting_started.md

The tree view of the project layout seemed to show that "github.com", "cmd", and "pkg" were all in the same directory.  The usage later in the document (and normal go layout) would have them as subdirectories.
The new tree output was generated with the below:
(cd `mktemp -d`
mkdir -p github.com/me/foo/{cmd/foo,pkg/baz}
touch github.com/me/foo/{cmd/foo/main,pkg/baz/bar{_test,}}.go
tree -n --noreport github.com/me/foo
)

Documentation: expand project layout to match usage

---

pkg/locspec/locations.go
pkg/proc/amd64_arch.go
pkg/proc/arm64_arch.go
pkg/proc/bininfo.go
pkg/proc/breakpoints.go
pkg/proc/dwarf_expr_test.go
pkg/proc/eval.go
pkg/proc/fncall.go
pkg/proc/i386_arch.go
pkg/proc/native/proc_linux.go
pkg/proc/proc_test.go
service/test/integration2_test.go

The compiler produces ABI compatibility wrappers for some functions.
We have changed the support for breakpoints to allow a single logical
breakpoint to correspond to multiple physical breakpoints, take
advantage of that to set breakpoints on both the ABI wrapper and the
real function.
Fixes #3296

proc: support multiple functions with the same name

---

_fixtures/reflecttypefncall.go
pkg/proc/fncall.go
pkg/proc/proc_test.go

deref'd
Fix infinite recursion if escapeCheck, at some point during its
recursion, creates an unreadable variable.
The deeper reason for this is that we evaluate function calls in a very
weird order so that we can always have stack space to store
intermediate evaluation results.
The variable 'value' happens to be stored in a register when we try to
make the call and because of our weird evaluation strategy registers
are no longer available to us when we evaluate 'value'.
This is not a complete fix for the issue, the real fix would be to
evaluate everything in its natural order, storing intermediate values
in Delve's memory instead of the target's stack. To do this we need a
mechanism to pin heap allocated objects, which at the moment does not
exist.
Updates #3310

proc: fix escapeCheck infinite recursion if something can not be

---

pkg/terminal/starbind/conv.go

Hi. Without this fix, Starlark fails to print boolean fields.
I hit this while trying to debug GeeseFS, it fails with messages similar to:
`Command failed: *github.com/yandex-cloud/geesefs/internal.FileBuffer has no .loading field or method (did you mean .loading?)`
Yes I did mean .loading! :)
Test case. `main.go`:
```
package main
import "runtime"
type A struct {
field bool
}
func main() {
var a A
a.field = true
runtime.Breakpoint()
}
```
test.star:
```
a = eval(None, "a")
print(a.Variable.Value.field)
```
cli:
```
$ ../dlv debug .
Type 'help' for list of commands.
(dlv) c
> [hardcoded-breakpoint] main.main() ./booltest.go:13 (hits total:0) (PC: 0x45f1c5)
8:
9: func main() {
10:     var a A
11:     a.field = true
12:     runtime.Breakpoint()
=>  13: }
(dlv) source test.star
Command …
```

terminal: Fix printing boolean values in Starlark scripts

---

pkg/proc/proc_test.go

Looks like `normalFn.Name != normalFn.Name` is a copy-paste error.
This mistake was found by the [`gocritic`](https://github.com/go-critic/go-critic):
```
gocritic check -enable dupSubExpr ./...
```

proc: fix match condition in TestGnuDebuglink

---

_fixtures/stepshadow.go
pkg/proc/breakpoints.go
pkg/proc/proc_test.go
pkg/proc/stackwatch.go
pkg/proc/target.go
pkg/proc/target_exec.go

When using Step on a function that has a dynamic CALL instruction we
set a Step breakpoint on the call.
When it is hit we determine the destination of the CALL by looking at
registers, set a breakpoint there and continue.
If the Step breakpoint is hit simultaneously with a normal breakpoint
our Step logic will take precedence and the normal breakpoint hit will
be hidden from the user.
Move the Step logic to a breaklet callback so that it does not
interfere with the decision to stop.

proc: step breakpoints shouldn't hide normal breakpoints

---

service/debugger/debugger.go

convertDefers should not try to dereference nil if the deferred
location does not belong to a function.

debugger: do not panic if defer location can not be found

---

service/api/conversions.go
service/api/types.go
service/client.go
service/dap/daptest/gen/main.go
service/dap/server.go
service/dap/server_test.go
service/dap/types.go
service/rpc2/client.go
service/rpccallback.go
service/test/integration1_test.go
service/test/integration2_test.go

This PR corrects typos and removes duplicated words.  Changes are only in comments in `service` directory.

service: fix typos in comments

---

pkg/proc/test/support.go

`testName` is needed only to support Go <= 1.7.

proc/test: replace old func testName with T.Name

---

service/dap/server_test.go
service/debugger/debugger.go

Refactor to use `Regexp.MatchString` and `Regexp.MustCompile`.

service/dap,service/debugger: refactor regexp funcs

---

service/dap/server.go

The only part of the reloaded value that was used was the Children. This caused a bug where the Time format string was reloaded, but it was not being displayed.
Fixes go-delve/delve#3342

service/dap: use reloaded value

---

pkg/proc/internal/ebpf/helpers.go
vendor/github.com/cilium/ebpf/rlimit/rlimit.go
vendor/modules.txt

pkg/proc: remove memlock limit for ebpf trace backend

---

pkg/proc/proc_test.go

From the [doc](https://pkg.go.dev/net/http#Get):
```
// When err is nil, resp always contains a non-nil resp.Body.
// Caller should close resp.Body when done reading from it.
```

pkg/proc: add missing response body Close in test

---

pkg/proc/core/core_test.go
pkg/proc/gdbserial/rr.go
pkg/proc/test/support.go

We can simplify the following code
```go
dir, err := os.Open(dirname)
if err != nil {
return err
}
defer dir.Close()
dirs, err := dir.Readdir(-1)
```
with just `os.ReadDir(dirname)`. `os.ReadDir` is recommended over `Readdir()`, as stated in the official doc [^1]
[^1]: "Most clients are better served by the more efficient ReadDir method." https://pkg.go.dev/os#File.Readdir

refactor: replace `Readdir(-1)` with `os.ReadDir`

---

_fixtures/testvariables2.go
pkg/dwarf/godwarf/type.go
pkg/proc/variables_test.go

Alignment calculation for typedef types was wrong due to a missing
Align method.
Fixes #3360

dwarf/godwarf: fix alignment calculation for typedef types

---

service/dap/server.go

This PR removes `error` from functions that always returns `nil` as a result error.

service/dap: refactor funcs always returning nil error

---

Documentation/usage/dlv_trace.md
cmd/dlv/cmds/commands.go
pkg/config/config.go
pkg/terminal/command.go

trace: add timestamp to the output

---

pkg/proc/core/core.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/rr.go
pkg/proc/native/nonative_darwin.go
pkg/proc/native/proc.go
pkg/proc/native/proc_darwin.go
pkg/proc/native/proc_freebsd.c
pkg/proc/native/proc_freebsd.go
pkg/proc/native/proc_freebsd.h
pkg/proc/native/proc_linux.go
pkg/proc/native/proc_windows.go
pkg/proc/proc_test.go
pkg/proc/target.go
pkg/proc/target_group.go
pkg/terminal/command.go
service/api/conversions.go
service/api/types.go
service/debugger/debugger.go

Read the command line of the main target process as well as any other
process Delve attaches to in follow exec mode.
The command line can be viewed using the 'target list' command.
In follow exec mode this command line is used to match the follow exec
regex to decide whether or not to attach to a child process.
On macOS or when using rr the list of arguments is not available for
attached processes since there is no way to use the gdb serial protocol
to read it.
Fixes #2242

proc,terminal: read command line of new processes

---

_scripts/rtype-out.txt
pkg/proc/bininfo.go
pkg/proc/fncall.go
pkg/proc/proc_test.go
pkg/proc/types.go
pkg/proc/variables.go
pkg/proc/variables_test.go

Go 1.21 renamed runtime._type to internal/abi.Type and changed the name
of its fields. Update Delve so that it uses the new names for loading
interfaces and generic type parameters.

proc: fix runtime type handling for Go 1.21

---

cmd/dlv/cmds/commands.go

This PR fixes `os.Exit will exit, and ``defer logflags.Close()`` will not run` in `connectCmd`.

cmd/dlv: logger is not closed in connect command

---

_fixtures/fncall.go
pkg/proc/dwarf_export_test.go
pkg/proc/mem.go
pkg/proc/target.go
pkg/proc/variables.go
pkg/proc/variables_test.go

On 64 bit system, the byte size of the following struct is 16:
```go
type myStruct struct {
a int
b uint32
}
```
But `extractVarInfoFromEntry` only allocates a mem of 12 bytes for it. When calling method of this struct with the `call` command, it will result in this error:
````
write out of bounds
````
This patch extends the mem by adding padding bytes to the end of the mem.
Fixes #3364.

pkg/proc: pad variable mem in extractVarInfoFromEntry

---

Documentation/usage/dlv_debug.md
Documentation/usage/dlv_test.md
Documentation/usage/dlv_trace.md
cmd/dlv/cmds/commands.go
cmd/dlv/dlv_test.go
pkg/gobuild/defaultexe.go
service/dap/server.go

Using a fixed path as the default output binary means that executing
Delve twice in the same directory will cause the second invocation to
overwrite the output binary of the first instance of Delve, making the
restart command not work correctly.
Fixes #3345

cmd/dlv,service/dap: use randomized name as default output binary

---

pkg/proc/proc_test.go
pkg/terminal/command_test.go

> Go Response Body MUST be closed, even if you don’t read it
https://manishrjain.com/must-close-golang-http-response

pkg/proc,pkg/terminal: close response body in tests

---

pkg/proc/amd64_arch.go
pkg/proc/arm64_arch.go
pkg/proc/stack.go

This field was part of the original stack tracing algorithm, we haven't
used this in years.

proc: remove addrret field from Stackframe struct

---

service/api/prettyprint.go
service/api/types.go
service/dap/daptest/client.go
service/dap/server.go
service/dap/server_test.go
service/rpc2/server.go
service/test/integration2_test.go

This PR corrects spelling mistakes in the `service` folder.

service: fix typos in comments, logs, tests, errors, and vars

---

pkg/dwarf/godwarf/tree_test.go
pkg/dwarf/godwarf/type.go
pkg/dwarf/reader/reader.go
pkg/proc/i386_disasm.go
pkg/proc/linutil/dynamic.go
pkg/proc/proc_test.go

This PR fixes typos in the `pkg` folder.

dwarf,proc: fix typos in comments and error messages

---

pkg/proc/debuginfod/debuginfod.go

Test by setting $DEBUGINFOD_PROGRESS=1 or $DEBUGINFOD_VERBOSE=1
before invoking dlv.  A "no such file or directory" dlv error results the first time,
even though debuginfod-find succeeded.  If rerun (and thus the file is found in
the debuginfod client cache), diagnostics may not be printed, so dlv may work.

debuginfod-find stderr may contain diagnostics; look at stdout only

---

Documentation/cli/starlark.md

It took me a bit to understand how to pass structs to Starlark built-ins. The documentation didn't really address it - there was an example, but quite hidden. This patch adds some words about it.

documentation: add a note about starlark structs

---

Documentation/cli/starlark.md
pkg/terminal/starbind/starlark.go
vendor/go.starlark.net/lib/time/time.go
vendor/go.starlark.net/starlarkstruct/module.go
vendor/go.starlark.net/starlarkstruct/struct.go
vendor/modules.txt

This patch makes the time library available to Starlark scripts. This library is one of the very few few that are built into starlark-go (the others are json, math, proto).
I've played around with Starlark scripting today, and immediately I wanted to measure how long certain computations take.

starbind: Make the time module available to star scripts

---

pkg/dwarf/op/op.go

dwarf/op gained the ability to execute DW_OP_deref opcodes a while ago
but because we didn't save the readMemory function in the context
structure it never worked.

dwarf/op: use readMemory function

---

_scripts/gen-travis.go
_scripts/make.go

This PR fixes typos in `_scripts` files.

_scripts: fix typos

---

_fixtures/decllinetest.go
pkg/dwarf/reader/variables.go
pkg/proc/proc_test.go

Before this patch, the visibility of function arguments for purposes
like the `locals` command was considered to start on the line on which
they are declared. I believe this was incorrect; instead their
visibility should start at the beginning of the function. This makes a
difference for function declarations like:
```
1: func foo(
2:   a int,
3:   b int,
4: )
```
Here, foo() starts on line 1 (e.g. a breakpoint on "foo" will break on
:1), but "a" has a decl_line of :2 and "b" has :3. This was causing a
and b to not be readable for a few instructions at the beginning of the
function, although they should have been.
This patch fixes it by ignoring decl_line for function arguments,
essentially making them visible throughout the function.
Note that function arguments are not subject to the …

dwarf: ignore DeclLine for function args

---

service/rpccommon/server.go

This is not an HTTP server.
Fixes #3315

service/rpccommon: correct wrong comments

---

.teamcity/settings.kts

It seems that our linux/386 builders no longer (or never did?) use
linux/386, the i386/ubuntu:20.04 docker image has become (or always
was?) multiarchitecture and docker starterd picking (always picked?)
the amd64 version. This change should fix the problem (or break
everything).

TeamCity: actually run linux/386 tests on linux/386

---

service/debugger/debugger.go

These two functions are only called once and can be inlined easily.

debugger: inline clearBreakpoint, createLogicalBreakpoint

---

cmd/dlv/cmds/commands.go

I use dlv 1.20.2 (the latest). I experienced the problem that dlv trace -e always fails to read separated debug info like the below,
```
$ ~/go/bin/dlv trace --log -e /usr/bin/hugo 'commands\.new.*'
2023-06-05T01:50:12+09:00 info layer=debugger launching process with args: [/usr/bin/hugo]                                                                          
2023-06-05T01:50:12+09:00 warning layer=debugger gnu_debuglink link "7c03fe5487be2cbd7f7097fae18a1337dc56bf.debug" not found in any debug info directory            
could not launch process: could not open debug info - debuggee must not be built with 'go run' or -ldflags='-s -w', which strip debug info
```
The root cause is that the traceCmd function in cmd/dlv/cmds/commands.go doesn't reference conf.DebugInfoDirectories, …

cmd/commands: fix to read debug info file from correct directory in trace command

---

.teamcity/settings.kts

Change cc05aa2 broke linux/arm64 builds, this should fix them.

TeamCity: fix linux/arm64 build

---

pkg/terminal/command.go

If there are some breakpoints and the user executes 'quit -c' (quit and
continue) ask for confirmation since the behavior in that case may be
unexpected.
Fixes #1961

terminal: ask for confirmation when using 'quit -c' with breakpoints

---

pkg/proc/test/support.go

Cgo testing on FreeBSD was accidentally disabled by 4e24209, FreeBSD
does not have gcc by default anymore.

proc/test: reenable cgo testing on FreeBSD

---

_scripts/gen-starlark-bindings.go
pkg/terminal/starbind/starlark.go
pkg/terminal/starbind/starlark_mapping.go

Adds a new starlark builtin 'help' that prints the list of available
builtins when called without arguments and help for the specified
builtin when passed an argument.
The help is autogenerated from godoc comments so it isn't always
exactly accurate for starlark (in particular we sometimes refer to the
In structs), but it's better than nothing.

terminal/starbind: add online help for starlark

---

pkg/proc/bininfo.go
pkg/proc/pclntab.go
pkg/proc/proc_test.go

Only print the warning that gopclntab can not be read for the first
image (i.e. the executable file), also change the returned when neither
DWARF nor gopclntab are found to preserve the DWARF error.

proc: only print warning when gopclntab can not be read for first image

---

pkg/proc/proc_test.go

PIEs do not have a .data.rel.ro.gopclntab section on linux/386. Disable
the test.

proc: skip TestDebugStripped on linux/386/pie

---

CHANGELOG.md
pkg/goversion/compat.go
pkg/version/version.go

Thank you @alexandear, @chenhengqi, @cuishuang, @alexsaezm, @suzmue, @spacewander, @ZekeLu, @fche, @andreimatei, @nozzy123nozzy

all: Bump to v1.21.0

---

pkg/locspec/locations.go
pkg/terminal/command.go
pkg/terminal/command_test.go
service/client.go
service/debugger/debugger.go
service/rpc1/server.go
service/rpc2/client.go
service/rpc2/server.go
service/test/common_test.go
service/test/integration2_test.go

Change FindLocation so it can return a substitute location expression
and propagate it to pkg/terminal/command.
When breakpoints are set using the syntax :<lineno> or +<lineno>
produce a substitute location expression that doesn't depend on having
a valid scope and can be used to restore the breakpoint.
Fixes #3423

terminal: restore breakpoints set with line offset on restart

---

pkg/proc/variables_test.go
service/api/prettyprint.go

When printing a pointer variable first print the address that it points
to before printing its dereferenced value.
Fixes #3446

service/api: in multiline mode print address of pointers

---

pkg/proc/target.go

Only a few types can be read with ebpf, mark everything else as
unreadable so that there are no downstream crashes.
Fixes #3443

proc,ebpf: mark as unreadable args with unsupported types with ebpf

---

pkg/terminal/starbind/conv.go
pkg/terminal/starbind/conv_test.go

The unmarshaling code for slices wasn't actually setting the destination. This patch fixes it.

starbind: fix Starlark slice unmarshaling

---

Documentation/backend_test_health.md
Documentation/usage/dlv_attach.md
Makefile
cmd/dlv/cmds/commands.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/interface.go
pkg/proc/native/nonative_darwin.go
pkg/proc/native/proc.go
pkg/proc/native/proc_darwin.go
pkg/proc/native/proc_freebsd.go
pkg/proc/native/proc_linux.go
pkg/proc/native/proc_windows.go
pkg/proc/proc_test.go
pkg/proc/proc_unix_test.go
pkg/proc/target.go
service/debugger/debugger.go

Adds a waitfor option to 'dlv attach' that waits for a process with a
name starting with a given prefix to appear before attaching to it.
Debugserver on macOS does not support follow-fork mode, but has this
feature instead which is not the same thing but still helps with
multiprocess debugging somewhat.

proc: add waitfor option to attach

---

Makefile
_scripts/test_linux.sh

We must pass the build tag through during the 'vet' check, and additionally there was some extra commands at the end of test_linux.sh that were not necessary.

*: Fix ppc64le test runs

---

.teamcity/settings.kts
_scripts/test_linux.sh
_scripts/test_mac.sh
_scripts/test_windows.ps1
pkg/goversion/compat.go

Update test matrix to remove 1.18 and add 1.21, fix build scripts to
deal with the new format returned by:
https://golang.org/VERSION?m=text
which now has an extra second line with the time.

goversion,teamcity: update test matrix and fix build scripts

---

service/dap/server.go

The documentation of io.EOF:
Read must return EOF itself, not an error wrapping EOF, because callers will test for EOF using ==.
This is a trivial change; people may think it's normal use of "errors.Is", even it's OK, it could be
replaced with "errors.Is(err, io.EOF)" in idiomatic way.

service/dap: use == to test io.EOF

---

.teamcity/settings.kts

Programs built with `-gcflags='all=-N -l'` do not work on
linux/386/1.21 due to https://github.com/golang/go/issues/61975

teamcity: hold back linux/386 builds to 1.20

---

pkg/proc/bininfo.go
pkg/proc/gdbserial/gdbserver.go

Go1.22 switched to emitting PIE by default and also changed some
details of the PIE implementation. This breaks delve entirely on macOS.
Fix how relocations are handled on macOS.

proc: fix PIE support on macOS

---

pkg/proc/amd64_arch.go
pkg/proc/arm64_arch.go
pkg/proc/i386_arch.go
pkg/proc/ppc64le_arch.go

TestStacktraceGoroutine failed intermittently on freebsd/amd64/go1.20
due to stacktraces being broken when doing a runtime.nanotime system
call.

proc: fix stacktraces on freebsd/amd64/go1.20

---

pkg/locspec/locations.go
pkg/locspec/locations_test.go

Normalize separators when converting a Windows path into a Linux path.
Fixes #3447

locspec: fix SubstitutePath when converting a Windows path to Linux

---

pkg/gobuild/gobuild.go
pkg/gobuild/gobuild_test.go

The -C argument must come first on the command line of 'go build' so
pass the flags specified by build-flags first.
Replaces #3380

gobuild: pass user specified arguments of go build first

---

pkg/dwarf/godwarf/type.go
pkg/dwarf/op/regs.go
pkg/proc/amd64util/xsave.go
pkg/proc/arch.go
pkg/proc/core/core.go
pkg/proc/disasm.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/scope_test.go
pkg/proc/target.go
pkg/proc/target_exec.go
pkg/terminal/docgen.go
service/rpc1/server.go
service/rpc2/server.go

This PR renames receiver names to be consistent across all methods in the same struct.

pkg,service: make receiver names consistent

---

pkg/astutil/astutil.go
pkg/proc/core/core_test.go
pkg/proc/eval.go
pkg/proc/proc_test.go
pkg/proc/stack_sigtramp.go
pkg/proc/stackwatch.go
pkg/proc/target_exec.go
pkg/proc/variables_test.go
service/debugger/debugger.go

If there is no current goroutine when 'next', 'step' or 'stepout' are
used set a condition that the thread ID should stay the same instead.
This makes stepping work for multithreaded C programs or Go programs
that have threads started by cgo code.
Fixes #3262

proc: when stepping set condition on thread ID if there is no curg

---

.teamcity/settings.kts
_scripts/make.go
_scripts/test_linux.sh
pkg/proc/proc_test.go

* add architecture rule for ppc64le so that incompatible agents don't
pick up the build
* disable PIE tests on linux/ppc64le (the tests claim it doesn't work)
* enable PIE tests on darwin/amd64 now that the entry point calculation
has been fixed
* remove dependency on wget and curl in the test script for linux to
reduce test time
* only install git in the linux test script when we need it
* remove staticcheck from linux/ppc64le builds (it takes almost 5
minutes between installation and execution and makes the test timeout
sometimes)
* drop windows/arm64/tip build, the windows/arm64 build is broken
anyway and since there is only one agent it makes CI runs slow
* drop linux/ppc64le/tip build, there is only one agent, it's slow and
it will always timeout. CI runs in excess of 1h are too …

teamcity: misc changes to CI

---

cmd/dlv/cmds/commands.go

Ensure we send a Halt command to stop the process being traced so that the deferred Detach can run ensuring proper cleanup upon exit.
Fixes #3228

cmd/dlv: handle ctrl-c during tracing

---

pkg/dwarf/frame/table.go

Implementing the `DW_CFA_remember_state` and `DW_CFA_restore_state` according to the DWARF specification requires us to create a stack that can store an arbitrary number of elements, that is, there could be multiple "pushes" before "popping" them.
From the 5th revision of the spec [0]:
> 6.4.2.4 Row State Instructions
> DW_CFA_remember_state
> 	The DW_CFA_remember_state instruction takes no operands. The required
>	action is to push the set of rules for every register onto an implicit stack.
> DW_CFA_restore_state
>	The DW_CFA_restore_state instruction takes no operands. The required action
>	is to pop the set of rules off the implicit stack and place them in the
>	current row.
0: https://dwarfstd.org/doc/DWARF5.pdf
Fixes: https://github.com/go-delve/delve/issues/3206

DWARF CFI: use a stack for restore/remember opcodes

---

Documentation/backend_test_health.md
pkg/proc/proc_test.go

They are flaky in CI, I can not reproduce the problem locally.

proc: disable "wait-for" tests on freebsd

---

Documentation/cli/README.md
Documentation/cli/starlark.md
_fixtures/changoroutines.go
pkg/proc/eval.go
pkg/terminal/command.go
pkg/terminal/starbind/starlark_mapping.go
service/api/command.go
service/api/types.go
service/client.go
service/debugger/debugger.go
service/rpc2/client.go
service/rpc2/server.go
service/test/integration2_test.go

Adds -chan option to the goroutines command to list only the goroutines
running on a specified channel.
Also when printing a variable if it is a channel also print the list of
goroutines that are waiting on it.

proc,service,terminal: add ways to list goroutines waiting on a channel

---

pkg/proc/core/core.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/interface.go
pkg/proc/native/nonative_darwin.go
pkg/proc/native/proc.go
pkg/proc/native/proc_darwin.go
pkg/proc/native/proc_freebsd.go
pkg/proc/native/proc_linux.go
pkg/proc/native/proc_windows.go
pkg/proc/target.go
pkg/proc/target_group.go

Miscellaneous non-functional changes to prepare for adding support for
follow-exec mode on Windows:
* removed (*nativeProcess).wait function from Windows backend (unused).
* move close of ptraceDoneChan from release to handlePtraceFuncs, this
makes postExit callable by a function executed by execPtraceFunc.
* change addTarget to detach before creating the target object if we
don't actually want to attach to the child process, also moved the
detach call to (*processGroup).add instead of having one in addTarget
and one in the code that calls (*processGroup).add.
* changed Detach to be a method of TargetGroup/ProcessGroup, the
Windows backend will need access to the process group to call
WaitForDebugEvent.
* moved resume method to processGroup. First all threads stopped at a
breakpoint need …

proc: refactorings to implement follow-exec mode on Windows

---

cmd/dlv/dlv_test.go
pkg/proc/proc_test.go
pkg/proc/stack_sigtramp.go
pkg/proc/variables.go
pkg/terminal/starbind/conv_test.go
service/dap/server_test.go
service/debugger/debugger.go
service/test/integration2_test.go

This PR corrects spelling mistakes.

pkg,service: fix typos in comments, exceptions, tests

---

pkg/proc/variables_test.go
service/api/prettyprint.go
service/dap/server.go

Fix hexadecimal printing of variables that can be represented using
symbolic const values in DAP as well as the command line interface.
Fixes #3485

api,dap: fix hexadecimal printing of vars with symbolic const values

---

Documentation/backend_test_health.md
pkg/proc/ppc64le_disasm.go
pkg/proc/proc_test.go

PIE tests (tests on binaries built with PIE mode) on ppc64le port were having issues such as not matching expected patterns as in non PIE mode while stepping and not stepping into functions as expected creating errors due to which these tests were skipped on PIE mode 
These problems were occurring due to the special prologue emitted on ppc64le to deal with the TOC register or R2 
In some cases we had to modify the expected line numbers while stepping 
and in some other cases where the breakpoint was set in the prologue instruction even before function entry as a result of which the breakpoint was deemed void and the program control was not entering inside the function we had to modify delve to recognize these patterns to appropriately skip the special prologue and move the breakpoint a …

Fix PIE tests on ppc64le port

---

service/dap/server.go
service/dap/server_test.go

This solves the problem that function names with long package paths are hard to read when the callstack window is narrow, because all you see is the beginning of the package path.
For example, instead of
```
github.com/some/long/package/path/pkg.(*SomeType).SomeMethod
```
we now display
```
pkg.(*SomeType).SomeMethod
```
Fixes #3323.

service/dap: strip package paths from symbols in callstack

---

pkg/proc/internal/ebpf/helpers.go

From the Go specification:
> "1. For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary.

pkg/proc/internal/ebpf: remove redundant nil check

---

cmd/dlv/dlv_test.go
pkg/proc/proc_test.go
pkg/terminal/command_test.go
service/dap/server_test.go
service/debugger/debugger_test.go
service/debugger/debugger_unix_test.go
service/test/integration2_test.go

This PR refactors tests by replacing `os.Setenv` with [`t.Setenv`](https://pkg.go.dev/testing#T.Setenv).

proc,service: simplify tests with T.Setenv

---

_scripts/gen-cli-docs.go

It became redundant after #1649

_scripts: remove unnecessary os.ExpandEnv

---

pkg/gobuild/gobuild.go
service/dap/server.go
service/dap/server_test.go
service/dap/types.go

This change accepts both string type and []string type (actually, []interface{} type due to Go's json decoding behavior).
Fixes #2718
For golang/vscode-go#1831, golang/vscode-go#1027
cc @suzmue

service/dap: accept a string list as launch request's buildFlags

---

pkg/proc/core/core.go
pkg/proc/fncall.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/interface.go
pkg/proc/native/nonative_darwin.go
pkg/proc/native/proc_darwin.go
pkg/proc/native/proc_freebsd.go
pkg/proc/native/proc_linux.go
pkg/proc/native/proc_windows.go
pkg/proc/native/threads.go
pkg/proc/native/threads_darwin.go
pkg/proc/native/threads_freebsd.go
pkg/proc/native/threads_linux.go
pkg/proc/native/threads_windows.go
pkg/proc/proc_test.go
pkg/proc/target_exec.go
pkg/proc/threads.go

Move StepInstruction method to TargetGroup since it will need access to
the process group on Windows to call WaitForDebugEvent.

proc: move StepInstruction method to TargetGroup

---

pkg/terminal/command.go

The current implementation assumes a specific command line interface for opening an editor at a specific location within the source file. This patch updates for different formats, namely the one used by the editor 'hx'.

pkg/terminal: support more editors with edit command

---

Documentation/backend_test_health.md
pkg/proc/bininfo.go
pkg/proc/pclntab.go
pkg/proc/proc_test.go

Load a symbol table from pclntab as when debugging stripped ELF binaries.

macho: Enable debugging stripped binaries

---

_fixtures/testvariables2.go

With recent changes to debian/ubuntu tzdata package, the Mexico/BajaSur is not valid anymore (not present by default). It is now present in the tzdata-legacy package, which is not a essential package. Without this timezone, the call to time.LoadLocation() will send a nil location, which will provoke a panic in time.ParseInLocation(). This change uses the underlying associated timezone America/Mazatlan.
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1052030

Use a valid timezone in tested binary

---

service/test/integration2_test.go

It doesn't work with rr because it uses runtime.Breakpoint to stop.

service/test: disable TestClientServer_chanGoroutines with rr backend

---

pkg/dwarf/godwarf/fakes.go
pkg/dwarf/godwarf/helpers.go
pkg/proc/eval.go
pkg/proc/evalop/eval_go117.go
pkg/proc/evalop/eval_go118.go
pkg/proc/evalop/evalcompile.go
pkg/proc/evalop/evalop_test.go
pkg/proc/evalop/ops.go
pkg/proc/fncall.go
pkg/proc/variables.go
pkg/proc/variables_fuzz_test.go
pkg/proc/variables_test.go

This commit splits expression evaluation into two parts. The first part (in
pkg/proc/evalop/evalcompile.go) "compiles" as ast.Expr into a list of
instructions (defined in pkg/proc/evalop/ops.go) for a stack machine
(defined by `proc.(*evalStack)`).
The second part is a stack machine (implemented by `proc.(*EvalScope).eval`
and `proc.(*EvalScope).evalOne`) that has two modes of operation: in the
main mode it executes inteructions from the list (by calling `evalOne`), in
the second mode it executes the call injection protocol by calling
`funcCallStep` repeatedly until it either the protocol finishes, needs more
input from the stack machine (to set call arguments) or fails.
This approach has several benefits:
* it is now possible to remove the goroutine we use to evaluate expression
and the …

proc: use stack machine to evaluate expressions

---

pkg/proc/eval.go
pkg/proc/variables_test.go

Go 1.21 added two new builtins: min and max. Add them to the expression
evaluator.

proc: add min and max builtins

---

_scripts/test_linux.sh
cmd/dlv/dlv_test.go

Update staticcheck version and re-enable TestStaticcheck on Go 1.22.

CI: update staticcheck version

---

pkg/proc/eval.go
pkg/proc/evalop/evalcompile.go
pkg/proc/fncall.go

We have used a goroutine to keep track of some of the expression
evaluation status across target resumes during call injections.
Now that the expression interpreter has been rewritten to use a stack
machine we can move what little state is left into the stack machine
and get rid of the goroutine-and-channel mechanism.

proc: remove expr evaluation goroutine from EvalExpressionWithCalls

---

pkg/proc/gdbserial/gdbserver_conn.go
pkg/proc/proc_test.go
service/dap/server_test.go

* fix TestRefreshCurThreadSelGAfterContinueOnceError and TestBadAccess
to work when debugserver has --unmask-signals
* when a fatal signal is received while singlestepping delay its
delivery until the subsequent continue, otherwise debugserver will get
stuck completely (fixes TestNilPtrDerefInBreakInstr)

proc,service/dap,proc/gdbserial: fixes for debugserver --unmask-signals

---

pkg/proc/native/proc.go
pkg/proc/native/proc_darwin.go
pkg/proc/native/proc_freebsd.go
pkg/proc/native/proc_linux.go
pkg/proc/native/proc_windows.go
pkg/proc/native/threads_darwin.go
pkg/proc/native/threads_freebsd.go
pkg/proc/native/threads_linux.go
pkg/proc/native/threads_windows.go

Only Linux and Windows are affected but it's better to do this for all
platforms for consistency.

proc/native: wherever we check for exited we should also check detached

---

Documentation/backend_test_health.md
_fixtures/inlinestripped.go
pkg/internal/gosym/additions.go
pkg/internal/gosym/pclntab.go
pkg/internal/gosym/symtab.go
pkg/internal/moduledata/moduledata.go
pkg/internal/moduledata/moduledata_test.go
pkg/proc/bininfo.go
pkg/proc/native/proc_linux.go
pkg/proc/pclntab.go
pkg/proc/proc_test.go

This patch adds support for listing and setting breakpoints on inlined functions within stripped binaries. It uses a forked version of `debug/gosym` copied from golang.org/x/vuln/internal/vulncheck/internal/gosym which adds support for parsing the inline tree of the pclntab section. Parsing this section requires knowing the offset of the "go:func.*" symbol, which is not present in stripped binaries via the `.symtab` section so instead, we search the `.noptrdata` section which contains `runtime.moduledatap` which contains the value of that missing symbol, which we then can use to find the inline tree for a given function.
Given all this we parse the inline tree for each function we find, and then add that information the the appropriate `Function` contained in `bi.Functions`, using a …

pkg/proc: add inline function support for stripped binaries

---

cmd/dlv/cmds/commands.go
cmd/dlv/cmds/helphelpers/help.go
cmd/dlv/dlv_test.go
cmd/dlv/main.go

Also fixes a potential nil pointer deref error in a test.

cmd: fix a bunch of linter warnings from GoLand

---

_fixtures/issue3548.go
pkg/proc/variables_test.go

Issue #3548 describes a bug in the compiler which was fixed by commit
505e50b. But this case wasn't covered by our current tests (obviously)
and the fix in the compiler looks accidental so it's worth adding a
test for it.
Fixes #3548

proc: add regression test for issue #3548

---

pkg/proc/redirector_windows.go
pkg/version/buildinfo.go
service/internal/sameuser/sameuser_linux.go
service/internal/sameuser/sameuser_linux_test.go

This PR removes some `//go:build` constraints.
We can remove OS-specific build constrains like `//go:build windows` if a file name ending with `_windows.go` (according to the [doc](https://pkg.go.dev/cmd/go#hdr-Build_constraints)).
`//go:build go1.12` is redundant for delve because the minimum supported version is Go 1.17.

pkg,service: Remove redundant build constraints

---

service/api/prettyprint.go
service/api/shorten_type.go
service/api/shorten_type_test.go
service/dap/server.go
service/dap/server_test.go

The variables view in VS Code is a lot easier to read if long type names are
shortened in much the same way as we shorten them for functions in the call
stack view.
We only shorten them in the value strings; the Type field of dap.Variable is
kept as is. Since this only appears in a tooltip, it isn't a problem to have the
full type visible there.
Fixes #3516.

Shorten variable types

---

.teamcity/settings.kts
Documentation/backend_test_health.md
pkg/proc/proc_test.go
service/dap/server_test.go

The bug that prevented updating to linux/386 has been fixed upstream,
update linux/386 to 1.21 in the test matrix and fix some broken bugs.

TeamCity: reupgrade linux/386 builder to Go 1.21

---

Documentation/backend_test_health.md
pkg/proc/proc_amd64_test.go
pkg/proc/proc_darwin_amd64_test.go
pkg/proc/proc_darwin_test.go
pkg/proc/proc_linux_test.go
pkg/proc/proc_test.go

Reinstates tests which are passing locally, and reorganizes arch/os specific tests into their own respective files to reduce the amount of skipped tests on irrelevant arch/os.

pkg/proc: unskip passing tests and reorganize

---

pkg/terminal/command_test.go
pkg/terminal/config.go

terminal: clear substitute path rules cache when config is used

---

.teamcity/settings.kts

We haven't had a builder for 2 months so it can be declared legally
dead.

TeamCity: remove windows/arm64 builders from chain

---

pkg/proc/amd64_arch.go
pkg/proc/arch.go
pkg/proc/arm64_arch.go
pkg/proc/bininfo.go
pkg/proc/fncall.go
pkg/proc/ppc64le_arch.go

Instead of having a different version for each architecture have a
single version that uses an architecture specific list of registers.
Also generalize it so that, if we want, we can extend the workaround to
other runtime functions we might want to call (for example the channel
send/receive functions).

proc: simplify and generalize runtime.mallocgc workaround

---

.teamcity/settings.kts

The following is done:
- Tip builds are moved to a separate sub-project on the same level as arch-related projects
- Tip builds are excluded from Aggregator
- A branch filter is added to tip builds so that they don't run on pull requests

Extract tip builds into a separate sub-project

---

.teamcity/pom.xml
.teamcity/settings.kts

It's not strictly necessary but doesn't seem to hurt, either. TeamCity suggests doing it for now, but in the future, it might require it.

update TeamCity DSL version to 2023.05 and remove tip configurations from Aggregator

---

pkg/proc/native/proc_linux.go
pkg/proc/proc_test.go

If the target process exits and receives a signal at the same time and
we receive the signal first we should call waitpid again to read the
target's exit status.
This also fixes a nil pointer dereference when trapWaitInternal returns
an error, this fix is probably incomplete but I wasn't able to
reproduce its circumstances after 30000 runs of TestIssue1101 to
properly address it.

proc: fix TestIssue1101 flake

---

pkg/proc/target_exec.go

When using debugserver as a backend a manual stop request can end up
looking like an hardcoded breakpoint if the thread that receives the
stop request happens to be stopped right after a hardcoded breakpoint
(and the space between functions is filled with hardcoded breakpoints).
When creating hardcoded breakpoints we should ignore the trapthread if
a manual stop has been requested.
This problem made TestSetBreakpointWhileRunning and
TestSetFunctionBreakpointWhileRunning fail on macOS between 1.7% and 6%
of the time.
TestIssue1376 in rr_test.go used to pass accidentally, the stop when
the start of the recording was reached was mistaken for a hardcoded
breakpoint.

proc: skip trapthread for harcoded breakpoints after manual stop

---

pkg/proc/proc_test.go
service/dap/daptest/client.go
service/dap/server_test.go

Go1.22 has changed some line number assignments. The new line number
assignments are still valid however some tests in dap relied on them
being different and broke as a result. This commit fixes those tests
and makes them less brittle.
Also disables TestDebugStripped and TestDebugStripped2 temporarily on
1.22.

tests: fix tests in go1.22

---

Documentation/api/dap/README.md
service/dap/command.go
service/dap/config.go
service/dap/config_test.go
service/dap/server.go
service/dap/server_test.go
service/dap/types.go

If a goroutine has labels, we add them after the ID.
Fixes #3493.

Show pprof labels in thread names

---

_fixtures/testvariables2.go
pkg/proc/eval.go
pkg/proc/variables_test.go
pkg/terminal/command_test.go

The interaction of type casts with load configuration is sometimes
counterintuitive. This commit changes the way it is performed so that
when converting slices to strings and vice versa the maximum size
corresponding to the target type is used (i.e. MaxStringLen when
converting slices to strings and MaxArrayValues when converting slices
to strings).
This doesn't fully solve the problem (conversions to []rune are
problematic and multiple chained type casts will still be confusing)
but removes the problem for the majority of practical uses.
Fixes #3595, #3539

proc: make some type casts less counterintuitive

---

pkg/proc/eval.go

The name of the ppc64 architecture is ppc64le not ppc64.

proc: fix ppc64 arch name check

---

pkg/goversion/go_version.go

Change VersionAfterOrEqual(x, A, B) to return true for pre-releases of
version A.B. This is what it did before, it was broken when goversion
was changed to support the new version format.

goversion: include pre-releases in VersionAfterOrEqual check

---

CHANGELOG.md
pkg/version/version.go

Thank you @alexandear, @stefanhaller, @testwill

*: release version 1.22.0 [WIP]

---

.cirrus.yml

It looks like FreeBSD 12 is no longer available

Cirrus-CI: update FreeBSD version

---

go.mod
go.sum
vendor/github.com/go-delve/liner/signal_unix.go
vendor/modules.txt

Update version of go-delve/liner to include the Ctrl-Z fix (SIGTSTP
should be sent to our process group instead of just sending it to
ourselves to correctly imitate a terminal).
Fixes #3605

go.mod: Update version of go-delve/liner

---

_scripts/test_linux.sh
pkg/proc/proc_linux_test.go
pkg/proc/proc_test.go
service/dap/server_test.go
service/test/integration2_test.go

The builder is currently spending 15 to 20 minutes installing gcc and
upgrading packages every time we run the tests.
Because of this the build fails sometimes by running out of time.
This change reduces that to 5 minutes by:
* switching from curl to wget (which seems to have fewer dependencies)
* not installing gcc on ppc64le
* skipping tests that depend on gcc or other binutils

TeamCity: speed up ppc64le CI

---

pkg/terminal/command.go

Add automatic paging to the output of print, vars, args and locals.
Fixes #3615

terminal: add paging to print, vars, args and locals

---

pkg/proc/eval.go
pkg/proc/target_exec.go

The flake manifests as an error where the variable i can not be found in
frame 1 and happens in go1.22rc1 between 0.1% and 0.5% of the time (it is highly dependent on CPU contention)
This problem is caused by the new code in evalop.PushLocal referencing the
stale value of SelectedGoroutine. This happens because:
*  evalop.PushLocal calls ConvertEvalScope
* ConvertEvalScope calls FindGoroutine
* FindGoroutine checks the value of selectedGoroutine
When breakpoint conditions are evaluated both the value of selectedGoroutine
and currentThread are stale because we can only set their definitive value
*after* all breakpoint conditions have been evaluated.
The fact that it only happens in 1.22rc1 is coincidental, it's probably
caused by the fact that 1.22rc1 migrates goroutines between threads …

proc: fix TestCondBreakpointWithFrame flakes on 1.22rc1

---

pkg/proc/linutil/dynamic.go
pkg/terminal/command.go

With the glibc loader the link map entry for the static executable has
an empty name field and address equal to 0x0. This case was already
handled by the check in bininfo.go AddImage for names to be valid
paths.
With the musl loader however the first entry, corresponding to the
static executable, has a valid path with address equal to 0x0, since we
record a real address for the image corresponding to the static
executable this results in having two entries for the executable when
musl is used to link go programs.
Change the code scanning the debug link map so that the first entry is
skipped if it has address equal to zero.
Fixes #3617

proc: fix dynamic library loading with musl loader

---

_fixtures/panicline.go
pkg/proc/proc_test.go
pkg/proc/stack.go

The first frame after sigpanic didn't execute a call so we shouldn't
decrement the PC address to look up its location.
Fixes #3634

proc: fix stacktrace frame after runtime.sigpanic

---

pkg/proc/native/nonative_darwin.go

Removes unnecessary code from nonative_darwin.go

proc/native: remove dead code in nonative_darwin.go

---

_scripts/make.go

When running `make` to re-test an existing build, the `test` target fails with the following error (on macOS):
```
$ make
Testing default backend
=== RUN   TestBuild
dlv_test.go:92: makefile error: exit status 1
output go build -ldflags "-extldflags -static" -tags=macnative "-ldflags=-s -X main.Build=88380654feb85c213d2bb60532d95be8d562c86e" github.com/go-delve/delve/cmd/dlv
codesign -s dlv-cert ./dlv
./dlv: is already signed
exit status 1
```
This PR adds a check to `_scripts/make.go` to simply skip the codesigning step if the `codesign --verify` command reports the executable is already signed with a valid certificate.

make.go: skip codesigning when testing an existing build

---

service/dap/server.go
service/dap/server_test.go

_fixtures/fncall.go was made to support TestCallFunction in pkg/proc
and new things must be added to fncall.go to test new features. Having
a test depend on precise line numbers makes the process tedious.

service/dap: make TestEvaluateCallFunction independent of line numbers

---

pkg/proc/proc_test.go

The test can never work on development versions of Go.

proc: skip TestDebugStripped on development versions of Go

---

pkg/proc/eval.go
pkg/proc/evalop/evalcompile.go
pkg/proc/evalop/ops.go
pkg/proc/variables.go
pkg/proc/variables_test.go

When the users uses a reslice operation load the whole resliced
variable, ignoring the MaxArrayValues setting.
Only apply this when the 'high' part is specified and a literal and the
'low' part is either unspecified or a literal.
Fixes #3600

proc: if a reslice operator is used load the whole slice

---

service/dap/server.go
service/dap/server_test.go
service/dap/types.go

Add a waitfor option for 'dap attach' that waits for a process with a
given name to appear before attaching to it.
This recovers PR #3584, originally by @muggle-nil, which was fine
except for a broken test.

service/dap: support waitfor option for 'dap attach' only

---

Documentation/usage/dlv_attach.md
Documentation/usage/dlv_backend.md
Documentation/usage/dlv_connect.md
Documentation/usage/dlv_core.md
Documentation/usage/dlv_dap.md
Documentation/usage/dlv_debug.md
Documentation/usage/dlv_exec.md
Documentation/usage/dlv_log.md
Documentation/usage/dlv_redirect.md
Documentation/usage/dlv_replay.md
Documentation/usage/dlv_run.md
Documentation/usage/dlv_test.md
Documentation/usage/dlv_version.md
cmd/dlv/cmds/commands.go
cmd/dlv/dlv_test.go

Add support for listening on a unix domain socket in headless mode and
in the 'connect' command.
Fixes #3654

cmd/dlv: support unix domain sockets

---

pkg/config/config.go
pkg/terminal/command.go
pkg/terminal/terminal.go
service/api/prettyprint.go
service/dap/server.go

Adds configurable highlighting for function names and filenames in stack traces.
Fixes #720

terminal: add color highlighting to stacktraces

---

pkg/config/config.go
pkg/terminal/terminal.go

Add option to configure prompt color.
Fixes #3603

terminal: add prompt color option

---

CHANGELOG.md
pkg/version/version.go

Thank you @ardnew, @muggle-nil, @michaelmerg

*: release version 1.22.1

---

pkg/dwarf/dwarfbuilder/info.go

It did not terminate the section with the required 0 byte.

dwarfbuilder: fix makeAbbrevTable

---

_scripts/rtype-out.txt
_scripts/rtype.go
cmd/dlv/dlv_test.go
pkg/proc/variables.go
pkg/terminal/command.go

* skip staticcheck on go1.23 for now
* fix reading interface values in go1.23
* sync list of waitreasons from go1.23

*: misc fixes for go1.23

---

go.mod
go.sum
vendor/github.com/google/go-dap/schematypes.go
vendor/modules.txt

A new version of github.com/google/go-dap is available, update to latest.

Upgrade github.com/google/go-dap to v0.12.0

---

pkg/proc/evalop/eval_go117.go
pkg/proc/evalop/eval_go118.go
pkg/proc/evalop/evalcompile.go

The PR cleans up code files that are needed to support compiling with Go 1.17. Since the https://github.com/go-delve/delve/pull/3589 these files are not used.

proc/evalop: remove no longer needed Go 1.17 files

---

pkg/dwarf/loclist/dwarf5_loclist.go

The PR removes the redundant `err != nil` check because `err` cannot be `nil` in that context.
This was found by the [`nilness`](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness) analyzer:
```sh
❯ go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@latest
❯ go vet -vettool=$(which nilness) ./...
pkg/dwarf/loclist/dwarf5_loclist.go:121:10: impossible condition: nil != nil
```

dwarf/loclist: remove impossible condition

---

pkg/proc/bininfo.go

Adds a recover to the functions reading debug info from the go runtime
data structures for stripped executables.
This function is best-effort and can sometimes fail in weird ways,
instead of crashing recover any panic and turn them into errors.
Fixes #3650

proc: catch panics when reading debug info for stripped executables

---

pkg/dwarf/godwarf/tree.go
pkg/proc/eval.go
pkg/proc/proc_test.go

The `scope.Locals` function did not have any guard checks against missing DWARF information. This patch adds a check, which likely will need to be added to other functions as well.
Fixes #3694

pkg/proc: defend better against missing DWARF

---

_fixtures/closurecontents.go
pkg/dwarf/godwarf/type.go
pkg/dwarf/reader/variables.go
pkg/proc/bininfo.go
pkg/proc/proc_test.go
pkg/proc/variables.go
service/api/prettyprint.go
service/api/types.go
service/dap/server.go

Supports showing captured variables for function closures on versions
of Go that export informations about the closure struct (Go >= 1.23)
Fixes #3612

proc: support reading captured variables of closures

---

Documentation/cli/README.md
_fixtures/test if path/main.go
pkg/locspec/locations.go
pkg/terminal/command.go
pkg/terminal/command_test.go

Allows for a user to specify the breakpoint condition directly
when creating the breakpoint. The new syntax looks like the
following:
```
break <name> <locspec> [if <expression>]
```
Also updates docs to include more examples and locspec description
instead of directing users to the online / source documentation.

pkg/terminal: allow postfix if for breakpoint conds 

---

cmd/dlv/cmds/commands.go

Mostly to avoid the default filename completions to flags that don't operate on filenames. Then again, mark ones that do explicitly as such, and add more specific completions for a number of other cases, too.

cmd/dlv: add shell (non-)completions to flags taking args

---

_scripts/rtype-out.txt
_scripts/rtype.go
pkg/proc/types.go
pkg/proc/variables.go
service/dap/server_test.go

* Adjust rtype.go script to handle constants moved to internal/abi from
runtime
* Remove tests in service/dap/server_test that relied on knowledge of
the internal layout of channels.

tests: fix tests on Go 1.23

---

pkg/terminal/command.go
pkg/terminal/command_test.go

When a breakpoint was set on the current line via `break if i ==3` style condition setting, we would erroneously set the breakpoint name to be 'if'.

pkg/terminal: clear erroneous name setting on postfix if

---

Documentation/cli/README.md
pkg/terminal/command.go

The PR removes the duplicated word `line` from the `break` command help.

pkg/terminal: remove duplicated word

---

cmd/dlv/cmds/commands.go

Avoid default filename completions when not applicable.

cmd/dlv: improve positional argument completion

---

pkg/proc/eval.go
pkg/proc/evalop/evalcompile.go
pkg/proc/evalop/ops.go
pkg/proc/fncall.go

Generalizes the function for checking for escaping pointers so that it
can be used to iterate on all pointers of a variable.
Also generalizes the string allocation opcodes so that in the future we
can use it to call other special runtime functions (for example: map
access, channel send/receive, etc)

proc: generalize escapeCheck and allocString

---

cmd/dlv/dlv_test.go
pkg/terminal/command.go

Currently the trace option prints function names only for call instructions and does not print it for return instructions
Add function name even on return, this will help in pairing call and returns when we eventually add a depth parameter to trace children as well

Add function name even in return trace

---

pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/gdbserver_conn.go

This change optimizes the gdbwire backend by reducing the number of
round trips we have to make to debugserver. It does this by using the
jstopinfo packet to only query threads which we know to have a stop
reason, and it also uses the registers returned by the 'T' packet
to avoid issuing a bunch of 'p' packets to get the register values.

pkg/proc/gdbserial: optimize gdbwire backend

---

pkg/proc/gdbserial/gdbserver_conn.go
pkg/proc/gdbserial/rr.go

The following fixes have been applied to make delve work with rr 5.7.0
* added a new launch prefix to exclude from stderr output
* allow the thread selection packet to be sent for 'c' commands even
when the stub supports thread suffixes, because the specification is
unclear over what should be done with bc and bs packets with thread
suffixes.
* changed the way qRRCmd are escaped and added a thread selector to
them to match changes to rr codebase

gdbserial: fixes for rr 5.7.0

---

pkg/terminal/starbind/conv_test.go
pkg/terminal/starbind/repl.go
pkg/terminal/starbind/starlark.go

This PR removes usage of [starlark global variable options](https://pkg.go.dev/go.starlark.net/resolve#pkg-variables), see https://github.com/google/starlark-go/issues/435. Changes:
- Remove `resolve.AllowNestedDef, resolve.AllowLambda, resolve.AllowFloat, resolve.AllowBitwise` because this obsolete flags has no effect.
- Use `starlark.ExecFileOptions` instead of deprecated [`starlark.ExecFile`](https://pkg.go.dev/go.starlark.net/starlark#ExecFile).
- Use `starlark.EvalOptions` instead of deprecated [`starlark.Eval`](https://pkg.go.dev/go.starlark.net/starlark#Eval).
- Use `starlark.EvalExprOptions` instead of deprecated [`starlark.EvalExpr`](https://pkg.go.dev/go.starlark.net/starlark#EvalExpr).

pkg/terminal: remove deprecated starlark global options

---

pkg/dwarf/frame/entries_test.go
pkg/dwarf/line/line_parser_test.go
pkg/dwarf/line/state_machine_test.go
pkg/proc/bininfo.go
pkg/proc/core/linux_core.go
pkg/proc/dwarf_expr_test.go
pkg/proc/evalop/evalcompile.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/moduledata.go
pkg/proc/proc_test.go
pkg/proc/scope_test.go
pkg/proc/stack_sigtramp.go
pkg/proc/target_exec.go
pkg/proc/variable_test.go
pkg/proc/variables_test.go
pkg/terminal/docgen.go
pkg/terminal/terminal.go
service/api/conversions.go
service/api/prettyprint.go
service/dap/server.go
service/dap/server_test.go
service/debugger/debugger.go
service/test/integration1_test.go
service/test/integration2_test.go

This PR removes excessive empty lines at the start and end of a block. They can be deleted without harming readability.

*: remove redundant lines at the start/end of block

---

Documentation/usage/dlv_backend.md
cmd/dlv/cmds/commands.go
pkg/proc/gdbserial/rr.go

Adds two environment variables to configure rr invocations.
Fixes #3670

proc/gdbserial: add environment variables to configure rr invocation

---

Documentation/backend_test_health.md
_fixtures/stackwatchbug.go
pkg/proc/amd64util/debugregs.go
pkg/proc/proc_test.go
pkg/proc/stackwatch.go
pkg/proc/target_exec.go

When stack watchpoints go out of scope simultaneously they can hide (or
duplicate the effect) of other breakpoints (including other watchpoints
going out of scope) that are placed on the same physical memory
location.
This happens because we delete the watchpoint-out-of-scope breakpoint
while we are evaluating hit breakpoints, mangling the breaklets list.
This commit moves breakpoint deletion out of the
watchpoint-out-of-scope condition, delaying it until all hit
breakpoints have been evaluated.
Also fix a bug where on amd64 if all four watchpoints are in use the last one is not checked.
Fixes #3739

proc: fix bug with stack watchpoints going out of scope

---

pkg/proc/proc_test.go
pkg/proc/stack.go

Fix TestRangeOverFuncNext on non-linux operating systems, on arm64 and
when the build mode is PIE.

proc: fix TestRangeOverFuncNext

---

pkg/proc/eval.go
pkg/proc/evalop/evalcompile.go
pkg/proc/evalop/ops.go
pkg/proc/proc_test.go
pkg/proc/variables_test.go

Because of how range-over-func is implemented it is difficult to
determine the set of visible local variables during expression
compilation (i.e. it is difficulto to keep the HasLocal function
correct).
This commit moves that logic from expression compilation to expression
evaluation.
Updates #3733

proc: refactor identifier evaluation for range-over-func support

---

service/debugger/debugger.go

Print a better message when an unattended stop happens for reasons
other than hitting a breakpoint.

service: print better message for unattended stops

---

pkg/astutil/astutil.go
pkg/elfwriter/writer.go

The PR fixes the Go reference documentation for the `astutil` and `elfwriter` packages.
Before (https://pkg.go.dev/github.com/go-delve/delve):
After:

pkg/astutil,pkg/elfwriter: fix package doc

---

pkg/proc/breakpoints.go
pkg/proc/eval.go
pkg/proc/fncall.go
pkg/proc/proc_test.go
pkg/proc/stack_sigtramp.go

Supports viewing local variables and evaluating expressions correctly
when range-over-func is used.
The same limitations that the previous commit on this line had still
apply (no inlining, wrong way to identify the range parent in some
cases).
Updates #3733

proc: initial support for expressions with range-over-func

---

pkg/terminal/command.go

The PR removes usage of deprecated [`strings.Title`](https://pkg.go.dev/strings#Title).
In our case, for titling three words `breakpoint, tracepoint, watchpoint` the `strings.Title` is perfectly fine. But I decided to remove it anyway.

pkg/terminal: do not use deprecated strings.Title

---

CHANGELOG.md
_fixtures/issue2896.go
pkg/proc/bininfo.go
pkg/proc/native/support_sentinel_darwin.go
pkg/terminal/command_test.go
service/dap/server_test.go
service/rpccallback.go

The PR corrects spelling issues:
- fix wrong username in CHANGELOG;
- fix package name;
- `information` do not use in plural;
- correct typos in comments.

all: fix typos in CHANGELOG, comments and package name

---

pkg/proc/bininfo.go
service/debugger/debugger.go

Fixes bug where the incorrect Build ID could be used to try and download the source for a binary. This is because the Build ID was stored on the BinInfo object for a target and not the image itself.

pkg/proc,service/debugger: fix debuginfod-find source

---

pkg/proc/mem.go
pkg/proc/proc_general_test.go

fix https://github.com/go-delve/delve/issues/3760

fix: mem cache out of range panic caused by overflow

---

pkg/dwarf/reader/variables.go
pkg/proc/eval.go
pkg/proc/proc_test.go
pkg/proc/stack.go
pkg/proc/target_exec.go

Extends support for stepping through range-over-func statement to
programs compiled with inlining enabled.
Updates #3733

proc: support stepping through range-over-func statements with inlining

---

cmd/dlv/dlv_test.go
service/debugger/debugger.go
service/test/integration2_test.go

Use a thread scope to evaluate breakpoint variables if the current
thread does not have an associated goroutine.
Fixes #3758

service/debugger: evaluate breakpoint vars on g-less threads

---

README.md
pkg/proc/core/linux_core.go
pkg/proc/linutil/dynamic.go
pkg/proc/native/proc_darwin.c
pkg/proc/native/ptrace_linux_386.go
pkg/proc/variables.go

The PR edits links in comments:
- Replace `http://` with `https://`.
- Fix not existent links:
- Replace `http://lxr.free-electrons.com/source/include/uapi/linux/elfcore.h` with the latest available `https://elixir.bootlin.com/linux/v4.20.17/source/fs/binfmt_elf.c`
- Replace `http://uhlo.blogspot.fr` with `https://uhlo.blogspot.com`

pkg/proc: fix 404 links and change to https

---

pkg/terminal/command.go

The PR adds missing `f.Close()` call.
If `_, err = f.Write(...)` returns an error, the program doesn't call `f.Close()`:
```go
f, err := os.CreateTemp("", "dlv-on-cmd-")
if err != nil {
return err
}
defer func() {
_ = os.Remove(f.Name())
}()
// ...
_, err = f.Write([]byte(strings.Join(attrs, "\n")))
if err != nil {
// missing f.Close() which is called below
return err
}
err = f.Close()
if err != nil {
return err
}
```

pkg/terminal: add missing file.Close() call

---

_scripts/gen-faq-toc.go
pkg/dwarf/dwarfbuilder/info.go
pkg/proc/dump.go
pkg/proc/gdbserial/rr.go
pkg/terminal/command.go

The PR refactors code to `.WriteString(...)` instead of `.Write([]byte(...))`, both for `File` and `Buffer`.
[`File.WriteString(...)`](https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/os/file.go;l=293) may be more efficient than `File.Write([]byte(...))` because it utilizes `unsafe` under the hood to convert a `string` to `[]byte` without allocation.

pkg: refactor to .WriteString() instead of .Write([]byte())

---

pkg/dwarf/line/line_parser_test.go
pkg/proc/proc_test.go

[`t.Logf`](https://pkg.go.dev/testing#T.Logf) is slightly better than `fmt.Printf` for tests:
> Logf formats its arguments according to the format, analogous to Printf, and records the text in the error log. A final newline is added if not provided. For tests, the text will be printed only if the test fails or the -test.v flag is set.

pkg/dwarf/line: use t.Logf instead of fmt.Printf in tests

---

service/rpc1/doc.go
service/rpc1/readme.txt

This page https://pkg.go.dev/github.com/go-delve/delve/service@v1.22.1
- before:
- after:

service/rpc1: add Go Reference doc

---

pkg/proc/breakpoints.go
pkg/proc/eval.go
pkg/proc/proc_test.go
pkg/proc/stack.go
pkg/proc/target_exec.go

Set a breakpoint on the return address of the current function, if it's
a range-over-func body, and clear the stepping breakpoints for the
current function (except the entry one) when its hit.
Without this what can happen is the following:
1. the range-over-func body finishes and returns to the iterator
2. the iterator calls back into the range-over-func body
3. a stepping breakpoint that's inside the prologue gets hit
Updates #3733

proc: fix bug with range-over-func stepping

---

.teamcity/settings.kts
pkg/goversion/compat.go

Add 1.23 to supported versions and to test matrix, remove 1.19 and 1.20
from supported versions (1.19 should have been removed long ago, but we
forgot to do it on release).

goversion: add 1.23 to supported versions, update test matrix

---

pkg/proc/breakpoints.go
pkg/proc/stepping_test.go
pkg/proc/target_exec.go

Fixes a repeated stop on the first line of a range-over-func body when
stepping through a program. The entry point breakpoint is changed to a
special breakpoint that, when hit:
* clears the current temporary breakpoints
* sets breakpoints like 'next' would, and
* resumes execution.

proc: fix step stuttering when entering range-over-func bodies

---

_fixtures/rangeoverfunc.go
pkg/proc/stepping_test.go

TestRangeOverFuncNext and TestRangeOverFuncNextInlined are failing on
linux/386 with go1.23 due to an inconsistency on how append works on
32bit platforms.

proc: fix TestRangeOverFuncNext on linux/386

---

pkg/proc/eval.go
pkg/proc/variables.go
pkg/proc/variables_test.go

fix a couple of places where we needed to track the cap

eval: Allow reslicing a slice up to its cap, rather than its length

---

_fixtures/testvariables2.go
pkg/terminal/starbind/conv.go
pkg/terminal/starlark_test.go

If a value of a derived integer type matches a named constant, Delve will wrap the string representation of the value with the name of the constant, causing ParseInt/ParseUint to fail. This change removes the wrapping before attempting to parse the value before sending it to Starlark.
Fixes  #3801

terminal/starbind: fix starlark conversion of named consts

---

service/dap/handles.go
service/dap/server.go

The oldest version of Go we compile with is 1.20 at this point, we can
thus make use of generic type parameters and the handlesMap support
type in service/dap is improved by them.

service/dap: make handlesMap generic

---

service/dap/server_test.go

Encoding/json changed some error messages in 1.24, fix the tests.

service/dap: fix test failure with 1.24

---

_fixtures/testvariables2.go
pkg/proc/eval.go
pkg/proc/variables_test.go

The Go specification says that the result of division of untyped
constants should be an untyped integer constant if both constants are
untyped integers, the go/constant package however does something
different by always producing an untyped floating constant.
Fixes #3793

proc: fix result type of division of untyped constants

---

pkg/proc/gdbserial/gdbserver.go

We have a check for Rosetta that should point users towards
misconfiguration, however occasionally we still get new issues about
debugserver crashing and some of those, as it turns out, are still
caused by Rosetta (see for example #3804).
Check the output of 'uname -a' and check that it isn't 'x86_64' if we
are an 'arm64' process: if that happens we are running unemulated but
debugserver will refuse to work.

proc: improve Rosetta check

---

_fixtures/setiterator.go
pkg/proc/bininfo.go
pkg/proc/eval.go
pkg/proc/fncall.go
pkg/proc/stack.go
pkg/proc/variables_test.go

For optimized functions .closureptr is sometimes omitted from DWARF,
allow it to be 0 and try to recover the range-over-func stack by best
effort.
Fixes #3806
Argument variables of a range-over-func body closure should be returned
flagged as normal local variables, not as function arguments.
Updates #3806

proc: for optimized functions allow .closureptr to not exist

---

pkg/proc/bininfo.go
pkg/proc/target.go
pkg/proc/types.go

Cache module data so that we don't reload it every time we look up a
variable with a generic type.

proc: cache module data

---

Documentation/EditorIntegration.md

Hi, this patch mentions dape in the list of editor plugins for Emacs.

Documentation: Add dape to list of plugins

---

Documentation/usage/dlv_dap.md
cmd/dlv/cmds/commands.go
cmd/dlv/dlv_test.go

This change updates the '--client-addr' flag to accept Unix domain sockets (UDS). Currently, the --listen flag supports UDS, but --client-addr does not. This modification ensures consistency across the APIs and improves support for vscode-go, which uses reverse mode (via client-addr) to connect to DAP.
Fixes #3814
See - https://github.com/golang/vscode-go/issues/3216

cmds/commands: Update 'client-addr' to support Unix domain sockets

---

pkg/proc/gdbserial/rr_test.go
pkg/proc/proc_test.go
pkg/proc/scope_test.go

The PR refactors tests that check for `proc.ErrProcessExited` by using `errors.As`.

pkg/proc: simplify tests by using errors.As

---

cmd/dlv/dlv_test.go

The test is currently broken due to a change to the export format.

tests: disable TestGeneratedDoc on 1.24 (tip)

---

Documentation/cli/README.md
pkg/terminal/command.go
pkg/terminal/starbind/conv.go
service/rpc2/server.go

Change the examinemem command to have a new format 'raw' that just
prints the raw memory bytes.
Change the transcript command to add a new flag that disables prompt
echo to the output file.
Fixes #3706

terminal,service: add raw examinemem dump

---

pkg/proc/bininfo.go
pkg/proc/dwarf_export_test.go
pkg/proc/eval.go
pkg/proc/evalop/evalcompile.go
pkg/proc/evalop/ops.go
pkg/proc/fncall.go
pkg/proc/mem.go
pkg/proc/target_exec.go
pkg/proc/types.go
pkg/proc/variables.go
pkg/proc/variables_test.go

This commit adds a new mode to call injection. If the runtime.debugPinner
function is available in the target executable it obtains a pinner by
calling it and then uses it to pin the pointers in the results of call
injection.
This allows the code for call injection to be refactored to execute the
calls in the normal order, since it doesn't need to be concerned with having
space on the target's memory to store intermediate values.
Updates #3310

proc: adds pointer pinning to call injection

---

_scripts/make.go
cmd/dlv/dlv_test.go
pkg/proc/native/support_sentinel_linux.go
pkg/proc/riscv64_arch.go
pkg/proc/riscv64_disasm.go

Delete non-working prologue detection code and mark port as experimental.
Updates #3832

*: mark riscv64 port as experimental

---

pkg/proc/core/core.go
pkg/proc/core/core_test.go
pkg/proc/core/delve_core.go
pkg/proc/core/linux_core.go
pkg/proc/core/windows_amd64_minidump.go

Cleans up repetitive code in pkg/proc/core and also adds coredumpctl
support to our test suite.

pkg/proc/core: Clean up some repetitive code

---

pkg/goversion/compat.go
pkg/goversion/go_version.go
pkg/goversion/version_test.go
pkg/proc/bininfo.go
pkg/proc/proc_test.go
pkg/proc/test/support.go

Once upon a time Go version strings for development builds did not
reference the major/minor version they belonged to, therefore the best
we could do was to always assume that a development build belonged to
the most recently released version of Go.
This commit changes pkg/goversion so that the new style of development
version string is fully parsed.

goversion: parse version for development builds

---

Documentation/cli/README.md
pkg/locspec/locations.go
pkg/terminal/command.go
pkg/terminal/docgen.go

Changes < to &lt; in autogenerated documentation for CLI commands so that markdown does not interpret them as HTML tags.
Supersedes #3830
Fixes #3829

Documentation: fix autogenerated markdown documentation

---

pkg/proc/amd64util/xsave.go
pkg/proc/amd64util/xsave_amd64.go
pkg/proc/amd64util/xsave_other.go
pkg/proc/core/linux_core.go
pkg/proc/native/ptrace_freebsd_amd64.go
pkg/proc/native/ptrace_linux_386.go
pkg/proc/native/ptrace_linux_amd64.go

The offset of state component i can be found via
CPUID.(EAX=0DH,ECX=i):EBX. The ZMM_Hi256 is state component 6, so we use CPUID to enumerate the offset instead of hardcoding.
Fixes #3827.

proc: use CPUID to determine ZMM_Hi256 region offset

---

_scripts/test_linux.sh
cmd/dlv/dlv_test.go

Update version of staticcheck and reenable for go1.23

_scripts: update staticcheck version

---

service/rpc2/server.go

The maximum length changed in 52405ba86bd9e14a2e643db391cbdebdcbdb3368.

service/rpc2: correct ExamineMemory length error message

---

Documentation/installation/README.md

This PR modifies `Installation` section by placing the `go install` method above the `git clone + go install`. The `go install` is much simpler and should be on top.

Documentation: using `go install` is preferable

---

pkg/proc/fncall.go

This is probably the cause of the panic such as in issue #3848 and
other similar issues, it is hard to be sure because we never get a
proper reproducer but judging from the stack traces it should be this.
Also it doesn't affect versions of Go that have the debug pinner.
Fixes #3848

proc: do not ignore error return of funcCallEvalFuncExpr

---

cmd/dlv/dlv_test.go
pkg/dwarf/line/line_parser_test.go
pkg/proc/core/core_test.go
pkg/proc/gdbserial/rr_test.go
pkg/proc/proc_test.go
pkg/proc/test/support.go
pkg/terminal/command_test.go
service/dap/server_test.go
service/debugger/debugger_test.go
service/test/integration2_test.go

This PR simplifies tests by removing `os.Exit` calls in `TestMain`. It's not needed from Go 1.15, see golang/go#34129.
Additionally, this PR updates the comment for `RunTestsWithFixtures`.

tests: calling os.Exit in TestMain is not required

---

cmd/dlv/dlv_test.go
pkg/proc/breakpoints.go
service/dap/server.go
service/debugger/debugger.go
service/rpc1/server.go
service/rpc2/server.go

The PR removes redundant `var err error` lines across the project.

all: remove redundant err declarations

---

pkg/proc/core/minidump/minidump.go

proc/core/minidump: remove newlines from minidump logs

---

pkg/proc/native/proc_windows.go

When the Delve instance is running in a detached state and it launches
a process an additional child conhost.exe process will be created, we
should detach from it.
Fixes #3864

proc: fix issue on Windows when launching process while detached

---

pkg/proc/proc_test.go
pkg/proc/variables.go

If 'a' is a captured variable in a function pointer called 'f' let
'f.a' evaluate to its value.

proc: allow accessing captured variable as if they were struct fields

---

pkg/proc/breakpoints.go
pkg/proc/proc_test.go
pkg/proc/target_exec.go
pkg/proc/target_group.go
pkg/terminal/command_test.go
service/api/conversions.go
service/debugger/debugger.go
service/test/integration2_test.go

Previously breakpoints with hitcount conditions that became
unsatisfiable
would become disabled, this was done as an optimization so that the
continue loop would no longer need to stop on them and evaluate their
conditions.
As a side effect this meant that on restart these breakpoints would
remain disabled, even though their hit condition returned satisfiable.
This commit changes Delve behavior so that breakpoints with
unsatisifiable hitcount conditions are no longer disabled but the
associated physical breakpoints are removed anyway, preserving the
optimization.
Some refactoring is done to the way conditions are represented and the
enable status is managed so that in the future it will be possible to
use hitcount conditions to implement "chained" breakpoints (also known
as dependet …

pkg/proc,service/debugger: do not disable unsatisfiable breakpoints

---

_fixtures/amend_breakpoint.star
_scripts/gen-starlark-bindings.go
pkg/terminal/starbind/conv.go
pkg/terminal/starbind/starlark_mapping.go
pkg/terminal/starlark_test.go

Structs returned to starlark scripts by API calls were immutable, this
made amend_breakpoint nearly impossible to use since its argument must
be a api.Breakpoint struct which the caller has received from
get_breakpoint and modified.

terminal/starbind: allow modification of structs returned by API

---

_fixtures/testvariables2.go
_scripts/rtype-out.txt
_scripts/rtype.go
cmd/dlv/dlv_test.go
pkg/proc/eval.go
pkg/proc/mapiter.go
pkg/proc/variables.go
pkg/proc/variables_test.go

Adds support for the swiss table implementation for Go's maps.

pkg/proc: support swiss table map implementation

---

cmd/dlv/dlv_test.go
service/test/integration2_test.go

This PR removes useless `os.Remove(dlvbin)` in tests.
`protest.GetDlvBinary` calls `getDlvBinInternal` which creates `dlv.exe` inside the temporary directory from `t.TempDir()`. And [`T.TempDir`](https://pkg.go.dev/testing#T.TempDir) function automatically removes the returned directory.

tests: removing of dlvbin is not needed

---

.teamcity/settings.kts
pkg/goversion/compat.go
pkg/proc/stepping_test.go

Add go1.24 to compatibility set and test matrix.
Remove go1.21 from test matrix.
TestRangeOverFuncNextInlined is disabled because the improved inlining
of go1.24 produces symbol names that are too complicated for us to
correlate, a fix for this will require a change to the compiler that
will probably be too complex to make it into 1.24.

goversion,proc_test: add go1.24 compatiblity, disable broken test

---

service/rpc2/client.go
service/test/integration2_test.go

It does not work because of how TeamCity creates the build directory.

service/test: disable TestGuessSubstitutePath on TeamCity/linux/tip

---

pkg/proc/internal/ebpf/helpers.go

The update of gilium/ebpf introduced a beaking change in it's API: The `offset` in the UprobeOptions is now relative to the added option `address`. Since `address` was only default initalized, the library did not use `address` and `offset` as address for the uprobe, but tried to calculate the offset itself based on the given symbol. Since we set the path of the executable as symbol, the library errored when trying to resolve it.
Fixes https://github.com/go-delve/delve/pull/3491
How to test this PR: Run `sudo -E go run _scripts/make.go test -v --test-set cmd/dlv --test-run='^.*EBPF.*$' ` on the main branch, notice how it fails and re-run on this branch.

pkg/proc/internal/ebpf: Fix uprobe address

---

cmd/dlv/cmds/commands.go

Its actually a redundancy code.

delete redundancy code.

---

pkg/proc/bininfo.go
pkg/proc/types.go
pkg/proc/variables.go
pkg/proc/variables_test.go
pkg/terminal/command.go

The PR replaces `sort.Sort` with `slices.SortFunc` across the `pkg/proc` and `pkg/terminal` packages.
This change is made because the slices functions are slightly faster and easier to use.
See https://go-review.googlesource.com/c/go/+/626038.

pkg: refactor sort.Sort to slices.SortFunc

---

pkg/proc/arm64_disasm.go

The arm64 disassembler is in fact already compiled in unconditionally.

proc: remove irrelevant TODO comment

---

pkg/proc/stack.go

When creating a stack trace, if we make no progress with the normal
thread stack switch to the goroutine stack before giving up. This
improves stacktraces on the main thread of minidumps created on Windows
by WER.
Fixes #3824

proc: switch to goroutine stack if we make no progress on thread stack

---

service/dap/server.go
service/dap/server_test.go

This change adds support to emit the process DAP event after handling launch requests.
Note: I found myself in a situation where I needed this exact event get process information from delve. I discovered this event was not implemented, so I have added it in the place that seems to be the most logical place (just based on my limited exposure to the codebase). Please let me know if this change is unwarranted or if useful, if it needs any additional work.
Thanks!

service/dap: provide process events after launch

---

_fixtures/issue3310.go
pkg/proc/eval.go
pkg/proc/variables_test.go

After a call injection sequence terminates allow the evaluator to
access thread registers again so that variables stored in registers can
be used as arguments.
Fixes #3310

proc: allow access to thread registers after a function call

---

.teamcity/settings.kts

We haven't had a builder for 2 months, remove the configuration.

TeamCity: remove riscv64 from configuration

---

pkg/astutil/astutil.go
pkg/dwarf/godwarf/fakes.go
pkg/dwarf/godwarf/type.go
pkg/proc/bininfo.go
pkg/proc/breakpoints.go
pkg/proc/eval.go
pkg/proc/evalop/evalcompile.go
pkg/proc/fncall.go
pkg/proc/mapiter.go
pkg/proc/target_exec.go
pkg/proc/variables.go

* deduplicates exprToString, defined in multiple packages, and moves it
to astutil
* moves resolveTypedef into pkg/dwarf/godwarf, this is currently only
used by pkg/proc but we will need to call it from pkg/proc/evalop
* creates a new FakePointerType function in pkg/dwarf/godwarf, this is
also a function that is only used by pkg/proc but pkg/proc/evalop will
also need.
Updates #1465

proc: some refactorings for supporting struct literals

---

pkg/proc/gdbserial/gdbserver_conn.go
pkg/proc/gdbserial/rr.go

Previously we relied on availability of the thread suffix protocol
extension to determine whether we should use the old or new encoding
for the qRRCmd extension of rr. Newly released version 5.9.0 of rr
removes this ability by not reporting the thread suffix extension as
available unless it gets to start lldb itself.
Use the value of rr's version instead.
Fixes #3920

proc/gdbserial: use rr version to determine style of qRRCmd

---

Documentation/backend_test_health.md
_fixtures/watchpointInterface.go
pkg/proc/breakpoints.go
pkg/proc/proc_test.go

Adds support for setting a watchpoint on an interface by setting the watchpoint on the data pointer in the eface/iface runtime structs representing the interface.

pkg/proc: add support for interface watchpoints

---

service/test/integration2_test.go

When this test is run on machines with support for AVX-512, the length of xmm0var.Children will be greater, causing an out of bounds error when iterating through the `expected` slice.

service/test: handle wider registers in test

---

pkg/logflags/logflags.go
pkg/proc/bininfo.go
pkg/proc/eval.go
pkg/terminal/starbind/starlark.go
service/dap/server.go
service/rpccommon/server.go

Add stack counter for the various places where we catch internal
errors.

telemetry: add stack counter for internal errors

---

pkg/proc/evalop/evalcompile.go
pkg/proc/evalop/ops.go
pkg/proc/fncall.go
pkg/proc/variables_test.go
service/dap/server_test.go

For the toplevel function call do not perform pinning since the
function results are unpinned immediately.

proc: do not pin function call returns for toplevel call

---

Documentation/cli/README.md
Documentation/cli/cond.md
Documentation/cli/expr.md
Documentation/cli/starlark.md
_fixtures/bphitcountchain.go
_fixtures/chain_breakpoints.star
pkg/proc/breakpoints.go
pkg/proc/eval.go
pkg/proc/evalop/evalcompile.go
pkg/proc/evalop/ops.go
pkg/proc/proc_test.go
pkg/proc/target_group.go
pkg/proc/variables.go
pkg/terminal/command.go
pkg/terminal/starlark_test.go

Expose breakpoint hitcounts in the expression language through the
special variable runtime.bphitcount:
runtime.bphitcount[1]
runtime.bphitcount["bpname"]
will evaluate respectively to the hitcount of breakpoint with id == 1
and to the hitcount of the breakpoint named "bpname".
This is intended to be used in breakpoint conditions and allows
breakpoints to be chained such that one breakpoint is only hit after a
different is hit first.
A few optimizations are implemented so that chained breakpoints are
evaluated efficiently.

proc: expose breakpoint hitcounts in expressions

---

pkg/proc/ppc64le_arch.go

This field was not initialized.

proc: add RegnumToString to PPC64LE architecture

---

pkg/goversion/compat.go
pkg/proc/bininfo.go
service/debugger/debugger.go

Due to #3861 which was fixed in:
https://go-review.googlesource.com/c/go/+/656675
https://go-review.googlesource.com/c/go/+/655976
debugging DWARFv5 executables only works if Delve itself is built with
1.25 or later. Add this check to the version compatibility checks.
Fixes #3861

goversion: add check for DWARFv5 compatibility

---

_fixtures/spawn.go
_fixtures/spawnchild.go
pkg/locspec/locations.go
service/debugger/debugger.go
service/test/integration2_test.go

FindLocation should only return a "location not found" error if none of
the attached target processes can find the location.
Fixes #3933

service/debugger: fix FindLocation with child processes

---

service/test/integration2_test.go

Due to a merge conflict the tests in service/test are not compiling.

service/test: fix compile error in tests

---

cmd/dlv/cmds/commands.go

The PR fixes a typo in trace cmd.

cmd/dlv: fix typo

---

_fixtures/fncall.go
pkg/proc/bininfo.go
pkg/proc/eval.go
pkg/proc/evalop/evalcompile.go
pkg/proc/evalop/ops.go
pkg/proc/moduledata.go
pkg/proc/types.go
pkg/proc/variables.go
pkg/proc/variables_test.go
service/dap/server_test.go
service/test/integration2_test.go

Adds support for evaluating struct literals, and allocating them into
the target's memory.
Updates #1465

proc: add support for struct literals

---

pkg/proc/test/support.go
service/test/integration2_test.go

See: https://issues.redhat.com/browse/RHEL-83958

service/test: skip substitutepath test when modules disabled

---

pkg/proc/core/core_test.go

These tests have been somewhat silently failing on our CI because the test ends up
being skipped [due to the lack of coredumpctl](https://delve.teamcity.com/buildConfiguration/Delve_linux_ppc64le_1_24/66766?buildTab=tests&focusLine=NaN&name=testcore&suite=github.com%2Fgo-delve%2Fdelve%2Fpkg%2Fproc%2Fcore%3A+&expandedTest=build%3A%28id%3A66766%29%2Cid%3A2000000704&showLog=66766_20670_112.20612.20670&logFilter=debug&logView=flowAware).
When `coredumpctl` is present, the test [fails anyways](https://issues.redhat.com/browse/RHEL-83939), so let's just skip it on ppc64le for now.

proc/core: skip tests on ppc64le

---

pkg/proc/eval.go
pkg/proc/evalop/evalcompile.go
pkg/proc/evalop/ops.go
pkg/proc/mem.go
pkg/proc/variables_test.go

Do not always allocate new struct literals to the target's memroy. Wait
until they actually need to have an address.
Fixes #1465

proc: do not always allocate struct literals

---

pkg/proc/bininfo.go
pkg/proc/eval.go
pkg/terminal/starbind/starlark.go

The stack counter for executeOp errors is accidentally incremented too early.

proc: fix bug telemetry counter increment

---

pkg/proc/variables.go

When debugging Go 1.24 programs using some 3rd lib such as https://github.com/timandy/routine/tree/v1.1.4, Delve panics due to corrupted `labelMap` structures caused by unsafe pointer operations in older implementations. Specifically:
- These libraries would inject non-`labelMap` pointers (e.g., `*thread` structs) into `runtime.g.labels`.
- Delve's `Goroutine.Labels()` method assumes valid `runtime/pprof.labelMap` structures, leading to `panic: <nil> not a String` when encountering nil values during `constant.StringVal()` conversion.
This issue blocks debugging sessions for applications that still rely on older dependency versions while using the latest local Go version.
Add defensive checks to handle corrupted label structures safely and skip invalid key-value pairs

proc: skip invalid labels when debugging via Go 1.24

---

service/debugger/debugger.go

Acquire missing targetMutex lock in GuessSubstitutePath. This fixes
TestGuessSubstitutePath with the rr backend.

debugger: acquire missing lock to GuessSubstitutePath

---

pkg/proc/bininfo.go

When using cgo some of the compilation units are produced by the C
compiler and could be in DWARFv5 even if most of the executable is
DWARFv4. In those cases debugging will still work fine outside of C
areas of the executable, it's probably better to proceed.

proc: relax DWARFv5 check

---

pkg/proc/core/core.go
pkg/proc/fncall.go
pkg/proc/gdbserial/gdbserver.go
pkg/proc/gdbserial/rr_test.go
pkg/proc/native/threads.go
pkg/proc/proc_test.go
pkg/proc/target_exec.go
pkg/proc/threads.go
pkg/proc/variables.go
pkg/proc/variables_fuzz_test.go
service/api/conversions.go
service/debugger/debugger.go

Replaces the Thread.Location method with a ThreadLocation function. All
backends implemented the Location method exactly the same way, this
change deduplicates it.

proc: replace Thread.Location method with a function

---

CHANGELOG.md
pkg/version/version.go

Thank you @alexandear, @BronzeDeer, @hongyuh-hh, @codesoap, @Lslightly

Release 1.24.2

---

_scripts/test_linux.sh
cmd/dlv/dlv_test.go
pkg/proc/native/proc_linux.go

Update staticcheck and re-enable it on go1.24.x

cmd/dlv: update staticcheck

---

pkg/proc/eval.go
pkg/proc/moduledata.go
pkg/proc/types.go

The dwarfToRuntimeType does basically the same thing in another way and
doesn't have a bug with making unsigned comparisons that should be
signed. It also does more things compared to dieToRuntimeType but it
shouldn't matter since function call injection is very slow anyway.
Fixes an intermittent bug on windows:
https://delve.teamcity.com/buildConfiguration/Delve_windows_amd64_1_24/67152

proc: remove dieToRuntimeType

---

pkg/terminal/command_test.go

- Fix a typo.
- Include `err` to output.
- Replace `t.Errorf` with `t.Fatalf`.

pkg/terminal: improve TestBreakPointFailWithCond

---

pkg/version/fixbuild.go

Fixes #3986
Prior to this change, the Delve debugger's version information (via `dlv version` command) displays the blob hash of `pkg/version/version.go` as the a Git ident identifier $Id$. Upon reviewing the code a handful of times I wonder if this is intended, given we search for gitrevision key and try to write its value to Version.Build. From this logic in `buildInfoFixBuild` I would assume we would want the latest commit hash dlv is built with and not the file blob hash of `pkg/version/version.go`. That, and many users (myself included) originally though Build should/would represent the commit hash delve was installed/built with (thus the reason for my going down this rabbit hole surmising why its done this way)
If this should in fact be the built git hash then `buildInfoFixBuild` …

version: use git hash instead of file blob hash for Version.Build

---

pkg/proc/arch.go
service/dap/server.go
service/debugger/debugger.go
service/rpc2/server.go

We had a few problems with missing targetMutex acquisitions in
service/debugger, this commit takes care of a few other methods (although I
don't think any of these are problems in practice).
* DwarfRegisterToString is removed, there is no need to call this method
outside of the context of ScopeRegisters/ThreadRegisters which can
directly return the function that DwarfRegisterToString would call
* add lock acquisition to BuildID
* remove Target, TargetGroup, TargetLock and TargetUnlock. Replace them with
a single LockTargetGroup method that acquires the lock and returns the
target group and the unlock function. Callers can still misuse
LockTargetGroup by calling unlock immediately and continuing to use the
target group but this is harder to do accidentally compared to the others.

service/debugger,rpc2,dap: target locking review

---

pkg/proc/gdbserial/gdbserver_conn.go

It looks like some versions of debugserver in some circumstances will
return the wrong number of bytes when reading some registers.
Check for this condition and return an error instead of panic'ing.
Fixes #4008

proc/gdbserial: fix out of bounds access reading registers

---

pkg/proc/stepping_test.go

A couple of lines in rangeoverfunc.go do not produce instructions with
go1.25 on arm64, change the tests to handle this.
Also extend the TestRangeOverFuncNextInlined skip to go1.25 since the
problem with closure names will not be fixed in time.

proc: fix TestRangeOverFunc for arm64 on go1.25

---

pkg/proc/mapiter.go

This is probably the reason for the panics reported by telemetry, the
circumstances that cause this are unclear but we should be defensive
about this anyway.
Fixes #4005

proc: fix nil pointer dereference in swiss table iterator

---

service/dap/server.go
service/dap/server_test.go

If a disconnect requests comes in while the runUntilStopAndNotify
goroutine is hitting a breakpoint a nil debugger dereference can happen
at various points.
This change resolves the problem by never resetting the debugger field
to nil, instead a separate flag is set (which mostly just exist to
avoid duplicate logging and to keep tests happy).
Fixes #4006, #4007, #4020

service/dap: fix race condition between disconnect and continue

---

service/dap/server.go

While working on debugger support for [Zed](https://zed.dev), I noticed that
delve returns internal breakpoints in the "hit breakpoints" array when handling
a panic.
Although there's nothing really wrong with doing this, it caused an edge-case
in our parsing code (as in practice everyone uses unsigned integers for
breakpoint ids), and there's no particular value in doing so (because the
client has no record of the internal breakpoints).

Exclude internal breakpoints from response

---

pkg/proc/amd64_arch.go
pkg/proc/arm64_arch.go
pkg/proc/i386_arch.go
pkg/proc/loong64_arch.go
pkg/proc/ppc64le_arch.go
pkg/proc/riscv64_arch.go
pkg/proc/stack.go

As seen via https://github.com/go-delve/delve/pull/4017 it's possible
that lldb debugserver, in certain versions and circumstances (the
combination is currently not known) can return incorrect or incomplete
information on CPU registers. Be defensive on this by checking if the
result of `it.regs.Reg(it.regs.LRRegNum)` is nil.
Fixes https://github.com/go-delve/delve/issues/4030

proc: propogate errors from switchToGoroutineStack 

---

service/dap/server_test.go

This PR adds `resp.Body.Close()` in `TestBreakpointAfterDisconnect`.
From https://pkg.go.dev/net/http#Get:
> When err is nil, resp always contains a non-nil resp.Body. Caller should close resp.Body when done reading from it.

service/dap: add missing response body close

---

_fixtures/testvariables2.go
pkg/proc/eval.go
pkg/proc/variables_test.go

Type casts between slice types with the same element type should be
allowed. In theory this should be allowed by the check on the real type
(which already gets rid of typedefs) but the compiler here actually
creates a distinct type for Message instead of having it as a typedef
for []uint8.
Fixes #4042

pkg/proc: fix type cast between slices

---

pkg/gobuild/defaultexe.go

Instead of using the pattern that is always randomized, check if it doesn't exist otherwise use a random filename including the pattern. 
Removes annoying windows firewall issue #3494

For DAP try using debug filename pattern for debug binary path before using random string. fix for #3494 (new Windows Firewall detections)

---

service/dap/server.go

onThreadRequest should not try to get the location of unreadable
goroutines.
Fixes #4054

service/dap: do not try to stacktrace an unreadable goroutine

---

service/dap/server_test.go

The test was flaky and occasionally caused a panic. This patch fixes it by properly disconnecting from the server and waiting for shutdown.

service/dap: fix TestConfigurationDoneWithoutDebugSession

---

Documentation/cli/starlark.md
cmd/dlv/dlv_test.go
pkg/proc/bininfo.go
pkg/proc/debuginfod/debuginfod.go
pkg/proc/target_group.go
pkg/terminal/starbind/starlark_mapping.go
pkg/terminal/terminal.go
service/api/conversions.go
service/api/types.go
service/client.go
service/dap/server.go
service/dap/server_test.go
service/debugger/debugger.go
service/rpc2/client.go
service/rpc2/server.go
service/rpccommon/server.go
service/rpccommon/suitablemethods.go

Add a GetEvents method that can be used to retrieve debug events, adds
events for downloading debug info through debuginfod and shows those
events in the command line client as well as console messages in DAP.
In the future this events mechanism can be used to unify EBPF
tracepoints with old style tracepoints.
Update #3906

proc,service,terminal: add events call use it for dld notifications

---

pkg/proc/eval.go
pkg/proc/fncall.go

If we have an error in funcCallStep we must not mark the function call
as finished, otherwise the error will be discarded and execution will
continue under the assumption that there was no error.
Fixes #4085

proc: in-progress calls must be properly terminated

---

pkg/proc/stepping_test.go
pkg/proc/types.go
pkg/proc/variables.go

Change 091ff506 fixed loading the direct flag for Go 1.26 when we go
from a runtime type to a dwarf type, we also did the same check from
the dwarf type to a runtime type when converting variables into
'interface {}'.
This commit deletes unifies the two code paths deleting the one that
wasn't updated.
Fixes the tests on tip.

proc: early fixes for Go 1.26

---

Documentation/backend_test_health.md
pkg/proc/loong64_arch.go
pkg/proc/proc_test.go

These functions involve stack switching on loong64 and must be recognized for Delve to correctly unwind and produce accurate stack traces.
With Go 1.19 and later, cgo is fully supported on linux/loong64, so supporting these functions is required for proper debugging on this platform.
Fixes #4099

pkg/proc: add support for additional stack-switching functions on loong64

---

_fixtures/goroutinegroup.go
service/test/integration2_test.go

The test was spinning up more goroutines than necessary and was sleeping longer than necessary, casuing the test to run for a really long time and often timeout. Reduce both goroutine count and sleep time. Test still passes, as the test is based on goroutine groups not total count of goroutines.

service/test: reduce TestGoroutinesGrouping runtime

---

pkg/proc/bininfo.go
pkg/proc/types.go
pkg/proc/variables.go

pkg/proc: optimize range body lookup cost by trie searching and use moduledata cache to reduce LoadModuleData cost

---

_fixtures/fncall.go
pkg/proc/fncall.go
pkg/proc/variables_test.go

During a call injection if the user tries to call a non-ptr receiver
method on a nil ptr it should receive a nil pointer dereference error.
Fixes #4136

proc: return error when calling a non-ptr receiver method on a nil ptr

---

pkg/proc/variables.go

The fields of the sched structure could be unreadable if what we are
parsing isn't a real G struct.
Fixes #4138

proc: additional checks parsing g structs

---

_fixtures/issue4116.go
pkg/proc/eval.go
pkg/proc/variables_test.go

fix go-delve/delve#4116
Let `eval` get the value of `struct.field` more in line with the syntax of go

pkg/proc: hierarchical search structMember or method

---

Documentation/usage/dlv_debug.md
Documentation/usage/dlv_exec.md
cmd/dlv/cmds/commands.go
pkg/proc/gdbserial/rr.go
pkg/proc/gdbserial/rr_test.go
pkg/proc/proc_test.go
pkg/proc/variables_test.go
service/debugger/debugger.go

Fixes https://github.com/go-delve/delve/issues/4079

Add flag to retain trace directory after detach

---

pkg/proc/eval.go
pkg/proc/fncall.go
pkg/proc/loong64_arch.go
pkg/proc/target.go
pkg/proc/test/support.go

This change enables function call support on loong64, which was previously unsupported for Go versions before 1.24. With this patch, users can now evaluate expressions and perform function calls when debugging on loong64.

pkg/proc: add support for function calls on loong64

---

cmd/dlv/dlv_test.go

After the parallellization this test, for some reason, gets stuck
specifically on FreeBSD. Disable it.

dlv_test: disable TestUnattendedBreakpoint on FreeBSD

---

.teamcity/settings.kts
_scripts/gencert.sh
_scripts/make.go

TeamCity build fails on Mac arm cloud agent because codesigning hangs on a password prompt in GUI. This commit changes how we generate a certificate and how we import it into a keychain so that it does not prompt passwords in GUI.

ci/cd: fix codesigning on mac/arm cloud agent

---

.teamcity/settings.kts

Apparently, setting CI=true on a step level does not work, so we move it to the project level.

ci/cd: set CI=true on a project level

---

_fixtures/testenv2.go
_fixtures/testnextnethttp.go
_scripts/test_linux.sh
pkg/proc/proc_test.go
service/dap/server_test.go
service/test/integration2_test.go

This patch fixes the test suite to enable tests to be ran in parallel test processes via https://github.com/go-delve/paratest.
* Ensure fixtures which bind to a socket use a random port
* Ensure we use `t.Setenv`
* Ensure no tests are modifying fixtures in place that other tests may rely on

service,proc: fix tests to enable parallel runs

---

pkg/proc/bininfo.go

pkg/proc: fix nil pointer dereference when calling extra on a nil func

---

pkg/proc/bininfo.go
pkg/proc/target_exec.go
pkg/proc/types.go
pkg/proc/variables.go

The rangeParent calculation was changed 0b74953f0 to address slowness
(due to repeated calculations) when calling PackageVariables. That
changed caused to program to use a lot of memory due to having to
calculate the range bodies of every function. This change reverts
0b74953f0 and splits off rangeBodies calculation from the extras method
of Function, so that it isn't called from PackageVariables.
Fixes #4146

pkg/proc: split off rangeParent from function extras

---

service/debugger/debugger.go

We've always said that predefined breakpoints (like the
unrecovered-panic breakpoint) are just like any other breakpoint and
clients can remove them by using the ClearBreakpoint API.
However commit 78471b3a in 2022 made this not true by treating negative
IDs (which is what we assign to predefined breakpoints) specially.
That change was made as part of a series of changes to support
debugging child processes: prior to that change breakpoints were
cleared by address only (which worked fine for predefined breakpoints)
but this was not tenable for multiprocess debugging.
So ClearBreakpoint was changed to clear breakpoints by breakpoint ID
and only use address in a backward compatibility mode when no ID was
specified.
The current implementation of ClearBreakpoint works fine for user …

service/debugger: use address in ClearBreakpoint only when ID is 0
