- command/command.go
- proctl/proctl.go
- proctl/proctl_test.go
- proctl/threads.go
- proctl/variables_test.go
- Gave breakpoints a monotonically increasing id (similar to gdb) for easier manipulation. 
- Centralized looking up address by location (file+line, function) to DebuggedProcess.FindLocation
- FindLocation supports arbitrary addresses and breakpoint ids
- Added BreakByLocation and ClearByLocation to DebuggedProcess and changed the commands to call them instead.
- BreakByLocation can now also use an address `b 0x400d60` will work
- ClearByLocation can take a breakpoint id or address (as well as the existing file + line and function)
> Breakpoints now have ids. Consolidated location lookup logic

- _fixtures/testvariables.go
- proctl/variables.go
- proctl/variables_test.go
Built on #45 
- Generalized arrays and slices, print/eval supports arrays and slices of all types.
> Better handling of arrays and slices

- proctl/breakpoints_linux_amd64.go
Improves error message on systems that delve is failing on.
> proctl: propagate underlying error for failing hardware breakpoint.

- proctl/breakpoints_linux_amd64.go
Enable usage of dr1-dr3.  Clear control bits when a breakpoint
is disabled. Use DR_LEN_1 instead of DR_LEN_8 so breakpoint work on
unaligned adresses.
Fixes #51.
> Some hw breakpoint fixes

- command/command.go
the message from "help" command for "info" is different from the one with "info" when the "type" doesn't match
> be consistent with messages for "info" command

- proctl/proctl_test.go
Eliminate a race condition in TestHalt where the RequestManualStop
call can precede the Continue call, causing the test to sporadically
fail.
> Make TestHalt deterministic

- CONTRIBUTING.md
CONTRIBUTING.md says to get the delve version with `dlv -v`. This fails:
```
$ dlv -v
flag provided but not defined: -v
Delve version 0.5.0.beta
flags:
-addr=localhost:0: Debugging server listen address.
-headless=false: Run in headless mode.
-log=false: Enable debugging server logging.
-version=false: Print version number and exit.
Invoke with the path to a binary:
dlv ./path/to/prog
or use the following commands:
run - Build, run, and attach to program
test - Build test binary, run and attach to it
attach - Attach to running process
```
The flag cannot be abbreviated. This works:
```
$ dlv -version
Delve version: 0.5.0.beta
```
> Update CONTRIBUTING.md to not abbreviate dlv -version

- proc/threads.go
$ ./dlv run
Type 'help' for list of commands.
(dlv) break main
Breakpoint 1 set at 0x45fa20 for main .../src/go/src/runtime/rt0_linux_amd64.s:63
(dlv) continue
current loc: main .../src/go/src/runtime/rt0_linux_amd64.s:63
58: GLOBL _rt0_amd64_linux_lib_argc<>(SB),NOPTR, $8
59: DATA _rt0_amd64_linux_lib_argv<>(SB)/8, $0
60: GLOBL _rt0_amd64_linux_lib_argv<>(SB),NOPTR, $8
61: 
62: TEXT main(SB),NOSPLIT,$-8
=> 63:  MOVQ    $runtime·rt0_go(SB), AX
64:  JMP     AX
(dlv) stack
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x61a52c]
goroutine 13 [running]:
github.com/derekparker/delve/proc.(*Thread).getG(0xc8207fb4d0, 0x0, 0x7fc168636000, 0xc820d484c0)
.../go/src/github.com/derekparker/delve/proc/threads.go:311 +0x4dc …
> proc: don't deref nil pointer if getG fails

- proc/breakpoints.go
- proc/proc.go
additionally fixes a bug when Detach is called on an exiting/exited thread: dbp.CurrentThread could point to a thread that has already been removed from dbp.Threads by trapWait which will lead to a nil pointer dereference caused proc.Process.clearBreakpoint getting nil from dbp.Threads[tid]
> ClearBreakpoint should clear a hardware breakpoint from all threads

- proc/registers_darwin_amd64.go
- proc/registers_linux_amd64.go
This change right-aligns the register names in the output of the "regs" command, and pads out the display of the hex value of each register to 16 bytes. This makes scanning registers for set values a bit easier.
For example, the current output for regs looks like:
```
(dlv) regs
Rip = 0x135830
Rsp = 0xc20809c838
Rax = 0xc20801eb00
Rbx = 0x135830
Rcx = 0x65646f6370697a3a
Rdx = 0x10127b8
Rdi = 0x41e710
Rsi = 0xc20806ea4b
Rbp = 0x5
R8 = 0x0
R9 = 0xc2080d6580
R10 = 0x3576a0
R11 = 0xc208092090
R12 = 0xc20800bb38
R13 = 0xa3b208270c78
R14 = 0x140005dd94bec400
R15 = 0xc20800aef0
Rflags = 0x202
Cs = 0x2b
Fs = 0x0
Gs = 0x0
Gs_base = 0x7fff7b0823f0
```
With the change:
```
(dlv) regs
Rip = 0x000000000000002000
Rsp = 0x0000000002081bbf90
Rax = 0x000000000208180120
Rbx = 0x0000000002081c8090
Rcx = …
```
> Visually align registers & show 16 bytes for each

- proc/variables.go
I noticed `next` was giving me an 'input/output error' on a specific point on one of my programs, it turns out it was because `chanRecvReturnAddress` was using `g.SP` instead of the `SP` register from the thread.
> proc/variables: chanRecvReturnAddress uses outdated frame info

- terminal/command.go
Fixes #257 
Sometimes the thread randomly selected by a ^C or when attaching to a process is not running any goroutine.
> terminal/command: check for SelectedGoroutine == nil in goroutines

- terminal/terminal.go
`<esc>[0m` (reset) should be used instead of `<esc>[37m` (set foreground
color to white)
Before:
After:
> terminal: correct CSI sequence in (*Term).Println

- cmd/dlv/main.go
```
/Users/quentinperez/go/src/github.com/derekparker/delve/proc/proc_darwin.go:39 +0x8ad
/Users/quentinperez/go/src/github.com/derekparker/delve/service/debugger/debugger.go:57 +0x37d
```
```
/Users/quentinperez/go/src/github.com/derekparker/delve/cmd/dlv/main.go:243 +0x264
```
> Fix 2 x panic: runtime error: index out of range

- proc/doc.go
- terminal/command.go
Noticed on godoc.org that these weren't quite right.
> proc, terminal: fix package docstrings

- proc/proc.go
Use runtime.allgs instead of runtime.allg that has been removed in
https://github.com/golang/go/commit/5a68eb9f25a2a6290800278df972e04a4085cee3.
Fixed #282
> proc: handle rename of runtime.allg to runtime.allgs

- _fixtures/testvariables3.go
- _fixtures/testvariables4.go
- dwarf/reader/reader.go
- proc/eval.go
- proc/proc_test.go
- proc/variables.go
- service/api/conversions.go
- service/api/prettyprint.go
- service/api/types.go
- service/test/variables_test.go
- terminal/command.go
- terminal/command_test.go
- terminal/terminal.go
Supported operators:
- All (binary and unary) operators between basic types except <-, ++ and -- (includes & to take the address of an expression)
- Comparison operators between supported compound types
- Typecast of integer constants into pointer types
- struct members
- indexing of arrays, slices and strings
- slicing of arrays, slices and strings
- pointer dereferencing
- true, false and nil constants
Implements #116, #117 and #251 
The big missing things are:
- function calls
- support for some kinds (maps, interfaces, chans)
- support for some builtins that do not require function calls (like `len` for example)
- support for type casts between simple types
The weirdest thing here is that constants in go are untyped so evaluating a constant results in a variable with `Type == ""`. …
> proc: Implements expression interpreter

- proc/eval.go
- proc/variables.go
- service/test/variables_test.go
> proc/eval: Return an error when slicing a map over its length

- service/debugger/locations.go
- service/test/integration_test.go
`packagename.SomeFunction` should match `github.com/someuser/packagename.SomeFunction` since the former is the familiar syntax.
To disambiguate between `io.SomeFunction` and `github.com/someuser/somepackage/io.SomeFunction` specify one extra slash at the start of the location specifier: `/io.SomeFunction`.
Fixes Issue #296
> service/debugger: support function spec. with partial package paths

- Makefile
- scripts/testsign
Fixes up certain Makefile targets and the testsign script.
Makefile: Properly pass 'test.run' flag
testsign: Run will all args instead of first
> dev: Fixup Makefile and testsign script

- .travis.yml
Make Go tip an "allowed failure" in travis.
@aarzilli there is a failing test on master that only fails on tip: `TestEvalExpression`. I think in general however, we should stay on top of changes to `tip` of Go, but let's not mark a build as failed if it doesn't pass against tip.
> travis: allow failures on tip

- _fixtures/testvariables3.go
- proc/proc_test.go
- proc/variables.go
`recurseLevel` value should not be reset when evaluating the contents
of an interface variable
Fixes #316
> proc/variables: bugfix: hang on ptr loop including interfaces

- proc/proc.go
- service/test/variables_test.go
- Updated TestEvalExpression to work with the new behaviour of `go/constant` in go1.6beta1
- Reverted `runtime.buildVersion` change :(
> Go 1.6beta1 compatibility

- proc/eval.go
- service/test/variables_test.go
For example: in testvariables3.go the `main` function instead of having an entry for `i1` has an entry for `&i1`. I guess this could be considered a go bug and I think at some point fixing it was discussed in the issue tracker, however it doesn't seem like it's getting fixed in 1.6 and it happens frequently in ordinary code.
> workaround: proc/eval: go sometimes inserts &v instead of v

- _fixtures/bpcountstest.go
- _fixtures/issue262.go
- cmd/dlv/main.go
- proc/breakpoints.go
- proc/exec_darwin.c
- proc/proc.go
- proc/proc_darwin.c
- proc/proc_darwin.go
- proc/proc_darwin.h
- proc/proc_linux.go
- proc/proc_test.go
- proc/threads.go
- proc/threads_darwin.c
- proc/threads_darwin.go
- proc/threads_darwin.h
- proc/threads_linux.go
- service/api/conversions.go
- service/api/types.go
- service/debugger/debugger.go
- service/rpc/client.go
- service/test/integration_test.go
- terminal/command.go
This is a fix for the problem unearthed by PR #255, it is submitted for discussion, not definitive.
There are two problems with `(*Process).Continue`
1. The first is that between the time one breakpoint is triggered and the point where we loop over all threads and `Halt` eacho one the second goroutine may hit the breakpoint too, this second hit gets lost
2. The second problem is that the way `Continue` resumes the process has a race condition with the tracee
Let's that thread A hit the breakpoint and thread B was sleeping when `Continue` called `Halt` on it. After we finish processing the breakpoint on A we call `Continue` again, `Continue` then loops through all threads, it calls `resume` on B, then moves onto thread A, sees that it's on a breakpoint so it calls `(*Thread).Step()`.
If …
> proc.(*Process).Continue skips breakpoints [WIP]

- _fixtures/testvariables3.go
- proc/eval.go
- proc/mem.go
- proc/proc_test.go
- proc/variables.go
Prefetch the entire memory of structs and arrays and cache it instead
of issuing readMemory calls only when we get down to primitive types.
This reduces the number of system calls to ptrace that variables makes.
Improves performance in general, greatly improving it in some
particular cases (involving large structs).
```
Benchmarks without prefetching:
BenchmarkArray-4         	      10	 132189944 ns/op	   0.06 MB/s
BenchmarkArrayPointer-4  	       5	 202538503 ns/op	   0.04 MB/s
BenchmarkMap-4           	     500	   3804336 ns/op	   0.27 MB/s
BenchmarkGoroutinesInfo-4	      10	 126397104 ns/op
BenchmarkLocalVariables-4	     500	   2494846 ns/op
Benchmarks with prefetching:
BenchmarkArray-4         	     200	  10719087 ns/op	   0.76 MB/s
BenchmarkArrayPointer-4  	     100	  11931326 ns/op …
```
>  proc/variables: prefetch of target process memory 

- _fixtures/issue305.go
- proc/proc.go
- proc/proc_test.go
- proc/threads.go
- proc/variables.go
Temp breakpoints should be cleared even if a non-temp breakpoint is
triggered on the same goroutine that the temp breakpoints are set on.
> proc: bugfix: clearing temp breakpoints

- terminal/command.go
Splitting an empty string results in a one element array with a
single empty string element.
See: http://play.golang.org/p/EzVX64Q82A
> terminal/command: bugfix: goroutines doesn't work without arguments

- proc/proc.go
Instead of the `step` command single stepping every thread, instead only
step the "current" thread. This fixes a few issues surrounding single
stepping, and simplifies the logic. The original concerns around only
stepping a single thread (with regard to coordination) are invalid and
generally non-issues.
> proc: Single step only "current" thread

- appveyor.yml
- cmd/dlv/main.go
- dwarf/line/line_parser_test.go
- proc/arch.go
- proc/proc.go
- proc/proc_darwin.go
- proc/proc_linux.go
- proc/proc_test.go
- proc/proc_windows.go
- proc/ptrace_darwin.go
- proc/ptrace_linux.go
- proc/ptrace_windows.go
- proc/registers_windows_amd64.go
- proc/test/support.go
- proc/threads.go
- proc/threads_darwin.go
- proc/threads_linux.go
- proc/threads_windows.c
- proc/threads_windows.go
- proc/threads_windows.h
- service/debugger/debugger.go
- service/debugger/debugger_linux.go
- service/debugger/debugger_windows.go
- service/debugger/locations.go
- terminal/terminal.go
Initial work on porting Delve to support Windows.  
There's a lot more to do before this is ready to be merged, but most of the core infrastructure for Windows support is in place, and some basic Delve scenarios are working in simple scenarios (launching, setting breakpoints, continuing, breaking on breakpoints, inspecting registers, seeing sources, inspecting locals, exiting, etc.).
Fixes #198.
> [WIP] Windows support

- proc/breakpoints.go
- proc/eval.go
- proc/proc.go
- proc/proc_test.go
- proc/threads.go
- proc/variables.go
- service/debugger/debugger.go
Changed `Breakpoint.Cond` to accept any expression that can be evaluated instead of just an integer.
Added fake variable `runtime.curg` to `eval.go` so that temp breakpoints used by `Next` can be expressed as a comparision on `runtime.curg.goid`.
> Conditional Breakpoints (backend)

- _fixtures/teststep.go
- proc/proc.go
- proc/proc_darwin.go
- proc/proc_linux.go
- proc/proc_test.go
- proc/proc_windows.go
- proc/threads.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc/client.go
- terminal/command.go
This patch modifies the `step` command to step to the next source line,
stepping into any function encountered along the way.
Fixes #360
> proc: step now goes to next line, including funcs

- proc/mem.go
- terminal/command.go
- terminal/command_test.go
This pull request attempts to address the two bugs reported in Issue #354.
@antonikonovalov's bug is probably connected to reading uninitializer memory, I can't be sure because there aren't any exect instructions to reproduce it, but it seems pretty likely.
@OneOfOne's bug happens when the stack contains one frame or less.
> Two bugs reported in issue #354

- cmd/dlv/main.go
The tracepoint should be set on the function's first line, not the
function's entry point to avoid function prologue weirdness.
Fixes #389
> cmd/dlv/main: trace subcommand shows duplicate entries

- _fixtures/issue332.go
- proc/proc_test.go
- proc/threads.go
- proc/variables.go
- terminal/command.go
These bugs were found while investigating Issue #332:
1. A running goroutine is by definition not parked waiting for a
chan recv
2. The FDE end address is intended to be exclusive, the code
interpreted as inclusive and sometimes ended up setting a breakpoint
on a function other than the current one.
This however does not fix Issue #332 itself. The problem there is that the FDE information is wrong inside some parts of the prologue for some functions (not all functions and not all parts of the prologue). I have added a test (disabled) for this problem.
The fix for issue #332 is to check if the current instruction is a `CALL` and if it is set a temp breakpoint after the function's prologue and call `proc.(*Process).Continue`.
We would need to implement Issue #368 to do this.
In addition I …
> proc: bugs setting next breakpoints

- proc/proc_windows.go
- proc/registers_windows_amd64.go
- proc/syscall_windows.go
- proc/syscall_windows_amd64.go
- proc/threads_windows.go
- proc/zsyscall_windows.go
Unrelated to conversion, I have also changed (*Thread).readMemory
to return only first count bytes of memory just as advised
by ReadProcessMemory.
Fixes #409
@lukehoban for your review. Thank you.
Sorry about the size of this change. I tried to make it as small as possible.
> proc: replace cgo with syscalls on windows

- _fixtures/math.go
- terminal/command.go
- terminal/command_test.go
Fixes #411
I've added a bit of test tooling in command_test.go. I tried using gexpect but it doesn't agree with peterh/liner. One issue was that gexpect doesn't intercept SIGWINCH which means peterh/liner will think the pty is not a terminal and quit immediately, but even after changing that (in peterh/liner) it still wouldn't work.
> terminal: Next does not fill BreakpointInfo

- cmd/dlv/cmds/commands.go
- service/debugger/debugger.go
- terminal/command.go
- terminal/command_test.go
- terminal/terminal.go
Implements extensible mechanism to specify which commands accept
prefixes (goroutine, frame, on) instead of hardcoding them in
a switch.
Implements #240 
In the process of testing this I also found and fixed a bug in `Debugger`.
> terminal: Mechanism to handle command prefixes

- proc/proc.go
- proc/proc_test.go
- proc/types.go
Caches the mapping of type names to offset in `debug_info` to speed up
variable evaluation.
```
BEFORE:
BenchmarkArray-4         	     100	  13'238'441 ns/op	   0.62 MB/s
BenchmarkArrayPointer-4  	     200	  10'044'093 ns/op	   0.87 MB/s
BenchmarkMap-4           	    1000	   1'332'530 ns/op	   0.77 MB/s
BenchmarkGoroutinesInfo-4	      10	 114'677'462 ns/op
BenchmarkLocalVariables-4	    2000	   1'223'975 ns/op
AFTER:
BenchmarkArray-4         	     200	   9'925'686 ns/op	   0.83 MB/s
BenchmarkArrayPointer-4  	     100	  11'143'930 ns/op	   0.78 MB/s
BenchmarkMap-4           	    2000	   1'302'520 ns/op	   0.79 MB/s
BenchmarkGoroutinesInfo-4	      30	  35'079'549 ns/op
BenchmarkLocalVariables-4	    1000	   1'137'299 ns/op
```
Note in particular the speedup of `BenchmarkGoroutinesInfo`, since …
> proc: Caching type offsets

- _fixtures/panic.go
- proc/proc.go
- proc/proc_test.go
- service/debugger/debugger.go
- service/test/integration_test.go
- terminal/command.go
Automatically sets a breakpoint on runtime.startpanic, the function
that gets called by runtime.dopanic when a panic is not recovered.
Implements #317
> proc: Breakpoint to catch unrecovered panics

- Documentation/installation/osx/install.md
I ran through these instructions and didn't notice that the
certificate I'd created appeared three times in the list I
was looking at.  Emphasize where the trust setting is
enabled.
> Instruct OSX users to trust certificate, not key

- terminal/command.go
- terminal/command_test.go
When I started using delve, and I ran commands to look at variables, I became uneasy when there were no variables at that breakpoint:
```
(dlv) locals
(dlv)
```
```
(dlv) args
(dlv)
```
I couldn't tell if something went wrong or there were actually no locals or args at that point. This pull request makes the `vars`, `locals`, and `args` commands print messages when there is nothing to show:
```
(dlv) locals
(no locals)
(dlv)
```
```
(dlv) args
(no args)
(dlv)
```
This is completely about user experience and doesn't add any real functionality. I didn't add tests for `args` and `vars`, because I would like to get feedback on whether or not this seems like a good idea before investing the time to do so.
> terminal: show message if there are no vars/locals/args

- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_test.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- cmd/dlv/cmds/commands.go
This is a very minor correction, but seems the same mistake just happened to propagate, thanks likely to Copy&Paste.
> Changed word from singular to plural form to better fit context.

- proc/exec_darwin.c
- proc/exec_darwin.h
- proc/proc_darwin.c
- proc/proc_darwin.go
- proc/proc_darwin.h
- proc/threads_darwin.c
- proc/threads_darwin.h
This set of patches sets the close-on-exec flag on the pipes used for parent/child coordination. Also includes a small refactor to avoid type coercion for C types.
I should have another PR up soon to clean up a few other issues on OSX.
> Misc osx refactors

- _fixtures/testargs.go
- proc/proc_test.go
- proc/proc_windows.go
This is a better-formatted PR replacing #479 and fixing the issue of command-line arguments not getting passed to the binary on Windows, including tests.
The nit has been fixed and commits are formatted better. Sorry for not reading the documentation on contributing!
> Fix command-line arguments on Windows

- _fixtures/testvariables2.go
- cmd/dlv/cmds/commands.go
- proc/breakpoints.go
- proc/eval.go
- proc/proc.go
- proc/proc_test.go
- proc/variables.go
- service/api/conversions.go
- service/api/prettyprint.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/debugger/locations.go
- service/rpc1/client.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/common_test.go
- service/test/integration1_test.go
- service/test/integration2_test.go
- service/test/variables_test.go
- terminal/command.go
- terminal/command_test.go
Most of these changes were proposed on the mailing list.
[dlv output before the changes](https://gist.githubusercontent.com/aarzilli/8a78798bb359d2aa5c08/raw/b88f679252b91437615526bd6d50f832c35fbe92/before)
[dlv output after the changes](https://gist.githubusercontent.com/aarzilli/3503eff5b25952befff9/raw/5c5296c0a02263f8973d20b5da1447bcaf100b57/after)
Commit messages for the changeset:
service/api: Removed unused fields of service/api.Function
proc/eval: Set return variable name to input expression
all: fine-grained control of loadValue for better variable printing
Makes proc.(*Variable).loadValue loading parameters configurable
through one extra argument of type LoadConfig.
This interface is also exposed through the API so clients can control
how much of a variable delve should read. …
> Improvements to Variable printing

- Documentation/api/README.md
- Documentation/api/json-rpc/README.md
- service/rpc2/server.go
I've adapted the documentation we had in `service/client.go` for `service/rpc2/server.go` so that godoc generates the API documentation for us. I've also added to `Documentation/api/json-rpc/README.md` a brief explanation of how to use the documentation on godoc.org for our json-rpc service.
> API documentation improvements

- Makefile
For codesign part in Makefile, we should check if $GOBIN is set instant using $GOPATH/bin.
For all homebrew user the $GOBIN will always set on /usr/local/Cellar/go/VERSION/libexec/bin
Fixs #502
> area/makefile: Check $GOBIN before codesign, if not exist using $GOPATH/bin

- terminal/terminal.go
Our handling of SIGINT is confusing to people that expect SIGINT to be
delivered to inferior when they press ^C (see #483 for example).
Let's make an effort to point out what's happening and how one can send
SIGINT to inferior.
> terminal: helpful message in SIGINT handler

- service/rpc1/client.go
- terminal/command.go
While tracing delve may spend most of its time outside of
proc.(*Process).Continue, which renders
service/rpc/client.(*Client).Halt ineffective.
This commit changes the implementation of
service/rpc/client.(*Client).Halt to make it capable of stopping traces.
> service: Make Halt work during tracing

- _fixtures/testvariables2.go
- dwarf/reader/reader.go
- proc/eval.go
- proc/types.go
- service/test/variables_test.go
This set of commits was prompted by Issue #426. Obviously we can't print the contents of an unsafe.Pointer (because we don't know what it contains), however one should be able to cast it to some other type and read it that way, in that case: `(*map[string]interface{})(0x...)`.
However that doesn't work because of the way `go/printer` formats the expression `map[string]interface{}`: `go/printer` doesn't put a space between `interface` and `{}`, but in debug_info the type appears as `map[string]interface {}`.
I took a look at other anonymous types and found other discrepancies. The first commit attempts to fix these discrepancies in the most common circumstances. It's not a perfect solution, it would probably be better to abandon `go/printer` and just write a serialization that matches the …
> Better support for type casts to anonymous types

- _fixtures/issue387.go
- proc/proc.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc1/client.go
- service/rpc2/client.go
- service/rpc2/server.go
- terminal/command.go
- terminal/command_test.go
Make dlv call continue automatically when a breakpoint is hit on a
different goroutine during a next or step operation.
Added API hooks to implement the other solution to this problem (cancel
the next/step operation if a different breakpoint is hit).
Fixes #387
> terminal,service: auto-continue during next and step

- Documentation/README.md
- Documentation/cli/README.md
- Documentation/cli/expr.md
- Documentation/cli/locspec.md
- Makefile
- scripts/gen-cli-docs.go
- terminal/command.go
- terminal/command_test.go
- terminal/docgen.go
Copied old wiki documentation in `Documentation/cli/`, changed `help` command so it prints only a summary of each command and more detailed documentation when followed by the name of a command, added a script to automatically generate `Documentation/cli/README.md`.
> Documentation for command line frontend

- Documentation/installation/windows/install.md
We don't need MinGW to build delve on Windows. Lets change installation instructions to reflect that.
Alex
> docs: Do not mention MinGW during Windows installation

- dwarf/util/util.go
> Fix typo in dwarf/util/util.go

- cmd/dlv/cmds/commands.go
For better user experience, display subcommands in alphaetic order.
> dlv: Display subcommads in alphabetic order.

- proc/mem.go
- proc/proc_test.go
> proc: bugfix: unsigned integer overflow in proc.(*memCache).contains

- proc/go_version.go
- proc/proc_test.go
Appengine run its own version of Go.
The version returned is "go1.6.1 (appengine-1.9.37)".
The function ParseVersionString does not support that customization of the version.
This PR provides a simple patch that uses only the first part of the string (before space) to parse the version.
> Add support for Appengine; parsing Appengine Go custom version

- cmd/dlv/cmds/commands.go
- service/api/types.go
- service/config.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/rpccallback.go
- service/rpccommon/server.go
- service/test/cmd/typecheckrpc.go
- service/test/integration1_test.go
- service/test/integration2_test.go
- terminal/command_test.go
This version preserves the order of requests, allows the
client to switch between API versions and introduces a
way to send notifications to the client (see TODO item at:
proc/proc_linux.go:325).
Fixes #523, #571
> Replaced net/rpc with custom version

- service/debugger/locations.go
- service/debugger/locations_test.go
`parseFuncLocationSpec` did not parse function locations with a full package path correctly, just like go's `debug/gosym` didn't before go1.7. My fault :(
> debugger/locations: Fixed bug parsing remote package paths

- proc/proc_linux.go
- proc/proc_test.go
- proc/registers.go
Fixes flakiness of TestCmdLineArgs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/599)
> proc: bugfix: cleaning up spurious process exited errors

- _fixtures/issue573.go
- proc/proc.go
- proc/proc_test.go
Detect calls that do not target a function's entrypoint
(i.e, calls to runtime.duffzero and runtime.duffcopy) and
instead step into them directly.  StepInto sets a breakpoint
past the called function's prologue and expects that continue
will hit that breakpoint, but because the call is into the
interior of the function (well past the prologue) this fails.
Fixes #573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/575)
> proc: Fix stepping into runtime.duff*

- service/test/variables_test.go
go1.8 changed the way anonymous struct names are generated for DWARF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/627)
> Changed TestIssue426 to work with go 1.8

- cmd/dlv/cmds/commands.go
Currently, `dlv` not support multiple build flags such as `-v -x`.
If set `--build-flags='-v -x'`, will occur `flag provided but not defined: -v -x` error from go compiler because append the `-v` and `-x` does not separate by space.
Also, `--build-flags=-v --build-flags=-x` is recognizes `-x` only.
This pull request will split `BuildFlags` variable to `[]string` slice uses `string.Fields`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/619)
> cmd: Support space separate flags for build-flags

- _fixtures/buildtest/main.go
- cmd/dlv/cmds/commands.go
- cmd/dlv/cmds/commands_test.go
- cmd/dlv/dlv_test.go
- terminal/command_test.go
Allows quoted substrings in build-flags flag. This fixes a build
problem on windows where the default build flags must contain a space.
Fixes #634 and #638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/639)
> dlv: bugfix: Allow quoting in build flags argument

- _fixtures/defercall.go
- _fixtures/issue561.go
- _fixtures/issue573.go
- _fixtures/teststepconcurrent.go
- _fixtures/teststepprog.go
- proc/breakpoints.go
- proc/proc.go
- proc/proc_test.go
- proc/threads.go
- service/debugger/debugger.go
Instead of repeatedly calling StepInstruction set breakpoints to the
destination of CALL instructions (or on the CALL instructions
themselves for indirect CALLs), then call Continue.
Calls to unexported runtime functions are skipped.
Reduces the number of code paths managing inferior state from 3 to 2
(StepInstruction, Continue).
Fixes #561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/603)
> proc: Implement Step using Continue 

- _fixtures/issue594.go
- proc/disasm_amd64.go
- proc/proc_test.go
- proc/proc_windows.go
- proc/syscall_windows.go
- proc/threads_windows.go
This solves most of the test flakiness that the windows back end has on multi core. 
Before this patch when multiple breakpoints were hit simultaneously only one was reported, the other one was processed by (*Thread).singleStep while stepping over the breakpoint which caused the second breakpoint to be missed and the first breakpoint to be processed twice, because (*Thread).singleStep was unable to complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/598)
> proc: changed windows backend to deal with simultaneous breakpoints

- _fixtures/locationsprog3.go
- service/debugger/locations.go
- service/test/integration2_test.go
If the location specification matches the name of a function exactly
return that function as a match event if the expression matches other
functions as well.
Without this some functions, like math/rand.Intn are unmatchable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/651)
> debugger/locations: prioritize exact matches of function names

- _fixtures/testvariables2.go
- service/api/prettyprint.go
- service/test/variables_test.go
It's often useful to see the concrete type of the individual elements that comprise an array of interface type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/591)
> prettyprint: Print type of the elements of arrays of interface type

- config/config.go
- terminal/command.go
- terminal/terminal.go
- terminal/terminal_test.go
Allows to rewrite a source path stored in program's debug information, if the sources were moved to a different place between compilation and debugging.
Implements similar logic as `substitute-path` [in gdb](https://sourceware.org/gdb/onlinedocs/gdb/Source-Path.html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/640)
> Add substitute-path parameter to configuration file.

- _fixtures/pkgrenames.go
- _fixtures/vendor/dir0/pkg/main.go
- _fixtures/vendor/dir0/renamedpackage/main.go
- _fixtures/vendor/dir1/pkg/main.go
- proc/eval.go
- proc/moduledata.go
- proc/proc.go
- proc/types.go
- proc/variables.go
- service/test/variables_test.go
Generate names of the concrete types stored inside interface variables
by fully parsing their runtime._type instead of simply using the str
field.
This allows delve to read the contents of an interface variable when
the program imports multiple packages that have the same name. It also
allows delve to correctly interpret some complex anonymous types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/632)
> proc: Names of concrete types of interfaces parsing their runtime._type

- _fixtures/testvariables2.go
- proc/proc_test.go
- proc/variables.go
Since we store all signed integers as int64 the sign bit should be
extended, otherwise we read negative integers as their 2-complement
value.
> proc/variables: extend sign of read negative integers.

- Makefile
- proc/exec_darwin.c
- proc/proc_darwin.c
- proc/proc_darwin.go
- proc/proc_darwin.h
- proc/proc_windows.go
- proc/test/support.go
- proc/threads_darwin.go
- proc/variables.go
Fixes #645
Works on minimal example, makes delve slower, not tested on versions of OS X before 10.12.1, not tested on 10.12.2, needs printf cleanup, needs gofmt.
If someone wants to finish this instead of me I want nothing more than wash my hands of the undocumented mess that is Mac OS X, OS X or macOS is.
> proc: support for ver. 10.12.1 the OS formerly known as Mac OS X

- Documentation/cli/README.md
- _fixtures/fputest/fputest.go
- _fixtures/fputest/fputest_amd64.s
- proc/disasm.go
- proc/disasm_amd64.go
- proc/proc.go
- proc/proc_test.go
- proc/ptrace_linux.go
- proc/registers.go
- proc/registers_darwin_amd64.go
- proc/registers_linux_amd64.go
- proc/registers_windows_amd64.go
- proc/stack.go
- proc/syscall_windows_amd64.go
- proc/test/support.go
- proc/threads.go
- proc/threads_darwin.c
- proc/threads_darwin.h
- proc/threads_linux.go
- service/api/conversions.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/integration2_test.go
- terminal/command.go
- terminal/terminal_test.go
Adds ability to load x87, SSE and AVX registers.
Fixes #666 
@derekparker: this does not compile on 1.5.x because I'm using bytes.Buffer.Reset, should I make it compile with 1.5?
@dgryski: congratulations on getting issue 666, is this formatting acceptable:
```
(dlv) regs -a
Rip = 0x00000000004010fa
Rsp = 0x000000c420041ed8
Rax = 0x3fcccccd3fc00000
Rbx = 0x000000c42001c0b8
Rcx = 0x000000c4200001a0
Rdx = 0x0000000000000000
Rdi = 0x0000000000000000
Rsi = 0x000000c42001c080
Rbp = 0x000000c420041f38
R8 = 0x000000c41ffff1fc
R9 = 0x0000000000000011
R10 = 0x00000000ffffffee
R11 = 0x0000000000000000
R12 = 0x0000000000000060
R13 = 0x0000000000000060
R14 = 0x0000000000000002
R15 = 0x0000000000000000
Orig_rax = 0xffffffffffffffff
Cs = 0x0000000000000033
Eflags = 0000000000000206	[PF IF IOPL=0]
Ss = …
```
> proc: load more registers

- proc/proc.go
- proc/proc_darwin.go
- proc/proc_linux.go
- proc/proc_windows.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/integration2_test.go
- terminal/command.go
service/debugger: Restore breakpoints using file:line on restart
Restoring by address can cause the breakpoint to be inserted in the
middle of an instruction if the executable file has changed.
terminal: Warn of stale executable when printing source
> Two bugfixes regarding stale executable files, and executables changing between restarts

- service/api/types.go
- service/debugger/debugger.go
```
service/debugger: bugfix: error values can not be marshalled
```
> service/debugger: bugfix: error values can not be marshalled

- _fixtures/issue683.go
- dwarf/line/state_machine.go
- proc/proc_test.go
- proc/threads.go
- service/rpccommon/server.go
service: Prevent panics from crashing delve and killing the target
Catch all unrecovered proc and debugger panics in the service layer and
report them as errors, allow users to cleanly detach from the target
and quit.
Fixes #614
proc: Next/Step should not panic if line info can not be found.
Fixes #683
> Fix for #614 and #683

- _fixtures/testvariables2.go
- proc/eval.go
- proc/variables.go
- service/api/conversions.go
- service/test/variables_test.go
```
proc/variables: support NaN/Inf float values
Unfortunately go/constant does not support NaN and Inf float values so
we need to store this information alongside.
Fixes #705
```
> proc/variables: support NaN/Inf float values

- _fixtures/traceperf.go
- dwarf/reader/reader.go
- proc/proc.go
- proc/proc_linux.go
- proc/proc_test.go
- proc/threads.go
- proc/threads_linux.go
- proc/types.go
- proc/variables.go
Following up from a mailing list discussion I took some measurements on where the time is spent on a simple Continue()+FunctionArguments() loop and made some optimizations taking the time spent on a single loop iteration from ~40ms to under 1ms.
The bulk of the improvement comes from skipping a time.Sleep in the linux implementation of singleStep, this sleep is needed to work around a quirk of the linux kernel but that particular quirk can not happen when we are stepping over a breakpoint, so it's unnecessary in that case.
The rest of the optimizations have a much smaller impact but cumulate to ~50% of the remaining time.
```
* proc: Added trace benchmark
Results:
BenchmarkTrace-4   	    5000	  36195899 ns/op
* proc/linux: faster single step implementation.
BenchmarkTrace-4   	    5000 …
```
> Trace optimizations

- proc/threads.go
- service/test/integration2_test.go
```
proc: Make sure CurrentLoc of G returned by GetG is up to date
We are already doing this in GoroutinesInfo we should be doing it for
GetG. The main consequence of not doing this is that the CurrentLoc of
DebuggerState.SelectedGoroutine is out of date compared to the location
of the thread running it.
```
> proc: Make sure CurrentLoc of G returned by GetG is up to date

- _fixtures/binarytrees.go
- proc/proc_test.go
- proc/stack.go
- proc/variables.go
- service/rpccommon/server.go
```
* proc/stack: handle stack barriers correctly
Correctly handle stack barriers insterted during garbage collection.
* proc: bugfix: crash of parseG when target is in runtime.deferreturn
runtime.deferreturn will change the value of curg._defer.fn in such a
way that if the target is stopped at just the right instruction will
crash parseG.
* service/rpccommon: fixed typo
```
> Improve stacktraces

- pkg/proc/proc_darwin.go
- pkg/proc/threads_darwin.go
Currently, can't compile on darwin.
Fixed some variable to unexported name.
> pkg/proc: fix struct methods to unexported name & format by goimports

- _fixtures/testvariables2.go
- pkg/proc/proc_test.go
- pkg/proc/variables.go
- service/api/prettyprint.go
```
proc/variables: fix infinite recursion with pointer loop
loadValue didn't react correctly to pointer loops going through
slice -> interface{} -> slice or pointer -> interface{} -> pointer.
```
> proc/variables: fix infinite recursion with pointer loop

- pkg/proc/stack.go
```
proc: use original PC for Call position
The PC we have is relative to the first instruction after the CALL
instruction currently being executed.
Anyone watching a disassembly will understand what's happening if we
report the return PC, but reporting the first PC of the current line is
useless and confusing.
```
> proc: use original PC for Call position

- cmd/dlv/dlv_test.go
- pkg/proc/proc_test.go
- pkg/proc/proc_windows.go
- pkg/proc/registers.go
- pkg/proc/registers_darwin_amd64.go
- pkg/proc/registers_linux_amd64.go
- pkg/proc/registers_windows_amd64.go
- pkg/proc/stack.go
- pkg/terminal/command_test.go
- service/debugger/debugger.go
- service/test/integration2_test.go
Sometimes windows will send us events about breakpoints we have
already removed from the code despite the fact that we go to great
lengths to avoid this already.
Change waitForDebugEvent to check that when we receive a breakpoint
event the corresponding memory actually contains an INT 3
instruction, if it doesn't ignore the event and restart the thread.
On Windows we can sometimes encounter threads stopped in locations for
which we do not have entries in debug_frame.
These cases seem to be due to calls to Windows API in the go runtime,
we can still produce a (partial) stack trace in this circumstance by
following frame pointers (starting with BP).
We still prefer debug_frame entries when available since go functions
do not have frame pointers before go1.8.
It was possible for …
> Miscellaneous bug fixes on windows

- .travis.yml
Dropping test coverage for Go 1.6.
> Add Go 1.8 to Travis test matrix

- pkg/proc/proc.go
- pkg/proc/proc_test.go
```
proc/tests: use Detach(true) instead of Kill in tests
The rest of the code uses Detach to "close" a proc.Process, the tests
should do the same.
Any cleanup that proc.Process needs to do can then be put inside Detach
and the tests will run it.
```
> proc/tests: use Detach(true) instead of Kill in tests

- pkg/proc/proc_test.go
```
proc/tests: make TestStacktraceGoroutine more reliable
One of those goroutines could also conceivably be stopped on line 8.
```
> proc/tests: make TestStacktraceGoroutine more reliable

- pkg/proc/proc_test.go
- pkg/proc/stack.go
- pkg/proc/variables.go
Stack barriers were removed in Go 1.9, and thus code that
expected various stack-barrier-related symbols to exist
does not find them.  Check for their absence and do not
crash when they are missing.
> pkg/proc: tolerate absence of stack barriers in Go 1.9

- pkg/proc/registers_darwin_amd64.go
- pkg/proc/registers_linux_amd64.go
- pkg/proc/registers_windows_amd64.go
```
bugfix: wrong register used for CH
We only use Registers.Get besides for evaluating the argument of a CALL
instruction so this doesn't matter in practice, but it's still wrong.
```
> bugfix: wrong register used for CH

- pkg/terminal/terminal.go
When running interactive command in gdb, it will remove beginning space,
so do the same for dlv, which will be more convient for user
> terminal: trim space in interactive console

- Documentation/EditorIntegration.md
Not sure if it's better to wait for the official release of Gogland, or point it out now so more people test it.
In near daily use for the past few weeks, it's been better than using the IntelliJ plugin version.  Which itself was pretty good.
> Add an entry for Gogland

- _fixtures/testnextnethttp.go
- pkg/proc/proc.go
- pkg/proc/proc_darwin.go
- pkg/proc/proc_linux.go
- pkg/proc/proc_test.go
- pkg/proc/proc_windows.go
Detach did not work for processes we attach to via PID.
Linux: we were only detaching from the main thread, all threads are
detached independently
Windows: we must resume all threads before detaching.
macOS: still broken.
Updates #772
> proc: add test for attach/detach, fix detach

- pkg/proc/arch.go
- pkg/proc/bininfo.go
- pkg/proc/breakpoints.go
- pkg/proc/disasm.go
- pkg/proc/disasm_amd64.go
- pkg/proc/eval.go
- pkg/proc/moduledata.go
- pkg/proc/proc.go
- pkg/proc/proc_darwin.go
- pkg/proc/proc_linux.go
- pkg/proc/proc_test.go
- pkg/proc/proc_windows.go
- pkg/proc/stack.go
- pkg/proc/threads.go
- pkg/proc/threads_darwin.go
- pkg/proc/threads_linux.go
- pkg/proc/threads_windows.go
- pkg/proc/types.go
- pkg/proc/variables.go
- pkg/target/target.go
- service/debugger/debugger.go
- service/debugger/locations.go
```
proc: compile support for all executable formats unconditionally
So far we only compiled in support for loading the executable format
supported by the host operating system.
Once support for core files is introduced it is however useful to
support loading in all executable formats, there is no reason why it
shouldn't be possible to examine a linux coredump on windows, or
viceversa.
proc: refactor BinaryInfo part of proc.Process to own type
The data structures and associated code used by proc.Process
to implement target.BinaryInfo will also be useful to support a
backend for examining core dumps, split this part of proc.Process
to a different type.
```
> proc refactor: split out BinaryInfo implementation

- cmd/dlv/cmds/commands.go
> cmd/dlv: Use Printf over Println

- cmd/dlv/cmds/commands.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/terminal.go
```
terminal: bugfix: tolerate spurious spaces after command prefixes
Expressions such as:
frame 0    list
frame   0   list
on abreakpoint     print x
goroutine    1    frame     0     list
should all execute correctly
Fixes #712
```
> terminal: bugfix: tolerate spurious spaces after command prefixes

- pkg/terminal/command.go
- pkg/terminal/command_test.go
```
terminal: better list command
- always print a header with the path to the file being displayed
- always evaluate the linespec argument, even if a scope prefix is present
Fixes #711, #713
```
> terminal: better list command

- service/test/common_test.go
- service/test/integration1_test.go
- service/test/integration2_test.go
- service/test/variables_test.go
According to https://golang.org/cmd/go/#hdr-Test_packages
service_test is more appropriate because this directory contains
no non-test code and the intention is to compile these *_test.go
files as a separate package and link/run with the main test package.
> service/test: change test package name to service_test

- pkg/proc/arch.go
- pkg/proc/go_version.go
- pkg/proc/proc_test.go
- service/test/integration1_test.go
- service/test/integration2_test.go
- service/test/variables_test.go
Go recently introduced proposal tags to their version tags, we
are simply allowing delve to handle it appropriately.
See:
https://github.com/golang/go/commit/0954fdd51e390e209317d4652d7effc15512fd50
> Fixed delve's version extraction to allow propsals

- pkg/proc/core/linux_amd64_core.go
```
proc: fix build on go1.6
Fixes #799
```
> proc: fix build on go1.6

- .gitattributes
- Makefile
- pkg/version/version.go
```
makefile: use git's $Id$ instead of setting ver.Build in makefile
```
> makefile: use git's $Id$ instead of setting ver.Build in makefile

- pkg/proc/core/core.go
- pkg/proc/disasm_amd64.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
- pkg/proc/native/threads.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/threads.go
- service/debugger/debugger.go
- service/debugger/locations.go
```
proc: turn FindFileLocation, FindFunctionLocation, FirstPCAfterPrologue methods into function
proc/native: remove unused utility methods
```
> Minor post-refactoring cleanup

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/native/threads_darwin.go
- pkg/proc/native/threads_linux.go
- pkg/proc/native/threads_windows.go
- service/test/common_test.go
```
proc/native: error when reading/writing memory of exited process
Fixes #809
```
> proc/native: error when reading/writing memory of exited process

- _fixtures/testenv.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/proc_test.go
```
proc/gdbserial: pass environment variables to target
debugserver requires a special option to forward the environment to the target.
Fixes #818
```
> proc/gdbserial: pass environment variables to target

- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/proc_test.go
```
proc/native: Detach should use Kill with child processes we want killed
While implementing the gdbserial backend everything was changed to call
Detach to "close" a process so that gdbserial could do its clean up in
a single place. However the native implementation of Detach does not
actually kill processes we launched.
Fixes #821
```
> proc/native: Detach should use Kill with child processes we want killed

- _fixtures/notify-v2.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
```
terminal: bugfix: deref of nil SelectedGoroutine switching goroutines
If CurrentThread isn't running a goroutine SelectedGoroutine can be
nil, do not blindly dereference it.
Fixes #827
```
> terminal: bugfix: deref of nil SelectedGoroutine switching goroutines

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/native/proc.go
```
proc: print runtime.curg._panic.arg on unrecovered-panic breakpoint
You usually want to know the reason for the panic when a panic happens,
it can be printed manually this is a small quality of life improvement.
```
> proc: print runtime.curg._panic.arg on unrecovered-panic breakpoint

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/proc_test.go
```
proc/gdbserial: fix passing arguments to target via debugserver
Debugserver does not work as documented, "--" needs to be specified to
pass arguments to the target process (but only if it's an argument that
starts with a dash).
Fixes #839
```
> proc/gdbserial: fix passing arguments to target via debugserver

- _fixtures/increment.go
- pkg/proc/breakpoints.go
- pkg/proc/core/core.go
- pkg/proc/eval.go
- pkg/proc/moduledata.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/stack.go
- pkg/proc/threads.go
- pkg/proc/variables.go
This is a substantial change to our implementation of next/step/stepout so maybe we should hold it until after 1.0.0. OTOH next/step/stepout won't work on recursive functions because currently we are only checking that we stay on the same goroutine, where we should be checking that we stay on the same *call frame* too. 
```
proc: next, stepout should work on recursive goroutines
Before this commit our temp breakpoints only checked that we would stay
on the same goroutine.
However this isn't enough for recursive functions we must check that we
stay on the same goroutine AND on the same stack frame (or, in the case
of the StepOut breakpoint, the previous stack frame).
This commit:
1. adds a new synthetic variable runtime.frameoff that returns the
offset of the current frame from the base of …
```
> proc: next, stepout should work on recursive goroutines

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/rr.go
I think most of the problems in issue #838 may actually be due to people not noticing debugserver's authorization prompt, since debugserver won't connect back to us until user authorization is given we should wait forever for a connection as long as the debugserver process remains alive.
Waiting for a fixed amount of time was an ugly solution anyway.
PS. 20% of the code causes 80% of the bugs.
```
proc/gdbserial: wait for a connection from stub as long as stub lives
The authorization prompt on macOS can take a long time to be
acknowledged by the user, we should keep waiting for a connection as
long as the debugserver instance we launched remains alive.
```
> proc/gdbserial: wait for a connection from stub as long as stub lives

- pkg/proc/interface.go
- pkg/proc/variables.go
```
pkg/proc: remove unused types
type M struct was never used (as far as I know).
type VariableEval interface was used for a brief period of time during
the refactoring, now both its methods are functions.
```
> pkg/proc: remove unused types

- pkg/proc/proc_test.go
- pkg/proc/variables.go
This problem came up while I was implementing #831, it's pretty rare and I can only seem to reproduce it with the lldb backend, it's caused by the length of G.waitreason containing garbage.
```
proc/variables: protect form invalid G struct in parseG
A waitreason string that has invalid length (because the G struct is
corrupted or being modified) could cause a crash.
```
> proc/variables: protect form invalid G struct in parseG

- _fixtures/testvariables2.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc/variables: bugfix: parsing of maps with zero sized value type
Buckets of maps with zero sized value types (i.e. map[T]struct{}) have
zero length value arrays.
```
> proc/variables: bugfix: parsing of maps with zero sized value type

- pkg/proc/native/proc_linux.go
- pkg/proc/native/threads_linux.go
```
proc/native/linux: call waitFast instead of wait in addThread and halt
The condition that causes waitFast to fail can not happen in addThread
and halt so we don't need to call the slower wait.
```
> proc/native/linux: call waitFast instead of wait in addThread and halt

- _fixtures/testvariables2.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc/variables: fill Len field of maps when recursion limit is reached
If we don't fill the Len field there will be no way for the user to
distinguish maps we didn't load from empty maps.
```
> proc/variables: fill Len field of maps when recursion limit is reached

- CHANGELOG.md
- pkg/proc/core/core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_linux.go
- pkg/proc/proc_test.go
- pkg/proc/proc_unix_test.go
- service/debugger/debugger.go
There were really two sources of data races, one was native.(*Process).Running with native.(*Process).ContinueOnce, which only affected tests. The other was native.(*Process).RequestManualStop with native.(*Process).trapWait, this one could have affected real use, in principle, but only if the compiler applied some extra-aggressive reordering, which it doesn't.
```
proc: document thread safety of Process interface.
proc/*: remove Process.Running
Implementing proc.Process.Running in a thread safe way is complicated
and nothing actually uses it besides tests, so we are better off
rewriting the tests without Running and removing it.
In particular:
* The call to d.target.Running() in service/debugger/debugger.go
(Restart) can never return true because that line executes while
holding …
```
> Solving data races in tests

- CHANGELOG.md
- service/debugger/debugger.go
- service/test/integration2_test.go
```
debugger: collect breakpoint information on next/step/stepout
A next/step/stepout command could hit a normal breakpoint, decorated
with a list of variables to evaluate, if that happens the variable
should be evaluated just as if the breakpoint was hit by a continue.
```
> debugger: collect breakpoint information on next/step/stepout

- CHANGELOG.md
- pkg/terminal/command_test.go
- service/api/types.go
- service/debugger/debugger.go
```
api: add FrameOffset to Stackframe
Other debuggers can be instructed to decorate the stacktrace with the
value of SP. Our SP equivalent is the frame offset, since we can add it
to the Stackframe structure without incurring into added costs we
should, so that frontends can use it if they want.
```
> api: add FrameOffset to Stackframe

- pkg/proc/arch.go
- pkg/proc/bininfo.go
- pkg/proc/core/core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/native/proc.go
- pkg/proc/proc.go
- pkg/proc/threads.go
When a Go program is externally linked, the external linker is
responsible for picking the TLS offset. It records its decision in the
runtime.tlsg symbol. Read the offset from that rather than guessing -16.
This implementation causes a regression: pre-1.5.2 (I think?) versions
will no longer work, since they apparently had a different default TLS
offset, and reading the version during initialization is quite awkward.
If you still want to support versions that old I can go back to the
previous initialization order. Maybe we should add a DW_AT_producer
attribute so that reading the version is easier.
Fixes issue #468.
> proc: read G struct offset from runtime.tlsg if possible

- pkg/proc/eval.go
- pkg/proc/variables.go
- service/api/prettyprint.go
- service/test/variables_test.go
```
proc/variables: dereference concrete value of interface variables
The concrete value of an interface is always stored as a pointer inside
an interface variable. So far we have followed the memory layout and
reported the type of the 'data' attribute of interfaces as a pointer,
however this makes it impossible to distinguish interfaces with
concrete value of type 'A' from interfaces of concrete value of type
'*A'.
With this changeset when we autodereference pointers when the concrete
type of an interface is not a pointer.
```
> proc/variables: dereference concrete value of interface variables

- pkg/proc/core/core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
- pkg/proc/proc.go
```
proc: fix interaction of RequestManualStop and conditional breakpoints
A conditional breakpoint that is hit but has the condition evaluate to
false can block a RequestManualStop from working. If the conditional
breakpoint is set on an instruction that is executed very frequently by
multiple goroutines (or many conditional breakpoints are set) it could
prevent all calls to RequestManualStop from working.
This commit fixes the problem by changing proc.Continue to exit
unconditionally after a RequestManualStop is called.
```
> proc: fix interaction of RequestManualStop and conditional breakpoints

- pkg/proc/bininfo.go
- pkg/proc/types.go
- pkg/proc/variables.go
```
proc/eval: optimize variable lookup
Variable lookup is slow because it requires a full scan of debug_info
to check for package variables, this doesn't matter much in interactive
use but can slow down evaluation of breakpoint conditions
significantly.
Providing benchmark proof for this is hard since this effect doesn't
show for small programs with small debug_info sections.
```
> proc/eval: optimize variable lookup

- Documentation/EditorIntegration.md
This pull request is introducing [vim-delve](https://github.com/sebdah/vim-delve) to the editor support page. It's also sorting the editors alphabetically and increases the documentation readability with more structure.
> docs: Add vim-delve and clean up page

- Makefile
- cmd/dlv/main.go
```
cmd/dlv: bugfix: make version command actually print revision number
```
In the meeting @hyangah pointed out that it's hard to tell which version of delve one is actually running.
> cmd/dlv: bugfix: make version command actually print revision number

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/native/proc.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/stack.go
- pkg/proc/threads.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- service/api/types.go
- service/debugger/debugger.go
- service/test/integration2_test.go
This mostly came out of issue #893. I don't think it's plausible that a user will be able to next all the way from the start of the process to main, while the runtime is setting up the environment (too many unusual things happen), however there were some legitimate bugs there.
This also fixes issue #868 which is mostly harmless but sometimes makes travis fail.
```
proc: treat assembly files like go code in Next
proc/native,proc/gdbserial: set selectedGoroutine after StepInstruction
When stepping through runtime sometimes the current goroutine will
change. It is impossible to handle this in Next, Step and StepOut but
StepInstruction can reset the current goroutine correctly.
service/debugger: revert Next/StepOut/Step behavior on exit
When the process exits during we used to return an …
```
> Small fixes to delve behavior when target is in an unusual state

- cmd/dlv/dlv_test.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_windows.go
Delve opens debugged executable to read binary info it
contains, but it never closes the file. Windows will not
let you delete file that is opened. So close Process.bi
in Process.postExit, and actually call Process.postExit
from windows Process.Kill.
Also Windows sends some debugging events
(EXIT_PROCESS_DEBUG_EVENT event in particular) after Delve
calls TerminateProcess. The events need to be consumed by
debugger before debugged process will be released by
Windows. So call Process.waitForDebugEvent after
TerminateProcess in Process.Kill.
Fixes #398
> proc/native: make sure debugged executable can be deleted on windows

- _fixtures/locationsprog.go
- service/debugger/locations.go
- service/test/common_test.go
- service/test/integration2_test.go
```
debugger/locations: if locspec isn't found try interpreting it as expr
If the user tries to list the contents of a function pointer but
forgets the '*' operator the location lookup will fail and result in a
unhelpful "location not found" error.
Instead if the location lookup fails we should try interpreting the
locspec as if it was preceded by '*'.
```
> debugger/locations: if locspec isn't found try interpreting it as expr

- pkg/proc/disasm.go
- pkg/proc/native/proc.go
- pkg/proc/proc.go
- pkg/proc/stack.go
- service/debugger/debugger.go
Instead of panicing for sending on a closed channel, detect that the
process has exited and return a proper error message.
This patch also cleans up some spots where the Pid is omitted from the
error.
Fixes #920
> pkg/proc: return proper error when process has exited

- pkg/terminal/command_test.go
- service/test/integration2_test.go
```
tests: remove rr trace directory after running tests
Can't get the trace directory from the server after we disconnect from
it.
```
> tests: remove rr trace directory after running tests

- Documentation/cli/locspec.md
This is a "fix" for the issue of being unable to see the source when setting a breakpoint on main.init.
Fixes #922
> Add breakpoint init functions suggestion

- Documentation/installation/README.md
```
Documentation: After the go1.9 support PR delve no longer builds on <1.7.
```
> Documentation: After the go1.9 support PR delve no longer builds on <1.7.

- Makefile
- pkg/proc/native/proc_windows.go
```
proc/tests: fix intermittent test stall on windows
While we are waiting for the process to exit in native.(*Process).Kill
we could receive queued exception events, those must be continued or
the wait will never finish.
```
> proc/tests: fix intermittent test stall on windows

- pkg/proc/variables.go
- service/api/types.go
```
proc: auto-dereference local variables that escape to the heap
The compiler a variable 'v' that escapes to the heap with a '&v' entry.
Auto dereference those local variables.
Fixe #871
```
> proc: auto-dereference local variables that escape to the heap

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- service/debugger/debugger.go
```
proc/gdbserial: automatically retrieve exe path on attach on macOS
debugserver doesn't support qXfer:exec-file:read, and it doesn't return
the executable path in the response to qProcessInfoPID, however we can
find out the executable path by using jGetLoadedDynamicLibrariesInfos.
```
> proc/gdbserial: automatically retrieve exe path on attach on macOS

- _fixtures/testvariables2.go
- service/api/conversions.go
- service/api/prettyprint.go
- service/api/types.go
- service/test/variables_test.go
```
proc/variables: distinguish between nil and empty slices and maps
Fixes #959
```
> proc/variables: distinguish between nil and empty slices and maps

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/native/proc.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/terminal/command.go
```
proc/gdbserial: return error if stopped with a sginal
On macOS we can also stop when we receive a signal,
propagate this reason upwards to the client.
Also clear internal breakpoints after an unrecovered-panic since they
can not be reached anymore.
Fixes #872
```
> proc/gdbserial: return error if stopped with a sginal

- pkg/proc/proc_test.go
- pkg/proc/threads.go
```
proc: change next to skip deferred functions
Make 'next' skip deferred functions unless they are called via a panic.
Call to a deferred function through 'return' are predictable, if the
user wants to step into them 'step' can be used but without this change
there is no way to avoid stepping into them.
Implements #956
```
> proc: change next to skip deferred functions

- Documentation/cli/expr.md
- _fixtures/testvariables2.go
- pkg/proc/eval.go
- pkg/proc/types.go
- service/api/prettyprint.go
- service/test/variables_test.go
```
proc/eval: support more type casts
* string to []rune
* string to []byte
* []rune to string
* []byte to string
* any pointer to uintptr
The string, []rune, []byte conversion pairs aligns this to the go
language.
The pointer -> uintptr conversion pair is symmetric to the uintptr ->
pointer that we already have.
Also lets the user specify any size for byte array types instead of
just the ones already used by the program, this can be used to read
arbitrary memory.
Fixes #548, #867
```
> proc/eval: support more type casts

- _fixtures/scopetest.go
- pkg/proc/scope_test.go
- pkg/proc/test/support.go
```
pkg/prog/test: add flag to run target with -race flag
Adds test command line flag to compile target fixtures using the -race flag.
Multiple tests will fail because of https://github.com/golang/go/issues/22600
but eventually this should work.
```
> pkg/prog/test: add flag to run target with -race flag

- pkg/dwarf/frame/entries.go
- pkg/dwarf/frame/table.go
- pkg/dwarf/op/op.go
- pkg/dwarf/op/op_test.go
- pkg/dwarf/op/regs.go
- pkg/dwarf/reader/reader.go
- pkg/proc/arch.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/registers.go
- pkg/proc/stack.go
- pkg/proc/threads.go
- pkg/proc/variables.go
- service/debugger/debugger.go
```
proc: refactor stack.go to use DWARF registers
Instead of only tracking a few cherrypicked registers in stack.go track
all DWARF registers.
This is needed for cgo code and for the locationlists emitted by go in
1.10:
* The debug_frame sections emitted by C compilers can not be used
without tracking all registers
* the loclists emitted by go1.10 need all registers of a frame to be
interpreted.
```
> proc: refactor stack.go to use DWARF registers

- _fixtures/nextcond.go
- pkg/proc/breakpoints.go
- pkg/proc/core/core.go
- pkg/proc/disasm.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/native/threads.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/scope_test.go
- pkg/proc/threads.go
- service/api/conversions.go
- service/debugger/debugger.go
```
proc: next should not skip lines with conditional bps
Conditional breakpoints with unmet conditions would cause next and step
to skip the line.
This breakpoint changes the Kind field of proc.Breakpoint from a single
value to a bit field, each breakpoint object can represent
simultaneously a user breakpoint and one internal breakpoint (of which
we have several different kinds).
The breakpoint condition for internal breakpoints is stored in the new
internalCond field of proc.Breakpoint so that it will not conflict with
user specified conditions.
The breakpoint setting code is changed to allow overlapping one
internal breakpoint on a user breakpoint, or a user breakpoint on an
existing internal breakpoint. All other combinations are rejected. The
breakpoint clearing code is changed to …
```
> proc: next should not skip lines with conditional bps

- _fixtures/testvariables2.go
- pkg/proc/eval.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc: automatically dereference interfaces on member access
If 'iv' is an interface variable with a struct as a concrete value let
'iv.A' evaluate to the access to field 'A' of the concrete value of
'iv'.
proc: support access to chan buffers
Replace the unsafe.Pointer type of the buf field of channels with the
appropriate array type, allow expressions accessing member field of the
channel struct.
Fixes #962
```
> proc: better eval support for channels and interfaces

- pkg/proc/disasm.go
- pkg/proc/disasm_amd64.go
- pkg/proc/proc.go
- pkg/proc/threads.go
```
pkg/proc: fix StepBreakpoint handling
StepBreakpoints are set on CALL instructions, when they are hit we
disassemble the current instruction, figure out the destination address
and set a breakpoint after the prologue of the called function.
In order to disassemble the current instruction we disassemble the area
of memory starting from PC and going to PC+15 (because 15 bytes is the
maximum length of one instruction on AMD64). This means that we won't
just disassemble one instruction but also a few instructions following
it ending with one truncated instruction.
This usually works fine but sometimes the disassembler will panic with
an array out of bounds error when trying to disassemble a truncated
instruction. To avoid this problem this commit changes the funciton
disassemble to take …
```
> pkg/proc: fix StepBreakpoint handling

- pkg/proc/native/ptrace_linux.go
- pkg/proc/native/registers_linux_amd64.go
```
proc/native/linux: ignore ENODEV when retrieving fp registers
Either the CPU or the kernel may not support the calls we do when
retrieving floating point registers, this isn't an error we should
propagate.
Also improve the error reporint of pkg/proc/native.fpRegisters.
Fixes #1022
```
> proc/native/linux: ignore ENODEV when retrieving fp registers

- pkg/dwarf/reader/variables.go
- pkg/proc/proc_test.go
On macOS, externally linked programs will have an abbrev for
DW_TAG_subprogram without the haschildren flag set. We should handle
this case instead of expecting all DW_TAG_subprogram entries to have
list of children.
Fixes #1034
> proc: handle DW_TAG_subprogram with a nochildren abbrev

- service/api/prettyprint.go
It can happen if the interface variable escaped, it's out of scope and
we autodereference it.
> variables: toplevel interface variables may have a 0 address

- pkg/dwarf/line/state_machine.go
- pkg/proc/proc_test.go
We need to reset the current file and line number.
Fixes #1008
> dwarf/line: handle DW_LNE_end_of_sequence correctly

- Makefile
- _fixtures/consts.go
- _fixtures/decllinetest.go
- cmd/dlv/cmds/commands.go
- pkg/dwarf/line/line_parser_test.go
- pkg/dwarf/reader/variables.go
- pkg/proc/bininfo.go
- pkg/proc/core/core_test.go
- pkg/proc/dwarf_expr_test.go
- pkg/proc/eval.go
- pkg/proc/moduledata.go
- pkg/proc/proc_test.go
- pkg/proc/stack.go
- pkg/proc/types.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- service/api/conversions.go
- service/api/types.go
- service/test/variables_test.go
- Changes command line options of `go build` and `go test -c` to take advantage of go 1.10 new caching
- Use DW_AT_producer to warn user about debugging optimized functions
- Use DW_TAG_constants to describe variable values
- Use DW_AT_decl_line to determine variable visibility (fixes #186, #83)
- Miscellaneous test fixes for go1.10.
> Go 1.10 support

- pkg/dwarf/line/state_machine.go
```
dwarf/line: fix output for the last line of a compile unit
The last entry of the debug_line table is supposed to be valid for
every PC address greater than its address.
```
> dwarf/line: fix output for the last line of a compile unit

- cmd/dlv/dlv_test.go
```
dlv_test: disable one of the checks of TestOutput on windows
Sometimes delve on Appveyor can't remove the built binary before
exiting and gets an "Access is denied" error when trying.
See: https://ci.appveyor.com/project/derekparker/delve/build/1527
```
> dlv_test: disable one of the checks of TestOutput on windows

- Makefile
As of Go 1.8, allows empty GOPATH environment variable.
Fall back `make install` when GOPATH is not set on darwin OS.
> Makefile: handle empty GOPATH on darwin

- pkg/config/config.go
- pkg/dwarf/op/op.go
- pkg/proc/bininfo.go
- pkg/proc/stack.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- pkg/terminal/config.go
- service/api/conversions.go
- service/api/types.go
Split out of https://github.com/derekparker/delve/pull/958.
Another possibility is to make &x return a string with the location expression of x when it doesn't have a phisical address.
```
pkg/terminal: print DWARF location expression with whatis
Adds a configuration option (show-location-expr) that when activated
will cause the whatis command to also print the DWARF location
expression for a variable.
```
> pkg/terminal: print DWARF location expression with whatis

- Documentation/installation/linux/install.md
- Documentation/installation/windows/install.md
`go get` needs key `-u` to use network. Mentioned `go get github.com/dereparker/delve/cmd/dlv` without `-u` didn't work for me on debian 9.
> Added key `-u` for `go get` in linux installation readme 

- _fixtures/pr1055.go
- service/debugger/debugger.go
- service/test/integration2_test.go
I've noticed that Delve is inconsistent in marking when a process exits based on the API call which triggered the exit to happen.
In my case, I've noticed this happening for using ` next ` (via RPC).
To have an example to reproduce this
```go
package main
import (
"fmt"
"go/ast"
"os"
)
func main() {
a := &ast.CompositeLit{}
fmt.Println("demo", a) // set breakpoint here and use next twice 
os.Exit(2)
}
```
This allows clients to have a consistent way to handle cases when the process exits.
> Remove limitation of exit notification only for specific API calls

- Documentation/cli/getting_started.md
- README.md
Improve the link ordering for the main README and add a
"Getting Started" doc with basic usage information for new users.
> Documentation: Improve link layout, add getting started doc

- service/test/integration2_test.go
```
service/test: disable TestClientServerConsistentExit for rr backend
The rr backend doesn't report the exit status (the argument of the W
packet seems to always be 0).
Fixes #1067
```
> service/test: disable TestClientServerConsistentExit for rr backend

- pkg/terminal/command.go
This would help out those of us habituated to [pdb](https://docs.python.org/3/library/pdb.html). 😊
> Add "l" alias for list command

- pkg/proc/proc_test.go
```
proc_test: deflake TestSystemstackOnRuntimeNewstack
Depending on how the runtime schedules our goroutines we can get
unlucky and have the first call to runtime.newstack we intercept be for
a different goroutine (usually the garbage collector).
Only check stacktraces that happen on the same goroutine that executed
main.main.
```
> proc_test: deflake TestSystemstackOnRuntimeNewstack

- _fixtures/clientdo.go
- pkg/proc/variables.go
- service/api/prettyprint.go
- service/test/variables_test.go
```
proc,prettyprint: guard against autodereferenced escaped pointers
Much like the bug in issue #1031 and commit
f6f6f0bf13e4c708cb501202b83a6327a0f00e31 pointers can also escape to
the heap and then have a zero address (and no children) when we
autodereference.
1. Mark autodereferenced escaped variables with a 0 address as
unreadable.
2. Add guards to the pretty printers for unsafe.Pointer and pointers.
Fixes #1075
```
> proc,prettyprint: guard against autodereferenced escaped pointers

- .travis.yml
- pkg/proc/core/core_test.go
```
core_test: fix TestCoreFpRegisters on go1.9
It was broken by 7bec20e5fca48552b004fc8776dd9e6502a11706
```
> core_test: fix TestCoreFpRegisters on go1.9

- pkg/proc/gdbserial/rr.go
```
gdbserial: fix rr output parsing to support rr 5.1.0
```
> gdbserial: fix rr output parsing to support rr 5.1.0

- pkg/terminal/terminal.go
- pkg/terminal/terminal_test.go
```
terminal: disable file path case normalization on macOS
Fixes #1088
```
> terminal: disable file path case normalization on macOS

- pkg/proc/dwarf_expr_test.go
- pkg/proc/mem.go
- pkg/proc/variables.go
```
proc: disable caching for variables with an extended location
Our current frame caching strategy doesn't handle extended locations
expressions correctly, disable it on variables that don't have a simple
address.
```
> proc: disable caching for variables with an extended location

- pkg/proc/native/proc_darwin.go
pkg/proc: Retry task_for_pid if handed parent task instead of child
On macOS a call to fork and a subsequent call to task_for_pid will race each other. This is because the macOS kernel assigns a new proc_t structure early but the new task, thread and uthread come much later. The function exec_mach_imgact in the XNU sources contains this logic.
In a system under load or one with delays in fork processing (i.e. various security software), task_for_pid as currently called by Delve often returns the parent task. This can be seen by printing out the task number around line 86. In a normal system we would see three calls:
-> ~/go/bin/dlv --listen=localhost:59115 --headless=true --api-version=2 --backend=native exec ./___main_go -- 
Task: 9731
Task: 9731
Task: 9731
API server listening at: …
> Handle race between fork and task_for_pid

- pkg/dwarf/reader/reader.go
- pkg/proc/bininfo.go
- pkg/proc/core/core_test.go
- pkg/proc/moduledata.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/threads.go
- pkg/proc/variables.go
- service/debugger/debugger.go
- service/test/variables_test.go
```
dwarf/reader,proc: support DW_AT_abstract_origin
debug_info entries can use DW_AT_abstract_origin to inherit the
attributes of another entry, supporting this attribute is necessary to
support DW_TAG_inlined_subroutine.
Go, starting with 1.10, emits DW_TAG_inlined_subroutine entries when
inlining is enabled.
```
> dwarf/reader,proc: support DW_AT_abstract_origin

- pkg/config/config.go
Previously the file handle for the newly created default config was
being closed and thrown away as opposed to returned to the caller to
finish setting up config for the rest of the process. This patch changes
to return a handle to the newly created config so setup can happen as
normal. This fixes a bug where Delve can crash on first run when a
config is not present on the system.
Fixes #1129
> config: Return handle for created default config

- pkg/proc/variable_test.go
- pkg/proc/variables.go
Fixes a bug where the 'go' statement that created a goroutine was
incorrectly reported.
Fixes #1135
> pkg/proc: Fix reporting of 'go' statement

- _fixtures/dotpackagesiface.go
- _fixtures/vendor/dir.io/dir.go
- _fixtures/vendor/dir.io/io.io/io.go
- pkg/proc/proc_test.go
- pkg/proc/types.go
```
proc: support interface type resolution for packages containing a dot
If the last entry of the package path contains a '.' the corresponding
DIEs for its types will replace the '.' character with '%2e'. We must
do the same when resolving the package path of the concrete type of an
interface variable.
Fixes #1137
```
> proc: support interface type resolution for packages containing a dot

- Documentation/installation/osx/install.md
```
Documentation: remove homebrew as an install method
The formula is broken and produces an endless stream of duplicate bug
reports yet nobody steps up to fix it. Using the formula isn't
necessary and hasn't been in almost a year, the maintainers of delve
aren't using it and the original maintainer of the formula vacated.
```
> Documentation: remove homebrew as an install method

- _fixtures/issue1101.go
- pkg/proc/core/core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/native/threads.go
- pkg/proc/native/threads_darwin.go
- pkg/proc/native/threads_linux.go
- pkg/proc/native/threads_windows.go
- pkg/proc/proc_test.go
- pkg/proc/proc_unix_test.go
- service/test/variables_test.go
* Removes proc.Process.Kill, it was only used by tests at this point
* Removes proc.Process.Halt, fuses the Halt in proc/native with native's setCurrentBreakpoints into a single stop method. Halt wasn't used outside of native and some tests, and it was redundant with RequestManualStop.
* Moves the fields Process.halt and Thread.running in native to os specific structs and removes them from all operating system implementations that don't actually make use of them.
> miscellaneous proc/native cleanups

- _fixtures/coreemptystring.go
- pkg/proc/core/core_test.go
- pkg/proc/variables.go
```
proc: fix reading of empty strings in core files
Every time we read an empty string we accidentally issue a read for 0
bytes at address 0, this is fine for real memory but the core file
reader doesn't like it.
Fixes an issue reported on the mailing list.
```
> proc: fix reading of empty strings in core files

- Documentation/installation/linux/install.md
Assuming installation docs are for people not familiar with
Go, I think it's important to specify how to properly run
`make install`.
> Documentation: make install must run in workspace

- _fixtures/fputest/fputest_amd64.s
- pkg/proc/core/core_test.go
```
proc/core: Make TestCoreFpTest less flaky
Registers XMM1 and XMM2 get sometimes clobbered between the time we set
them and the panic. There is no guarantee that they won't in the go
spec so we shouldn't expect any register to keep its value. However
since this seems to only affect 1 and 2 let's try to use 9 and 10
instead.
```
> proc/core: Make TestCoreFpTest less flaky

- _fixtures/consts.go
- _fixtures/vendor/dir0/pkg/main.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc: allow evaluating constants specified with a partial package path
Fixes #1151
```
> proc: allow evaluating constants specified with a partial package path

- _fixtures/goroutinestackprog.go
- pkg/proc/proc_test.go
- pkg/proc/variable_test.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
With this change, sommand
frame 3
sets up so that subsequent "print", "set", "whatis" commands
will operate on frame 3.
frame 3 print foo
continues to work too.
Added "up", "down". They move the current frame up or down.
Implementation note:
This changes removes "scopePrefix" mode from the terminal/command.go and instead
have the command examine the goroutine/frame value to see if it is invoked in a
scoped context.
> Extend the "frame" command to set the current frame.

- _fixtures/testinline.go
- pkg/dwarf/line/state_machine.go
- pkg/dwarf/reader/reader.go
- pkg/dwarf/reader/variables.go
- pkg/proc/bininfo.go
- pkg/proc/dwarf_expr_test.go
- pkg/proc/eval.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/scope_test.go
- pkg/proc/stack.go
- pkg/proc/test/support.go
- pkg/proc/threads.go
- pkg/proc/variables.go
```
proc: support inlining
Go 1.10 added inlined calls to debug_info, this commit adds support
for DW_TAG_inlined_call to delve, both for stack traces (where
inlined calls will appear as normal stack frames) and to correct
the behavior of next, step and stepout.
The calls to Next and Frame of stackIterator continue to work
unchanged and only return real stack frames, after reading each line
appendInlinedCalls is called to unpacked all the inlined calls that
involve the current PC.
The fake stack frames produced by appendInlinedCalls are
distinguished from real stack frames by having the Inlined attribute
set to true. Also their Current and Call locations are treated
differently. The Call location will be changed to represent the
position inside the inlined call, while the Current location …
```
> proc: support inlining

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/rr.go
- service/debugger/debugger.go
```
gdbserial,debugger: better error message when debugserver not installed
When gdbserial can not find debugserver or lldb-server the error
message is always the same and it complains about lldb-server not being
found.
This is fine on linux (where the backend is unnecessary) but incomplete
on macOS (where the backend is actually used).
Make the error message clearer so that users who do not bother reading
install instructions are not confused.
```
> gdbserial,debugger: better error message when debugserver not installed

- pkg/proc/gdbserial/gdbserver.go
I can't reproduce this problem, somebody who can needs to verify if this works.
```
proc/gdbserial: disable g command on version 902 of debugserver
Fixes #1165
```
> proc/gdbserial: disable g command on version 902 of debugserver

- pkg/proc/native/proc_windows.go
```
proc/native/windows: when there is an error during Attach dbp might be nil
```
> proc/native/windows: when there is an error during Attach dbp might be nil

- _fixtures/testvariables2.go
- pkg/proc/eval.go
- service/test/variables_test.go
```
proc/eval: strings of different length are never equal
```
> proc/eval: strings of different length are never equal

- pkg/proc/proc.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
```
terminal: make printcontext use SelectedGoroutine
printcontext should use SelectedGoroutine instead of trusting that the
goroutine running on current thread matches the SelectedGoroutine.
When the user switches to a parked goroutine CurrentThread and
SelectedGoroutine will diverge.
Almost all calls to printcontext are safe, they happen after a continue
command returns when SelectedGoroutine and CurrentThread always agree,
but the calls in frameCommand and listCommand are wrong.
Additionally we should stop reporting an error when the debugger is
stopped on an unknown PC address.
```
> terminal: make printcontext use SelectedGoroutine

- pkg/proc/proc_test.go
```
proc_test: instrument TestFrameEvaluation
I've seen TestFrameEvaluation fail in CI in the past. It's been a while
since the last time and I couldn't reproduce it locally at all. I'd
like to have some instrumentation in case it happens again.
```
> proc_test: instrument TestFrameEvaluation

- _fixtures/testvariables2.go
- pkg/proc/eval.go
- service/test/variables_test.go
```
proc: Short circuit evaluation of && and || like go does
Change evaluation of binary operators so that both && and || only
evaluate their second argument conditionally, like go does.
```
> proc: Short circuit evaluation of && and || like go does

- _fixtures/issue951.go
- pkg/proc/eval.go
- pkg/proc/mem.go
- pkg/proc/proc.go
- pkg/proc/proc_general_test.go
- pkg/proc/proc_test.go
- pkg/proc/threads.go
- pkg/proc/variables.go
- service/api/types.go
- service/debugger/debugger.go
```
proc: Flag shadowed arguments as shadowed
Fixes #951
proc: cache entire frame in FrameToScope instead of variablesByTag
Caching the frame in variablesByTag is problematic:
1. accounting for variables that are (partially) stored in registers is
complicated (see issue #1106)
2. for some types (strings, interfaces...) simply creating the Variable
object reads memory, which therefore happens before we can do any
caching.
Instead cache the entire frame when the EvalScope object is created.
The cached range is between the SP value of the current frame and the
CFA of the preceeding frame, if available, or the CFA of the current
frame otherwise.
Fixes #1106
proc: change memCache to delay reading
Change memCache so that the preloaded memory is not read immediately
but only after the actual …
```
> proc: Refactor proc.(*EvalScope).variablesByTag

- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_core.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_replay.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_test.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- cmd/dlv/cmds/commands.go
- cmd/dlv/dlv_test.go
- pkg/logflags/logflags.go
```
cmd/dlv: Revert 4e177b, use new flag name for debug logging options
Previously to 4e177bb99acc511897f9cdbfc6cbc50d92ae4725 it was possible
to use --log without arguments to enable logging, this commit reenables
that use case.
The new functionality of the --log flag moved to a new flag name
--logx.
Fixes #1188
```
> cmd/dlv: Revert 4e177b, use new flag name for debug logging options

- pkg/terminal/terminal.go
fixes a SIGSEGV I had when debugger with no tty and trying to print a variable.
> check that t.conf is not nil in loadConfig

- pkg/terminal/terminal.go
```
terminal: always initialize conf
So we don't have to worry about having a nil conf field, even if there
is no configuration.
```
> terminal: always initialize conf

- pkg/proc/variables.go
```
proc: do not assume g.gopc is valid
Fixes #1203
```
> proc: do not assume g.gopc is valid

- pkg/proc/bininfo.go
Go seems to be generating multiple compilation units that have
the same file. I think this happens for functions that get inlined.
Without this patch, those inlined functions break the ability to set
a breakpoint at other lines in the file. I was able to load the same
binary in gdb and set a breakpoints throughout the file without issue.
Inlined functions are still a little weird. setting a breakpoint on
a function that gets inlined picks the first occurence. That being
said, I think delve should still do something reasonable for the rest
of the lines in the file.
Some potential debugging info:
```
➜ objdump --dwarf=decodedline automate-gateway | grep handler/users.go
.../handler/users.go:[++]
s/.../handler/users.go           20            0xb6dd88
.../handler/users.go:[++] …
```
> Keep searching for file:line until found

- cmd/dlv/cmds/commands.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_unix.go
- pkg/proc/gdbserial/gdbserver_windows.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/proc_test.go
- service/config.go
- service/debugger/debugger.go
- service/rpccommon/server.go
- service/test/variables_test.go
```
proc/native,proc/gdbserial: let target access terminal
Change the linux verison of proc/native and proc/gdbserial (with
debugserver) so that they let the target process use the terminal when
delve is launched in headless mode.
Windows already worked, proc/gdbserial (with rr) already worked.
I couldn't find a way to make proc/gdbserial (with lldb-server) work.
No tests are added because I can't think of a way to test for
foregroundness of a process.
Fixes #65
```
> proc/native,proc/gdbserial: let target access terminal

- pkg/proc/gdbserial/gdbserver.go
```
proc/gdbserial: disable foreground if /dev/tty can't be opened
Passing --stdin-path /dev/tty will crash debugserver if /dev/tty can't
be open.
Fixes #1215
```
> proc/gdbserial: disable foreground if /dev/tty can't be opened

- .travis.yml
- _fixtures/dwzcompression.go
- pkg/proc/bininfo.go
- pkg/proc/proc_test.go
- pkg/proc/test/support.go
- pkg/proc/types.go
'dwz' is a tool that reduces the size of DWARF sections by deduplicating
symbols. The deduplicated symbols are moved from their original 'compile
unit' to a 'partial unit', which is then referenced from its original
location with an 'imported unit' tag.
In the case of Go binaries, all symbols are located in a single 'compile
unit', and the name of each symbol contains a reference to its package,
so 'dwz' is not able to deduplicate them. But still, some C symbols
included in the binary are deduplicated, which also alters the structure
of the DWARF sections, making delve unable to parse them (crashing in
the attempt).
While it would've been possible to simply ignore the C symbols, or
blindly loading all then into BinaryInfo members (packageVars,
Functions...), for correctness sake this …
> proc: add support for dwz compressed DWARF

- pkg/proc/core/core_test.go
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/test/support.go
- pkg/terminal/command_test.go
```
tests: call RunTestsWithFixtures everywhere we use BuildFixture
If we don't build artifacts aren't removed after the tests run. Also
add a check to prevent this mistake from reoccuring.
```
> tests: call RunTestsWithFixtures everywhere we use BuildFixture

- pkg/proc/eval.go
- pkg/proc/proc_test.go
```
pkg/proc: respect specified load configuration after reslicing a map
Maps were always loaded with using the default configuration during a
reslice. This is probably a remnant from when we didn't let clients
configure the load parameters.
```
> pkg/proc: respect specified load configuration after reslicing a map

- pkg/proc/gdbserial/gdbserver.go
> proc/gdbserial: add syscall.Syscall* to list of blocking functions

- _fixtures/stepoutret.go
- pkg/proc/breakpoints.go
- pkg/proc/core/core.go
- pkg/proc/core/linux_amd64_core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/threads.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/threads.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/terminal.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc2/client.go
- service/test/integration2_test.go
```
proc,service: display return values when stepping out of a function
Displays the return values of the current function when we step out of
it after executing a step, next or stepout command.
Implementation of this feature is tricky: when the function has
returned the return variables are not in scope anymore. Implementing
this feature requires evaluating variables that are out of scope, using
a stack frame that doesn't exist anymore.
We can't calculate the address of these variables when the
next/step/stepout command is initiated either, because between that
point and the time where the stepout breakpoint is actually hit the
goroutine stack could grow and be moved to a different memory address.
```
```
proc: move AllGCache to a common struct
Add a new method "Common" to proc.Process …
```
> proc,service: display return values when stepping out of a function

- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_core.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_replay.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_test.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- cmd/dlv/cmds/commands.go
- pkg/logflags/logflags.go
- service/debugger/debugger.go
- service/rpccommon/server.go
```
service,logflags: log all RPC messages
We occasionally receive bug reports from users of VSCode-go and GoLand.
GoLand has its own way of capturing the packet exchange between itself
and delve but VSCode-go (supposedly) doesn't.
So far this hasn't been a problem since all bug reports were obvious
bugs on the plugin or easy to reproduce without VSCode-go, but it might
be helpful in the future to have a way to log the packet exchange
between dlv and a frontend.
This commit adds a --log-output option to enable logging of all rpc
messages and changes service/rpccommon accordingly.
```
> service,logflags: log all RPC messages

- Documentation/cli/expr.md
- _fixtures/pkgrenames.go
- _fixtures/vendor/dir0/pkg/main.go
- _fixtures/vendor/dir1/pkg/main.go
- pkg/proc/eval.go
- service/test/variables_test.go
```
proc: allow "package/path".varname syntax
If the application being debugged imports two packages with the same
name (but different paths) there was no way to disambiguate the two,
since the character '/' can not appear inside a go identifier.
By allowing users to use a string literal as the package name a package
path can be specified.
```
> proc: allow "package/path".varname syntax

- pkg/proc/proc_test.go
- pkg/proc/test/support.go
- pkg/proc/types.go
- pkg/terminal/command_test.go
```
proc,command: fix optimized function warning in 1.9
A user complained on the mailing list about having continuous
"optimized function warnings" on non-optimized functions when using 1.9.
This commit fixes the problem by disabling optimized function detection
on 1.9 and earlier (where it's impossible) and adds a test so we don't
break it again in the future.
```
> proc,command: fix optimized function warning in 1.9

- pkg/dwarf/godwarf/sections.go
- pkg/dwarf/line/line_parser_test.go
- pkg/proc/bininfo.go
- pkg/proc/gdbserial/gdbserver_conn.go
```
proc: support GNU compressed debug sections (go1.11 support)
Go1.11 switched to the zlib-gnu compression format for debug sections.
Change proc and and a test in dwarf/line to support this change.
Also deletes some dead code from pkg/proc/bininfo.go that hadn't been
used in a long time.
```
> proc: support GNU compressed debug sections (go1.11 support)

- service/rpccommon/server.go
```
rpccommon: restore API port message
This message is used by clients to determine the port that a headless
instance is using, therefore the format can not change or move to a
different file handle.
Fixes #1245
```
> rpccommon: restore API port message

- Documentation/cli/README.md
- cmd/dlv/cmds/commands.go
- pkg/proc/core/core.go
- pkg/proc/disasm.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/terminal/command.go
- pkg/terminal/terminal.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/rpccommon/server.go
- service/test/integration2_test.go
```
proc,terminal,service: let headless instances run without connected clients
This pull request makes several changes to delve to allow headless
instancess that are started with the --accept-multiclient flag to
keep running even if there is no connected client. Specifically:
1. Makes a headless instance started with --accept-multiclient quit
after one of the clients sends a Detach request (previously they
would never ever quit, which was a bug).
2. Changes proc/gdbserial and proc/native so that they mark the
Process as exited after they detach, even if they did not kill the
process during detach. This prevents bugs such as #1231 where we
attempt to manipulate a target process after we detached from it.
3. On non --accept-multiclient instances do not kill the target
process unless we …
```
> proc,terminal,service: let headless instances run without connected clients

- pkg/proc/variables.go
- service/api/conversions.go
- service/api/types.go
```
proc,service: export declaration line of variables
Adds a field, DeclLine, to Variable containing the declaration line
number of the variable.
```
> proc,service: export declaration line of variables

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- pkg/proc/types.go
- service/debugger/debugger.go
- service/rpccommon/server.go
```
*: Fix log level setting in logrus
Setting the Level field of a logrus logger doesn't actually do anything
since the Level field simply reports the log level of the last log
message emitted on the logger.
The right way to do that is to set logger.Logger.Level.
Also cleans up newline characters from log messages emitted through
logrus and fixes the direction of the arrows in the messages emitted by
rpccommon, which was inconsistent with the arrows of gdbserial.
```
> *: Fix log level setting in logrus

- Documentation/api/ClientHowto.md
- Documentation/internal/README.md
- README.md
```
Documentation: better documentation menu, add guide to writing a client
* Adds some links to the more relevant documentation pages on the main
README.md
* Adds a document informally describing how to write a client of delve
* Adds link to slides describing the architecture of delve
```
> Documentation: better documentation menu, add guide to writing a client

- pkg/proc/threads.go
The JSON-RPC layer doesn't like non-nil error that return an empty string
when the Error method is called and when this happens it shuts down the
connection to the server.
Since we can return a ThreadBlockedError to the client it can't have an
empty string as return value.
Fixes #1251
> proc: make proc.(ThreadBlockedError).Error() return a non-empty string

- Documentation/cli/README.md
- pkg/proc/variables.go
- pkg/terminal/command.go
- service/api/conversions.go
- service/api/types.go
```
proc,service,terminal: propagate g.startpc
Adds StartPC to proc.G, StartLoc to api.Goroutine and show the start
location in the command line client when appropriate.
Updates #1104
```
> proc,service,terminal: propagate g.startpc

- pkg/dwarf/line/state_machine.go
- pkg/proc/proc.go
```
dwarf/line: remove foundFile "optimization" from LineToPC
There is no guarantee that files will end up stored contiguously in the
debug_line section which makes this optimization wrong in the general
case.
In particular with recent versions of go1.11 and a go.mod file present
the go compiler seems to sometimes produce executables that actually
violate this assumption.
```
> dwarf/line: remove foundFile "optimization" from LineToPC

- pkg/terminal/command.go
```
terminal: disable next/step/stepout if current frame isn't 0
next/step/stepout should work even if the current frame isn't the
topmost stack frame, but their behavior should be different in that
case (they should continue inside the function of the selected frame).
Most of the logic of next/step/stepout would work correctly if we
simply replaced the call to proc.topframe with something that took a
frame index. However the breakpoint they set on the first deferred
function is wrong, and fixing it requires scanning the defer stack and
matching it to the call stack, something we can't do yet.
Given that enhancing next/step/stepout will take time and the current
behavior confuses users (see issue #1240) return an error if
next/step/stepout are called while the currently selected frame …
```
> terminal: disable next/step/stepout if current frame isn't 0

- _fixtures/deferstack.go
- pkg/proc/core/core_test.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/stack.go
- pkg/proc/threads.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/disasmprint.go
- service/api/conversions.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/debugger/locations.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/integration1_test.go
- service/test/integration2_test.go
```
proc,service,terminal: read defer list
Adds -defer flag to the stack command that decorates the stack traces
by associating each stack frame with its deferred calls.
Reworks proc.next to use this feature instead of using proc.DeferPC,
laying the groundwork to implement #1240.
```
> proc,service,terminal: read defer list

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_unix.go
- pkg/proc/gdbserial/gdbserver_windows.go
- pkg/proc/gdbserial/rr.go
- pkg/proc/native/proc_linux.go
```
proc/native,proc/gdbserial: ignore SIGTTIN, SIGTTOU when fg'ing target
If we send a process to foreground while the headless instance may get
a SIGTTOU/SIGTTIN, if not ignored this signal will stop the headless.
It's not clear why this only happens the second time we do this but
that's how it is.
Also removes the direct syscall to TIOCSPGRP and lets the go runtime do
it instead.
Fixes #1279
```
> proc/native,proc/gdbserial: ignore SIGTTIN, SIGTTOU when fg'ing target

- Documentation/installation/README.md
This updates the documentation for the Go version needed to compile Delve.
Fixes #1291
> Documentation update for install version

- pkg/proc/bininfo.go
- pkg/proc/proc_test.go
- pkg/proc/types.go
This patch makes it so inlined functions are returned in the
function
list, and also allows users to set breakpoints on the call site of
inlined functions.
Fixes #1261
> proc: Increase inline function support

- _fixtures/fncall.go
- _fixtures/testvariables2.go
- pkg/dwarf/godwarf/type.go
- pkg/proc/bininfo.go
- pkg/proc/eval.go
- pkg/proc/fncall.go
- pkg/proc/mem.go
- pkg/proc/test/support.go
- pkg/proc/types.go
- pkg/proc/variables.go
- service/test/integration2_test.go
- service/test/variables_test.go
```
proc: use (*Variable).setValue in fncall
proc: change (*Variable).setValue for use in CallFunction
Changes (*Variable).setValue so that it can be used in CallFunction to
set up the argument frame for the function call, adding the ability to:
- nil nillable types
- set strings to the empty string
- copy from one structure to another (including strings and slices)
- convert any interface type to interface{}
- convert pointer shaped types (map, chan, pointers, and structs
consisting of a single pointer field) to interface{}
This covers all cases where an assignment statement can be evaluated
without allocating memory or calling functions in the target process.
```
> Use setValue in CallFunction

- Documentation/cli/README.md
- _fixtures/fncall.go
- _fixtures/testvariables2.go
- pkg/proc/core/core.go
- pkg/proc/eval.go
- pkg/proc/fncall.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- pkg/proc/native/registers_darwin_amd64.go
- pkg/proc/native/registers_linux_amd64.go
- pkg/proc/native/registers_windows_amd64.go
- pkg/proc/threads.go
- pkg/proc/types.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- service/test/variables_test.go
```
terminal: updated call description
Updated call description to reflect current limitations.
proc: support calls through function pointers
proc: support calls to methods directly and through interface
proc: evaluate var.method expressions
Evaluates var.method expressions into a variable holding the
corresponding method with the receiver variable as a child, in
preparation for extending CallFunction so that it can call methods.
```
> Support calls of methods and function variables

- service/debugger/debugger_linux.go
```
debugger: make yama error more verbose
Explain why we are asking the user to write to a /proc file.
```
> debugger: make yama error more verbose

- _fixtures/fncall.go
- pkg/proc/bininfo.go
- pkg/proc/eval.go
- pkg/proc/types.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc: fix type of some struct global variables
Normally variables that have a named struct as a type will get a
typedef entry as their type, sometimes however the Go linker will
decide to use the DW_TAG_structure_type entry instead.
For consistency always wrap a struct type into a typedef when we are
creating a new variables (see comment in newVariable for exceptions).
This fixes a bug where it would be impossible to call methods on a
global variable.
```
> proc: fix type of some struct global variables

- .travis.yml
- pkg/proc/core/core.go
- pkg/proc/fncall.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- pkg/proc/native/proc_windows.go
- pkg/proc/native/registers_darwin_amd64.go
- pkg/proc/native/registers_linux_amd64.go
- pkg/proc/native/registers_windows_amd64.go
- pkg/proc/native/threads.go
- pkg/proc/native/threads_darwin.go
- pkg/proc/native/threads_linux.go
- pkg/proc/native/threads_windows.go
- pkg/proc/registers.go
- pkg/proc/test/support.go
- pkg/proc/threads.go
```
proc: replace SavedRegisters interface with a Copy method
Fncall.go was written with the assumption that the object returned by
proc.Thread.Registers does not change after we call
proc.Thread.SetPC/etc.
This is true for the native backend but not for gdbserial. I had
anticipated this problem and introduced the Save/SavedRegisters
mechanism during the first implementation of fncall.go but that's
insufficient.
Instead:
1. clarify that the object returned by proc.Thread.Registers could
change when the CPU registers are modified.
2. add a Copy method to Registers that returns a copy of the registers
that are guaranteed not to change when the CPU registers change.
3. remove the Save/SavedRegisters mechanism.
This solution leaves us the option, in the future, to cache the output
of …
```
> proc: replace SavedRegisters interface with a Copy method

- pkg/proc/stack.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- service/api/types.go
- service/debugger/debugger.go
- service/rpc2/server.go
```
proc,service,terminal: information about stack trace truncation
Add a flag to Stackframe that indicates where the stack frame is the
bottom-most frame of the stack. This allows clients to know whether the
stack trace terminated normally or if it was truncated because the
maximum depth was reached.
Add a truncation message to the 'stack' command.
```
> proc,service,terminal: information about stack trace truncation

- Documentation/cli/README.md
- pkg/terminal/command.go
```
terminal: refactor edit/list to share getLocation code
Refactors edit and list so that they use the same code to get the
current location and also both accept a locspec as an argument.
```
> terminal: refactor edit/list to share getLocation code

- Makefile
- cmd/dlv/dlv_test.go
- scripts/make.go
```
Makefile: replace makefile with a script
We were using our makefile not for the intended purpose of makefiles
but to multiplex a series of small scripts.
We can easily achieve the same result in a more reasonable programming
language and as a bonus we don't need to install a version of make on
windows anymore.
Additionally our test script had become fairly complicated and will
become even more complicated when testing of PIE buildmode is
introduced.
Fixes building when GOPATH isn't set.
Fixes #759
```
> Makefile: replace makefile with a script

- Documentation/api/ClientHowto.md
```
Documentation: mention that interfaces can also not be loaded
An interface with a children that has onlyAddr set to true was not
loaded due to the depth limit having been reached.
```
> Documentation: mention that interfaces can also not be loaded

- pkg/proc/proc.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- service/api/conversions.go
- service/api/types.go
```
proc: be more lenient with errors in GoroutinesInfo
Instead of failing on the first goroutine we can't read save the error
message and keep going.
Fixes a bug reported on the mailing list:
https://groups.google.com/d/msgid/delve-dev/3b3bfaa3-83d5-4676-b974-1fec40e5bf53%40googlegroups.com?utm_medium=email&utm_source=footer
```
> proc: be more lenient with errors in GoroutinesInfo

- pkg/proc/eval.go
- service/test/variables_test.go
```
proc: implement conversion of integers to string
Go allows converting a single integer value to string, resulting in a
string containing a single unicode rune with the same code as the value
of the integer.
Allow the same conversion to happen.
Fixes #1322
```
> proc: implement conversion of integers to string

- scripts/make.go
Correctly locates the installed executable path for darwin when GOBIN is not set. The current logic ignores the `bin` component of the install dir as well as adds a superfluous newline character to the output of `go env GOPATH`
Before:
```bash
05:52:24[/delve (master=)]$ make install
Password:
go install "-ldflags=-s -X main.Build=50419b61da7ef7be972ca7a3199c1f8a10a75a93" github.com/derekparker/delve/cmd/dlv
codesign -s dlv-cert /Users/kevincantwell/go
/dlv
/Users/kevincantwell/go
/dlv: No such file or directory
exit status 1
make: *** [install] Error 1
```
After:
```bash
06:22:10[/delve (master *=)]$ make install
go install "-ldflags=-s -X main.Build=50419b61da7ef7be972ca7a3199c1f8a10a75a93" github.com/derekparker/delve/cmd/dlv
2018/09/26 06:22:34 /Users/kevincantwell/go/bin/dlv
codesign …
```
> Fix scripts/make.go for darwin

- Documentation/cli/expr.md
- _fixtures/testvariables2.go
- pkg/proc/eval.go
- service/test/variables_test.go
```
proc: add iface.(data) syntax to access concrete value of an interface
With this syntax users do not need to type the concrete type of an
interface variable to access its contents. This also sidesteps the
problem where the serialization of a type by go/printer is different
from the one used for debug_info type names.
Updates #1328
```
> proc: add iface.(data) syntax to access concrete value of an interface

- Documentation/installation/osx/install.md
- pkg/proc/native/exc_user_darwin.c
- pkg/proc/native/exec_darwin.c
- pkg/proc/native/exec_darwin.h
- pkg/proc/native/mach_exc_user_darwin.c
- pkg/proc/native/nonative_darwin.go
- pkg/proc/native/proc_darwin.c
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_darwin.h
- pkg/proc/native/ptrace_darwin.go
- pkg/proc/native/registers_darwin_amd64.go
- pkg/proc/native/threads_darwin.c
- pkg/proc/native/threads_darwin.go
- pkg/proc/native/threads_darwin.h
- pkg/proc/proc_test.go
- pkg/proc/test/support.go
- pkg/terminal/command_test.go
- scripts/make.go
- service/test/integration2_test.go
```
On macOS 10.14 Apple changed the command line tools so that system
headers now need to be manually installed.
Instead of adding one extra install step to the install procedure add a
build tag to allow compilation of delve without the native backend on
macOS. By default (i.e. when using `go get`) this is how delve will be
compiled on macOS, the make script is changed to enable compiling the
native backend if the required dependencies have been installed.
Insure that both configuration still build correctly on Travis CI and
change the documentation to describe how to compile the native backend
and that it isn't normally needed.
Fixes #1359
```
> proc/native,Makefile: allow compiling on macOS without native backend

- cmd/dlv/cmds/commands.go
- service/listenerpipe.go
- service/rpc2/client.go
- service/test/integration2_test.go
```
cmd,service: in non-headless mode use an in-memory connection
Replace the socket connection with an in-memory connection (created by net.Pipe) for non-headless uses of delve.
This is faster and more secure.
Fixes #1332
```
> cmd,service: in non-headless mode use an in-memory connection

- cmd/dlv/cmds/commands.go
- service/server.go
Use the defination of `Server interface` in service package, instead of
temporary in func.
> cmd,service: remove temporary def of `Server interface` in func

- _fixtures/testvariables2.go
- pkg/proc/eval.go
- service/test/variables_test.go
Extend `string()`
1.convert byte/rune array(not only slice) to string.
2.convert string to string(itself), just like `string(str)` in go language.
> pkg/proc: extend conversion about `string` for array/str

- Documentation/cli/README.md
- _fixtures/fncall.go
- pkg/dwarf/godwarf/type.go
- pkg/proc/eval.go
- pkg/proc/fncall.go
- pkg/terminal/command.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc2/client.go
- service/test/integration2_test.go
- service/test/variables_test.go
```
proc: add flag to disable escape checking in function calls
Fix escape checking in function calls  and add a flag to disable it.
```
> proc: add flag to disable escape checking in function calls

- Documentation/cli/README.md
- _fixtures/deferstack.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/stack.go
- pkg/terminal/command.go
- service/api/types.go
- service/debugger/debugger.go
- service/test/common_test.go
- service/test/integration1_test.go
- service/test/integration2_test.go
```
proc,service,terminal: eval expressions in the scope of a deferred call
Add ability to evaluate variables on the scope of a deferred call's
argument frame.
```
> proc,service,terminal: eval expressions in the scope of a deferred call

- Documentation/cli/README.md
- _fixtures/issue1374.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/terminal/command.go
```
proc/gdbserial: backward continue should stop at start of process
ContinueOnce didn't detect the way RR signals that it has reached the
start of the process and would never finish.
Fixes #1376
proc: Continue should always work after CallFunction
Continue did not resume execution after a call to CallFunction if the
point where the process was stopped, before the call CallFunction, was
a breakpoint.
Fixes #1374
Documentation: rename "where" parameter of checkpoint to "note"
The name "where" may confuse users into thinking that this parameter
actually does something where in fact it's just arbitrary text used to
identify the checkpoint.
Fixes #1373
```
> Miscellaneous one-line bugfixes

- cmd/dlv/cmds/commands.go
Fix a bug where the regexp would be used as a package string
incorrectly. This would manifest when trying to execute the trace
subcommand as `dlv trace <regexp>` without specifying a package
identifier. The `<regexp>` would be passed to the Go build command
causing an error.
> cmd: Fix trace bug when no package specified

- Documentation/usage/dlv_trace.md
- cmd/dlv/cmds/commands.go
Adds an --exec flag for the trace subcommand allowing users to specify a
pre-compiled binary to exec and trace.
Also adds a --test flag as a convienance for compiling and tracing a
test binary.
Fixes #1073
Includes #1380 until it's merged then I will rebase.
> cmd: Add --exec and --test flags for trace sub cmd

- Documentation/installation/osx/install.md
- scripts/make.go
```
Documentation,Makefile: better error when gencert.sh fails
Fixes #1378
```
> Documentation,Makefile: better error when gencert.sh fails

- pkg/proc/native/proc_windows.go
Some libraries (for example steam_api64.dll) will send this exception
code to set the thread name on Microsoft VisualC.
In theory it should be fine to send the exception back to the target,
which is responsible for setting a handler for it, in practice in some
cases (steam_api64.dll) this will crash the program. So we'll mask it
instead.
Fixes #1383
> proc/native: Mask MS_VC_EXCEPTION [windows]

- cmd/dlv/cmds/commands.go
- pkg/proc/breakpoints.go
- pkg/proc/disasm_amd64.go
- pkg/proc/proc.go
- pkg/proc/threads.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- service/api/conversions.go
- service/api/types.go
- service/debugger/debugger.go
- service/rpc2/client.go
- service/rpc2/server.go
This patch allows the `trace` CLI subcommand to display return values of
a function. Additionally, it will also display information on where the
function exited, which could also be helpful in determining the path
taken during function execution.
Fixes #388 
(Note: There is still some work to be done to improve trace both as CLI subcommand and within a debug session. Most notably with the addition of the return value printing, we should visually show recursive function calls better to match call with return.)
> *: Show return values on CLI trace

- pkg/proc/core/core_test.go
- pkg/proc/fncall.go
- pkg/proc/moduledata.go
- pkg/proc/proc_test.go
- pkg/proc/stack.go
- pkg/proc/types.go
- pkg/proc/variables.go
- service/api/conversions.go
- service/debugger/locations.go
- service/rpc1/server.go
- service/test/variables_test.go
```
proc: Improve performance of loadMap on very large sparse maps
Users can create sparse maps in two ways, either by:
a) adding lots of entries to a map and then deleting most of them, or
b) using the make(mapType, N) expression with a very large N
When this happens reading the resulting map will be very slow
because loadMap needs to scan many buckets for each entry it finds.
Technically this is not a bug, the user just created a map that's
very sparse and therefore very slow to read. However it's very
annoying to have the debugger hang for several seconds when trying
to read the local variables just because one of them (which you
might not even be interested into) happens to be a very sparse map.
There is an easy mitigation to this problem: not reading any
additional buckets once we …
```
> proc: Improve performance of loadMap on very large sparse maps

- cmd/dlv/dlv_test.go
- pkg/proc/bininfo.go
- pkg/proc/breakpoints.go
- pkg/proc/core/core.go
- pkg/proc/core/core_test.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/interface.go
- pkg/proc/native/nonative_darwin.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/proc.go
This patch is a slight refactor to share more code used for generic
process initialization. There will always be OS/backend specific
initialization, but as much as can be shared should be to prevent
duplicating of any logic (setting internal breakpoints, loading bininfo,
etc).
> pkg/proc: Refactor process post initialization

- pkg/proc/core/core_test.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/variable_test.go
- pkg/terminal/command.go
- service/client.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/integration2_test.go
Instead of unconditionally returning all present goroutines,
GoroutinesInfo now allows specifying a range (start and count). In
addition to the array of goroutines and the error, it now also returns
the next goroutine to be processed, to be used as 'start' argument on
the next call, or 0 if all present goroutines have already been
processed.
This way clients can avoid eating large amounts of RAM while debugging
core dumps and processes with a exceptionally high amount of goroutines.
Fixes #1403
> proc/proc: Extend GoroutinesInfo to allow specifying a range

- pkg/proc/mem.go
- pkg/proc/variables.go
```
proc: do not panic if we can't satisfy a composite location
When a location expression requests a register check that we have as
many bytes in the register as requested and if we don't report the
error.
Updates #1416
```
> proc: do not panic if we can't satisfy a composite location

- _fixtures/cgostacktest/main.go
- pkg/proc/breakpoints.go
- pkg/proc/disasm_amd64.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/native/proc.go
- pkg/proc/proc_test.go
- pkg/proc/threads.go
- pkg/proc/types.go
- service/test/integration2_test.go
```
proc: correctly extract name of functions that have been inlined
If a function can be inlined it will appear as two entries in
debug_info. A DW_TAG_subprogram entry with DW_AT_inlined = true (that
will be used as the abstract origin) and a second DW_TAG_subprogram
entry with an abstract origin.
To retrieve the name of this second entry we must load its abstract
origin.
proc/*: allow stepping into functions without debug_info symbols
If proc.Step encounters a CALL instruction that points to an address
that isn't associated with any function it should still follow the
CALL.
The circumstances creating this problem do not normally occur, it was
encountered in the process of fixing a bug created by Go1.12.
tests: minor fixes for Go 1.12
proc: remove inversion of return variables from …
```
> Early Go 1.12 support

- pkg/dwarf/dwarfbuilder/info.go
- pkg/proc/dwarf_expr_test.go
- pkg/proc/variables.go
```
proc: do not panic if we can't satisfy a composite location for a slice var
The fix in 7f53117 for Issue #1416 had a bug, fix it and add a test.
Fixes #1419
```
> proc: do not panic if we can't satisfy a composite location for a slice var

- cmd/dlv/dlv_test.go
dlv_test.go:TestBuild() fails when dlv_test.go:projectRoot() fails to detect that this is a "gopath mode" when GOPATH contains several paths ex. "d:\\dir\\gopath;f:\\dir\\gopath2".
dlv version
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
go version
go version go1.11 windows/amd64
go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\z.malinovskiy\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\za\GO\gopath;f:\Zavla_VB\GO
set GOPROXY=
set GORACE=
set GOROOT=d:\za\GO\go
set GOTMPDIR=
set GOTOOLDIR=d:\za\GO\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-O -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set …
> main_test: Fix "gopath mode" detection in projectRoot()

- pkg/proc/bininfo.go
- pkg/proc/proc.go
```
pkg/proc: align memory size of tls arena to pointer sized boundary
The size of the TLS memory arena needs to be aligned to pointer sized
boundaries on 86x64 architectures, otherwise some programs using cgo
will not have the correct offset for the g struct.
No tests because reproducing this problem depends on behavior of the
GNU ld linker caused by unclear influences.
Fixes #1428.
proc: handle gid == 0 in FindGoroutine
Goroutine id == 0 is special (there can be many goroutines with id 0).
If the caller of FindGoroutine asks for gid==0 and current thread is
running a goroutine 0 (i.e. either no goroutine or a special
goroutine) return whatever goroutine is running on the current thread.
Updates #1428
```
> pkg/proc: align memory size of tls arena to pointer-sized boundary (fix for #1428)

- _fixtures/issue1432.go
- pkg/proc/proc_test.go
- pkg/proc/variables.go
When casting an integer into a struct pointer we make a fake pointer variable that doesn't have an address, maybeDereference and structMember should still work on this kind of Variable.
Fixes #1432
> proc: make structMember work on pointer Variables created through cast

- pkg/proc/test/support.go
Some build environments (such as when building RPMs) enjoy symlinking
things. This unfortunately causes our tests to fail as we record the
path of fixtures and use that when looking up file:line information.
However, the debug info in the binary records the original file
location, not the location of the symlink.
> pkg/proc/test: Eval symlinks for test source

- pkg/proc/proc.go
- pkg/proc/proc_test.go
- service/rpc2/server.go
```
service: make ListGoroutines return all running goroutines when
Start==0
Change ListGoroutines API call so that it tries to fit all running
goroutines in the ListGoroutines(Start=0) results.
Users are more likely to be interested in running goroutines, with this
change a frontend that just calls ListGoroutines(Start=0, Count=n) is
guaranteed to show all running goroutines to its users (as long as
there aren't more than n running goroutines).
proc: improve performance of FindGoroutine in normal circumstances
FindGoroutine can be slow when there are many goroutines running. This
can not be fixed in the general case, however:
1. Instead of getting the entire list of goroutines at once just get a
few at a time and return as soon as we find the one we want.
2. Since FindGoroutine is mostly …
```
> Improvements to ListGoroutines

- CHANGELOG.md
- pkg/version/version.go
```
all: Bump to v1.2.0
Add new version to CHANGELOG and update internal version.
Thank you @sbromberger @chainhelen, @dishmaev, @kevin-cantwell,
@Russtopia, @slp, @zavla, @the4thamigo-uk, @altimac and
@GregorioMartinez.
```
> Release Notes for 1.2.0

- pkg/proc/test/support.go
When compression is applied by default running the DWZ tool on the
resulting binary will crash.
The actual default compression code will look and see if compression
makes any difference and if so replace the normal `.debug_*` section
with `.zdebug_*`. This is why it may not have been hit before. On one of
my workstations I build with 1.12rc1 and no compression happens, but on
a Fedora VM I build and the binary results in compressed DWARF sections.
Adding this flag will make this test more consistent overall.
> pkg/proc: Disable default compression on DWZ test

- pkg/proc/bininfo.go
```
proc: better error message when we don't have debug_info
Do not mention external debug info files when the problem might just be
that the executable was stripped.
```
> proc: better error message when we don't have debug_info

- service/api/prettyprint.go
```
service/api: add quotes around types when needed in prettyprint.go
Type names need to be quoted when that expression is evaluated, by
printing them quoted the user can just copy and paste the output.
```
> service/api: add quotes around types when needed in prettyprint.go

- pkg/proc/arch.go
- pkg/proc/core/core_test.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- pkg/proc/linutil/regs.go
- pkg/proc/native/registers_darwin_amd64.go
- pkg/proc/registers.go
- pkg/proc/registers_amd64.go
- pkg/proc/winutil/regs.go
- pkg/terminal/command_test.go
- service/debugger/debugger.go
```
proc/gdbserial: do not return floating point regs when not requested
Fixes #1493
```
> proc/gdbserial: do not return floating point regs when not requested

- pkg/proc/bininfo.go
```
proc: do not crash if executable doesn't have a PT_TLS section
Fixes #1481
```
> proc: do not crash if executable doesn't have a PT_TLS section

- _fixtures/issue1469.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/threads.go
```
proc: workarounds for runtime.clone
runtime.clone (on some operating systems?) work similarly to fork:
when a thread calls runtime.clone a new thread is created. For a
short period of time both the parent thread and the child thread
appear to be running the same goroutine, until the child thread
adjusts its TLS to point to the correct goroutine.
This means that proc.GetG for a thread that's currently running
'runtime.clone' could be wrong and, consequently, the field
proc.(G).thread of a G struct returned by GoroutinesInfo could be
also wrong. And, finally, that FindGoroutine could sometimes return
a *G with a bad associated thread if the goroutine of interest
recently called 'runtime.clone'.
To work around this problem this commit makes two changes:
1. proc.GetG will return nil for …
```
> proc: workarounds for runtime.clone

- _fixtures/testdeadlock.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
```
proc: catch fatal runtime errors
Like we do with unrecovered panics, create a default breakpoint to
catch runtime errors that will cause the program to terminate.
Primarily intended to give users the opportunity to examine the state
of a deadlocked process.
```
> proc: catch fatal runtime errors

- Documentation/cli/README.md
- _fixtures/internal/pluginsupport/pluginsupport.go
- _fixtures/plugin1/plugin1.go
- _fixtures/plugin2/plugin2.go
- _fixtures/plugintest.go
- _fixtures/plugintest2.go
- pkg/proc/bininfo.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/linutil/dynamic.go
- pkg/proc/native/proc_linux.go
- pkg/proc/proc_test.go
- pkg/proc/test/support.go
- pkg/terminal/command.go
- service/api/conversions.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc2/client.go
- service/rpc2/server.go
```
proc,proc/native,proc/gdbserial: initial plugin support
Adds initial support for plugins, this is only the code needed to keep
track of loaded plugins on linux (both native and gdbserial backend).
It does not actually implement support for debugging plugins on linux.
Updates #865
```
> Plugin support (part 1)

- README.md
> doc/readme: Fix 'Github' spelling

- Documentation/api/ClientHowto.md
- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_core.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_replay.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_test.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- cmd/dlv/cmds/commands.go
- pkg/logflags/logflags.go
- pkg/proc/core/windows_amd64_minidump.go
- pkg/proc/fncall.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/proc_test.go
- service/debugger/debugger.go
- service/rpccommon/server.go
- service/test/integration2_test.go
```
cmd/dlv: add command line options to redirect logs
Adds two options, --log-to-file and --log-to-fd, to redirect logs to a
file or to a file descriptor.
When one of those two options is specified the "API server listening
at:" message will also be redirected to the specified file/file
descriptor.
This allows clients that want to use the "API server listening at:"
message to do so even if they want to redirect the target's stdout to
another file or device.
Implements #1179, #1523
logflags: replace default formatter of logrus
The default formatter of logrus emits logs in two different formats
depending on whether or not the output is going to a terminal. The
output format for non-terminals is indented to be machine readable, but
we mostly read logs ourselves and the excessive quoting …
```
> Miscellaneous logging improvements

- Documentation/cli/README.md
- pkg/proc/proc_test.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/integration2_test.go
```
proc,debugger,terminal: read goroutine ancestors
Add options to the stack command to read the goroutine ancestors.
Ancestor tracking was added to Go 1.12 with CL:
https://go-review.googlesource.com/c/go/+/70993/
Implements #1491
```
> proc,debugger,terminal: read goroutine ancestors

- service/api/conversions.go
- service/test/variables_test.go
```
service: decorate symbolic constant values with their numerical value
When we resolve a numerical value to a symbolic constant also report
the numerical value, for clarity.
Fixes #1516
```
> service: decorate symbolic constant values with their numerical value

- _fixtures/issue1531.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc: Update map reading code for Go 1.12
Go 1.12 introduced a change to the internal map representation where
empty map cells can be marked with a tophash value of 1 instead of just
0.
Fixes #1531
```
> proc: Update map reading code for Go 1.12

- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_core.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_replay.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_test.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- cmd/dlv/cmds/commands.go
- pkg/goversion/compat.go
- pkg/goversion/go_version.go
- service/config.go
- service/debugger/debugger.go
- service/rpccommon/server.go
- service/test/integration2_test.go
```
cmd/dlv: add Go version check
Before doing anything check that the version of Go is compatible with
the current version of Delve.
This will improve the error message in the case that  another change as
disruptive as Go1.11 dwarf compression, happens.
```
> cmd/dlv: add Go version check

- pkg/proc/proc_test.go
```
proc/test: fix flakyness of TestCallConcurrent
Remove the breakpoint set in TestCallConcurrent so that it doesn't
interfere with the call injection protocol.
The fact that it can is a bug but that bug is better addressed after
PRs #1503 and #1504 are merged, this keeps tests happy in the meantime.
Fixes #1542
```
> proc/test: fix flakyness of TestCallConcurrent

- pkg/dwarf/frame/entries.go
- pkg/dwarf/godwarf/type.go
- pkg/proc/arch.go
- pkg/proc/bininfo.go
- pkg/proc/dwarf_expr_test.go
- pkg/proc/fncall.go
- pkg/proc/moduledata.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/stack.go
- pkg/proc/threads.go
- pkg/proc/types.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- service/api/conversions.go
- service/api/types.go
- service/debugger/debugger.go
- service/test/variables_test.go
```
proc: support debugging plugins
This change splits the BinaryInfo object into a slice of Image objects
containing information about the base executable and each loaded shared
library (note: go plugins are shared libraries).
Delve backens are supposed to call BinaryInfo.AddImage whenever they
detect that a new shared library has been loaded.
Member fields of BinaryInfo that are used to speed up access to dwarf
(Functions, packageVars, consts, etc...) remain part of BinaryInfo and
are updated to reference the correct image object. This simplifies this
change.
This approach has a few shortcomings:
1. Multiple shared libraries can define functions or globals with the
same name and we have no way to disambiguate between them.
2. We don't have a way to handle library unloading.
Both of …
```
> Plugin support (part 2)

- pkg/proc/variables.go
```
proc: save location expr and decl line for escaped variables
Copy the location expression and declaration line of escaped variables
when auto-dereferencing them.
```
> proc: save location expr and decl line for escaped variables

- pkg/proc/bininfo.go
Just noticed it while looking through the DWARF parsing code.
> proc: trivial typo fix

- Documentation/EditorIntegration.md
The old URL pointed to the deprecated OSS plugin.  The new URL points to the official plugin, which uses the same code GoLand is based on.
> documentation: update idea plugin url

- _fixtures/fncall.go
- pkg/proc/fncall.go
- pkg/proc/interface.go
- pkg/proc/mem.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc: bugfix: closure addr was wrong for non-closure functions
proc: support nested function calls
Changes the code in fncall.go to support nested function calls.
This changes delays argument evaluation until after we have used
the call injection protocol to allocate an argument frame. When
evaluating the parse tree of an expression we'll initiate each
function call we find on the way down and then complete the function
call on the way up.
For example. in:
f(g(x))
we will:
1. initiate the call injection protocol for f(...)
2. progress it until the point where we have space for the arguments
of 'f' (i.e. when we receive the debugCallAXCompleteCall message
from the target runtime)
3. inititate the call injection protocol for g(...)
4. progress it until the point where we have space for …
```
> More Function Calls, parts 2

- pkg/proc/bininfo.go
- pkg/proc/types.go
```
proc: simplify partial unit support
Instead of reading partial units as we see them skip them entirely and
then re-read them when they are imported, directly into the destination
compile unit.
This avoids a lot of duplicate code in the loadDebugInfoMaps function
and will simplify implementing logical breakpoints and support for the
new DW_AT_go_package_name attribute added in Go 1.13.
```
> proc: simplify partial unit support

- Documentation/usage/dlv_debug.md
- cmd/dlv/cmds/commands.go
- cmd/dlv/dlv_test.go
Prevent conflicts by choosing a name that is extremely unlikely to
conflict with any actual package a user may have in their code.
Fixes #580
> cmd/dlv: Change name for binary dlv auto compiles

- pkg/proc/proc_test.go
- pkg/proc/variables.go
- service/debugger/debugger.go
```
proc: fix panic when calling Ancestors on a parked goroutine
Fixes #1568
```
> proc: fix panic when calling Ancestors on a parked goroutine

- service/rpccommon/server.go
- service/test/integration2_test.go
```
service: return an error when a client calls an unknown method
Without this a client calling an method on a version of Delve that
doesn't have that method (for example because it's old) will never get
a response back.
```
> service: return an error when a client calls an unknown method

- pkg/proc/types.go
```
proc: support childless compile units in loadDebugInfoMaps
Childless compile units would confuse loadDebugInfoMaps.
No test because I don't know what causes go to invoke GNU As in such a
way that it produces a childless compile unit.
Fixes #1572
```
> proc: support childless compile units in loadDebugInfoMaps

- _fixtures/testvariables2.go
- pkg/dwarf/godwarf/type.go
- service/test/variables_test.go
```
godwarf: fix nil pointer reading recursive types involving an array
Fixes #1578
```
> godwarf: fix nil pointer reading recursive types involving an array

- pkg/proc/linutil/regs.go
- pkg/proc/linutil/regs_test.go
The bitmasks for transforming a 64-bit register into it's lower-bit
counterparts (e.g. RAX -> EAX -> AX -> AH/AL) were incorrect. This patch
fixes the bitmasks and adds an additional test.
> proc/linutil: Fix register bitmasks

- _fixtures/fncall.go
- pkg/dwarf/reader/variables.go
- pkg/proc/eval.go
- pkg/proc/fncall.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc: support setting string values when it requires an allocation
Allow changing the value of a string variable to a new literal string,
which requires calling runtime.mallocgc to allocate the string into the
target process.
This means that a command like:
call f("some string")
is now supported.
Additionally the command:
call s = "some string"
is also supported.
Fixes #826
```
> proc: support setting string values when it requires an allocation

- pkg/dwarf/dwarfbuilder/info.go
- pkg/proc/bininfo.go
- pkg/proc/dwarf_expr_test.go
- pkg/proc/types.go
```
proc: add LocationCover method to BinaryInfo
Also fixes findCompileUnitForOffset which was broken in some edge cases
(when looking up an offset inside the last child of the compilation
unit) which don't happen in normal executables (we only look up types, and those
are always direct childs of compile units).
```
> proc: add LocationCover method to BinaryInfo

- Documentation/api/ClientHowto.md
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- service/debugger/debugger.go
- service/debugger/locations.go
- service/rpc2/server.go
- service/test/integration1_test.go
- service/test/integration2_test.go
- service/test/variables_test.go
```
proc,service: remove support for locspec '<fnname>:0'
The location specified '<fnname>:0' could be used to set a breakpoint
on the entry point of the function (as opposed to locspec '<fnname>'
which sets it after the prologue).
Setting a breakpoint on an entry point is almost never useful, the way
this feature was implemented could cause it to be used accidentally and
there are other ways to accomplish the same task (by setting a
breakpoint on the PC address directly).
```
> proc,service: remove support for locspec '<fnname>:0'

- pkg/dwarf/line/state_machine.go
- pkg/proc/bininfo.go
- pkg/proc/proc_test.go
Support for bulk queries makes the DWARF quality checker
run much more efficiently (replace quadratic cost with
linear). See https://github.com/dr2chase/dwarf-goodness .
> proc: added *BinaryInfo.AllPCsForFileLine for faster bulk queries

- pkg/proc/dwarf_expr_test.go
- pkg/proc/eval.go
- pkg/proc/fncall.go
- pkg/proc/interface.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc2/client.go
- service/test/integration2_test.go
- service/test/variables_test.go
```
proc: fix EvalExpressionWithCalls for constant expressions
The lack of address of constant expressions would confuse EvalExpressionWithCalls
Fixes #1577
proc: allow simultaneous call injection to multiple goroutines
Changes the call injection code so that we can have multiple call
injections going on at the same time as long as they happen on distinct
goroutines.
```
> proc: allow simultaneous call injection to multiple goroutines

- _fixtures/issue1601.go
- pkg/dwarf/godwarf/type.go
- pkg/proc/proc_test.go
```
godwarf: support recursive types involving C qualifiers and typedefs
Backports debug/dwarf commit: 535741a69a1300d1fe2800778b99c8a1b75d7fdd
CL: https://go-review.googlesource.com/18459
The x/debug/dwarf that we used for dwarf/godwarf/type.go was forked
from debug/dwarf long before this commit.
Original description:
Currently readType simultaneously constructs a type graph and resolves
the sizes of the types. However, these two operations are
fundamentally at odds: the order we parse a cyclic structure in may be
different than the order we need to resolve type sizes in. As a
result, it's possible that when readType attempts to resolve the size
of a typedef, it may dereference a nil Type field of another typedef
retrieved from the type cache that's only partially constructed.
To fix …
```
> godwarf: support recursive types involving C qualifiers and typedefs

- _fixtures/issue1615.go
- pkg/proc/eval.go
- pkg/proc/proc_test.go
- pkg/proc/variables.go
```
proc: increase maximum string length when loading string for binary ops
Increases the maximum string length from 64 to 1MB when loading strings
for a binary operator, also delays the loading until it's necessary.
This ensures that comparison between strings will always succeed in
reasonable situations.
Fixes #1615
```
> proc: increase maximum string length when loading string for binary ops

- pkg/proc/fncall.go
- pkg/proc/variables.go
- service/api/types.go
```
proc: flag variables that have a 'fake' address
Add variables flag to mark variables that are allocated on a register
(and have no address) and variables that we read as result of a
function call (and are allocated on a stack that no longer exists when
we show them to the user).
```
> proc: flag variables that have a 'fake' address

- go.mod
```
go.mod: add Go version to go.mod
Go 1.13 insists on adding a go version to go.mod, add one that makes
sense.
```
> go.mod: add Go version to go.mod

- pkg/proc/native/proc_linux.go
```
proc/native/linux: call postExit when process is killed by SIGINT
If we return ErrProcessExited we should also set exited to true.
```
> proc/native/linux: call postExit when process is killed by SIGINT

- pkg/terminal/terminal.go
- pkg/terminal/terminal_test.go
Fix #1617 by modifying the terminal to prompt the user to kill the remote headless instance if the remote process has exited.
```sh
$ dlv connect :59090
Type 'help' for list of commands.
(dlv) c
Process 36365 has exited with status 0
(dlv) exit
Remote process has exited. Would you like to kill the headless instance? [Y/n] y
```
There doesn't seem to be a clean way to determine whether `GetClient()` returned an error because `ErrProcessExited` on the remote or for some other reason.
> terminal: prompt to kill remote if process exited

- pkg/config/config.go
- pkg/terminal/command_test.go
- pkg/terminal/terminal.go
Add max-variable-recurse parameter for print depth of pointers, nested structs and etc 
See feature request from issue https://github.com/go-delve/delve/issues/1625
> add max-variable-recurse parameter

- pkg/dwarf/dwarfbuilder/info.go
- pkg/proc/dwarf_expr_test.go
- pkg/proc/types.go
```
proc: ignore DW_TAG_inlined_subroutine entries without abstract origin
GCC produces DW_TAG_inlined_subroutine entries without a
DW_AT_abstract_origin attribute.
From the bug report:
<1><1fe6c7c>: Abbrev Number: 41 (DW_TAG_subprogram)
<1fe6c7d>   DW_AT_external    : 1
<1fe6c7d>   DW_AT_name        : (indirect string, offset: 0x485814): MultiGetImpl
(omissis)
<2><1fe6c9e>: Abbrev Number: 65 (DW_TAG_inlined_subroutine)
<1fe6c9f>   DW_AT_low_pc      : 0x311023a
<1fe6ca7>   DW_AT_high_pc     : 0x5
<1fe6caf>   DW_AT_call_file   : 10
<1fe6cb0>   DW_AT_call_line   : 1690
<2><1fe6cb2>: Abbrev Number: 20 (DW_TAG_inlined_subroutine)
<1fe6cb3>   DW_AT_abstract_origin: <0x1ffb534>
<1fe6cb7>   DW_AT_entry_pc    : 0x311023f
<1fe6cbf>   DW_AT_ranges      : 0xe9bf20
<1fe6cc3>   DW_AT_call_file   : 10 …
```
> proc: ignore DW_TAG_inlined_subroutine entries without abstract origin

- Documentation/installation/osx/install.md
```
Documentation: mention DevToolsSecurity in documentation (macOS)
```
> Documentation: mention DevToolsSecurity in documentation (macOS)

- Documentation/cli/README.md
- pkg/terminal/command.go
- pkg/terminal/command_test.go
Add support for an optional [count] to the next command -- similar to gdb.
This fixes no outstanding issue, it just makes life a little easier for people familiar with gdb.
> terminal/command: add support for next [count]

- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_backend.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_core.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_log.md
- Documentation/usage/dlv_replay.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- cmd/dlv/cmds/commands.go
- cmd/dlv/dlv_test.go
- scripts/gen-cli-docs.go
- scripts/gen-usage-docs.go
```
Documentation,cmd/dlv: tidy up --help output
The description of --log-dest, --log-output and --backend is very
verbose and messes up the output of --help, move it to two "additional
help" subcommands.
scripts: use relative path in gen-cli-docs.go
Makes gen-cli-docs.go work outside GOPATH.
```
> Documentation,cmd/dlv: tidy up --help output

- _fixtures/cgosigsegvstack.go
- cmd/dlv/main.go
- pkg/proc/proc_test.go
- pkg/proc/stack.go
```
cmd/dlv: actually disable C compiler optimizations when building
proc: fix stacktraces when a SIGSEGV happens during a cgo call
When a SIGSEGV happens in a cgo call (for example as a result of
dereferencing a NULL pointer) the stack layout will look like this:
(system stack) runtime.fatalthrow
(system stack) runtime.throw
(system stack) runtime.sigpanic
(system stack) offending C function
... other C functions...
(system stack) runtime.asmcgocall
(goroutine stack) call inside cgo
The code in switchStack would switch directly from the
runtime.fatalthrow frame to the first frame in the goroutine stack,
hiding important information.
Disable this switch for runtime.fatalthrow and reintroduce the check
for runtime.mstart that existed before this version of the code was
implemented in …
```
> cmd/dlv: actually disable C compiler optimizations when building

- pkg/proc/arch.go
- pkg/proc/bininfo.go
- pkg/proc/dwarf_expr_test.go
- pkg/proc/stack.go
- pkg/proc/variables.go
This is part 1 in a series of upcoming small untangling refactors. I've been trying, unsuccessfully, to refactor to code base as it's in need of a lot of cleanup. The main goal I am trying to get to is that `proc` should more or less be stateless, and just provide low-level functionality for manipulating a process. The debugger layer should actually be taking on a lot more of the actual "business logic".
The problem that I ran into when trying to clean things up over the past few days is that *everything* within `pkg/proc` knows about *everything else* within `pkg/proc`. We pass around `BinaryInfo` and copy it everywhere, we pass in full structs (such as `BinaryInfo`, `G`, etc) when the function maybe only needs one member, which we can just pass explicitly.
Anyways, all that to say: I'm …
> pkg/proc: Refactor pkg/proc/arch.go

- _fixtures/issue1656/main.go
- _fixtures/issue1656/main.s
- pkg/proc/core/core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_freebsd.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/native/threads.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/threads.go
```
proc: next/step/stepout restarts thread from wrong instruction
proc.Next and proc.Step will call, after setting their temp
breakpoints, curthread.SetCurrentBreakpoint. This is intended to find
if one of the newly created breakpoints happens to be at the same
instruction that curthread is stopped at.
However SetCurrentBreakpoint is intended to be called after a Continue
and StepInstruction operation so it will also detect if curthread is
stopped one byte after a breakpoint.
If the instruction immediately preceeding the current instruction of
curthread happens to:
1. have one of the newly created temp breakpoints
2. be one byte long
SetCurrentBreakpoint will believe that we just hit that breakpoint and
therefore the instruction should be repeated, and thus rewind the PC of
curthread by …
```
> proc: next/step/stepout restarts thread from wrong instruction

- pkg/proc/bininfo.go
Intent here is to bring optargorder up to date with delve
and keep it in sync (and to use optargorder to help monitor
compiler output for debugging quality regressions).
> proc: add *Function.PrologueEndPC to support optargorder tool

- pkg/proc/core/core.go
Sets started to true on line 107 of core.go in the function ReadMemory. This ensures that "if a read goes into an unmapped region, it will be silently continued at the next mapping instead of failing or zero-filling" (https://github.com/go-delve/delve/issues/1071#issuecomment-518838215).
Fixes issue #1071
> Set started to true in core.go

- pkg/proc/gdbserial/gdbserver_conn.go
```
proc/gdbserial: reset thread updater in step loop
threadUpdater needs to be reset before every possible use.
Fixes #1659
```
> proc/gdbserial: reset thread updater in step loop

- pkg/proc/bininfo.go
```
proc: discard variables with address 0 in disassembly sym lookup
They are irrelevant and confusing.
```
> proc: discard variables with address 0 in disassembly sym lookup

- pkg/dwarf/frame/parser.go
- pkg/dwarf/frame/parser_test.go
According to the description of "CIE: length, CIE_id, version, augmentation"
in Page 122 of  http://dwarfstd.org/doc/Dwarf3.pdf ,
`augmentation` should exclude `version`
> pkg/dwarf/frame/parser: Fix `parse augmentation`

- Makefile
- scripts/make.go
This change adds the `make uninstall` command which will uninstall delve.
> scripts: Add 'make uninstall' command

- .travis.yml
- pkg/goversion/compat.go
```
travis: bump continuous integration to 1.13
Bump continuous integration to include Go 1.13, drop 1.10 from
compatiblity file.
```
> travis: bump continuous integration to 1.13

- Documentation/KnownBugs.md
- _fixtures/scopetest.go
- pkg/proc/eval.go
- pkg/proc/scope_test.go
- pkg/proc/variables.go
```
proc: correctly mark closure variables as shadowed
If a closure captures a variable but also defines a variable of the
same name in its root scope the shadowed flag would, sometimes, not be
appropriately applied to the captured variable.
This change:
1. sorts the variable list by depth *and* declaration line, so that
closure captured variables always appear before other root-scope
variables, regardless of the order used by the compiler
2. marks variable with the same name as shadowed even if there is only
one scope at play.
This fixes the problem but as a side effect:
1. programs compiled with Go prior to version 1.9 will have the
shadowed flag applied arbitrarily (previously the shadowed flag was not
applied at all)
2. programs compiled with Go prior to versoin 1.11 will still …
```
> proc: correctly mark closure variables as shadowed

- Documentation/cli/README.md
- Documentation/cli/starlark.md
- pkg/proc/core/core_test.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/stack.go
- pkg/proc/threads.go
- pkg/proc/variables.go
- pkg/terminal/command.go
- pkg/terminal/starbind/starlark_mapping.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/integration2_test.go
```
proc: add options to bypass smart stacktraces
Add options to start a stacktrace from the values saved in the
runtime.g struct as well as a way to disable the stackSwitch logic and
just get a normal stacktrace.
```
> proc: add options to bypass smart stacktraces

- _fixtures/fncall.go
- pkg/dwarf/godwarf/type.go
- pkg/proc/eval.go
- pkg/proc/fncall.go
- pkg/proc/proc_unexported_test.go
- service/test/variables_test.go
```
proc: allow calls to optimized functions
Trust argument order to determine argument frame layout when calling
functions, this allows calling optimized functions and removes the
special cases for runtime.mallocgc.
Fixes #1589
```
> proc: allow calls to optimized functions

- _fixtures/fncall.go
- pkg/proc/eval.go
- service/test/variables_test.go
`func (v *Variable) findMethod` should support for searching methods of an
embedded filed.
Fixes #1688
> pkg/proc: fix can not call method of an embedded filed directly

- Documentation/usage/dlv_backend.md
- Documentation/usage/dlv_log.md
- cmd/dlv/dlv_test.go
```
tests: fix TestGeneratedDoc
It was failing silently.
```
> tests: fix TestGeneratedDoc

- service/debugger/debugger.go
- service/test/integration2_test.go
```
service/debugger: make Disassemble work without a selected goroutine
The Disassemble API call should work when there is no selected
goroutine (for example because the program was just started).
Fixes #1703
```
> service/debugger: make Disassemble work without a selected goroutine

- pkg/proc/core/core.go
The origin error message is confusing, so add some details.
Fixes #1700   
-----   
I not sure whether the change is reasonable. So I will close this pr if disagree.   
-----   
This [ci](https://ci.appveyor.com/project/derekparker/delve-facy3/builds/27721539) failed, but it doesn't seem to have anything to do with my changes.
> pkg/proc/core: add error details when reading spliced memory

- pkg/dwarf/line/line_parser_test.go
- pkg/dwarf/line/state_machine.go
- pkg/dwarf/line/state_machine_test.go
```
dwarf/line: fix state machine behavior with multi-sequence units
A compile unit can produce a debug_line program consisting of multiple
sequences according to the DWARF standard. The standard guarantees that
addresses monotonically increment within a single sequence but
different sequences may not follow this rule.
This commit changes dwarf/line (in particular PCToLine and
AllPCsBetween) to support debug_line sections containing units with
multiple sequences.
TestPCToLine needs to be changed so that it picks valid addresses (i.e.
addresses covered by a sequence) as values for basePC, instead of just
rounding.
```
> dwarf/line: fix state machine behavior with multi-sequence units

- pkg/dwarf/line/state_machine.go
- pkg/proc/bininfo.go
```
proc: better handling of bad DW_TAG_inlined_subroutine without debug_line
Avoid crashing with nil pointer dereference, signal error instead.
Fixes #1720
```
> proc: better handling of bad DW_TAG_inlined_subroutine without debug_line

- pkg/proc/threads.go
```
proc: GetG should check that loc isn't nil before accessing its members
Updates #1711
```
> proc: GetG should check that loc isn't nil before accessing its members

- Documentation/cli/starlark.md
- _fixtures/testrerecord.go
- cmd/dlv/cmds/commands.go
- cmd/dlv/dlv_test.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/rr.go
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/proc_test.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/starbind/starlark_mapping.go
- service/client.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/integration2_test.go
- service/test/variables_test.go
```
*: add option to re-record recorded targets
Adds a '-r' option to the 'restart' command (and to the Restart API)
that re-records the target when using rr.
Also moves the code to delete the trace directory inside the gdbserial
package.
```
> *: add option to re-record recorded targets

- CHANGELOG.md
- pkg/version/version.go
Thanks to everyone who contributed!
The jump from 1.3.0 to 1.3.2 in the CHANGELOG might seem odd at first but due to a tagging error (mine - I blame it on trying to tag a release while taking care of my newborn son) but it's due to the fact that 1.3.1 was tagged in order to fix the incorrect version reporting on the 1.3.0 tag.
Jumping ahead in the changelog just ensure the tags and reported versions and changelog versions are all aligned once again.
> all: Bump to v1.3.2

- Documentation/cli/starlark.md
- pkg/proc/bininfo.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/starbind/starlark_mapping.go
- service/client.go
- service/debugger/debugger.go
- service/debugger/locations.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/common_test.go
- service/test/integration2_test.go
```
terminal: let 'list' work on file:line exprs that don't map to code
Make the 'list' command succeed for file:line expressions that don't
map to any instruction.
Adds an argument to the FindLocations API call that makes FindLocations
return if the expression can be parsed, even if it doesn't end up
matching any instruction in debug_line.
```
> terminal: let 'list' work on file:line exprs that don't map to code

- Documentation/cli/starlark.md
```
Documentation: add another starlark example script
This script re-runs a program until it fails or hits a breakpoint, it
is useful for debugging non-deterministic problems when used in
conjunction with rr.
```
> Documentation: add another starlark example script

- _fixtures/nopbreakpoint/main.go
- _fixtures/nopbreakpoint/main.s
- pkg/proc/native/threads.go
- pkg/proc/proc_test.go
```
proc: fix breakpoint confusion on resume
Fixes a case of breakpoint confusion on resume caused by having two
breakpoints one byte apart. This bug can cause the target program to
resume execution a single byte inside an instruction and crash either
with SIGILL or a SIGSEGV, or misbehave (depending on how the truncated
instruction is decoded).
native.(*Thread).StepInstruction should call FindBreakpoint using
adjustPC==false because at that point the PC of the thread should
already have been adjusted (and it has been).
```
> proc: fix breakpoint confusion on resume

- _fixtures/testvariables2.go
- pkg/proc/bininfo.go
- pkg/proc/eval.go
- pkg/proc/proc_test.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc: always resolve array types even if they don't appear in the
program
When evaluating type casts always resolve array types.
Instead of resolving them by looking up the string in debug_info
construct a fake array type so that a type cast to an array type always
works as long as the element type exists.
We already did this for byte arrays, this commit extends this to any
array type. The reason is that we return a fake array type (that
doesn't exist in the target program) for the array of a channel type.
Fixes #1736
```
> proc: always resolve array types even if they don't appear in the

- pkg/dwarf/line/state_machine.go
- pkg/proc/bininfo.go
- pkg/proc/breakpoints.go
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/types.go
- service/api/conversions.go
- service/api/types.go
- service/debugger/debugger.go
- service/debugger/locations.go
- service/test/variables_test.go
```
proc,debugger: implement logical breakpoints
Modifies FindFileLocation, FindFunctionLocation and LineToPC as well as
service/debugger to support inlining and introduces the concept of
logical breakpoints.
For inlined functions FindFileLocation, FindFunctionLocation and
LineToPC will now return one PC address for each inlining and one PC
for the concrete implementation of the function (if present).
A proc.Breakpoint will continue to represent a physical breakpoint, at
a single memory location.
Breakpoints returned by service/debugger, however, will represent
logical breakpoints and may be associated with multiple memory
locations and, therefore, multiple proc.Breakpoints.
The necessary logic is introduced in service/debugger so that a change
to a logical breakpoint will be mirrored to …
```
> proc,debugger: implement logical breakpoints

- pkg/terminal/command.go
- service/api/types.go
- service/debugger/debugger.go
- service/debugger/locations.go
- service/rpc2/server.go
```
service,terminal: support logical breakpoints
Changes CreateBreakpoint to create a logical breakpoint when multiple
addresses are specified, FindLocation and the api.Location type to
return logical locations and the cli to support logical breakpoints.
```
> service,terminal: support logical breakpoints

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- pkg/proc/proc_unix_test.go
```
gdbserial: propagate unhandled signals back to a specific thread
Instead of just sending unhandled signals back to the process send them
to the specific thread that received them.
This is important because:
1. debugserver does not appear to support the vCont;CXX packet without
specifying a target thread
2. the non-cooperative preemption change in an upcoming version of Go
(1.15?) will require sending signals to a specific thread.
Fixes #1744
```
> gdbserial: propagate unhandled signals back to a specific thread

- pkg/proc/native/proc_linux.go
- pkg/proc/native/threads_linux.go
- pkg/proc/proc_test.go
- scripts/make.go
```
proc/linux: do not route signals to threads while stopping
While we are trying to stop the process we should not route signals
sent to threads because that will result in threads being resumed.
Also keep better track of which threads are stopped.
This fixes an incompatibility with Go 1.14, which sends a lot of
signals to its threads to implement non-cooperative preemption,
resulting in Delve hanging waiting for an already-stopped thread to
stop.
In principle however this bug has nothing to do with Go 1.14 and could
manifest in any instance of high signal pressure.
```
> proc/linux: do not route signals to threads while stopping

- pkg/proc/core/core_test.go
- scripts/make.go
```
proc/core: enable PIE tests
PIE tests for core files were never enabled due to a missing flag.Parse
call.
Makefile: discard stderr of "go list"
In module mode "go" will print messages about downloading modules to
stderr, we shouldn't confuse them for the real command output.
```
> proc/core: enable PIE tests

- pkg/dwarf/loclist/loclist.go
- pkg/proc/bininfo.go
- pkg/proc/types.go
Move the loclist code out of proc and into its own package in
`pkg/dwarf`.
> pkg/proc,pkg/dwarf: Introduce loclist package

- service/rpccommon/sameuser.go
- service/rpccommon/sameuser_linux.go
- service/rpccommon/sameuser_linux_test.go
- service/rpccommon/server.go
This prevents other users on the same machine (e.g. a production server) from
using dlv under the credentials of another user, which poses a security issue.
> verify local connections originate from the same UID

- pkg/proc/bininfo.go
```
proc: make ignorable errors reading debug_info look less scary
We used to not do anything say anything at all about them anyway.
```
> proc: make ignorable errors reading debug_info look less scary

- _fixtures/internal/dir.io/dir.go
- _fixtures/pkgrenames.go
- pkg/dwarf/godwarf/type.go
- pkg/proc/bininfo.go
- pkg/proc/eval.go
- pkg/proc/moduledata.go
- service/debugger/locations.go
- service/test/integration2_test.go
- service/test/variables_test.go
```
proc: support DW_AT_go_package_name
Use the name specified by compile unit attribute DW_AT_go_package_name,
introduced in Go 1.13, to map package names to package paths, instead of
trying to deduce it from names of types.
Also use this mapping for resolving global variables and function
expressions.
```
> proc: support DW_AT_go_package_name

- pkg/proc/native/proc.go
the tracee may coredumped in detaching: trace/breakpoint trap (core dumped).
> native/proc: coredumped after detach (#1771)

- pkg/terminal/command_test.go
- pkg/terminal/terminal.go
During a debug session if the process exited and then the user quit the
debug session, the process exit message would display again and Delve
would exit non-zero (specifically with exit code 1) despite nothing
going wrong.
This patch fixes this so that Delve exits with a clean 0 status and the
process exit message is not printed yet again.
> pkg/terminal: Fix exit status

- .travis.yml
```
travis: exclude builds of Go other than most recent from ARM64 builds
```
> travis: exclude builds of Go other than most recent from ARM64 builds

- service/debugger/debugger.go
- service/test/integration2_test.go
```
debugger: fix nil pointer dereference in FunctionReturnLocations
Fixes #1787
```
> debugger: fix nil pointer dereference in FunctionReturnLocations

- .travis.yml
```
Revert "travis: exclude builds of Go other than most recent from ARM64 builds"
This reverts commit 35d168ac16527dcb19f8e8761ad7c5de24b56eca.
See: https://github.com/go-delve/delve/pull/1786#issuecomment-562160264
```
> Revert "travis: exclude builds of Go other than most recent from ARM64 builds"

- pkg/proc/proc_test.go
It seems that there is no GlobalVars be showed in disass on arm64. It's arm64/linux objdump feature.
> test: add reason for skipping TestDisassembleGlobalVars on arm64 (1778)

- pkg/proc/test/support.go
```
tests: disable function call injection tests on macOS on Travis-CI
Updates #1802
```
> tests: disable function call injection tests on macOS on Travis-CI

- pkg/proc/native/proc_linux.go
- service/debugger/debugger.go
```
proc/native: call ElfUpdateSharedObjects after Attach
When attaching to a process in linux ElfUpdateSharedObjects will be
called for the first time during the call to updateThreadList,
unfortunately it won't do anything because the dynamic section of the
base elf executable needs to have been read first and that's done when
we initialize the BinaryInfo object (which happens later during the
call to initialize).
debugger: fix off-by-one error in ListDynamicLibraries
```
> Misc plugin-related bugfixes

- _fixtures/issue1817.go
- pkg/dwarf/line/state_machine.go
- pkg/proc/proc_test.go
```
dwarf/line: make LineToPCIn behave like LineToPC for lines without stmt
When a line has instructions associated but none of them have is_stmt
set LineToPC and LineToPCIn should behave in the same way.
Fixes #1817
```
> dwarf/line: make LineToPCIn behave like LineToPC for lines without stmt

- Documentation/cli/starlark.md
- pkg/dwarf/line/state_machine.go
- pkg/proc/bininfo.go
- pkg/proc/proc_test.go
- pkg/terminal/starbind/starlark_mapping.go
- service/api/types.go
- service/debugger/debugger.go
- service/rpc2/server.go
```
proc,service: construct import path to directory path map
Adds an API call that returns a map from import paths to directory
paths that can be used by IDEs to map source file paths between
different development environments.
```
> proc,service: construct import path to directory path map

- _fixtures/issue1795.go
- pkg/dwarf/reader/reader.go
- pkg/proc/bininfo.go
- pkg/proc/proc_test.go
```
proc: fix inlined stack reading for midstack inlined calls
Due to a bug in the Go compiler midstack inlined calls do not report
their ranges correctly. We can't check if an address is in the range of
a DIE by simply looking at that DIE's range, we should also recursively
check the DIE's children's ranges.
Also fixes the way stacktraces of midstack inlined calls are reported
(they used to be inverted, with the deepest inlined stack frame
reported last).
Fixes #1795
```
> proc: fix inlined stack reading for midstack inlined calls

- pkg/proc/native/proc_windows.go
Specifically, make sure that both DebugActiveProcess and
WaitForDebugEvent Windows APIs are executed on the same thread.
Otherwise WaitForDebugEvent fails with ERROR_INVALID_HANDLE as per its
documentation
https://docs.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-waitfordebugevent
'... Only the thread that created the process being debugged can call
WaitForDebugEvent. ...'
Fixes #1825
> pkg/prog: Make sure Attach is executed on a single thread

- go.mod
We've dropped support for 1.11 in our CI runs, we should also update the
minimum require Go version in the mod file as well.
Resolves #1813
> *: Update go.mod version to 1.11

- service/test/integration2_test.go
Should judge `state.Err` instead of `err`.
> service/test: Fix a wrong judgment about err.

- pkg/proc/interface.go
- pkg/proc/proc.go
```
proc: cache mapping between goroutine ID and runtime.allgs index
Caches the mapping between a goroutine ID and its position inside the
runtime.allgs array, this allows speeding up FindGoroutine and makes
commands like 'goroutines -t' not be accidentally quadratic in the
number of goroutines.
```
> proc: cache mapping between goroutine ID and runtime.allgs index

- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/config.go
Expression such as:  
```
config show-location-expr  true
disassemble -a  0x4a23a0 0x4a23f2
disassemble -a 0x4a23a0  0x4a23f2 
```
should all execute correctly.
Extend #795. 
---- 
1. I take this pr beacause I meet one problem when working on #1810. 
Ex:
```
(dlv) config show-location-expr true
(dlv) config show-location-expr  true
```
The second type show nothing(no error), but set `show-location-expr` false actually which is not expected.
2. Then I test some similar cmd.
```
(dlv) disassemble -a  0x4a23a0 0x4a23f2
Command failed: wrong argument:  is not a number
```
or 
```
disassemble -a 0x4a23a0  0x4a2424
Command failed: wrong argument:  0x4a2424 is not a number
```
or
```
(dlv) locals  -v   a  
(get `  a` but expected `a`)
```
3. #795 maybe not solve that spurious spaces between …
> pkg/terminal: tolerate spurious spaces between arguments of cli.

- CONTRIBUTING.md
- README.md
Keep gitter chat link valid.
Fix #1842
> README: rollback gitter chat link.

- _fixtures/goroutineLabels.go
- pkg/proc/proc_test.go
- pkg/proc/variables.go
- service/api/conversions.go
- service/api/types.go
Labels can help in identifying a particular goroutine during debugging.
Fixes #1763
> proc,service: expose goroutine pprof labels in api

- pkg/proc/core/core.go
- pkg/proc/core/core_test.go
- pkg/proc/fncall.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/rr.go
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/goroutine_cache.go
- pkg/proc/interface.go
- pkg/proc/native/nonative_darwin.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_freebsd.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/native/threads.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/proc_unix_test.go
- pkg/proc/scope_test.go
- pkg/proc/target.go
- pkg/proc/threads.go
- pkg/proc/variable_test.go
- service/debugger/debugger.go
- service/test/variables_test.go
I've distilled a lot of the conversation that came about the large refactor I submitted and have found a path to perform a more measured refactor. This patch set serves as part 1 of that refactor.
Introduce a new type `proc.Target` which will build on top of the various backends to remove complexity and duplication. The first step is removing `proc.CommonProcess` and pushing all that functionality further up the stack to `proc.Target`.
> pkg/proc: Introduce Target and remove CommonProcess

- README.md
It seems the project in AppVeyor moved from go-delve to my AppVeyor account and I'm not sure how that happened. However, it did break the badge rendering on the README so this patch fixes it with the current correct link.
> *: Update AppVeyor badge

- pkg/proc/amd64_arch.go
Left is i386, and rigth is x86_64.  
Should be `Rflags` here on amd64 if I understand right.
> pkg: fix abbreviation of Flag Register on amd64

- _fixtures/issue1549.go
- pkg/dwarf/reader/reader.go
- pkg/proc/fbsdutil/regs.go
- pkg/proc/linutil/regs_amd64_arch.go
- pkg/proc/linutil/regs_arm64_arch.go
- pkg/proc/native/registers_darwin_amd64.go
- pkg/proc/proc_test.go
- pkg/proc/registers.go
- pkg/proc/winutil/regs.go
```
dwarf/reader: precalcStack does not need to read past the first entry
It was reading all the way to the end of the debug_info section,
slowing down stacktraces substantially.
BenchmarkConditionalBreakpoints-4   	       1	80344642562 ns/op
BenchmarkConditionalBreakpoints-4   	       1	22218288218 ns/op
i.e. a reduction of the cost of a breakpoint hit from 8ms to 2.2ms
Updates #1549
tests: add benchmark for conditional breakpoints
proc: remove CX method from proc.Registers
It is not used anymore besides internally by the proc/gdbserial
backend.
```
> Fix serious performance degradation when building stack traces

- Documentation/cli/expr.md
I updated the docs to add more information about element limit configuration options in the CLI. I came to the *expr* page reading about the element limit, but it was not apparent that I could change these limits.
> Documentation/cli: add info for element limit config keys

- cmd/dlv/dlv_test.go
- pkg/dwarf/line/line_parser.go
- pkg/dwarf/line/line_parser_test.go
- pkg/dwarf/line/state_machine_test.go
- pkg/goversion/compat.go
- pkg/proc/bininfo.go
- pkg/proc/core/core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- pkg/proc/gdbserial/rr.go
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_freebsd.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/native/threads_windows.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/target.go
- pkg/terminal/command_test.go
- scripts/make.go
- service/test/variables_test.go
```
goversion: update maximum supported version
tests: misc test fixes for go1.14
- math.go is now ambiguous due to changes to the go runtime so specify
that we mean our own math.go in _fixtures
- go list -m requires vendor-mode to be disabled so pass '-mod=' to it
in case user has GOFLAGS=-mod=vendor
- update version of go/packages, required to work with go 1.14 (and
executed go mod vendor)
```
> Go 1.14 support branch

- CHANGELOG.md
- pkg/version/version.go
```
all: bump version number and release notes
Thank you to: @stapelberg, @hengwu0, @tykcd996, @chainhelen,
@alexbrainman, @nd and @stigok.
```
> Delve 1.4.0 release notes

- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_backend.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_core.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_log.md
- Documentation/usage/dlv_replay.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_test.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- cmd/dlv/cmds/commands.go
- service/config.go
- service/rpccommon/sameuser_linux.go
- service/rpccommon/server.go
```
cmd: add flag to disable same-user check
Fixes #1835
service: also search IPv6 connections when checking user
When checking if the user is allowed to connect to this Delve instance
also search IPv6 connections even though the local address is IPv4.
Fixes #1835
```
> Fix same-user check and add flag to disable it

- CHANGELOG.md
I think that should've been 2020 ;)
> Update CHANGELOG.md - fix v1.4.0's date being 2019

- Documentation/cli/README.md
- pkg/terminal/docgen.go
Per the current `pkg/config/config.go`, the config and history files are not always at `$HOME/.config/dlv/`, so this just changes the docs to say so :pray:
> terminal/docgen: Specify all possible config locations

- pkg/proc/amd64_arch.go
- pkg/proc/arch.go
- pkg/proc/arm64_arch.go
- pkg/proc/core/core_test.go
- pkg/proc/fbsdutil/regs.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/linutil/regs_amd64_arch.go
- pkg/proc/linutil/regs_arm64_arch.go
- pkg/proc/native/registers_darwin_amd64.go
- pkg/proc/registers.go
- pkg/proc/winutil/regs.go
- service/api/conversions.go
- service/debugger/debugger.go
```
proc: only format registers value when it's necessary
A significant amount of time is spent generating the string
representation for the proc.Registers object of each thread, since this
field is rarely used (only when the Registers API is called) it should
be generated on demand.
Also by changing the internal representation of proc.Register to be
closer to that of op.DwarfRegister it will help us implement #1838
(when Delve will need to be able to display the registers of an
internal frame, which we currently represent using op.DwarfRegister
objects).
BenchmarkConditionalBreakpoints-4   	       1	22292554301 ns/op
BenchmarkConditionalBreakpoints-4   	       1	17326345671 ns/op
Reduces conditional breakpoint latency from 2.2ms to 1.7ms.
Updates #1549, …
```
> proc: only format registers value when it's necessary

- pkg/proc/amd64_arch.go
- pkg/proc/arm64_arch.go
- pkg/proc/stack.go
```
proc: do not load g0 until it's needed when stacktracing
The stacktrace code occasionally needs the value of g.m.g0.sched.sp to
switch stacks. Since this is only needed rarely and calling parseG is
relatively expensive we should delay doing it until we know it will be
needed.
BenchmarkConditionalBreakpoints-4              1        17326345671 ns/op
BenchmarkConditionalBreakpoints-4   	       1	15649407130 ns/op
Reduces conditional breakpoint latency from 1.7ms to 1.56ms.
Updates #1549
```
> proc: do not load g0 until it's needed when stacktracing

- Documentation/cli/README.md
- Documentation/cli/starlark.md
- _fixtures/examinememory.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/starbind/starlark_mapping.go
- service/api/prettyprint.go
- service/client.go
- service/debugger/debugger.go
- service/rpc2/client.go
- service/rpc2/server.go
According to #1800 #1584 #1038, `dlv` should enable the user to dive into
memory. User can print binary data in specific memory address range.
But not support for sepecific variable name or structures temporarily.(Because
I have no idea that modify `print` command.)  
Close #1584.
Next some questions: 
1. support the format for `print`cmd, include `address` , `variable name` and `structures`(no idea).  
2. support the form about `t(binary), f(float), a(address), i(instruction), c(char), s(string)` .  
3. support the negative position from address. (This is why also use `x /<FMT> [address]` like gdb, but not `x -<FMT> [address]`).  
----
I can close this pr if you against.
> pkg,service: add cmd `examinemem`(`x`) for examining memory.

- pkg/logflags/logflags.go
```
logflags: reduce default loglevel to Error
Logged errors should be visible even if the corresponding flag was not
selected.
```
> logflags: reduce default loglevel to Error

- Documentation/usage/dlv.md
- Documentation/usage/dlv_dap.md
- Documentation/usage/dlv_log.md
- _fixtures/helloworld.go
- cmd/dlv/cmds/commands.go
- go.mod
- go.sum
- pkg/logflags/logflags.go
- service/dap/daptest/client.go
- service/dap/error_ids.go
- service/dap/server.go
- service/dap/server_test.go
- vendor/github.com/google/go-dap/.travis.yml
- vendor/github.com/google/go-dap/LICENSE
- vendor/github.com/google/go-dap/README.md
- vendor/github.com/google/go-dap/codec.go
- vendor/github.com/google/go-dap/go.mod
- vendor/github.com/google/go-dap/io.go
- vendor/github.com/google/go-dap/schematypes.go
This change adds an initial synchronous implementation for running delve over DAP that supports a handful of requests (initialize, launch, set breakpoint, continue, disconnect). This min viable version is lacking support for many requests and other features (see comments in the code), but this should be enough to agree on the overall approach before diving into more details. (I do plan to add more tests to service_test and dlv_test in future PRs.)
Updates #1515
> service/dap: Initial implementation for 'dlv dap'

- pkg/proc/native/proc_linux.go
```
proc/native: optimize native.status through buffering
BenchmarkConditionalBreakpoints-4              1        15649407130 ns/op
BenchmarkConditionalBreakpoints-4   	       1	14586710018 ns/op
Conditional breakpoint evaluation 1.56ms -> 1.45ms
Updates #1549
```
> proc/native: optimize native.status through buffering

- pkg/proc/stack.go
- pkg/proc/threads.go
- pkg/proc/variables.go
```
proc: optimize parseG
runtime.g is a large and growing struct, we only need a few fields.
Instead of using loadValue to load the full contents of g, cache its
memory and then only load the fields we care about.
BenchmarkConditionalBreakpoints-4              1        14586710018 ns/op
BenchmarkConditionalBreakpoints-4   	       1	12476166303 ns/op
Conditional breakpoint evaluation: 1.45ms -> 1.24ms
Updates #1549
```
> proc: optimize parseG

- pkg/proc/core/core.go
- pkg/proc/core/linux_core.go
- pkg/proc/linutil/regs_arm64_arch.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/threads_linux_arm64.go
Implementing coredump functionality for ARM64 , now it can be checked by using "dlv core " command.
Floating point registers are not handled yet, working on it.
> proc/core: implementing coredump functionality for ARM64 

- pkg/proc/disasm.go
- service/test/integration2_test.go
Avoid panic if start addr is greater than end addr when disasm.
[`mem := make([]byte, int(endAddr-startAddr))`](https://github.com/go-delve/delve/blob/6c1571e8ab071e42f9b653430c3400c4d44151de/pkg/proc/disasm.go#L105-L113) panic.
> pkg/proc: Judge the validity of addr ranges when disasm.

- _fixtures/fncall.go
- pkg/proc/eval.go
- pkg/proc/fncall.go
- service/test/variables_test.go
Removes the restriction that the DWARF type for the receiver of a method
must be a TypeDef. This seems reasonable in theory, but in practice it turns out
Go DWARF does not consider
```
type X int
```
to be a typedef. This patch also allows for calling a method where the
receiver is not used or passed in, such as:
```
func (_ X) Method() { println("why") }
```
> pkg/proc: Allow function calls on non-struct types

- service/dap/daptest/client.go
- service/dap/server.go
- service/dap/server_test.go
- Move package doc comments so they are recognized as package doc.
- Use t.Helper when appropriate.
> service/dap: minor cosmetic changes

- scripts/make.go
macOS hasn't /usr/include/sys/types.h header with Canalina or later.
switch types.h path to CommandLineTools if kernel minor version up to 15 or later.
> scripts: support macOS 10.15 or later

- pkg/proc/threads.go
Avoid always showing `no G executing on thread 0` when ErrNoGoroutine on
g0 stack in GetG.
------
If hit [`mem.(Thread)` ](https://github.com/go-delve/delve/blob/master/pkg/proc/variables.go#L540) on g0 stack, the thread's id about error always is 0.
No testcase, I don't konw how to structure cases in normal scenario. I meet it when i do something on 386 linux.
But I think the thread's id should be showed if ErrNoGoroutine.
> pkg/proc: Fix ThreadId when ErrNoGoroutine on g0 stack in GetG

- pkg/proc/native/support_sentinel.go
```
proc/native: better error message when building on unsupported systems
As we rearrange the code and the Go compiler changes the error message
returned by the compiler on unsupported architectures will change too,
making it un-googlable. Since the error message tends to be rather
obscure too this regularly confuses newbies.
This is an effort to make the error message for unsupported GOOS/GOARCH
combinations the same across all unsupported combinations and to make
it more user friendly.
Directories containing Go source code are supposed to contain a single
package. This property happens to be checked by cmd/go itself so it
will happen even before the syntax is fully checked and therefore has a
high probability of being the first (and only) error message being
print.
Here we take …
```
> proc/native: better error message when building on unsupported systems

- Documentation/cli/starlark.md
- pkg/proc/amd64_arch.go
- pkg/proc/arch.go
- pkg/proc/arm64_arch.go
- pkg/proc/core/core_test.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/starbind/starlark_mapping.go
- service/api/conversions.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/integration2_test.go
```
proc,service: allow printing registers for arbitrary frames
Adds an optional scope prefix to the `regs` command which allows
printing registers for any stack frame (as long as they were somehow
saved). Issue #1838 is not yet to be closed since we are still not
recovering the registers of a segfaulting frame.
Updates #1838
```
> proc,service: allow printing registers for arbitrary frames

- service/debugger/debugger.go
- service/test/integration2_test.go
```
debugger: CreateBreakpoint should delete existing breakpoints
Fixes a bug introduced by the logical breakpoint change, where creating
the same breakpoint twice deletes the breakpoint.
```
> debugger: CreateBreakpoint should delete existing breakpoints

- service/dap/daptest/client.go
- service/dap/server.go
- service/dap/server_test.go
Using a stop channel to signal clean shutdown to the server's goroutines. Also updates the tests to trigger `disconnectChan`.
This helps avoid spurious error logs when the client disconnects, when Ctrl+C is pressed, etc.
Updates #1515
> service/dap: clean shutdown sequence in server

- Documentation/cli/README.md
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- service/api/prettyprint.go
- service/api/prettyprint_test.go
1. Don't use intelligent '#' in fmt of go because it is not always satisfying
for diffrent version of golang. Always keep one leading zero for octal and
one leading '0x' for hex manually. Then keep alignment for every byte.
2. Always keep addr alignment when the lens of two adjacent address are
different.
Update #1814.  
---- 
Sorry for the diplay detail  about 'x'. #1814
When I use x command to try to implemnt 386 linux, I find something not friendly to user.  
1.
```
Before optimization:
(dlv) x -len 20 -fmt hex 0x4abd6d
0x4abd6d:    0xcc    0x8d    0x5     0xb1    0x96    0x3     0x0     0x48
0x4abd75:    0x89    0x4     0x24    0x48    0xc7    0x44    0x24    0x8 
0x4abd7d:    0xc     0x0     0x0     0x0 
After optimization:
(dlv) x -len 20 -fmt hex 0x4abd6d
0x4abd6d:   0xcc   0x8d …
```
> pkg,service: Optimized the display of `examinemem` command.

- pkg/proc/native/ptrace_linux.go
- pkg/proc/native/threads_linux.go
This change adds `ProcessVmRead` and `ProcessVmWrite` wrappers around
the syscalls `process_vm_readv` and `process_vm_writev`, available since
Linux 3.2. These follow the same permission model as `ptrace`, but they
don't actually require being attached, which means they can be called
directly from any thread in the debugger. They also use `iovec` to write
entire blocks at once, rather than having to peek/poke each `uintptr`.
These wrappers are used in `Thread.ReadMemory` and `WriteMemory`, still
falling back to `ptrace` if that fails for any reason.  Notably,
`process_vm_writev` respects memory protection, so it can't modify
read-only memory like `ptrace`. This frequently occurs when writing
breakpoints in read-only `.text`, so to avoid a lot of wasted `EFAULT`
calls, we only try …
> proc/native/linux: try to use process_vm_readv/writev

- .travis.yml
This also removes Go 1.11 from the test matrix.
Now that 1.14 has been released, as always it should be included in the
test matrix.
> *: Add Go 1.14 to test matrix

- service/api/prettyprint.go
- service/api/prettyprint_test.go
Use strings.Builder and tabwriter to format the output of the examine
memory command instead of doing direct string manipulation and
allocating.
> service/api: Refactor examine memory pretty printer

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/native/proc_windows.go
- pkg/proc/proc.go
```
proc/gdbserial: disable async preemption on macOS
Disables async preemption on macOS
Fixes #1905
```
> proc/gdbserial: disable async preemption on macOS

- _fixtures/buildtest/main_test.go
- cmd/dlv/cmds/commands.go
- pkg/gobuild/gobuild.go
- service/dap/daptest/client.go
- service/dap/server.go
- service/dap/server_test.go
This change also:
-- refactors building helper functions from commands.go into its own gobuild package.
-- makes processing untyped launch args (that are implementation-specific and not part of the DAP spec) more robust, verified by additional tests
> service/dap: Add support for debug and test modes

- Documentation/cli/README.md
- pkg/terminal/command.go
- pkg/terminal/docgen.go
- pkg/terminal/groups.go
```
terminal: divide commands into categories
There are too many commands, for clarity they should be divided into
categories when printing and generating documentation.
```
> terminal: divide commands into categories

- pkg/proc/native/proc_linux.go
- pkg/proc/native/threads_linux.go
```
proc/native/linux: do not call (*Thread).Stopped inside (*Process).stop
(*Thread).Stopped is slow because it needs to open, read and parse a
file in /proc, we don't actually need to do that, we can just rely on
the value of Thread.os.running.
BenchmarkConditionalBreakpoints-4              1        12476166303 ns/op
BenchmarkConditionalBreakpoints-4   	       1	10403533675 ns/op
Conditional breakpoint evaluation: 1.24ms -> 1ms
Updates #1549
proc/native/linux: only set breakpoints on threads that receive SIGTRAP
```
> Better native.Process.stop performance for linux backend

- pkg/proc/core/core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/rr.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_freebsd.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/proc.go
- pkg/proc/target.go
- pkg/proc/threads.go
```
proc,proc/*: add StopReason field to Target
Adds a StopReason field to the Target object describing why the target
process is currently stopped. This will be useful for the DAP server
(which needs to report this reason in one of its requests) as well as
making pull request #1785 (reverse step) conformant to the new
architecture.
proc,proc/*: move SelectedGoroutine to proc.Target, remove PostInitializationSetup
moves SelectedGoroutine, SwitchThread and SwitchGoroutine to
proc.Target, merges PostInitializationSetup with NewTarget.
```
> proc,proc/*: add StopReason field to Target

- service/dap/daptest/client.go
- service/dap/error_ids.go
- service/dap/server.go
- service/dap/server_test.go
With this change, VS Code no longer gets stuck when paired with the new dlv-dap server and can use it to run simple debug session sequences with stop/continue on entry, set breakpoint, continue, and disconnect (although additional features are still needed for full integration with the UI).
This change also:
-- Updates the test client and unittest to start seq numbers from 1 to match VS Code
-- Expands TestStopOnEntry to cover the complete sequence of messages observed with VS Code with this most basic debug session scenario. Adds matching TestContinueOnEntry test.
-- Fixes TestSetBreakpoint not to send a redundant continue request.
-- Adds tests for when the threads request are issued during launch, mid-session and after termination.
> service/dap: Add support for threads request

- pkg/proc/target.go
- pkg/proc/threads.go
```
proc: cache result of GetG
BenchmarkConditionalBreakpoints-4   	       1	7031242832 ns/op
BenchmarkConditionalBreakpoints-4   	       1	5282482841 ns/op
Conditional breakpoint evaluation latency: 0.70ms -> 0.52ms
Updates #1549
```
> proc: cache result of GetG

- Documentation/cli/README.md
- pkg/terminal/command.go
Update: #1879
-----  
ps: 
In fact, I think the prompt of `goroutines` cmd maybe too long. 
How about this? 
```
goroutines [-u (default)| -r | -g | -s ](optional location) [-t (stack trace)] [-l (labels)]
``` 
the whole help info :
```
List program goroutines.
goroutines [-u (default)| -r | -g | -s ](optional location) [-t (stack trace)] [-l (labels)]
Print out info for every goroutine. The flag controls what information is shown along with each goroutine:
-u  displays location of topmost stackframe in user code
-r  displays location of topmost stackframe (including frames inside private runtime functions)
-g  displays location of go instruction that created the goroutine
-s  displays location of the start function
-t  displays goroutine's stacktrace
-l  displays goroutine's labels
If no …
```
> terminal: add `-l` prompt on goroutines help

- Documentation/KnownBugs.md
- Documentation/cli/README.md
- cmd/dlv/dlv_test.go
- pkg/proc/breakpoints.go
- pkg/proc/core/core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/rr_test.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/threads.go
- pkg/terminal/command.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc2/client.go
```
service,terminal: implement reverse step, next, stepout
proc: implement reverse step/next/stepout
When the direction of execution is reversed (on a recording) Step, Next and
StepOut will behave similarly to their forward version. However there are
some subtle interactions between their behavior, prologue skipping, deferred
calls and normal calls. Specifically:
- when stepping backwards we need to set a breakpoint on the first
instruction after each CALL instruction, once this breakpoint is reached we
need to execute a single StepInstruction operation to reverse step into the
CALL.
- to insure that the prologue is skipped reverse next needs to check if it
is on the first instruction after the prologue, and if it is behave like
reverse stepout.
- there is no reason to set breakpoints on …
```
> Implement reverse step, next and stepout

- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/terminal.go
```
terminal: preserve arguments and prefixes when repeating last command
```
> terminal: preserve arguments and prefixes when repeating last command

- .cirrus.yml
- .travis.yml
1. 32bit docker on cicurs CI
https://github.com/go-delve/delve/runs/501900175
https://github.com/go-delve/delve/runs/501900189
https://github.com/go-delve/delve/runs/498813610
https://github.com/go-delve/delve/runs/498813609
https://github.com/go-delve/delve/runs/498813615
...
This 32bit docker on cirrus CI  failed frequency. The erros all have similar memory problems.  
Then I do 
```for ((i=1; i<=300; i++)); do go test -v -test.run TestStepConcurrentDirect ; done```
on cirrus CI, see the error every CI period. 
(150 loops is enough in fact)
2. Never reproduct on my local env.
A. 386/centos  go1.12.8/go1.13.6/go1.14
B. 386 docker on 64-bit ubunut (kernel 5.3) go1.12.8/go1.13.6/go1.14
3. amd64 on cicurs CI
Then I try test amd64 on cicurs CI and find same problem as 386. 
Also use 
```for …
```
> *: Transfer 32-bit test into travis from cirrus

- .deepsource.toml
Adds a config for https://deepsource.io to enable some static analysis CI on this repo.
> *: Add DeepSource CI config

- pkg/proc/eval.go
- service/test/variables_test.go
If we call one expression which is the fake method of meanless
string, `delve` will panic. Strengthen the inspection of boundary
conditions when supporting function calls on non-struct types.
Update: #1871  
-----   
Eg: 
```
package main
import (
"fmt"
)
func main() {
fmt.Printf("hello world\n")  // set breakpoint
}
```
```
(dlv) call "delve".callme()
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6f614f]
goroutine 51 [running]:
github.com/go-delve/delve/pkg/proc.(*Variable).findMethod(0xc0001945a0, 0xc000362548, 0x6, 0xc0001945a0, 0x0, 0x0)
/media/chainhelen/LENOVO/xlworkspace/code/go/src/github.com/go-delve/delve/pkg/proc/eval.go:1829 +0x16f …
```
> pkg/proc: Prevent program crash when called meanless expression

- .travis.yml
- pkg/goversion/compat.go
- scripts/gen-travis.go
```
travis-ci: autogenerate .travis.yml
Autogenerates .travis.yml configuration using the contents of
pkg/goversion/compat.go.
Also:
- excludes testing of windows/amd64/tip and linux/arm64/tip (Travis-CI
can't get Go at tip for those combinations).
- Removes Go 1.11 from pkg/goversion/compat.go which we don't test
anymore.
```
> travis-ci: autogenerate .travis.yml

- Documentation/cli/README.md
- pkg/terminal/command.go
- pkg/terminal/terminal.go
```
terminal: add display command
Implements #1256
terminal: divide commands into categories
There are too many commands, for clarity they should be divided into
categories when printing and generating documentation.
```
> terminal: add display command

- pkg/proc/proc.go
- pkg/proc/proc_test.go
- pkg/proc/test/support.go
```
proc: fix bad cached goroutines after a call injection
Inserts a call to ClearAllGCache into stepInstructionOut so that cached
goroutine state is not inconsistent after an injected function call.\
Fixes #1925
```
> proc: fix bad cached goroutines after a call injection

- pkg/proc/gdbserial/gdbserver.go
```
proc/gdbserial: add logging when Thread.Location will fail
Add logging for Issue #1927. The bug happens during the call to
api.ConvertThread, returning an error will not suffice since
ConvertThread will not surface it.
Updates #1927
```
> proc/gdbserial: add logging when Thread.Location will fail

- go.mod
- go.sum
- pkg/dwarf/godwarf/tree.go
- pkg/dwarf/godwarf/tree_test.go
- pkg/dwarf/reader/reader.go
- pkg/dwarf/reader/variables.go
- pkg/proc/bininfo.go
- pkg/proc/eval.go
- pkg/proc/fncall.go
- pkg/proc/stack.go
- pkg/proc/threads.go
- pkg/proc/variables.go
- vendor/github.com/hashicorp/golang-lru/LICENSE
- vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
- vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
```
proc,dwarf: cache debug.Entry objects
Instead of rescanning debug_info every time we want to read a function
(either to find inlined calls or its variables) cache the tree of
dwarf.Entry that we would generate and use that.
BenchmarkConditionalBreakpoints-4   	       1	5164689165 ns/op
BenchmarkConditionalBreakpoints-4   	       1	4817425836 ns/op
Updates #1549
```
> proc,dwarf: cache debug.Entry objects

- pkg/proc/stack.go
```
proc: fix switch to goroutine stack
When switching to the goroutine stack the stack iterator registers
might not have any entry for the BP register, make sure to add it
instead of just trying to change it.
```
> proc: fix switch to goroutine stack

- .travis.yml
- scripts/gen-travis.go
This makes it so that CI will still work on forks, if necessary.
> travis.yml: Add go_import_path

- pkg/proc/proc_test.go
Reset the timer once we start executing the code paths we actually care
to measure, since the setup and continue steps can be relatively
expensive.
Also, disable recording on benchmarks. This seems less useful, and also
cuts out a lot of noise when benchmarks are run.
> pkg/proc: Reset time after continue in benchmarks

- Documentation/cli/README.md
- pkg/proc/gdbserial/rr.go
- pkg/terminal/command.go
- pkg/terminal/terminal.go
- scripts/gen-starlark-bindings.go
- service/api/types.go
- service/client.go
- service/debugger/debugger.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/rpccommon/server.go
- service/test/integration1_test.go
- service/test/integration2_test.go
```
proc/gdbserial,debugger: allow clients to stop a recording
Allows Delve clients to stop a recording midway by sending a Command('halt')
request.
This is implemented by changing debugger.New to start recording the process
on a separate goroutine while holding the processMutex locked. By locking
the processMutex we ensure that almost all RPC requests will block until the
recording is done, since we can not respond correctly to any of them.
API calls that do not require manipulating or examining the target process,
such as "IsMulticlient", "SetApiVersion" and "GetState(nowait=true)" will
work while we are recording the process.
Two other internal changes are made to the API: both GetState and Restart
become asynchronous requests, like Command. Restart because this way it can
be …
```
> proc/gdbserial,debugger: allow clients to stop a recording

- pkg/proc/amd64_arch.go
- pkg/proc/amd64_disasm.go
- pkg/proc/arch.go
- pkg/proc/arm64_arch.go
- pkg/proc/arm64_disasm.go
- pkg/proc/bininfo.go
- pkg/proc/core/core.go
- pkg/proc/core/core_test.go
- pkg/proc/disasm.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/i386_arch.go
- pkg/proc/i386_disasm.go
- pkg/proc/native/threads.go
- pkg/proc/stack.go
- pkg/proc/target.go
- pkg/proc/target_exec.go
- pkg/proc/threads.go
- pkg/proc/types.go
- pkg/proc/variables.go
- service/api/conversions.go
```
proc: convert Arch into a struct
Replace the interface type Arch with a struct with the same
functionality.
```
> proc: convert Arch into a struct

- pkg/proc/bininfo.go
- pkg/proc/eval.go
- pkg/proc/variables.go
- service/api/conversions.go
```
proc: avoid constructing unnecessary strings when evaluating variables
Avoids constructing:
1. name of runtime.curg fields while executing parseG
2. the location expression while evaluating any variable.
BenchmarkConditionalBreakpoints-4   	       1	4953889884 ns/op
BenchmarkConditionalBreakpoints-4   	       1	4419775128 ns/op
Updates #1549
```
> proc: avoid constructing unnecessary strings when evaluating variables

- cmd/dlv/cmds/commands.go
No reason for them to be public and exported.
> cmd/dlv: Unexport flag variables

- service/dap/server.go
- service/dap/server_test.go
Existing code matched [vscode-go](https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L824), setting reason to 'breakpoint', but that's misleading and according to the [spec](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Stopped), there is a special option for entry. Use that option. This impacts what is displayed in the UI ('paused on breakpoint' vs 'paused on entry').
> service/dap: Change event reason to "entry" when stopping on entry

- service/debugger/debugger.go
- service/test/integration2_test.go
```
debugger: ClearBreakpoint should clear a logical breakpoint
Clear all physical breakpoints associated with a logical breakpoint in
ClearBreakpoint.
Fixes #1955
```
> debugger: ClearBreakpoint should clear a logical breakpoint

- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_freebsd.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
- pkg/proc/proc_test.go
- pkg/proc/target.go
- service/api/types.go
- service/debugger/debugger.go
- service/debugger/debugger_test.go
- service/debugger/debugger_unix.go
- service/debugger/debugger_unix_test.go
- service/debugger/debugger_windows.go
This improves the overall error message when trying to run an executable of an invalid binary format for the host system. Also consolidates some basic sanity checks (is this file an executable?).
Before:
(MacOS):
```
could not launch process: stub exited while waiting for connection: exit status 0
```
(Linux):
```
could not launch process: fork/exec /home/deparker/code/rr-test/__debug_bin: exec format error
```
After:
```
could not launch process: could not launch executable /Users/derekparker/code/delve-test-progs/interface-test/__debug_bin: invalid executable binary format
```
Fixes #1310
> *: Better error launching invalid binary format

- Documentation/installation/osx/install.md
- service/debugger/debugger.go
Two minor spelling fixes to use the correct casing for "Xcode"
> Use proper spelling of Xcode

- Documentation/installation/freebsd/install.md
- Documentation/installation/linux/install.md
- Documentation/installation/osx/install.md
- Documentation/installation/windows/install.md
```
Documentation: add modules mode note to install documentation
1. Adds a note to the documentation describing how to use 'go get' in
modules mode
2. Removes the '-u' option which, when 'go get' is used incorrectly
will make 'go' try to compile Delve with unsupported dependencies
3. Removed obsolete note about Go 1.5 vendor experiment.
Fixes #1988
```
> Documentation: add modules mode note to install documentation

- Documentation/usage/dlv_attach.md
- cmd/dlv/cmds/commands.go
The `--continue` flag is being used downstream by the `attach` command however it's improperly blocked by the flag validation code. I decorated the `attachCommand` variable with the `--continue` reference, so this combination will be recognized as valid.
Fixes #1995
> cmds/commands: Add --continue flag to attach

- pkg/proc/bininfo.go
In my opinion, we should not return error directly which set `fileFound` to be true
if `lineInfo` of one `compileUnits` is nil.
> proc: do not set fileFound if there's a compileUnit without line section.

- .travis.yml
- cmd/dlv/cmds/commands.go
- pkg/terminal/command_test.go
- service/config.go
- service/dap/server.go
- service/dap/server_test.go
- service/debugger/debugger.go
- service/debugger/debugger_unix_test.go
- service/rpc1/server.go
- service/rpc2/server.go
- service/rpccommon/server.go
- service/test/integration1_test.go
- service/test/integration2_test.go
Embed the debugger config object in the service config object to avoid needless duplication of fields.
> *: Consolidate service/debugger config

- pkg/proc/proc_test.go
- pkg/proc/test/support.go
```
tests: properly check if cgo is enabled for cgo related tests
```
> tests: properly check if cgo is enabled for cgo related tests

- _scripts/make.go
```
Makefile: reduce test timeout when TRAVIS==true
Reduces test timeout by one minute so that Go will timeout before
Travis-CI and report useful informations about the hang.
```
> Makefile: reduce test timeout when TRAVIS==true

- pkg/proc/native/proc_linux.go
```
proc/native: report trapWaitInternal errors in nativeProcess.stop
The process could quit while we are inside stop, we should report the
error otherwise the following code will try to send on the closed
ptrace channel.
Fixes a sporadic error in TestIssue1101.
```
> proc/native: report trapWaitInternal errors in nativeProcess.stop

- pkg/proc/proc_test.go
```
scripts/make: do not test buildmode=pie on linux/386
The tests have a tendency to hang, see for example:
https://travis-ci.com/github/go-delve/delve/jobs/301890354
```
> proc/tests: disable TestIssue414 on linux/386/pie

- pkg/config/config.go
- pkg/terminal/command.go
- pkg/terminal/config.go
- service/api/types.go
Allow user to specify output syntax flavor of assembly in the
disassemble command.
Close #415
> pkg/config: add `disassemble-flavor` option for config 

- pkg/terminal/terminal.go
```
terminal: clarify Ctrl-C options with multiclient servers
Fixes #2028
```
> terminal: clarify Ctrl-C options with multiclient servers

- pkg/proc/target_exec.go
```
proc: keep debugger state consistent if callInjectionProtocol fails
pickCurrentThread should always run.
```
> proc: keep debugger state consistent if callInjectionProtocol fails

- pkg/proc/breakpoints.go
- pkg/proc/fncall.go
- pkg/proc/stack.go
- pkg/proc/variables.go
```
proc: move g.stackhi/g.stacklo to a struct
Mirroring the way this is implemented in the Go runtime and introducing
a type that will be useful to support the call injection changes in Go
1.15
```
> proc: move g.stackhi/g.stacklo to a struct

- pkg/proc/eval.go
- pkg/proc/proc_test.go
```
proc: use cached packageVars map in PackageVariables
```
> proc: use cached packageVars in proc.(*EvalScope).PackageVariables

- pkg/proc/bininfo.go
- pkg/proc/variables.go
```
proc: fix findCompileUnitForOffset when plugins are used
Splits the compileUnits slice between images so that we can search for
an offset inside the debug info of a specific image file.
```
> proc: fix findCompileUnitForOffset when plugins are used

- pkg/gobuild/gobuild.go
```
gobuild: pass-through stdout to 'go' command invocation
When trying to compile tests in a package that does not contain tests
'go' emits an error message on stdout instead of stderr. Let the 'go'
command write to stdout too.
Fixes #2042
```
> gobuild: pass-through stdout to 'go' command invocation

- pkg/config/config.go
- pkg/terminal/command.go
`printfile()` is called from a bunch of places, like when reaching a breakpoint, or running the `list` command. It's hard coded to print 5 lines before and after the cursor, but I often feel it's convenient to see a bigger window, so I added the `source-list-line-count` config option for this purpose. For instance:
```
(dlv) config source-list-line-count 20
(dlv) list
```
Now it will print 20 lines before and after the cursor instead. 0 (zero) also works, in which case it only prints the line under the cursor.
Thanks to the developers; it was really easy to implement this change :-)
> Config option for printfile() line count

- service/dap/server.go
- service/dap/server_test.go
> Adds launch request support for program args

- Documentation/usage/dlv_trace.md
- cmd/dlv/cmds/commands.go
- cmd/dlv/dlv_test.go
- pkg/locspec/doc.go
- pkg/locspec/locations.go
- pkg/locspec/locations_test.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- service/api/types.go
- service/config.go
- service/debugger/debugger.go
This patch improves the `dlv trace` subcommand output by reducing the
noise that is generated and providing clearer more concise information.
Also adds new tests closing a gap in our testing (we previously never
really tested this subcommand).
This patch also fixes the `dlv trace` REPL command to behave like the
subcommand in certain situations. If the tracepoint is for a function,
we now show function arguements and return values properly.
Also makes the overall output of the trace subcommand clearer.
> cmd/dlv: Fix trace output

- _fixtures/buildflagtest.go
- pkg/proc/test/support.go
- service/dap/server.go
- service/dap/server_test.go
> service/dap: Add buildFlags error checking and tests in launch requests

- _fixtures/issue2023.go
- cmd/dlv/cmds/commands.go
- cmd/dlv/dlv_test.go
`regexp` are always resolved to "" when tracing pid. And client set
breakpoint on all functions.
fix #2023
> cmd/dlv: fix bug when tracing pid

- pkg/terminal/command.go
```
terminal: fix nil pointer dereference when printing tracepoints
This issue causes a failure of TestTracePid that was observed in CI:
https://travis-ci.com/github/go-delve/delve/jobs/343053383
I'm not sure what causes it in this particular instance but there are
several ways in which a thread stopped at a breakpoint might have a
BreakpointInfo == nil field (see variable withBreakpointInfo in
debugger.Debugger.Command).
```
> terminal: fix nil pointer dereference when printing tracepoints

- service/api/conversions.go
```
service/api: do not try to convert unreadable goroutines
When reading truncated core files GoroutinesInfo will sometimes produce
some proc.G structs with only the Unreadable field set. These proc.G
can not be used for anything, but the service layer will still try to
convert them.
Since they are not fully initialized parts of the conversion will fail,
api.ConvertGoroutine should not try to call methods of unreadable
goroutines.
Fixes a bug reported on the mailing list.
https://groups.google.com/forum/#!msg/delve-dev/gauDqYaD81c/K5YDNBOhAAAJ
```
> service/api: do not try to convert unreadable goroutines

- Documentation/cli/expr.md
- _fixtures/testvariablescgo/test.c
- _fixtures/testvariablescgo/testvariablescgo.go
- pkg/proc/eval.go
- pkg/proc/proc_general_test.go
- pkg/proc/variables.go
- service/test/variables_test.go
```
proc: better support for C pointers
- treat C pointers as arrays
- print 'char *' variables as strings
proc: fix findCompileUnitForOffset when plugins are used
Splits the compileUnits slice between images so that we can search for
an offset inside the debug info of a specific image file.
```
> proc: better support for C pointers

- pkg/proc/bininfo.go
- pkg/proc/proc_test.go
The list of source files must include all files from all images, not
just the files from the last discovered image.
Fixes #2074
> proc: do not wipe sources list when a plugin is detected

- _fixtures/issue2078.go
- pkg/proc/proc_test.go
- pkg/proc/target_exec.go
On platforms other than macOS this doesn't matter but on macOS a
segmentation fault will cause ContinueOnce to return an error, before
returning it we should still fix the current thread and selected
goroutine values.
Fixes #2078
> proc: refresh cur thread/sel g after ContineOnce errors

- Documentation/api/ClientHowto.md
- Documentation/api/json-rpc/README.md
- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_backend.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_core.md
- Documentation/usage/dlv_dap.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_log.md
- Documentation/usage/dlv_replay.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_test.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- cmd/dlv/cmds/commands.go
```
Documentation: clarify API version status
Clarify that the currently supported version of the API is 2 and that
the preferred method for selecting it is sending a SetApiVersion
command after connection.
Fixes #2066
```
> Documentation: clarify API version status

- service/dap/server.go
- service/dap/server_test.go
Introduces a new struct type to track all launch arguments.
Reworks the test code to reduce duplicate boilerplate request sequences.
Updates #1515
> service/dap: Add launch request support for stackTraceDepth arg

- service/dap/error_ids.go
- service/dap/server.go
A while back I was able to clarify with vscode maintainers any questions we had about the error code values. @weinand wrote "The error numbers are private to some of our implementations. You should pick your own. There is no benefit of trying to reuse these numbers".
> service/dap: resolve minor error code TODO

- pkg/dwarf/godwarf/type.go
- pkg/proc/dwarf_expr_test.go
Backport https://go-review.googlesource.com/c/go/+/158797 from upstream.
Fixes #2101
> godwarf: handle unsupported types gracefully

- pkg/proc/bininfo.go
- pkg/proc/dwarf_export_test.go
- pkg/proc/dwarf_expr_test.go
Fully read compile units that contain nested entries we don't
understand (such as DW_TAG_namespace) by keeping track of the depth
we're at.
> proc: keep track of nesting depth while reading compile units

- pkg/proc/eval.go
Add nil check for v.LocationExpr
Fix #2049
-------------------   
Is it necessary to add a testcase?But how to construct such a testcase?   
----------
Has rebase.
> pkg/proc: Fix crash when LocationExpr is nil

- README.md
I noticed that the [Installation](https://github.com/go-delve/delve/tree/master/Documentation/installation) page has FreeBSD listed, but the main README doesn't. So here's the PR to add FreeBSD to the root README.
> Documentation: Add FreeBSD under main README

- pkg/proc/gdbserial/gdbserver.go
```
gdbserial: ensure registers are loaded in SetDX/SetSP/SetPC
These methods only work if registers have been loaded once after the
last resume, there's probably no code path that calls SetXX before
Thread.Registers but lets make sure it can't happen anyway.
```
> gdbserial: ensure registers are loaded in SetDX/SetSP/SetPC

- pkg/proc/proc_test.go
Recent change #2061:
292f5c6
proc: step into unexported runtime funcs when already inside runtime
means that TestIssue414 (which tries to step repeatedly until the
program exits) can now steps through way more runtime code than it ever
did before. This causes this test to occasionally fail. Stepping
blindly through runtime code has never been particularly safe as the
runtime can switch to a different goroutine causing Delve to misbehave.
This change restores the previous behavior of TestIssue414 where Step
behaved like Next inside runtime code.
> tests: fix flakiness of of TestIssue414 on windows

- _fixtures/decllinetest.go
- _fixtures/testvariables.go
- _scripts/make.go
- pkg/dwarf/reader/variables.go
- pkg/goversion/compat.go
- pkg/proc/arm64_disasm.go
- pkg/proc/core/windows_amd64_minidump.go
- pkg/proc/disasm.go
- pkg/proc/eval.go
- pkg/proc/fncall.go
- pkg/proc/proc_test.go
- pkg/proc/target_exec.go
- pkg/proc/test/support.go
- pkg/proc/x86_disasm.go
- pkg/terminal/command_test.go
- service/test/integration1_test.go
- service/test/integration2_test.go
```
goversion: add Go 1.15 to supported versions
core: support core files for PIEs on windows
Makefile: enable PIE tests on windows/Go 1.15
tests: properly check if cgo is enabled for cgo related tests
proc: silence go vet error
proc: start variable visibility one line after their decl line
In most cases variables shouldn't be visible on their declaration line
because they won't be initialized there.
Function arguments are treated as an exception.
This fix is only applied to programs compiled with Go 1.15 or later as
previous versions of Go did not report the correct declaration line for
variables captured by closures.
Fixes #1134
proc: use cached packageVars in proc.(*EvalScope).PackageVariables
```
> Go 1.15 support branch

- pkg/terminal/command.go
- pkg/terminal/command_test.go
Print breakpoint info (requested print variables, stacktrace) when a
tracepoint is hit.
Fixes #2116
> terminal: print breakpoint info for tracepoints

- pkg/proc/proc_test.go
- pkg/terminal/command_test.go
- service/test/integration1_test.go
Commit 1ee8d5c reviewed in Pull Request #1960 relaxed some tests using
goroutinestackprog but missed others.
Fixes some test flakiness that isn't relevant.
> tests: relax tests that use goroutinestackprog

- pkg/proc/variables.go
Limit the iteration depth of proc.(*G).UserCurrent so that it doesn't
keep going forever if the stack trace is not valid.
Fixes #2119
> proc: limit iteration depth of (*G).UserCurrent

- service/api/prettyprint.go
api.(*Variable).recursiveKind should not assume that a pointer is
always fully loaded.
Fixes #2130
> prettyprint: fix index out of range error

- pkg/dwarf/godwarf/addr.go
- pkg/dwarf/loclist/dwarf2_loclist.go
- pkg/dwarf/loclist/dwarf5_loclist.go
- pkg/dwarf/loclist/loclist5_test.go
- pkg/dwarf/util/util.go
- pkg/proc/bininfo.go
- pkg/proc/proc_general_test.go
- pkg/proc/types.go
Parses and uses the new debug_loclists section added to DWARFv5.
> Support DWARFv5 location list format

- pkg/proc/eval.go
- pkg/terminal/command_test.go
If OnlyAddr is not set pretty printing an interface will fail with an
index out of bounds error.
> proc: set OnlyAddr on variables created by typecast to pointer

- _fixtures/issue2138.go
- pkg/proc/native/proc_windows.go
- pkg/proc/proc_test.go
> proc/native/windows: do not call _DebugBreakProcess on a stopped process

- cmd/dlv/cmds/commands.go
> cmd/dlv: print error when build fails in 'dlv test'

- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_backend.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_core.md
- Documentation/usage/dlv_dap.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_log.md
- Documentation/usage/dlv_replay.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_test.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- _fixtures/buildtest/main_test.go
- cmd/dlv/cmds/commands.go
- cmd/dlv/dlv_test.go
Match 'go test' behaviour and switch to package directory, unless one
is specified with the '--wd' option.
Fixes #2125
> cmd/dlv: subcommand 'dlv test' should switch to package directory

- _fixtures/fputest/fputest.go
- _fixtures/fputest/fputest_amd64.s
- pkg/proc/amd64_arch.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/i386_arch.go
- pkg/proc/linutil/regs_amd64_arch.go
- service/test/integration2_test.go
Recent changes to the way registers are handled broke reporting of AVX registers (i.e. YMMx). This change restores the functionality by:
- concatenating the higher half of the YMMx registers to their corresponding XMMx lower half (YMMx registers do not have an independent DWARF register number)
- modifying the formatSSEReg function to handle them when they are present.
Fixes #2033
> proc: fix support for AVX registers

- _fixtures/issue2162.go
- pkg/proc/target_exec.go
- service/test/integration2_test.go
`sameFrameCond` should not be constructed as one `And Express` when
sameGCond which is the first child of `BinaryExpr` is nil.
Fixes: #2162
> pkg/proc: fix dlv panic when sameGCond is nil.

- service/dap/server.go
This is based on the pretty print logic for CLI. Testing appears too tricky to implement reliably.
> service/dap: Use 'nil' as string value for interfaces with 0 addr

- .travis.yml
- _scripts/gen-travis.go
> Travis-CI: bump version of Go used to test linux/386 to 1.15

- Documentation/cli/README.md
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- service/api/prettyprint.go
- service/api/prettyprint_test.go
- service/client.go
- service/rpc2/client.go
- service/rpc2/server.go
Make `examinemem` works like gdb x/FMT, in which FMT contains
- a number, represents a repeat times, similar to -count in examinemem
- a format letter, similar to -fmt in examinemem
- a size letter(b,d,w,h..), similar to -size in examinemem
Besides, I add a new format `address`, which has fixed size of sizeof(uintptr).
We can use it like:
1.address `x -fmt addr [-count ?]  <address>`
2.hex `x -fmt hex -count 16 -size 8  <address>`
> feature(examinemem): x -fmt <?> -count <?> -size <?> <address>, works like gdb `x/FMT`

- go.mod
- go.sum
- vendor/github.com/google/go-dap/.travis.yml
- vendor/github.com/google/go-dap/schematypes.go
- vendor/modules.txt
Pulls in v0.3.0 of google/go-dap; this version has some fixes and API
improvements which service/dap will be able to leverage to clean up some
code.
Note: I ran `go mod vendor` after changing the version in `go.mod`. I tried running `make vendor` but that command failed with `error executing go [list -mod=vendor ./...]`.
> service/dap: pull in newer version of google/go-dap

- pkg/proc/bininfo.go
- pkg/proc/native/proc_linux.go
Fixes #2168
This reverts commit 3e04ad0fada0c3ab57caf58bc024e4c0f9a3e01a.
> proc: resolve symlinks when searching for split debug_info if path is /proc/pid/exe

- .travis.yml
- service/dap/server.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/server.go
Which thread is used doesn't make any difference to the list of package
variables that is returned and this option was only ever used by an old
v1 API call.
> service/*: remove threadID argument of (*Debugger).PackageVariables

- .travis.yml
- pkg/dwarf/line/state_machine.go
Go 1.15 (but possibly prior versions of Go too) has a tendency to use
an address in the middle of an instruction for this entry, but if it
was correct it would be after the last instruction of the function
anyway.
This problem manifests especially frequently as a target crash in
TestStepConcurrentPtr on linux/arm64 (~6% of the runs).
> dwarf/line: ignore end_of_sequence entry if AllPCsBetween

- .travis.yml
- pkg/proc/eval.go
- pkg/proc/fncall.go
We can not, in general, use the argument position to determine the
address of a formal parameter, it will not work in presence of
optimizations or inlining. In those cases formal arguments could be
stored in registers.
Fixes #2176
> proc: use argument position for addr only when injecting function calls

- service/dap/server.go
- service/dap/server_test.go
- Add underlying type.
- Consider "collapsing" data level.
> service/dap: make interface variable to dap.Variable conversion more readable

- service/dap/daptest/client.go
- service/dap/error_ids.go
- service/dap/server.go
- service/dap/server_test.go
> service/dap: support clearing breakpoints and setting breakpoint conditions

- service/dap/server.go
- service/dap/server_test.go
- service/debugger/debugger.go
The unrecovered panic and fatal throw breakpoints are not set by the
user. We now check for these special breakpoints and send appropriate
stopped reasons to the client.
> service/dap: add "panic" and "fatal error" as stopped reasons

- Documentation/backend_test_health.md
- pkg/proc/proc_test.go
Due to a missing check TestCgoStacktrace2 didn't actually check
anything. Enable it and then skip it on linux/386 where it's broken.
> proc/test: enable TestCgoStacktrace2

- pkg/proc/arch.go
- pkg/proc/disasm.go
It returns an unexported type and is only used in a single place.
> proc: Remove (*Arch).Prologues method

- _fixtures/teststepprog.go
The test needs to set a breakpoint on main.CallFn after the prologue,
on linux/386 this function does not have any instruction after the
prologue on the function header line  because it doesn't need to
allocate space for local variables. Change the fixture so that this
isn't a problem.
This bug results on the test failing a small percentage of the time.
> proc/test: fix TestStepCallPtr on linux/386

- pkg/logflags/logflags.go
- service/rpccommon/sameuser_linux.go
If no logger is enabled manually write to stderr instead.
Fixes #2209
> service/rpccommon: log error for conns rejected by --only-same-user

- pkg/proc/native/registers_freebsd_amd64.go
- pkg/proc/native/registers_linux_amd64.go
> proc/native: increase max size of XSAVE area to support newer CPUs

- pkg/proc/arch.go
- pkg/proc/i386_arch.go
- pkg/proc/native/nonative_darwin.go
- pkg/proc/native/proc.go
- pkg/proc/native/proc_darwin.go
- pkg/proc/native/proc_freebsd.go
- pkg/proc/native/proc_linux.go
- pkg/proc/native/proc_windows.go
TestStepConcurrentDirect will occasionally fail (7% of the time on my
setup) by either causing the target processs to execute an invalid
instruction or (more infrequently) by switching to the wrong thread.
Both of those are caused by receiving SIGTRAPs for threads hitting a
breakpoint after it has been removed (the thread hits the breakpoint,
we stop everything and remove the breakpoint and only after we receive
the signal).
Change native.(*nativeProcess).stop to handle SIGTRAPs that can't be
attributed to a breakpoint, a hardcoded breakpoint in the program's
text, or manual stops (and therefore are likely caused by phantom
breakpoint hits).
> proc/native: fix flakyness of TestStepConcurrentDirect on linux/386

- .travis.yml
> Travis-CI: hold back version of Go 1.15.x to 1.15.3

- pkg/goversion/go_version.go
- pkg/proc/proc_test.go
> proc: fix TestStepIntoWrapperForEmbeddedPointer for Go 1.15.4

- _fixtures/cat.go
- cmd/dlv/dlv_test.go
- pkg/proc/gdbserial/gdbserver.go
1. Forward stdin/stdout/stderr to the target process when in foreground
mode instead of always forwarding the current tty (issue #1964)
2. When redirecting a file descriptor make sure to also specify
something for all three otherwise debugserver will misbehave (either
exit on launch or run but giving the target process a closed file
descriptor).
Fixes #1964
> proc/gdbserial: fix redirect bugs with debugserver

- Documentation/cli/starlark.md
- pkg/locspec/locations.go
- pkg/terminal/command.go
- pkg/terminal/command_test.go
- pkg/terminal/starbind/starlark_mapping.go
- pkg/terminal/terminal.go
- service/client.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/client.go
- service/rpc2/server.go
- service/test/common_test.go
- service/test/integration2_test.go
Change FindLocation to apply substitute path rules to location
expressions. Changes terminal to always print paths after applying
substitutions.
Implements #2203
> service,terminal: apply substitute path to trace/break argument

- pkg/proc/gdbserial/gdbserver.go
Calculate a possible debugserver path in the Xcode.app command line tools using xcode-select instead of a hardcoded path. The path is cached in the same manner as the existing implementation for continued use. 
Tested by adding a fmt.Println comment locally and running against my own environment:
```
checking: debugserver
checking: /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver
checking: /Applications/Xcode/12B45b/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/debugserver
```
Fixes #2227
> proc/gdbserial: Use the active xcode-select path instead of a hardcoded Xcode path

- service/dap/server.go
- service/dap/server_test.go
Also improve stackTrace tests.
Updates #1515, https://github.com/golang/vscode-go/issues/913
> service/dap: enable supportsDelayedStackTraceLoading capability

- pkg/dwarf/line/line_parser.go
- pkg/dwarf/line/state_machine.go
- pkg/dwarf/line/state_machine_test.go
This is needed to fix the problem we have with 1.15.4+ after the
backport is applied to it. The DWARF standard isn't clear on what
should happen with the end_of_sequence opcode but this is consistent
with debug/dwarf.LineReader as well as gdb.
> dwarf/line: do not consider end of sequence entries valid

- pkg/proc/fncall.go
- pkg/proc/target_exec.go
- pkg/proc/threads.go
- service/api/types.go
- service/dap/server.go
- service/debugger/debugger.go
Adds a flag that distinguishes the return values of an injected
function call from the return values of a function call executed by the
target program.
> proc: add flag to distinguish ReturnValues

- _fixtures/fncall.go
- pkg/proc/fncall.go
- service/test/variables_test.go
evalFunctionCall needs to remove the breakpoint from the current thread
after starting the function call injection, otherwise Continue will
think that the thread is stopped at a breakpoint and return to the user
instead of continuing the call injection.
> proc: make nested function calls work when stopped at a sw breakpoint

- pkg/proc/stack.go
The comment on the advanceRegs() method was referencing several
nonexistent fields. This patch fixes that, and improves the comment to
reference the peculiar interaction between the method and it.regs.
> proc: update a comment

- pkg/proc/variables.go
- service/api/conversions.go
- service/api/types.go
This adds the WaitSince and WaitReason fields for the goroutines to allow the users to easily understand why a goroutine is waiting.
> service/api: Expose WaitSince and WaitReason fields for goroutines

- pkg/proc/amd64util/xsave.go
- pkg/proc/amd64util/xsave_amd64.go
- pkg/proc/amd64util/xsave_amd64.s
- pkg/proc/amd64util/xsave_other.go
- pkg/proc/core/linux_core.go
- pkg/proc/fbsdutil/regs.go
- pkg/proc/linutil/regs_amd64_arch.go
- pkg/proc/linutil/regs_i386_arch.go
- pkg/proc/native/ptrace_freebsd.go
- pkg/proc/native/ptrace_linux_386.go
- pkg/proc/native/ptrace_linux_amd64.go
- pkg/proc/native/register_linux_386.go
- pkg/proc/native/registers_freebsd_amd64.go
- pkg/proc/native/registers_linux_amd64.go
the maximum size of the Xsave area was previously hardcoded but the
CPUID instruction can be used to determine its maximum size.
> proc: use CPUID to determine maximum size of XSAVE area

- service/debugger/debugger.go
- service/test/integration2_test.go
Do not call detach if the target is no longer valid.
Fixes #2259
> debugger: check that target is valid when detaching

- pkg/proc/native/register_linux_386.go
Change 24ec175 (use CPUID to determine maximum size of XSAVE area)
broke the linux/386 backend, this commit fixes it.
> proc/native: fix linux/386 native backend

- pkg/proc/core/core_test.go
- pkg/proc/proc_test.go
- service/dap/server_test.go
In Go 1.15 the call injection will be executed on a different goroutine
from the goroutine where it was started on to avoid confusing the
garbage collector, the test must be aware of this fact and use the
goroutine ID from the stopped response instead of assuming 1 is the
currently selected goroutine.
> Miscellaneous fixes for problems discovered by Github Actions tests

- pkg/proc/native/proc_windows.go
- pkg/proc/native/threads_windows.go
- pkg/proc/native/zsyscall_windows.go
Sometimes it makes debuggee to hang.
Should fix #2244
> Don't call suspend on DbgUiRemoteBreakin threads

- pkg/proc/native/proc_linux.go
- pkg/proc/proc_unix_test.go
Waits for the target process to have received the kill signal in
native.nativeProcess.kill. Fixes an infrequent error in TestKill.
> native/proc/linux: wait for the target process to be killed in kill

- _fixtures/loopprog.go
- service/dap/daptest/client.go
- service/dap/error_ids.go
- service/dap/server.go
- service/dap/server_test.go
> service/dap: Support local attach

- pkg/proc/bininfo.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/gdbserial/gdbserver_conn.go
- pkg/proc/gdbserial/gdbserver_conn_amd64.go
- pkg/proc/gdbserial/gdbserver_conn_arm64.go
- pkg/proc/native/support_sentinel.go
- service/test/integration2_test.go
This is an alternative fix for #2246 and one that might be easier to merge in than fixing the native darwin backend (see #2254).
Tests almost succeed, and it looks like those that do not, i.e. cgo-related ones, might be related to some Go 1.16 problems. I can provide a complete log of `make test` (it is currently running).
Fixes #2246
> proc/gdbserial: Added support for darwin/arm64 using gdbserver

- pkg/proc/variables.go
Before go1.11 waitreason field was a string, not an int. Return 0
waitreason for old go versions.
Should fix #2282
> Fix panic in goroutine parsing for binaries compiled with go1.10

- pkg/terminal/command.go
- pkg/terminal/terminal.go
The goroutines command can take a long time to complete if there are
many goroutines, add the possibility to terminate it early by pressing
ctrl-C.
> terminal: add way to cancel goroutines command with ctrl-C

- pkg/dwarf/line/line_parser.go
- pkg/dwarf/line/line_parser_test.go
- pkg/goversion/compat.go
- pkg/proc/amd64_arch.go
- pkg/proc/arm64_arch.go
- service/test/integration2_test.go
> Go 1.16 support branch

- Documentation/usage/dlv.md
- Documentation/usage/dlv_attach.md
- Documentation/usage/dlv_backend.md
- Documentation/usage/dlv_connect.md
- Documentation/usage/dlv_core.md
- Documentation/usage/dlv_dap.md
- Documentation/usage/dlv_debug.md
- Documentation/usage/dlv_exec.md
- Documentation/usage/dlv_log.md
- Documentation/usage/dlv_redirect.md
- Documentation/usage/dlv_replay.md
- Documentation/usage/dlv_run.md
- Documentation/usage/dlv_test.md
- Documentation/usage/dlv_trace.md
- Documentation/usage/dlv_version.md
- cmd/dlv/cmds/commands.go
This simple example removes confusion when user is trying to pass multiple arguments to the compiler via `--build-flags=`
> Add example of passing multiple arguments to `--build-flags=`

- service/dap/server.go
- service/dap/server_test.go
When keys are compound, the value is a type, which is not unique. The earlier version of this code used child index to differentiate, but that seems misleading given that maps are not indexed or ordered. Using the address as a differentiator will be closer to dlv's expression syntax for loading variables.
> service/dap: use address, not index to differentiate compound map keys

- service/dap/handles.go
- service/dap/server.go
- service/dap/server_test.go
Updates #1515
This feature enables "Add to Watch" and "Copy as Expression" in vscode VARIABLES pane.
> service/dap: Add support for evaluateName for variables

- .gitignore
- .teamcity/pom.xml
- .teamcity/settings.kts
- README.md
- _scripts/make.go
- _scripts/test_linux.sh
- _scripts/test_windows.ps1
- pkg/proc/gdbserial/gdbserver_conn_386.go
- service/dap/server_test.go
This pool request introduces the TeamCity build configuration (https://delve.beta.teamcity.com/). Additionally, it fixes two problems that prevent tests from running. One is relevant for darwin/386 (`restore gdbserial constants for 386`), another is for windows/amd64 (`skip TestAttachRequest on Windows as it never finishes`). I didn't investigate these problems. Instead, I've just implemented workarounds so that tests can run. Feel free to drop these commits if you feel that they bring more harm than good.
If you decide to accept this pool request, you'll need to additionally update the TeamCity configuration, so the server points at the original repo instead of my fork. It should be a rather trivial task. I've sent invites to Alessandro and Derek and will grant admin access as soon as …
> Introduce TeamCity builds

- service/api/prettyprint.go
The starting address should be incremented by `address += uintptr(cols*colBytes)`.
> fix/pmem: prettyprint outputs wrong starting address

- cmd/dlv/dlv_test.go
Change TestGeneratedDoc to ignore differences in line terminators.
> cmd/dlv/tests: fix TestGeneratedDoc on Windows

- .github/workflows/test.yml
Removes linux builders from the GitHub action matrix. These are covered
via the TeamCity CI solution now.
> *: Remove linux builders from GH matrix

- pkg/dwarf/dwarfbuilder/info.go
- pkg/proc/bininfo.go
- pkg/proc/dwarf_expr_test.go
- pkg/proc/types.go
The DWARF standard does not say that a DW_ATTR_abstract_origin can only
reference entries that appear before it, this change fixes BinaryInfo
to comply. See #2284 for an example of this happening.
> proc: do not assume abstract origins precede their uses

- pkg/proc/breakpoints.go
- pkg/proc/core/core.go
- pkg/proc/gdbserial/gdbserver.go
- pkg/proc/interface.go
- pkg/proc/native/proc.go
Moves common backend code in WriteBreakpoint to
proc.(*Target).SetBreakpoint.
> proc: refactor common code in WriteBreakpoint

- _fixtures/testvariables2.go
- pkg/proc/eval.go
- pkg/proc/variables.go
- service/dap/server_test.go
- service/test/variables_test.go
Both structMember and findMethod implemented a depth-first search in
embedded fields but the Go specification requires a breadth-first
search. They also allowed promotion of fields in the concrete type of
embedded interfaces even though this is not allowed by Go.
Furthermore they both lacked protection from infinite recursion
when a type embeds itself and the user requests a non-existent field.
Fixes #2316
> proc: fix embedded field search

- pkg/proc/core/core.go
- pkg/proc/core/core_test.go
core.(*splicedMemory).ReadMemory checked the entry interval
erroneously when dealing with contiguous entries.
> proc/core: off-by-one error reading ELF core files

- .teamcity/settings.kts
- pkg/goversion/compat.go
> teamcity,goversion: drop Go version 1.13 from test matrix

- service/dap/server.go
- service/dap/server_test.go
Updates https://github.com/golang/vscode-go/issues/1212
Following the same response pattern as the original vscode-go adapter seems to no longer result in the same vscode UI behavior - see BREAKPOINTS and margin marker. Adding optional information fixes that.
Before
After
> service/dap: include optional breakpoint info in setBreakpoints responses

- service/test/integration1_test.go
- service/test/integration2_test.go
When the runtime is allocating memory the stack trace needed to reach
user code might be greater than 10 frames.
> test: increase num of frames examined by TestClientServer_FullStacktrace

- _fixtures/testvariables2.go
- service/dap/server.go
- service/dap/server_test.go
Updates #1515
This lays foundation and tests for where to add support for loading variables on the fly.
> service/dap: detect and report unloaded variables

- .teamcity/settings.kts
Should finally fix https://delve.beta.teamcity.com/viewLog.html?buildId=2158&tab=buildResultsDiv&buildTypeId=Delve_linux_386_1_16&branch_Delve_linux_386=%3Cdefault%3E
> Run linux/386 builds only on amd64 agents

- .teamcity/settings.kts
- Documentation/backend_test_health.md
- pkg/proc/proc_test.go
- service/test/variables_test.go
So that it can be tested when we make the next-version-support-branch.
> TeamCity: add linux/arm64/tip and disable failing arm64 tests

- .teamcity/settings.kts
- _scripts/latestver.py
- _scripts/test_mac.sh
Also adds a disabled tip builder for the next-version support branch.
> TeamCity: select latest patch version of go for mac builds

- pkg/dwarf/frame/entries.go
- pkg/dwarf/frame/entries_test.go
- pkg/dwarf/frame/parser.go
- pkg/dwarf/frame/parser_test.go
- pkg/dwarf/util/util.go
- pkg/proc/bininfo.go
- service/test/variables_test.go
The eh_frame section is similar to debug_frame but uses a slightly
different format. Gcc and clang by default only emit eh_frame.
> dwarf/frame,proc: use eh_frame section

- service/dap/server.go
- service/dap/server_test.go
This PR does the following actions on the dap/onLaunchRequest method:
- Refactor and move to the start of the method the launch mode argument validation
- Removes the redundant validation on https://github.com/go-delve/delve/blob/2e80b32c417494ab3fabe929e7051076a7049f7c/service/dap/server.go#L490
PTAL @polinasok
> service/dap: refactor mode validation on onLaunchRequest

- _fixtures/testvariables.go
- pkg/terminal/command_test.go
- service/dap/server.go
- service/dap/server_test.go
- service/test/variables_test.go
Updates #1515
While we use fully qualified names for `evaluateName` (added in #2292) for readability, the auto-loading expressions are based on [ClientHowto.md#loading-more-of-a-variable](https://github.com/go-delve/delve/blob/master/Documentation/api/ClientHowto.md#loading-more-of-a-variable). These expressions work in a context of any frame.
> service/dap: support auto-loading of unloaded interfaces

- service/dap/server.go
- service/debugger/debugger.go
- service/rpc1/server.go
- service/rpc2/server.go
- service/rpccallback.go
- service/rpccommon/server.go
Wait until the target process has resumed before accepting new calls to
Command. Before this if a 'continue' was immediately followed by a
'halt' the 'halt' could be processed before the 'continue'.
Fixes #1608
Fixes #2216
> service: serialize calls to Command API

- Documentation/cli/README.md
- pkg/terminal/command.go
- pkg/terminal/command_test.go
This change allows specifying an optional linespec after the 'continue' command which sets a temporary breakpoint.
Fixed #2373
> terminal/command: Add [linespec] argument to 'continue' command

- service/rpc2/server.go
The wiki link was dangling. I think I got the right one instead.
> service: fix link to expr communication

- cmd/dlv/dlv_test.go
- pkg/gobuild/gobuild.go
- service/dap/server_test.go
I know #2372 added a longer delay. Do we still want to skip the errors like we discussed eariler?
> service/dap + dlv_test: skip Windows 'access denied' failures in tests

- pkg/dwarf/godwarf/tree.go
The godwarf package provides two ways to turn a dwarf.Entry into a
godwarf.Tree: LoadTree and EntryToTree. The former doesn't handle
children - it doesn't advance a Reader past them (in fact, it doesn't
even know about a Reader). EntryToTree is only used for variables and
formal param DIEs, which don't have children, and it would very likely
be incorrect to use it for DIEs with children. This patch makes the
function panic if the entry can have children.
> godwarf: assert children are not ignored

- service/dap/server.go
- service/dap/server_test.go
Take advantage of the function used with dlv cli `locals` command that inlines child values and can save users extra clicks to expand. Unlike `<type> `syntax used by vscode-go that inspired the first version of dap code, dlv cli's `(*type)(address)` syntax can be used as an expression to load variables that have not been fully loaded.
Updates https://github.com/golang/vscode-go/issues/1267
> service/dap: use (*api.Variable).SinglelinesString() for dap.Variable values

- service/dap/server.go
- service/dap/server_test.go
Following the DAP spec 
https://microsoft.github.io/debug-adapter-protocol/specification
Launch Request
This launch request is sent from the client to the debug adapter to 
start the debuggee with or without debugging (if ‘noDebug’ is true).
This is admittedly strange to be implemented inside delve (debugger),
but implementing this outside `dlv dap`  (from the editor plugin side)
implies the need for another DAP layer, which isn't desirable either.
If the launch requests has noDebug attribute set, run the built
binary directly. The launch request handler will block until
the binary terminates, so the editor won't send additional requests
like breakpoint setting etc. Still disconnect or restart requests
can flow in though and they should trigger killing of the target
process if it's still …
> service/dap: supports noDebug launch requests
