go-delve/delve

_fixtures/testvariables.go, proctl/variables.go, proctl/variables_test.go
- Fixes panic if trying to read a string over 16 bytes
- readString now works on sliced strings correctly
- Added tests for both
=> Fix panic in readstring

_fixtures/testvariables.go, proctl/variables.go, proctl/variables_test.go
- Support for bool values
- Support for uint values
- Support for function pointer values (even maps them back to their names)
- info locals and info args will skip any variables they cannot parse rather than just returning nothing.
=> Support for more types

client/cli/cli.go
Cleaned up pull request that only contains the new Term object.
Added Term object (terminal or terminator) that wraps the liner.State object so that it can be closed properly on exit. Changed a few functions (die, promptForInput, etc.) to be methods for Term.
=> Issue 73: die should restore the terminal state

proctl/proctl_linux.go
=> linux: Don't ask to kill a process that has exited

README.md
Add a couple of troubleshooting instructions for OSX users.
=> Add more instructions for OSX

terminal/terminal.go
This is a rebased version of #128 with an additional commit that changes the default answer to kill as requested.
=> Default to killing process on exit

terminal/command.go, terminal/command_test.go
=> added length check for args in terminal thread command

proc/breakpoints.go, proc/proc.go, proc/proc_test.go, proc/stack.go, proc/threads.go, service/api/conversions.go, service/api/types.go, service/client.go, service/debugger/debugger.go, service/rpc/client.go, service/test/integration_test.go, terminal/command.go
=> trace command

_fixtures/testvariables.go, proc/variables.go, proc/variables_test.go
=> Make info locals understand/print complex types

_fixtures/retstack.go, proc/proc.go, proc/proc_test.go, proc/stack.go, proc/threads.go, proc/variables.go, proc/variables_test.go, service/api/types.go, service/client.go, service/debugger/debugger.go, service/rpc/client.go, service/rpc/server.go, service/test/integration_test.go, terminal/command.go
When -full is passed all arguments and local variables of functions on the stacktrace are printed
=> stack command, added -full flag

proc/proc.go, proc/proc_linux.go, service/test/integration_test.go, terminal/terminal.go
See commit messages for a description. I'm not sure about the last one, it's a workaround, I don't know why that happens.
=> Three bug fixed concerning target termination on linux

_fixtures/locationsprog.go, service/debugger/locations.go, service/test/integration_test.go
=> service/debugger: Bugfix: support pkg names with slashes in linespecs

_fixtures/goroutinestackprog.go, proc/proc_test.go
TestStacktraceGoroutine would occasionally fail due to race
conditions in the test itself.
=> proc/proc_test: Fixed TestStacktraceGoroutine

terminal/command.go
=> terminal/command: bugfix: wrong check in sourceCommand

_fixtures/testvariables3.go, proc/proc_test.go, proc/variables.go
=> proc/variables: bugfix: infinite loading loop through maps

cmd/dlv/main.go, proc/arch.go, proc/breakpoints.go, proc/eval.go, proc/go_version.go, proc/proc.go, proc/proc_darwin.go, proc/proc_linux.go, proc/proc_test.go, proc/ptrace_darwin.go, proc/ptrace_linux.go, proc/registers.go, proc/registers_darwin_amd64.go, proc/registers_linux_amd64.go, proc/stack.go, proc/threads.go, proc/threads_darwin.go, proc/threads_linux.go, proc/variables.go, service/api/conversions.go, service/client.go, service/debugger/debugger.go, service/server.go, terminal/command.go, terminal/terminal.go
Fixes lint issues, adds documentation to undocumented functions, etc... Mostly a housekeeping commit.
cc: @aarzilli
=> misc: cleanup and documentation

proc/proc.go
=> proc: Fix step when on breakpoint

proc/proc.go, service/debugger/debugger.go, service/rpc/server.go, service/test/integration_test.go
=> proc: Do not panic when a command is executed on an exited process

cmd/dlv/main.go, terminal/terminal.go
=> cmd/dlv: bugfix: trace disables terminal echo

cmd/dlv/main.go
This patch allows certain commands (`debug`, `test`, and `trace`) to
take an argument specifying a package name. This allows a user to
specify a package other than that of the current package in the working
directory.
If a package name is not specified, the behavior remains the same, as in
Delve will look in the current working directory for a `main` package to
compile.
Fixes #423
=> dlv: Take package name in certain commands

cmd/dlv/main.go, service/config.go, service/rpc/server.go
See issue #383 for related discussion.
=> cmd/dlv: add flag to make headless server accept multiple clients

Makefile
=> Fixes quote of certificate

Documentation/installation/osx/install.md
=> docs: Update OSX install docs

Documentation/EditorIntegration.md, Documentation/README.md
=> Documentation: List of editor plugins

proc/stack.go
=> Fix typo in  /proc/stack.go

Documentation/KnownBugs.md, Documentation/README.md, _fixtures/issue528.go, service/test/integration2_test.go
Added a test that verifies that on go-tip issue #528 is solved, also added a short list of notable known bugs (including this one) to the documentation.
=> Added a test for issue #528

proc/proc.go, proc/proc_test.go, proc/stack.go, proc/threads.go, terminal/command.go
Also refactors proc.(*Process).Next to make implementing a stepout command easier.
=> Implement next, step, step-instruction for parked goroutines

_fixtures/nomaindir/file.go, cmd/dlv/cmds/commands.go, proc/mem.go, proc/proc.go, proc/proc_darwin.go, proc/proc_linux.go, proc/proc_test.go, proc/proc_windows.go, service/api/types.go, service/debugger/debugger.go
=> proc: better error message when running dlv debug when there is no main

proc/proc_linux.go
fix #531
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/532)
=> proc: fix could not read process comm name error

proc/proc.go, proc/proc_windows.go, proc/syscall_windows.go, proc/zsyscall_windows.go
This change implements attach command on windows
Updates #363
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/607)
=> proc: implement attach on windows

proc/disasm_amd64.go, proc/eval.go, proc/proc.go, proc/proc_linux.go, proc/proc_test.go, proc/variables.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/625)
=> Fix prologue detection on testvariables2.go's main.main

proc/proc_windows.go, proc/ptrace_windows.go, proc/syscall_windows.go, proc/zsyscall_windows.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/615)
=> proc: implement detach on windows

proc/variables.go
Fixes #642
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/643)
=> proc/variables: missing return statement on error

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/649)
=> add go1.7 to travis

proc/proc.go, proc/proc_test.go, service/api/types.go, service/client.go, service/debugger/debugger.go, service/rpc2/client.go, service/test/integration2_test.go, terminal/command.go
Command to step out of the currently executing function.
Implements #358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/derekparker/delve/583)
=> proc, terminal: stepout command

service/debugger/debugger.go, service/test/integration2_test.go, terminal/command.go
one `Println` was supposed to be `Printf`, thanks @zchee.
=> terminal: fixed typo.

proc/disasm_amd64.go
Improved prologue detection for big stackframes and added references to
the function of the compiler that inserts the prologue.
=> proc: Improved prologue detection for big stackframes

Documentation/EditorIntegration.md
```
Added jodosha/vim-godebug to Documentation/EditorIntegration.md
```
=> Added jodosha/vim-godebug to Documentation/EditorIntegration.md

_fixtures/callme.go, _fixtures/issue664.go, dwarf/line/line_parser_test.go, dwarf/line/state_machine.go, proc/go_version.go, proc/proc.go, proc/proc_test.go, service/test/integration1_test.go, service/test/integration2_test.go
Do not commit / Do not review.
=> Go 1.8 compatibility (part 2)

proc/variables.go
```
proc/variables: mark malformed maps as unreadable instead of panicking
Under currently undetermined circumstances we encounter a map type that
has a malformed buckets, oldbuckets or overflow field.
Check the type of buckets, oldbuckets and overflow before using them.
Fixes #685
```
=> proc/variables: mark malformed maps as unreadable instead of panicking

pkg/proc/proc_windows.go
=> fix delve on windows

Makefile, pkg/proc/proc_darwin.go
=> proc: fix proc.Launch, Makefile on macOS

pkg/proc/proc_test.go
```
proc_test: TestStacktraceWithBarriers failing on go1.8
Changes to the GC in 1.8 make this test fail because the GC isn't
inserting stack barriers into our test program anymore. This isn't the
same thing as being unable to print stacktraces in presence of stack
barriers so the test shouldn't fail.
```
=> proc_test: TestStacktraceWithBarriers failing on go1.8

Makefile, scripts/gencert.sh
=> Bash script to generate & install signing certificate for delve

Documentation/EditorIntegration.md, Documentation/README.md
```
documentation: add gdlv to list of alternative UIs
```
(self promotion)
=> documentation: add gdlv to list of alternative UIs

pkg/proc/breakpoints.go, pkg/proc/disasm.go, pkg/proc/disasm_amd64.go, pkg/proc/eval.go, pkg/proc/moduledata.go, pkg/proc/proc.go, pkg/proc/proc_test.go, pkg/proc/stack.go, pkg/proc/threads.go, pkg/proc/types.go, pkg/proc/variables.go, pkg/target/target.go, service/debugger/debugger.go, service/test/variables_test.go
Second step on the way to #782
=> proc refactoring: make stack, disassemble and eval independent of proc.Process

README.md
Readability! "Most likely" and "chances are" are redundant.
=> Improve sentence in README.md.

Documentation/installation/osx/install.md
```
documentation: updated macOS install instructions
```
=> documentation: updated macOS install instructions

_fixtures/pkgrenames.go, _fixtures/vendor/dir0/pkg/main.go, pkg/proc/eval.go, pkg/proc/proc_test.go, pkg/proc/variables.go
I've added two tests for PR #731
=> Pull Request #731 but with tests

cmd/dlv/dlv_test.go
<pre>
% go test -race -v -short
=== RUN   TestBuild
==================
WARNING: DATA RACE
Write at 0x00c4201379a0 by goroutine 9:
os.(*file).close()
/usr/local/go/src/os/file_unix.go:143 +0x10a
os.(*File).Close()
/usr/local/go/src/os/file_unix.go:132 +0x55
os/exec.(*Cmd).closeDescriptors()
/usr/local/go/src/os/exec/exec.go:263 +0x67
os/exec.(*Cmd).Wait()
/usr/local/go/src/os/exec/exec.go:448 +0x2b8
github.com/derekparker/delve/cmd/dlv.TestBuild.func1()
/home/kbuilder/go/src/github.com/derekparker/delve/cmd/dlv/dlv_test.go:82 +0x8e
github.com/derekparker/delve/cmd/dlv.TestBuild()
/home/kbuilder/go/src/github.com/derekparker/delve/cmd/dlv/dlv_test.go:104 +0xb6a
testing.tRunner()
/usr/local/go/src/testing/testing.go:657 +0x107
Previous read at 0x00c4201379a0 by goroutine 12: …
=> cmd/dlv: fix race in test

pkg/proc/gdbserial/gdbserver.go
```
proc/gdbserial: disable lldb backend on windows
Lldb-server does not currently support windows/amd64 (it's in
development). And delve's native backend seems to work well on windows.
Disable the lldb backend on windows for now.
Fixes #817
```
=> proc/gdbserial: disable lldb backend on windows

pkg/proc/gdbserial/gdbserver.go, pkg/proc/gdbserial/rr.go
```
proc/gdbserial: use reverse connect feature of debugserver
Fixes #836
```
=> proc/gdbserial: use reverse connect feature of debugserver

CHANGELOG.md
```
Update CHANGELOG with everything changed so far.
```
=> Update CHANGELOG with everything changed so far.

pkg/proc/gdbserial/gdbserver.go, pkg/proc/native/proc.go
See https://youtrack.jetbrains.com/issue/GO-3931#comment=27-2224179 for more details
=> Return breakpoints when they already exist

pkg/dwarf/line/line_parser_test.go
```
dwarf/line: load PE files correctly in test
Fixes #885
```
=> dwarf/line: load PE files correctly in test

cmd/dlv/cmds/commands.go, cmd/dlv/dlv_test.go, pkg/proc/gdbserial/gdbserver.go, service/config.go, service/rpc2/client.go, service/rpccommon/server.go
```
dlv: make headless servers quit automatically when client disconnects
```
=> dlv: make headless servers quit automatically when client disconnects

cmd/dlv/cmds/commands.go, pkg/config/config.go, pkg/dwarf/frame/entries.go, pkg/proc/disasm_amd64.go, pkg/proc/gdbserial/gdbserver.go, pkg/proc/gdbserial/gdbserver_conn.go, pkg/proc/go_version.go, pkg/proc/native/threads.go, pkg/proc/proc.go, pkg/proc/proc_test.go, pkg/proc/proc_unix_test.go, pkg/proc/variables.go, pkg/terminal/command_test.go, pkg/terminal/disasmprint.go, pkg/terminal/docgen.go, service/api/conversions.go, service/api/prettyprint.go, service/debugger/debugger_linux.go, service/debugger/locations.go, service/rpc1/client.go, service/rpc2/client.go, service/rpc2/server.go, service/rpccommon/server.go, service/test/common_test.go, service/test/integration1_test.go, service/test/integration2_test.go, service/test/variables_test.go
I've ran [megacheck](http://honnef.co/go/tools/cmd/megacheck) and fixed a few of the things that came up there.
=> Fix various issues detected by megacheck

_fixtures/issue877.go, pkg/proc/gdbserial/gdbserver.go, pkg/proc/proc_test.go
Unfortunately this is something I can't verify on my machine so I'll let the CI / users to do it for me.
=> Pass LD_/DYLD_ env vars to debugserver (fixes #877)

service/debugger/locations.go
When location spec is given and the base can be interpreted either in
source file name or function name, NomalLocationSpec searches both
the source file list and the function symbol list, and selects matching
candidates. Previously, all the matching candidates were added to one
single list regardless whether the candidate was from the source file
list or not. Then, later, Find tries to guess whether the candiate
was a function or a file based on a heuristic, i.e, whether the
candidate is an absolute file path. The heuristic is fragile - since
there is no guarantee that the included source file name is an absolute
path.
Instead, this CL preserves where the candidate was found; file list or
function symbol list. Then, use that info to determine whether the
candidate is a source file name or …
=> service/debugger: improve NomalLocationSpec.Find's heuristics

_fixtures/fputest/fputest.go, pkg/proc/core/core.go, pkg/proc/core/core_test.go, pkg/proc/core/linux_amd64_core.go, pkg/proc/native/ptrace_linux.go, pkg/proc/native/registers_linux_amd64.go, pkg/proc/registers.go
```
proc/core: support floating point registers
Updates #794
```
=> proc/core: support floating point registers

cmd/dlv/cmds/commands.go
```
cmd/dlv: do not delete built executable when using rr backend
Mozilla RR will create a trace directory that can be reused with the
replay verb, however if we delete the executable file the trace
directory will become useless.
The other acceptable behavior would be to also clean the trace
directory at the end, but I think this behavior is more useful and
easier to implement.
```
=> cmd/dlv: do not delete built executable when using rr backend

pkg/proc/proc_test.go
```
proc/tests: fix intermittent failure of TestNextParked
Always pick a goroutine that we know will have to be resumed before the
program terminates instead of relying on luck.
Fixes #803
```
=> proc/tests: fix intermittent failure of TestNextParked

pkg/proc/bininfo.go, pkg/proc/core/core.go, pkg/proc/core/core_test.go, pkg/proc/gdbserial/gdbserver.go, pkg/proc/gdbserial/rr_test.go, pkg/proc/native/proc.go, pkg/proc/native/proc_darwin.go, pkg/proc/native/proc_linux.go, pkg/proc/native/proc_windows.go, pkg/proc/proc_test.go, pkg/proc/test/support.go, pkg/terminal/command_test.go, service/test/integration1_test.go, service/test/integration2_test.go, service/test/variables_test.go
```
proc: report errors when loading executable on attach
Fixes #940
```
=> proc: report errors when loading executable on attach

Documentation/cli/README.md, pkg/terminal/command.go
```
terminal: implement whatis command
Implements #596
```
=> terminal: implement whatis command

CHANGELOG.md, pkg/version/version.go
```
*: Bump version to 1.0.0-rc.2
```
=> *: Bump version to 1.0.0-rc.2

CHANGELOG.md
```
CHANGELOG: changed rc.2 date.
```
=> CHANGELOG: changed rc.2 date.

pkg/proc/native/proc_linux.go
```
proc/native/linux: tolerate ESRCH error in setCurrentBreakpoints
A thread could terminate between the point when we stop for a
breakpoint and the point where we send a stop signal to all threads, if
this happens setCurrentBreakpoints will fail with an error.
We should tolerate this.
For some reason this happens very frequently when running delve on
processes with the race detector enabed.
```
=> proc/native/linux: tolerate ESRCH error in setCurrentBreakpoints

pkg/proc/stack.go
```
pkg/proc: remove callFrameRegs from stackIterator
Since it's just a scratchpad to calculate the new set of registers it
makes more sense to have it as a local variable in Next and
advanceRegs.
```
=> pkg/proc: remove callFrameRegs from stackIterator

Documentation/cli/README.md, _fixtures/cgostacktest/hello.c, _fixtures/cgostacktest/hello.h, _fixtures/cgostacktest/main.go, cmd/dlv/main.go, pkg/dwarf/frame/table.go, pkg/dwarf/op/regs.go, pkg/proc/arch.go, pkg/proc/eval.go, pkg/proc/proc.go, pkg/proc/proc_test.go, pkg/proc/stack.go, pkg/proc/test/support.go, pkg/proc/threads.go, pkg/proc/variables.go, pkg/terminal/command.go, pkg/terminal/command_test.go, service/api/types.go, service/debugger/debugger.go, service/rpc2/client.go
What the title says. Do not merge.
=> Better cgo support

service/api/conversions.go
=> api/conversions: fix converting of nil complex numbers

pkg/proc/gdbserial/gdbserver.go
```
proc/gdbserial: remove dead threads from thread list [WIP]
Fixes #1052
```
=> proc/gdbserial: remove dead threads from thread list

pkg/proc/threads.go
```
proc: check error accessing g.m.curg in GetG
I saw a test failure related to this in Travis-CI, if it happens again
I would like to know what's causing it.
```
=> proc: check error accessing g.m.curg in GetG

pkg/proc/proc_test.go, pkg/proc/stack.go
```
proc: avoid scanning system stack if it's not executing cgo
The runtime calls into g0 in many places, not necessarily using
runtime.systemstack or runtime.asmcgocall.
One example of this is the call to runtime.newstack inside
runtime.morestack.
If we stop the process while one goroutine is executing
runtime.newstack we would be unable to fully scan its stack because we
don't know that we have to switch back to the goroutine stack after
runtime.newstack.
Instead of tracking down every possible way that the runtime switches
to g0 we switch to the goroutine stack immediately after the top of the
stack, unless cgo is being executed on the systemstack.
Fixes #1066
```
=> proc: avoid scanning system stack if it's not executing cgo

Documentation/cli/getting_started.md
Document how to pass flags to the cli program being debugged.
=> getting_started: Document passing flags with `--`.

pkg/proc/proc.go, pkg/proc/proc_test.go, pkg/proc/scope_test.go, pkg/proc/stack.go, pkg/proc/variables.go
```
proc: Remove unused code
proc_test: clean some repeated patterns in proc_test
```
=> Miscellaneous proc_test and proc cleaning

pkg/proc/core/core.go, pkg/proc/gdbserial/gdbserver.go, pkg/proc/interface.go, pkg/proc/native/proc.go, pkg/proc/proc.go
```
proc: rename ManualStopRequested to CheckAndClearManualStopRequest
```
=> proc: rename ManualStopRequested to CheckAndClearManualStopRequest

CHANGELOG.md, pkg/version/version.go
Add new version to CHANGELOG and update internal version.
=> all: Bump to v1.0.0

_fixtures/issue1145.go, pkg/proc/proc.go, pkg/proc/proc_test.go, pkg/terminal/command.go, pkg/terminal/terminal.go
```
proc: manual stop requests should clear internal breakpoints
Fixes #1145
```
=> proc: manual stop requests should clear internal breakpoints

cmd/dlv/cmds/commands.go, pkg/logflags/logflags.go, pkg/proc/gdbserial/gdbserver.go, pkg/proc/gdbserial/gdbserver_conn.go
```
proc/gdbserial,dlv/cmds: make logGdbWire command line configurable
```
=> proc/gdbserial,dlv/cmds: make logGdbWire command line configurable

pkg/proc/test/support.go, service/test/integration1_test.go, service/test/integration2_test.go
```
tests: cache and delete fixtures built with non-zero flags
```
=> tests: cache and delete fixtures built with non-zero flags

pkg/proc/moduledata.go
This pull request was made with an automated tool.
The suggested change fixes one or more problems discovered by "go vet".
See https://github.com/functionary/functionary for more details on
the @functionary GitHub user.
=> pkg/proc: fix errors found by vet

pkg/proc/bininfo.go
To save disk space, some distributions strip the debugging information
from the binaries, putting it in separate files, usually distributed in
separate packages.
To locate the file containing the debug information for a certain
binary, an ELF note named ".note.gnu.build-id" is added to the latter,
which contains a header and a build identification. This identification
can be used to compose a path with this form:
/usr/lib/debug/.build-id/BUILDID[:2]/BUILDID[2:].debug
With this patch, if Delve can't find the debug information in the main
binary, it'll try to locate and parse ".note.gnu.build-id", to compose
and attempt to open a path with the format described above.
Fixes #1206
=> proc: add support for separate debug info

pkg/proc/core/linux_amd64_core.go
Core files created by gdb can have sections missing that would be
present in OS created core files.
We work around this by first reading PT_LOAD entries from the exe and
then reading them from the core.
Fixes #1121
=> Handle gdb core files better

service/debugger/debugger.go
```
service/debugger: better error message for go1.11 executables
Output a better error message when users try to debug a go1.11
executable but delve was not built with go1.11.
```
=> service/debugger: better error message for go1.11 executables

Documentation/api/ClientHowto.md
This PR adds a section on how to gracefully end a debugging session when using a custom client
=> Add docs on detaching

cmd/dlv/main.go
```
cmd/dlv: do not override user's CGO_CFLAGS
Fixes #1278
```
=> cmd/dlv: do not override user's CGO_CFLAGS

pkg/proc/proc_test.go
```
proc_test: fix test failure on macOS [WIP]
```
=> proc_test: fix test failure on macOS

cmd/dlv/cmds/commands.go
This changes make `dlv` support multifile specifically when dlv `debug`, 
`trace` and `test`. Just like `dlv debug a.go b.go`. Corresponding to 
`go build a.go b.go`.(a.go and b.go are  belong to `main` package).
Fix #984. (I meet similar problems).
=> Support multifile when dlv `debug`, `trace` and `test`

service/test/integration1_test.go, service/test/integration2_test.go
Fix one typo about test/integration.
=> Fix typo about test/integration

pkg/terminal/command.go
```
terminal: print something  when continue errors even if we don't have a file
We should print something when we exit from continue/next/step/stepout
even if we don't have a source file for the instruction that we are
stopped on.
This is mostly important on macOS where a SIGSEGV will cause 'continue'
to fail with a 'bad access' error (see #852) and the output can be
confusing.
Fixes #1244
```
=> terminal: print something  when continue errors even if we don't have a file

pkg/proc/breakpoints.go
Use `IsInternal` and `IsUser` of `Breakpoint`, not duplicate code
=> pkg/proc: use method not duplicate code

pkg/proc/core/core.go, pkg/proc/core/linux_amd64_core.go
```
pkg/core: make code in core.go OS/arch agnostic
Make code in core.go OS and architecture agnostic in preparation for
adding Windows minidump support.
```
=> pkg/core: make code in core.go OS/arch agnostic

cmd/dlv/dlv_test.go
When we updated to use the new Go 1.11 modules, this test was not updated, and only working because an old copy of Delve in the old GOPATH.
=> cmd/dlv: Fix tests for use with modules

appveyor.yml, go.mod
```
go.mod: update module name
Change module name to github.com/go-delve/delve
```
=> go.mod: update module name

pkg/dwarf/godwarf/type.go
```
dwarf/godwarf: tolerate cyclical type DIEs
As specified in line dwarf/godwarf/type.go:507 the typeCache entry
should always be set before recursive calls to readType to avoid infite
recursion.
Most code in readType already does this but some of the code added
later to handle Go types was wrong.
Fix this bug and also fix the String and Size methods of Type so that
they handle recursive types "correctly" (i.e. they don't recur
forever).
No test is added for this since all legitimate uses of cyclical types
were already handled correctly and the malformed types emitted by the
go compiler will probably be removed in 1.12.
See: https://github.com/golang/go/issues/29264
Fixes #1444
```
=> dwarf/godwarf: tolerate cyclical type DIEs

pkg/proc/bininfo.go
```
proc: fix nil pointer exception when Attach fails
Fixes #1471
```
=> proc: fix nil pointer exception when Attach fails

service/debugger/locations.go
This change try to match relative path according to
the directory of ptraced executable program when loc.FileMatch fail.
Fixes #1474  
En, If you don't support this pr, I will close it.
=> service/debugger: support relative paths in location expressions

pkg/proc/types.go
```
proc: drop support for reading interfaces in Go <= 1.6
Go 1.6 is now unsupported by the Go team and 3 years old and
runtimeTypeToDIE can use some simplification.
```
=> proc: drop support for reading interfaces in Go <= 1.6

.travis.yml
```
travis.yml: add 1.12 to test matrix
```
=> travis.yml: add 1.12 to test matrix

pkg/proc/stack.go
```
proc: simplify logic of (*stackIterator).newStackframe
The lookup at it.pc-1 is only ever done if fn is not nil and pc !=
fn.entry. Also when it happens only the File and Line fields are
allowed to change.
```
=> proc: simplify logic of (*stackIterator).newStackframe

pkg/proc/native/threads_linux.go, pkg/proc/proc_test.go
```
proc/native: fix target program crash caused by call injection (linux)
RestoreRegisters on linux would also restore FS_BASE and GS_BASE, if
the target goroutine migrated to a different thread during the call
injection this would result in two threads of the target process
pointing to the same TLS area which would greatly confuse the target
runtime, leading to fatal panics with nonsensical stack traces.
Other backends are unaffected:
- native/windows doesn't store the TLS in the same CONTEXT struct as
the other register values.
- native/darwin doesn't support function calls (and wouldn't store the
TLS value in the same struct)
- gdbserial/rr doesn't support function calls (because it's a
recording)
- gsdbserial/lldb extracts the value of TLS by executing code in the
target process.
```
=> proc/native: fix target program crash caused by call injection (linux)

pkg/proc/bininfo.go
The current wording is confusing - the file exists and the line exists, so what is the problem? I suspect this ambiguity is behind go-delve#1496 and likely others. It has lead to confusion both for myself and today a co-worker.
Also I updated the style to return values like the rest of the code in the file, which is also more readable (IMO and per https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters)
=> Less confusing error message for requesting break on blank line.

Documentation/cli/README.md, pkg/terminal/command.go
=> add alias go for goroutine and gos for goroutines

Documentation/faq.md, README.md
```
Documentation: add Frequently Asked Questions.
```
=> Documentation: add Frequently Asked Questions.

_fixtures/issue1598.go, pkg/terminal/command_test.go, pkg/terminal/config.go, pkg/terminal/terminal.go
```
terminal: update return value load configuration when it changes
Fixes #1598
```
=> terminal: update return value load configuration when it changes

pkg/proc/gdbserial/gdbserver.go, pkg/proc/gdbserial/gdbserver_conn.go
```
gdbserial: propagate signals to target while stepping
Propagate signals when stepping because debugserver will report them,
from the issue:
2019-07-11T16:31:25+02:00 debug layer=gdbconn <- $z0,105525d,1#c9
2019-07-11T16:31:25+02:00 debug layer=gdbconn -> $OK#00
2019-07-11T16:31:25+02:00 debug layer=gdbconn <- $vCont;s:c41c3#50
2019-07-11T16:31:25+02:00 debug layer=gdbconn -> $T1cthread:c41c3;threads:c41c3,c41d7,c41d8,c41d9,c41da;thread-pcs:105525d,7fffc464bf46,7fffc464bbf2,7fffc464bbf2,7fffc46...
2019-07-11T16:31:25+02:00 debug layer=gdbconn <- $Z0,105525d,1#a9
2019-07-11T16:31:25+02:00 debug layer=gdbconn -> $OK#00
in this case we request a single step on thread c41c3 but debugserver
reports instead a signal (in this case SIGWINCH).
Fixes #1610
```
=> gdbserial: propagate signals to target while stepping

service/api/types.go, service/debugger/debugger.go, service/rpccommon/server.go
```
service: add backend to GetVersion response
Implements #1640
```
=> service: add backend to GetVersion response

.travis.yml, pkg/proc/test/support.go
```
travis-ci: fix dwz test problems [WIP]
```
=> travis-ci: fix dwz test problems

pkg/proc/dwarf_expr_test.go, pkg/proc/eval.go, pkg/proc/fncall.go, pkg/proc/variables.go
```
proc: remove (*EvalScope).globalFor
```
=> proc: remove (*EvalScope).globalFor

pkg/dwarf/line/state_machine.go
=> dwarf/line: add some detail to unknown opcode messages

pkg/proc/proc_test.go, pkg/proc/proc_unix_test.go, pkg/proc/scope_test.go, pkg/proc/variable_test.go, service/test/variables_test.go
```
tests: remove duplicate code
```
=> tests: remove duplicate code

pkg/proc/bininfo.go
The fix for #1428 was buggy, partly because I communicated poorly. Sorry
about that.
The size of the TLS segment should be rounded to its alignment,
not to the machine word size. (For the record, the rounding logic is
working in bits, but PtrSize is in bytes, so it wasn't working as
originally intended either.)
=> proc: round TLS segment size to its alignment

Documentation/installation/README.md
I'm fairly new to Golang and needed to debug a program I was given. I came across this project and it's an excellent fit! However, I will admit, it was a bit of a hurdle to get up and running for the first time.
Firstly, the required Go version was `v1.8` and pulling down the project throws an error:
```
go version go1.8.7 linux/amd64
src/github.com/go-delve/delve/vendor/go.starlark.net/syntax/quote.go:97: undefined: strings.Builder
src/github.com/go-delve/delve/vendor/go.starlark.net/syntax/quote.go:206: undefined: strings.Builder
src/github.com/go-delve/delve/vendor/go.starlark.net/syntax/scan.go:836: undefined: strings.Builder
```
`strings.Builder` was added in `v1.10` so we'll want to get that bumped. Once I moved to that version, everything worked perfectly!
```
go version go1.10.8 …
```
=> Documentation: Tidy up odds and ends

pkg/proc/bininfo.go
```
proc: refactor dwarf function information loading
Splits the code that loads function information from debug_info into
multiple functions.
This makes the changes needed to implement logical breakpoints easier
to make.
```
=> proc: refactor dwarf function information loading

pkg/terminal/config.go
=> terminal: fix panic when config value set 0

Documentation/cli/starlark.md
```
Documentation: add new example to starlark documentation
```
=> Documentation: add new example to starlark documentation

pkg/goversion/compat.go, service/api/types.go, service/debugger/debugger.go
```
service: add min/max supported ver and target ver to GetVersion resp
Fixes #1713
```
=> service: add min/max supported ver and target ver to GetVersion resp

cmd/dlv/cmds/commands.go
This allows to execute and debug signal handlers in inferior.
=> Don't stop headless server on SIGINT on windows (go-delve#1745)

Documentation/cli/README.md, pkg/terminal/docgen.go
=> Documentation/cli: Add the configuration and command history file

pkg/proc/bininfo.go
```
proc: fix loclist access for Position Independent Executables
```
=> proc: fix loclist access for Position Independent Executables

pkg/proc/linutil/regs_arm64_arch.go
Change `copy form` into `copy from`.
=> pkg/proc: fix one typo.

pkg/proc/gdbserial/gdbserver.go
Instead of reloading the registers for every thread every time the
process executes, reload the registers on demand for individual threads
and memoize the result.
=> proc/gdbserial: Reload thread registers on demand

pkg/proc/types.go
```
proc: remove support for parsing interfaces in Go 1.8 and earlier
Go 1.8 has been out of date for a while and the code to support it is
potentially dangerous if a future version of Go removes the runtime
types from debug_info and also changes their representation.
```
=> proc: remove support for parsing interfaces in Go 1.8 and earlier

Documentation/cli/README.md, pkg/terminal/command.go
```
terminal: add ability to print goroutine labels
```
=> terminal: add ability to print goroutine labels

cmd/dlv/dlv_test.go
=> dlv_test: add a basic test for dap command

Makefile, cmd/dlv/cmds/commands.go, pkg/dwarf/godwarf/type.go, pkg/dwarf/util/buf.go, pkg/gobuild/gobuild.go, pkg/proc/core/core_test.go, pkg/proc/dwarf_expr_test.go, pkg/proc/native/registers_linux_amd64.go, pkg/proc/proc_test.go, pkg/proc/scope_test.go, pkg/proc/test/support.go, pkg/terminal/command.go, pkg/terminal/command_test.go, pkg/terminal/config.go, pkg/terminal/starbind/conv.go, pkg/terminal/starlark.go, pkg/terminal/terminal.go, service/api/conversions.go, service/debugger/debugger.go, service/debugger/locations.go, service/rpc1/server.go, service/rpc2/client.go, service/rpc2/server.go, service/test/common_test.go, service/test/integration1_test.go, service/test/integration2_test.go, service/test/variables_test.go
Run `go vet` on project, fix complaints.
=> *: Fix go vet complaints

.gitignore, scripts/make.go, vendor/github.com/spf13/cobra/LICENSE.txt, vendor/go.starlark.net/syntax/grammar.txt, vendor/modules.txt
```
vendor: check vendor directory
Remove gitignore rule preventing vendor/modules.txt file from being
commited, add check that the vendor directory is synchronized.
```
=> vendor: check vendor directory

pkg/proc/target.go, pkg/proc/target_exec.go
=> pkg/proc: Remove unused parameter

pkg/proc/target_exec.go
```
proc: StepOut remove if condition that is always true
```
=> proc: StepOut remove if condition that is always true

pkg/proc/native/proc.go, pkg/proc/native/proc_freebsd.go
```
proc/native: disable async preemption on freebsd
```
=> proc/native: disable async preemption on freebsd

service/debugger/debugger.go
Fixes a long standing dangling TODO item.
=> service/debugger: Rename processMutex to targetMutex

pkg/proc/native/proc_linux.go
https://github.com/go-delve/delve/issues/2024
On linux platform, we simply treated `/proc/$pid/exe` as the
executable of targeting process when doing `dlv attach`. The
`/proc/$pid/exe` is a symbol link of the real executable file.
Delve couldn't find the corrsponding external debug file based on the
symbol link:
```
could not attach to pid $pid: could not open debug info
```
The fix is to evaluate the symbol links to the actual executable path.
=> proc: Find executable should follow symbol links.

pkg/dwarf/op/op.go
```
dwarf/op: return register values when they are the only piece
When there is a single piece and it's a register value just return it.
This is important for clang compiled programs which will use DW_OP_regN
to specify the value of the frame base.
```
=> dwarf/op: return register values when they are the only piece

Documentation/cli/README.md, pkg/terminal/command.go
These are just some simple examples of how the list command can be used.  I'm not sure how you'd prefer to document these things, so I figured it would be worth throwing something together to at least start a discussion about what you'd prefer.
I was looking at the documentation struggling to remember how to use the list command and some concrete examples would be useful for me.  I essentially grabbed these from your tests.
=> Add some simple examples for the list command

pkg/proc/gdbserial/gdbserver.go
Unexport `GetDebugServerAbsolutePath` and avoid unnecessary repeated calls.
Remove `os.Stat` because `Exec.LookPath` has already used `os.Stat`.And Fix
some comments.
=> gdbserial/gdbserver: optimize the search of debugserver binary

_fixtures/http_server.go, cmd/dlv/dlv_test.go, pkg/proc/native/proc_darwin.go, pkg/proc/native/proc_freebsd.go, pkg/proc/native/proc_linux.go
Target process should exit when dlv launch failed.
Fix #2017.
=> [WIP] pkg/proc: avoid target process leaks.

README.md
=> doc/readme: Remove the Build Status of appveyor

pkg/proc/target_exec.go
```
proc: step into unexported runtime funcs when already inside runtime
Normally we don't step into unexported runtime functions because the
compiler is free to insert them into the code and they are not relevant
to the user, however if we are already stepping through a runtime
function we should let step into work normally and step into other
runtime functions.
```
=> proc: step into unexported runtime funcs when already inside runtime

go.mod, go.sum, pkg/terminal/command.go, vendor/github.com/cosiner/argv/README.md, vendor/github.com/cosiner/argv/argv.go, vendor/github.com/cosiner/argv/cmd.go, vendor/github.com/cosiner/argv/go.mod, vendor/github.com/cosiner/argv/parser.go, vendor/github.com/cosiner/argv/scanner.go, vendor/modules.txt
Fixes breaking changes in github.com/cosiner/argv v0.1.0
Fixes https://github.com/beego/bee/pull/665 but there are probably a lot of other libs cannot use `go get -u` because of this
=> Update cosiner/argv to v0.1.0

pkg/dwarf/line/line_parser.go, pkg/dwarf/line/parse_util.go, pkg/dwarf/line/state_machine.go
DWARFv5 has a new format for the header, directory table and line table
of the debug_line section.
=> dwarf/line: support DWARF version 5

CHANGELOG.md, _scripts/gen-travis.go, pkg/version/version.go
Thank you to:  @polinasok, @chainhelen, @alexsaezm, @bhcleek,
@letientai299, @gadelkareem and @b00f
=> Delve 1.5.0 release

pkg/proc/variables.go
=> proc: optimize FindGoroutine by checking the cache first

Documentation/faq.md
=> Documentation: update supported architectures

.travis.yml, _scripts/gen-travis.go, pkg/goversion/compat.go, service/dap/server_test.go
=> Travis-CI: bump Go version in test matrix

service/dap/daptest/client.go, service/dap/server.go, service/dap/server_test.go
=> service/dap: support next, stepIn and stepOut requests

pkg/proc/gdbserial/gdbserver.go
(*gdbThread).StepInstruction is a single call to stepInstruction so
inline it.
=> proc/gdbserial: inline (*gdbThread).stepInstruction

pkg/proc/gdbserial/gdbserver_conn.go
During the testing of the core dump generation feature two bugs were
discovered in gdbserial:
1. we don't check that both bytes of the checksum are read, if the
buffer only has one byte we can end up reading only one byte instead
of two and the second byte will mess up the parsing of the next
packet
2. binary encoded packets can start with an 'E' and not be errors, when
using binary responses add an extra check for the lenght of the
response before deciding that the response is an error.
Unfortunately this encoding is inherently ambiguous (we can't
distinguish a 3 byte response starting with 'E' from an error) so
binary requests that lead to short responses should be avoided.
Testing this is complicated, they will be tested implicitly by the
upcoming core dump test.
=> proc/gdbserial: fix two protocol bugs

pkg/proc/native/proc_linux.go
If the process receives a signal (or sends a singal to itself) and then
dies before we can route the signal back to it we still need to
retrieve its exit status.
Fixes a rare failure of TestIssue1101 in proc_test.go
=> proc/native/linux: get exit status if proc exits after receiving signal

Documentation/KnownBugs.md, Documentation/faq.md
1. Remove bug about unsupport systems, because we has pretty error msg.
2. Add usage for remote debugging.
Relate: #1883, #1829, #861, #1332.
=> Doc: update KnownBugs and faq.

Documentation/usage/dlv.md, Documentation/usage/dlv_attach.md, Documentation/usage/dlv_backend.md, Documentation/usage/dlv_connect.md, Documentation/usage/dlv_core.md, Documentation/usage/dlv_dap.md, Documentation/usage/dlv_debug.md, Documentation/usage/dlv_exec.md, Documentation/usage/dlv_log.md, Documentation/usage/dlv_redirect.md, Documentation/usage/dlv_replay.md, Documentation/usage/dlv_run.md, Documentation/usage/dlv_test.md, Documentation/usage/dlv_trace.md, Documentation/usage/dlv_version.md, cmd/dlv/cmds/commands.go, pkg/proc/gdbserial/gdbserver.go, pkg/proc/native/nonative_darwin.go, pkg/proc/native/proc_darwin.go, pkg/proc/native/proc_freebsd.go, pkg/proc/native/proc_linux.go, pkg/proc/native/proc_windows.go, pkg/proc/proc_linux_test.go, pkg/proc/proc_test.go, pkg/proc/target.go, service/debugger/debugger.go, service/test/variables_test.go
=> proc/*: add launch option to disable ASLR

Documentation/backend_test_health.md, pkg/proc/arch.go, pkg/proc/arm64_arch.go, pkg/proc/proc_test.go, pkg/proc/stack.go
=> proc: support reading deferred calls' arguments on linux/arm64

pkg/proc/interface.go, pkg/proc/native/proc.go
This patch adds some comments around RequestManualStop().
=> proc: add minor comments

pkg/dwarf/reader/variables.go, pkg/proc/eval.go
Fix some stale comments and add some comments that I would have found
useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/go-delve/delve/2253)
=> dwarf/reader: minor comments around variable resolving

CHANGELOG.md, pkg/version/version.go
Thank you to: @polinasok, @aurkenb, @pohzipohzi, @chainhelen,
@hitzhangjie, @eliben, @suzmue, @andreimatei, @aaronsky.
=> Version 1.5.1

pkg/proc/gdbserial/gdbserver.go
=> proc/gdbserial: use --unmask-signal debugserver option

pkg/dwarf/dwarfbuilder/builder.go, pkg/dwarf/frame/entries.go, pkg/dwarf/frame/parser.go, pkg/dwarf/frame/table.go, pkg/dwarf/line/line_parser.go, pkg/dwarf/line/state_machine.go, pkg/dwarf/util/util.go
Add godoc comments for some exported type, function, methods for the dwarf package.
=> dwarf/*: add godoc comments

.github/workflows/test.yml, .travis.yml, README.md, _scripts/gen-travis.go, _scripts/make.go, appveyor.yml
=> split testing load between more CI services

pkg/proc/native/proc_linux.go
=> pkg/proc/native: fix nil pointer dereference in linux backend

pkg/proc/native/proc_linux.go
If a thread exits while we are looking at it just treat it as if the
status had reported it as exited instead of doing something special.
Fixes flakiness in TestIssue387.
=> pkg/prog/native/linux: change handling of ESRCH in trapWaitInternal

cmd/dlv/dlv_test.go, pkg/terminal/command.go, service/api/conversions.go, service/api/types.go
=> terminal,service: print WaitReason, WaitSince for goroutines

service/dap/server_test.go
=> service/dap: fix race condition in TestAttachStopOnEntry

.teamcity/settings.kts
=> Fix .teamcity/settings.kts

pkg/proc/proc_test.go, service/test/integration1_test.go, service/test/integration2_test.go
=> Add more logging to TestClientServer_FullStacktrace to debug linux/arm64 failures

pkg/proc/arm64_arch.go
=> proc: correctly format ARM64 floating point registers

pkg/proc/eval.go, pkg/proc/variables.go
=> proc: remove dead code

pkg/config/config.go, pkg/terminal/colorize/colorize.go, pkg/terminal/command.go, pkg/terminal/terminal.go
=> terminal: Go syntax highlighting for listings

CHANGELOG.md, pkg/version/version.go
Thank you to: @andreimatei, @hitzhangjie, @dlsniper, @nd, @polinasok,
@oxisto, @zamai, @artspb.
=> Release 1.6.0

Documentation/api/json-rpc/README.md
Remove list of implementation since it seems no longer maintained
=> Fix broken link to JSON-RPC

.teamcity/settings.kts
=> TeamCity: fix mac test script name

pkg/proc/bininfo.go, pkg/proc/linutil/regs_arm64_arch.go, pkg/proc/native/proc.go, pkg/proc/native/registers_linux_arm64.go, pkg/proc/target.go
When cgo is used the address of the g struct is saved on the special
register TPIDR_EL0. Because executing C code could overwrite the
contents of R28 that normally contains the address of g we should read
it from TPIDR_EL0 instead when runtime.iscgo is set.
=> proc/native: correctly read g address on linux/arm64

service/dap/server_test.go
Inspired by discussion in #2364
=> service/dap: clarify default attributes behavior with tests

pkg/gobuild/gobuild.go
=> gobuild: wait longer when removing files on Windows

Documentation/cli/README.md, pkg/terminal/command.go
A single word in docs/cli/README
=> fix spelling error

pkg/terminal/command_test.go
=> terminal: fix TestContinueUntil on linux/386

Documentation/cli/README.md, Documentation/cli/starlark.md, _fixtures/testtoggle.go, pkg/proc/breakpoints.go, pkg/proc/target.go, pkg/terminal/command.go, pkg/terminal/starbind/starlark_mapping.go, service/api/types.go, service/client.go, service/debugger/debugger.go, service/rpc2/client.go, service/rpc2/server.go, service/test/integration2_test.go
These changes add the 'toggle' command, which allows us to enable or disable a breakpoint.
Fixes #2008
=> Adds toggle command

service/dap/server.go, service/dap/server_test.go
Updates #2392
Updates https://github.com/golang/vscode-go/issues/1348
=> service/dap: clarify treatment of relative output path

service/dap/server_test.go
Based on [proc_test](https://github.com/go-delve/delve/blob/c223ef656da3ddbab3a58ea87108d4217731a01c/pkg/proc/proc_test.go#L4969-L4977), looks like termination is a possible and acceptable outcome (which makes sense since the breakpoint is hit at the very last goroutine, so all others might already be wrapping up or done).
=> service/dap: handle terminated events in TestStepOutPreservesGoroutine

pkg/dwarf/godwarf/type.go, pkg/dwarf/line/state_machine.go, pkg/dwarf/line/state_machine_test.go, pkg/dwarf/util/buf.go, pkg/proc/arm64_arch.go, pkg/proc/bininfo.go, pkg/proc/dwarf_expr_test.go, pkg/proc/fncall.go, pkg/proc/native/threads_linux.go, pkg/proc/proc_test.go, pkg/terminal/starbind/starlark.go, service/dap/server_test.go, service/debugger/debugger.go
=> *: remove unused code, variables and constants

service/dap/server.go
=> service/dap: fallback to CurrentThread if SelectedGouroutine is not set

service/dap/server.go
Add logging of the working directory of the program being launched.
Updates golang/vscode-go#1439
=> service/dap: log working directory of launch program

service/dap/server_test.go
Fix the flaky test. The threads request may be processed after the program has already stopped.
=> service/dap: fix flaky TestPreSetBreakpoint test

pkg/gobuild/gobuild.go, service/dap/server.go, service/dap/server_test.go
Since the build error may be long, including it in the error response may not be a good way to get the info to the user. This change moves that information to an output event. It also includes the build command that produced the error.
Updates golang/vscode-go#1425
=> service/dap: move build error to output event

pkg/proc/native/proc_linux.go, pkg/proc/proc_unix_test.go, service/dap/server_test.go
Handle the signaled status for the thread leader like we handle the
exited status, by returning ErrProcessExited and recording the killer
signal  in it.
Prior to this commit we would find out about the death of the thread
later in the loop, the condition would still be reported as
ErrProcessExited, but without recording the signal number anywhere.
Also fixes a bug in TestAttachStopOnEntry where the test would
inadvertently cause a SIGPIPE to be sent to the target process, making
it terminate early.
=> proc/native/linux: better handling of process death due to signals

CHANGELOG.md, pkg/version/version.go
Update version and release notes.
=> all: v1.6.1

service/dap/server.go, service/dap/server_test.go
Use the same logic to halt the program execution for setting function breakpoints as we do for breakpoints.
=> service/dap: set function breakpoints while running

Documentation/EditorIntegration.md
=> Documentation: add vimspector to list of editor plugins

pkg/proc/gdbserial/gdbserver.go
PR #2498 / commit d552b338 left out some code due to a clerical error.
=> gdbserial: actually fix ZMM register support

.teamcity/settings.kts, _scripts/test_linux.sh, _scripts/test_mac.sh, _scripts/test_windows.ps1
=> TeamCity: add go1.17 to test matrix, disable go-tip builds

.teamcity/settings.kts, CHANGELOG.md, pkg/goversion/compat.go, pkg/version/version.go
Thanks to @aarzilli, @mknyszek, @suzmue, @dwagin, @hyangah, @staugust, and @polinasok.
=> *: Release 1.7.0

Documentation/usage/dlv.md, Documentation/usage/dlv_dap.md, cmd/dlv/cmds/commands.go
=> cmd/dap: server - always headless, target - always foregrounded

cmd/dlv/cmds/commands.go, service/dap/server.go, service/dap/server_test.go
updates golang/vscode-go/issues/1591
=> service/dap: add backend launch/attach attribute

_scripts/latestver.py, _scripts/test_linux.sh, _scripts/test_windows.ps1
Works around https://github.com/golang/go/issues/47367.
=> TeamCity: prefer go rc builds over beta

pkg/proc/proc_test.go
Adds tests that make sure that when a next request is interrupted by a breakpoint, the stepping breakpoints are cleared.
=> pkg/proc: add tests for next interrupted by breakpoint

cmd/dlv/cmds/commands.go
This refactoring reduces code duplication and makes the helper available to be used by dlv-dap command in the future.
=> cmd: refactor building logic into a helper

pkg/proc/breakpoints.go, pkg/proc/native/proc_windows.go
=> pkg/proc: Fix Windows ebpf build errors

service/dap/server.go, service/dap/server_test.go
Updates golang/vscode-go#1648
Updates golang/vscode-go#1544
=> service/dap: log execution-halted message when setting breakpoints

service/dap/server_test.go
The Threads request sent immediately after the ConfigurationDone
request can be processed in two possible states:
* while the program is being executed, when it will return Id=1,
Name=Dummy
* after the program terminates, when it will return Id=-1, Name=Current
additionally the response could be received in any order with the
Terminate event.
Remove the problematic Threads request from the test.
=> service/dap: fix race condition in TestContinueOnEntry

service/dap/daptest/client.go, service/dap/error_ids.go, service/dap/server.go, service/dap/server_test.go
=> service/dap: fix noDebug mode to handle requests while running

service/dap/server_test.go
=> service/dap: add test that verifies output path is relative to wd

cmd/dlv/dlv_test.go, service/rpccommon/server.go, service/test/integration2_test.go
Context: https://github.com/go-delve/delve/pull/2648#issuecomment-906954585
=> service/rpccommon: halt before detach in Stop

service/dap/server_test.go
Fix issue flagged by deepsource.
=> service/dap: remove unused test helper arg

pkg/logflags/logflags.go, service/dap/server.go, service/rpccommon/server.go
=> service/rpccommon,service/dap: warn about listening to remote connections

_scripts/latestver.py, _scripts/test_linux.sh, _scripts/test_mac.sh
=> Travis-CI: fix scripts selecting Go version

cmd/dlv/dlv_test.go, service/dap/server.go
=> service/dap: fix compile error from merge conflict

Documentation/installation/README.md
=> Documentation: add more installation instuctions

_scripts/make.go
This is useful to be able to build using Delve's build scripts when
working from within a directory that has been extracted from a source tarball,
or wherever we wouldn't have git history.
This can be invoked as:
```
go run _scripts/make.go build --no-git
```
=> _scripts: add option to disable invoking git during build

service/dap/server.go
SetVariableRequest and DisassembleRequest are no longer TODO.
SourceRequest moved to the TODO category.
=> service/dap: update request inventory comments in Server.handleRequest

pkg/proc/target.go, pkg/proc/target_exec.go, service/dap/server.go, service/dap/server_test.go
The stop reason is not updated when using step instruction. Update the stop reason to StepNextFinished.
=> pkg/proc: set stop reason for step instruction

service/dap/server.go, service/dap/server_test.go
The addresses need to be parseable as an int. The VS Code disassembly view uses a binary search to look for the appropriate address, so we set these to be the min value and the max value, so that the binary search will be effective.
Updates golang/vscode-go#1938
=> service/dap: set min/max addresses for invalid instructions

service/dap/server.go
This is a partial revert of PR #2660.
Some users develop in environments where execution of binaries
in temp directory is prohibited or undesirable. Moreover, the
current implementation creates binaries with random names
and that made it more difficult to set up firewall exclusion
rules. Revert it and always use the default debug output name.
(The debug binary will be created in the delve's working directory
and an editor does not have any promise on working directory
unless user specifies it through dlvCwd. So users still need to
chase them unless they set the exclusion rule purely based on
the file base name).
Fixes golang/vscode-go#1955
cc @suzmue @polinasok
=> dap: use defaultDebugBinary instead of creating binary in temp dir with temp name

CHANGELOG.md, pkg/version/version.go
Update CHANGELOG.md and version.
=> Version 1.8.1

cmd/dlv/dlv_test.go, pkg/proc/gdbserial/gdbserver.go, pkg/proc/test/support.go
=> proc/gdbserial: shut down debuggee when failing to debug

pkg/proc/native/proc.go
On FreeBSD and OpenBSD, the use of runtime.LockOSThread is resulting in segfaults
within the Go runtime (see https://github.com/golang/go/issues/52394) - while it
should not be necessary, calling runtime.UnlockOSThread upon exit from
handlePtraceFuncs avoids this issue and allows the tests to run correctly.
=> proc: unlock OS thread on exit from handlePtraceFuncs

_fixtures/fncall.go, _scripts/test_linux.sh, _scripts/test_windows.ps1, pkg/proc/amd64_arch.go, pkg/proc/arch.go, pkg/proc/arm64_arch.go, pkg/proc/core/delve_core.go, pkg/proc/fbsdutil/regs.go, pkg/proc/fncall.go, pkg/proc/gdbserial/gdbserver.go, pkg/proc/gdbserial/gdbserver_conn.go, pkg/proc/linutil/regs_amd64_arch.go, pkg/proc/linutil/regs_arm64_arch.go, pkg/proc/linutil/regs_i386_arch.go, pkg/proc/native/registers_darwin_amd64.go, pkg/proc/native/registers_linux_arm64.go, pkg/proc/native/threads_linux_arm64.go, pkg/proc/registers.go, pkg/proc/target.go, pkg/proc/test/support.go, pkg/proc/threads.go, pkg/proc/winutil/regs.go, service/test/variables_test.go
Support function call injection on arm64 with go1.19
=> proc: support function call injection on arm64

pkg/proc/core/core.go, pkg/proc/core/core_test.go
=> proc/core: return true for calls to Recorded

pkg/proc/variables_test.go
Moves variable evaluation tests to pkg/proc which is where most of the
code they test exists, this also allows the removal of a bunch of
duplicate support code.
=> service/test,proc: move variable evaluation test to pkg/proc

pkg/proc/arm64_arch.go
In commit eee6f9f82 Go changed the order that crosscall2 uses to save
its registers, update arm64SwitchStack to use the new order when the
binary was compiled by go 1.19.
Fixes #2993
=> proc: fix arm64SwitchStack for go1.19

Documentation/cli/README.md, _fixtures/condperghitcount.go, pkg/proc/breakpoints.go, pkg/terminal/command.go, pkg/terminal/command_test.go, service/api/command.go, service/api/conversions.go, service/api/types.go, service/dap/server.go, service/debugger/debugger.go
Support run command on every goroutine.
Fixes #3043
=> terminal/command: 'goroutines' command add new flags '-exec command'

pkg/proc/variables.go
=> proc: do not panic reading bad G struct

service/debugger/debugger.go
Change service/debugger.(*Debugger).state and collectBreakpointInfo
methods so that they work with TargetGroup.
Updates #2551
when running custom builds
abstraction
on '5660f9a4'.
=> service/debugger: refactor state/collectBreakpointInfo for TargetGroup

Documentation/cli/README.md, pkg/terminal/command.go
These were implemented in [1].
[1] https://github.com/go-delve/delve/pull/1785
=> Documentation: reverse step, next and stepout

pkg/proc/native/proc_windows.go
On Windows we need to acquire the SeDebugPrivilege privilege to be able
to debug programs owned by different users.
See:
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-privilege
This procedure will fail if the current user does not have this
privilege so do not complain too much about it.
Fixes #3136
=> proc/native: acquire debug programs privilege on Windows

_fixtures/fncall.go, pkg/proc/eval.go, pkg/proc/variables_test.go
=> proc: fix index access to already-loaded string values

pkg/proc/gdbserial/gdbserver.go
This change fixes recent situations where you can't really load to debugserver/lldb since of new protections
but you still want to load to the debugged process delve already supports moving the parameters to the child using -e, this just supresses issues being loaded to the debugger itself
=> proc/gdbserial/gdbserver: Don't pass DYLD/LD to debugserver

pkg/proc/bininfo.go
This PR fixes windows/amd64 port on `gotip`. Since [CL 431775](https://go-review.googlesource.com/c/go/+/431775) the G struct offset is no longer hardcoded to `0x28` but created initialized at runtime and stored in `runtime.tls_g`, just as it is already happening in windows/arm64.
Delve has to account for this change and dereference `runtime.tls_g` in order to obtain the real G struct offset value.
=> G struct offset is a pointer to an offset since go1.20

.teamcity/settings.kts, _scripts/test_windows.ps1, pkg/proc/native/support_sentinel_windows.go
Now that we have windows/arm64 agents (see #3197), let's try to exercise them.
=> Run CI tests on windows/arm64 agents

.teamcity/settings.kts, CHANGELOG.md, pkg/goversion/compat.go, pkg/version/version.go
Thank you @Frederick888, @emad-elsaid, @cuiweixie, @qmuntal, @suzmue,
@cuishuang, @aviramha, @dlipovetsky, @Foxboron, @gfszr.
=> *: CHANGELOG and bump to version 1.20.0

pkg/dwarf/godwarf/tree.go
I noticed this while processing some non-Go debuginfos. The relevant information regarding this type of entry from the DWARF spec:
> A debugging information entry that represents a declaration that completes another (earlier) non-defining declaration may have a `DW_AT_specification` attribute whose value is a reference to the debugging information entry representing the non-defining declaration. A debugging information entry with a `DW_AT_specification` attribute does not need to duplicate information provided by the debugging information entry referenced by that specification attribute.
=> godwarf: Attempt to load `DW_AT_specification` if present

pkg/terminal/command.go, service/debugger/debugger.go, service/test/integration1_test.go, service/test/integration2_test.go
=> debugger,terminal: Allow setting and clearing breakpoints after process exit

Documentation/cli/README.md, pkg/terminal/command.go
=> Documentation: watch example for arbitrary address

pkg/proc/core/core.go, pkg/proc/core/core_test.go, pkg/proc/core/linux_core.go, pkg/proc/core/windows_amd64_minidump.go, pkg/proc/variables_fuzz_test.go, pkg/proc/variables_test.go
Add code to fuzz the expression evaluator and variable loader, see
comment to FuzzEvalExpression for how to use this.
=> proc: fuzzing expression evaluator and variable loader

Documentation/backend_test_health.md, pkg/proc/proc_test.go, service/dap/server_test.go
Disable some tests on windows/arm64 that are flaky.
=> proc: disable flaky tests on windows/arm64

pkg/terminal/command.go
If the path passed to source starts with a ~ expand it into the user's
home directory, like the shell would.
=> terminal: expand ~ in paths passed to 'source'

.teamcity/settings.kts
Second attempt at doing what PR #3403 tried to do.
=> TeamCity: fix linux/arm64 build (second attempt)

pkg/proc/bininfo.go, pkg/proc/pclntab.go, pkg/proc/proc_test.go
Take into account static base for PIE binaries.
=> pkg/proc: improve stripped binary support with PIE

_fixtures/testvariables2.go, pkg/proc/variables.go, pkg/proc/variables_test.go
=> proc: check recursion level when loading pointers

service/dap/server.go
Fixes bugs introduced in v1.21.1
* Avoid dropping the last bytes from stderr/stdout when Read returns an error. (Read returns n>0). And skip sending Output event if Read returns n==0.
* Fix the bug that drops all stdout in the existing noDebug mode.
For #3094 #3253 
With this, the vscode-go test passes.
I wish we had testing for non-redirect mode, but I want to get this in soon since these bugs affect vscode go users.
=> service/dap: fix bugs in stdout/stderr handling

service/api/prettyprint.go
Use a bitfield for the internal flags used by the prettyprinting code.
=> service/api: use bitfield for prettyprint flags

_fixtures/condframe.go, pkg/proc/eval.go, pkg/proc/evalop/evalcompile.go, pkg/proc/evalop/ops.go, pkg/proc/native/threads_linux_ppc64le.go, pkg/proc/proc_test.go, pkg/terminal/command_test.go
=> proc: allow evaluator to reference previous frames

CONTRIBUTING.md
Adds a callout to the standard Go code of conduct in the CONTRIBUTING.md doc.
=> *: Add explicit code of conduct

_fixtures/nilptr.go, pkg/proc/amd64_arch.go, pkg/proc/arm64_arch.go, pkg/proc/proc_test.go, pkg/proc/stack.go
See: https://github.com/golang/go/issues/63862
Fixes #3545
=> pkg/proc: improve support unwinding from sigpanic

pkg/proc/gdbserial/gdbserver_conn.go
The gdb remote serial protocol returns in several places a list of key
value pair in the form key1:value1;key2:value2;...;keyN:valueN.
We had ad-hoc parsers for this in three places, this commit
consolidates the parser in a single utility object.
=> proc/gdbserial: refactor parsing of key-value pairs from gdb protocol

.teamcity/settings.kts
Fix a build config error and add a scheduled trigger
to perform nightly builds.
=> CI: update teamcity settings

go.mod
=> all: run go mod tidy

service/dap/server.go
This fixes an infrequent close on closed channel panic in service/dap
caused by a race condition with closing a channel.
=> service/dap: fix close on closed channel

pkg/elfwriter/writer.go
Add ability to write out section headers to elfwriter.
=> elfwriter: add WriteSectionHeaders

pkg/proc/gdbserial/rr.go
Attempt to fix https://github.com/go-delve/delve/issues/3704
I was having issues testing this locally and wasn't able to understand why. Unfortunately, all machines i have access to require the new `rr`, so its hard for me to test old vs new; I have low confidence this works
=> rr: fix gdb parsing

CHANGELOG.md, pkg/version/version.go
Thanks to @alexandear, @scop, @howardjohn, @archanaravindar, @abbasudo,
@fatanugraha, @jayantxie and @zdyj3170101136.
=> *: release version 1.23.0

pkg/proc/bininfo.go
Go 1.23 and earlier does not take into account that Mach-O section
names are limited to 16 characters, which causes DWARF sections with
long names to be truncated and become unreadable.
Fixes #3797
=> proc: workaround for macOS section name truncation

CHANGELOG.md, pkg/version/version.go
Thanks to @Jille, @linchizhen and @arvidfm.
=> *: release version 1.23.1

pkg/proc/variables.go
Go 1.24 changed the way goroutine labels are stored.
=> proc: fix loading goroutine labels on Go 1.24

pkg/terminal/command.go
Enhance editor support for the DELVE_EDITOR environment variable
1. Add support for the Zed editor by recognizing the 'zed' command and setting the appropriate line number syntax
2. Allow users to specify editor-specific arguments in DELVE_EDITOR by parsing the env var value into command and args parts
3. Modify runEditor() to pass through any user-specified args before appending the file/line args
This change allows more configuration flexibility through DELVE_EDITOR while maintaining backwards compatibility. The Zed editor is now supported alongside VSCode, Helix and Vim variants.
Fixes #3627
=> pkg/terminal: support zed editor and allow args in DELVE_EDITOR

pkg/proc/bininfo.go, pkg/proc/proc_test.go
Produce a better error when trying to set a breakpoint, by line, on
stripped binaries.
Fixes #3913
=> proc: better error message for breakpoints on stripped binaries

pkg/dwarf/line/line_parser.go, pkg/dwarf/line/line_parser_test.go, pkg/dwarf/line/state_machine.go, pkg/dwarf/parseutil.go, pkg/proc/bininfo.go, pkg/proc/proc_general_test.go, pkg/proc/proc_test.go
=> DWARFv5 fixes

Documentation/cli/substitutepath.md
The DAP server uses "from" and "to" with an opposite meaning to the command line client. This was previously documented incorrectly. Here is what the [official documentation for launch.json](https://github.com/golang/vscode-go/blob/77a4fdb77ded9b3b6a70a70d810eed1cb7e9a631/docs/debugging.md#launchjson-attributes) says:
Moreover, it was seemingly falsely claimed, that empty strings have special meaning with the DAP server. As far as I can tell, this is not the case. Instead, special placeholders must be used with the DAP server. An example can also be found in [the official documentation](https://github.com/golang/vscode-go/blob/77a4fdb77ded9b3b6a70a70d810eed1cb7e9a631/docs/debugging.md#connect-to-headless-delve-with-target-specified-at-server-start-up):
```
"substitutePath": [
{ "from": …
```
=> Documentation: fix substitutePath explanation for DAP server

pkg/proc/variables.go
This commit https://github.com/go-delve/delve/pull/3962/commits/a5c88606b8905ce9c61e4dc838c8da0223afe32b will `continue` the loop when it detects invalid goroutine labels to fix the issue https://github.com/go-delve/delve/issues/3928
However, when testing with Delve master https://github.com/go-delve/delve/commit/4dc820ee3c3364152aff34976927f051d800d6ca, corrupted `labelMap.Len` values still cause infinite parsing loops, hanging the debugger:
```
variables.go:588: labelMap len:  32210697599938149
```
~~Skip corrupted goroutines entirely instead of partially parsing them. This is should be safe because valid workflows wouldn't produce invalid label structures.~~
Limit the max length of the map
=> proc: limit the max length of goroutine's label map (#3928)

pkg/proc/gdbserial/gdbserver.go
This is the write side of commit f8dda39c.
Fixes #3977
=> gdbserial: fix call injection with newer versions of macOS

CHANGELOG.md, pkg/version/version.go
Thanks @aarzilli, @codeaucafe, @jersey1dev, @ConradIrwin!
=> *: Release v1.25.0

pkg/dwarf/line/line_parser_test.go, pkg/proc/proc_test.go, pkg/proc/variables_test.go, service/dap/server_test.go, service/test/integration2_test.go
Simplified code with no loss of clarity.
=> pkg,service: simplify tests with slices.Contains

pkg/proc/native/proc.go, pkg/proc/native/proc_windows.go
Fixes one race in https://github.com/go-delve/delve/issues/4117.
=> service/dap: fix nativeProcess race condition in tests

Documentation/backend_test_health.md, pkg/proc/loong64_arch.go, pkg/proc/proc_test.go
=> pkg/proc: fix and improve frame unwind context handling on loong64

pkg/proc/gdbserial/rr_test.go
Cleans up TestTraceDirCleanup avoids dumping stuff on the user's home
directory and cleans up the test directory if it was left over from
prior failed runs. Also alters its code so that the directory existence
check is done *after* deatch (the directory can never be removed before
we detach).
=> proc/gdbserial: cleanup TestTraceDirCleanup
